### ISSUE TITLE
Is not possible to handle an exception inside event listener when `alwaysStat=true` 

### ISSUE THREAD

**Issue by andreabreu-me** [paulmillr/chokidar#1002]
Right now is not possible to handle any exception inside `change` event listener, only when `alwaysStat=true`.

Culprit line: https://github.com/paulmillr/chokidar/blob/3.3.1/index.js#L611

Maybe something like this should fix:

```javascript
try {
  const stats = await stat(fullPath);
  // ...  
} catch (error) {
  // Suppress event when fs_stat fails, to avoid sending undefined 'stat'
  if (error.message && error.message.includes("fs_stat")) return; // how to know if is fs_stat error?
  throw error;
}
```

**Versions:**

 - Chokidar version: 3.3.1
 - Node version: 12.16.1
 - OS version: MacOS 10.14.6

**To Reproduce:**

```javascript
const chokidar = require('chokidar');
const fs = require('fs');

try {
  chokidar.watch('test*', { alwaysStat: true }).on('change', (path) => {
    console.log(path);
    throw new Error("test");
  })
  .on("error", (error) => {
    console.log("I never print");
  });
} catch(error) {
  console.log("I never print");
}

fs.writeFileSync('test.txt', 'testing 1');
```

**Comment by paulmillr** [comment]
chokidar doesn't throw errors. Use `on('error')` to handle fs errors.

for your particular case you can do try-catch inside `(event, path) =>` function.

**Comment by andreabreu-me** [comment]
> chokidar doesn't throw errors. Use `on('error')` to handle fs errors.
I have tried using `on('error')`, but it does not catch the exception, but when `alwaysStat` is `false`, it throws.

> for your particular case you can do try-catch inside `(event, path) =>` function.
I want to catch outside of it

**Comment by paulmillr** [comment]
Fixed in master

**Comment by andreabreu-me** [comment]
Thanks for this awesome library
