### ISSUE TITLE
Missing some events when monitoring multiple paths

### ISSUE THREAD

**Issue by albertobastos** [paulmillr/chokidar#1005]
**Describe the bug**

Some expected events are not triggered when a watcher is monitoring more than one path.

When working with several paths to be monitored, not all events are triggered as expected. On the other hand, when a separate watcher is created for each path, all the expected events are triggered.

**Versions (please complete the following information):**
 - Chokidar version: **3.4.0**
 - Node version: **v12.16.3 (LTS: Erbium)**
 - OS version: **Ubuntu 20.04 LTS**

**To Reproduce:**

Given the following **index.js**:

```
'use strict';

const path = require('path');
const chokidar = require('chokidar');

const opts = {ignoreInitial: true, atomic: false};
const paths = [path.join(__dirname, './a'), path.join(__dirname, './b')];
const handler = (act, pth) => console.log(`${act}\t${path.basename(pth)}`);

if(process.argv[2] === 'array') {
  console.log('Mode: chokidar.watch(array)');
  const watcher = chokidar.watch(paths, opts)
  watcher.on('all', handler);
} else {
  console.log('Mode: multiple watchers');
  for (const path of paths)
    chokidar.watch(path, opts).on('all', handler);
}
```

And the following **do_stuff.sh**:

```
#!/bin/bash
echo 'Doing stuff...'
touch a
sleep .1s
touch b
sleep .1s
touch a
sleep .1s
touch b
sleep .1s
rm a
sleep .1s
rm b
sleep .1s
touch a
sleep .1s
touch b
sleep .1s
rm a
sleep .1s
rm b
echo 'Done'
```

Running `node index.js` and in a separate console `./do_stuff.sh` prints the expected event sequence:

```
Mode: multiple watchers
add     a
add     b
change  a
change  b
unlink  a
unlink  b
add     a
add     b
unlink  a
unlink  b
```

However, running `node index.js array` and the separate script, not all paths are properly monitored:

```
Mode: chokidar.watch(array)
add     a
change  a
unlink  a
add     a
unlink  a
```

**Expected behavior**
The event sequence triggered using a single watcher with multiple paths should be the same as using independent watchers for each path.

**Comment by paulmillr** [comment]
Does this happen with chokidar 3.3?

**Comment by albertobastos** [comment]
@paulmillr Yes, the outcome is exactly the same using version 3.3.0.

**Comment by dperetti** [comment]
Having the same issue but in my case only `'raw'` is not called in my first instance if another instance is created.
