### ISSUE TITLE
Vagrant HMR problem

### ISSUE THREAD

**Issue by zeravcic** [paulmillr/chokidar#1013]
Hi,
I don't know if it's related to a Chokidar file watcher, but please take a look at the Hot Module Replacement problem described on:

- Create-nuxt-app issue "[Laravel Homestead and Nuxt HMR problem](https://github.com/nuxt/create-nuxt-app/issues/550)" or

- Laracast forum discussion "[Laravel homestead and nuxt](https://laracasts.com/discuss/channels/vue/laravel-homestead-and-nuxt#reply-617075)".

Any heeelp?

**Comment by zeravcic** [comment]
Simple test with Nuxt.js: https://github.com/nuxt/nuxt.js/issues/7553#issuecomment-646589883

**Comment by FerchoCarcho** [comment]
> It seems that problem is with Chokidar [v3.4.0](https://github.com/paulmillr/chokidar/tree/3.4.0)...
> 
> Simple test with Nuxt.js: [nuxt/nuxt.js#7553 (comment)](https://github.com/nuxt/nuxt.js/issues/7553#issuecomment-646589883)

Did you Find a Solution? It just update itself correctly when modifying the "nuxt.config.js" but nothing happens when changing something like text in "index.vue"

**Comment by zeravcic** [comment]
@FerchoCarcho It seems to work now, but yes, with occasional exceptions. I definitely don’t have full confidence in HMR.

Btw, sometimes recognizes a completely unrelated file when re-building content, I don't know why.

Now I use it with support for [TypeScript](https://typescript.nuxtjs.org/) (`"dev": "nuxt-ts"`) but i don't know is it important information :unamused:

Maybe for further monitoring: https://github.com/nuxt/nuxt.js/issues/5550
