### ISSUE TITLE
Explore shrinking the size of the library by 50% by removing glob support

### ISSUE THREAD

**Issue by fabiospampinato** [paulmillr/chokidar#1016]
[It seems](https://bundlephobia.com/result?p=chokidar@3.4.0) that about half the size of chokidar comes from glob-related features, I don't actually use any globs with chokidar so I'm kind of paying the weight and startup price for nothing.

I think it could be a good idea to offer a "chokidar-core" version of the library that doesn't support globs directly, and then "chokidar" proper would just provide glob support on top of it, basically as far as the user is concerned "chokidar" would stay the same, but there would be also a much smaller "chokidar-core" version available.

What do you think? I can probably eventually put in the time required for making this change and submit a PR for this.

**Comment by paulmillr** [comment]
Yeah, maybe
