### ISSUE TITLE
Watching directory with "." in the name

### ISSUE THREAD

**Issue by chenluu** [paulmillr/chokidar#1019]
When watching a directory that has a "." in the name eg. "my.folder". 

File Events are not triggered. However, if I rename the folder to "my_folder"

**Versions:**
 - Chokidar version3.4
 - Node version 12.18.2
 - OS version: Windows 10

**To Reproduce:**
Attempt watching a folder with a "." in the name.

```
const dir = "C:\Users\user\Desktop\my.folder\";
const chokidar = require("chokidar");
watcher = chokidar.watch(dir, {
      persistent: true,
      ignoreInitial: true,
      disableGlobbing: true
  });
watcher.on('add', async function(path) {

          console.log('Added -> ' + path)
      });
```

**Comment by aleclarson** [comment]
This isn't a problem in [filespy](https://github.com/alloc/filespy), an alternative to chokidar.
