### ISSUE TITLE
node 12.3.1 upath

### ISSUE THREAD

**Issue by McFlat** [paulmillr/chokidar#1021]
**Describe the bug**

yarn install v1.17.3
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
[3/5] 🚚  Fetching packages...
error upath@1.0.4: The engine "node" is incompatible with this module. Expected version ">=4 <=9". Got "12.3.1"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**Comment by nicograef** [comment]
Are you sure this is related to chokidar? Chokidar uses upath v1.2.0 (not 1.0.4)
Where do you run the `yarn` command?
