### ISSUE TITLE
Node Chokidar syntax error in the module's index.js

### ISSUE THREAD

**Issue by bharatpatil108** [paulmillr/chokidar#1022]
![image](https://user-images.githubusercontent.com/63630856/88769882-a1ec2d00-d19a-11ea-879d-d06f2fc4a096.png)

"chokidar": "^3.3.1",
    "electron-packager": "^14.2.1",
    "electron-rebuild": "^1.11.0",
    "grpc": "^1.24.2"
 - Node version [ 13.5.0, 
 - OS version: [Windows 10]

**To Reproduce:**

const chokidar = require('chokidar');

 var watcher = chokidar.watch("C:\\Logs\\", {ignored: /[\/\\]\./, persistent: true});

watcher.on('add', function(path) {
    console.log('File', path, 'has been added');

  })
  .on('addDir', function(path) {console.log('Directory', path, 'has been added');})
  .on('change', function(path) {console.log('File', path, 'has been changed');})
  .on('unlink', function(path) {console.log('File', path, 'has been removed');})
  .on('unlinkDir', function(path) {console.log('Directory', path, 'has been removed');})
  .on('error', function(error) {console.error('Error happened', error);});

While running npm start, its giving below issue - 
![a](https://user-images.githubusercontent.com/63630856/88771070-55a1ec80-d19c-11ea-9a92-47fccca43edc.png)
 

What would be the cause?

**Comment by paulmillr** [comment]
Seems like you are using old nodejs version instead of 13.5.
