### ISSUE TITLE
Performance issue when writing files atomically

### ISSUE THREAD

**Issue by fabiospampinato** [paulmillr/chokidar#1028]
**Describe the bug**

Writing to a file in a watched directory should be a O(1) operation as far as chokidar is concerned, but instead in some cases the number of files in the current watched directory matters, making this a O(n) operation.

In particular when writing files atomically a temporary file is written to disk, which I think under macOS causes [this function](https://github.com/paulmillr/chokidar/blob/95faa2fe42d1736b3c5bfbc0f17a9f0379b001f3/lib/fsevents-handler.js#L444) to be called, which my understanding is it scans the watched directory again, causing a significant performance issue.

**Versions (please complete the following information):**
 - Chokidar version: 3.3.1
 - Node version: 12.14.1
 - OS version: macOS 10.14

**To Reproduce:**

I don't have a gist for this issue, but essentially one only needs to write a file atomically (or just add a new file) in a watched directory with lots of files at the top level.

**Expected behavior**

Writing to a single file shouldn't scale with the number of top-level files present in the watched directory.

In this particular use case I have chokidar configured to ignore the added temporary file anyway, as a quick and dirty workaround for the issue I guess before doing any potentially expensive work chokidar should check if we actually care about that added path or not.

I'm not sure why the watched directory is being scanned at all, that doesn't sound like something efficient to do when a file is being added to the watched directory 🤔 

**Additional context**

Screenshot of the amount of work being performed when writing atomically to a single path, with ~2000 files at the root of the watched directory:

![image](https://user-images.githubusercontent.com/1812093/89720806-7527e900-d9d6-11ea-99b7-e90666e85378.png)

**Comment by paulmillr** [comment]
>I'm not sure why the watched directory is being scanned at all

Where is it scanned, which line?

**Comment by fabiospampinato** [comment]
@paulmillr I guess from here:

**Comment by paulmillr** [comment]
If the changed file is a directory, it reads directory contents.

**Comment by fabiospampinato** [comment]
I'm just writing a file in the watched directory, shouldn't a scan not be triggered under that circumstance?

**Comment by paulmillr** [comment]
I don't think it should be triggered.
