### ISSUE TITLE
Performance issue about throttling

### ISSUE THREAD

**Issue by fabiospampinato** [paulmillr/chokidar#1029]
**Describe the bug**

When lots of files are being watched the way throttling is currently implemented causes a performance issue.

**Versions (please complete the following information):**
  - Chokidar version: 3.3.1
  - Node version: 12.14.1
  - OS version: macOS 10.14

**To Reproduce:**

Watch a directory with lots of files, the following screenshots are the result of watching a directory with ~2000 files.

**Expected behavior**

Throttling shouldn't account for a sizable portion of the work being done by chokidar.

**Additional context**

First of all there's a significant amount of work caused by throttling:

![image](https://user-images.githubusercontent.com/1812093/89721054-2a5ba080-d9d9-11ea-80ff-003c12a51138.png)

Most of the time is being wasted just setting timeouts:

![image](https://user-images.githubusercontent.com/1812093/89721071-5545f480-d9d9-11ea-9ff7-91ed11789240.png)

I'm not sure if throttling is really necessary when emitting the first add events, but if it's needed it shouldn't account for this much work. 

Currently setting these timeouts is a O(n) operation, it could kind of be made a O(1) operation by setting an interval instead, which every 50ms or whatever loops through all throttled invocations, and if at least 50ms have passed since they got queued they are removed from the queue.

Once those timeouts elapse there's another big computation chunk that perhaps could be avoided:

![image](https://user-images.githubusercontent.com/1812093/89721117-fe8cea80-d9d9-11ea-943f-1a1e6ba04585.png)

Some of that work seems to be spent clearing out timeouts:

![image](https://user-images.githubusercontent.com/1812093/89721120-0ba9d980-d9da-11ea-9022-ac1ebeee2705.png)

It might be useful to note here that when the `clear` function is called from the timeout it doesn't make sense to clear out the timeout that just got triggered, as nothing would practically change, so perhaps we could save some time there by avoiding clearing out timeouts unnecessarily.

**Comment by fabiospampinato** [comment]
Apparently all the actions being throttled are also getting throttled for 0ms, which becomes 1ms under Node, that's a little weird, maybe on initial adds that shouldn't even happen 🤔

**Comment by paulmillr** [comment]
Fabio, thank you for doing the profiling!
