### ISSUE TITLE
Chokidar not watching folder with lot of files inside

### ISSUE THREAD

**Issue by pawel-miczka** [paulmillr/chokidar#1032]
**Describe the bug**

I found out today that when I'm trying to watch for changes on folder which contains a lot of files inside chokidar is not starting (not watching). Also no error occurs. I created empty folder to check if there is something wrong with my code but on empty folder it works fine.

**Versions (please complete the following information):**
Chokidar: 3.3.1
Node: 8.17.0

**To Reproduce:**
I have this code:

```js
let watcher = chokidar.watch(process.env.DIRECTORY_TO_WATCH, { ignoreInitial: true });

watcher
  .on('ready', () => consola.info(`Rozpoczęto nasłuchiwanie na ${process.env.DIRECTORY_TO_WATCH}`))
  .on('add', filePath => {
    PlateNumbersController.savePlateNumberFromFile(server, filePath);
  })
  .on('error', error => consola.error(error));
```

**Expected behavior**
It should work

**Comment by pawel-miczka** [comment]
And also "ready" event is not triggered. My folder's size I want to watch is 1.2GB.

**Comment by paulmillr** [comment]
Obviously, file watching works. Otherwise, people would have created an issue earlier, since chokidar is used everywhere.

Which means, the issue is specific to your files and your environment.

I can't help here much unless you provide a demo to reproduce the issue. Or, you can add console.logs to chokidar internals and see what's broken.

**Comment by pawel-miczka** [comment]
I think it might be problem with Node version because I have on my local env Node 12.x.x but on production I have Node 8.x.x. On my local computer it works fine even with big files. Anyway I fixed this by creating some new "cache" folder where I store files for later and move them there when they will appear on watched folder. Maybe I will try something else later. For now it works. Closing :)
