### ISSUE TITLE
Error from chokidar (C:\): Error: EBUSY: resource busy or locked, lstat 'C:\DumpStack.log.tmp'

### ISSUE THREAD

**Issue by brunofin** [paulmillr/chokidar#1037]
**Describe the bug**

I am trying to run Storybook 6 on Windows 10 and I get this error. Storybook is unable to run. On WSL2 and Docker under the exact same code, everything works fine.

The following error pops up:

```
Error from chokidar (C:\): Error: EBUSY: resource busy or locked, lstat 'C:\DumpStack.log.tmp'
Error from chokidar (C:\): Error: EBUSY: resource busy or locked, lstat 'C:\hiberfil.sys'
Error from chokidar (C:\): Error: EBUSY: resource busy or locked, lstat 'C:\pagefile.sys'
Error from chokidar (C:\): Error: EBUSY: resource busy or locked, lstat 'C:\swapfile.sys'
```

**Versions (please complete the following information):**
 - Chokidar version `3.4.1`
 - Node version `v10.15.0`, `v12` and `v14.11.0`
 - OS version: `Windows 10`

**To Reproduce:**

Try to run a storybook 6 project.

**Expected behavior**
Should launch.

**Comment by paulmillr** [comment]
you're watching swapfile and hibernation files. The error is legit. You should not be watching them. Watch something more granular e.g. C:\Files\dir, not C:\

**Comment by brunofin** [comment]
Sorry that was caused by a slash/backslash problem on my storybook settings on Windows.

**Comment by leolcao** [comment]
I find an related issue in the CMake Tools VS Code Extension: https://github.com/microsoft/vscode-cmake-tools/issues/1430.

and thanks for this issue to give me some idea.

**Comment by KarenGrigoryan92** [comment]
I still get this error
In watch parameters I have
ignored: /^.*\.(?!docx$)[^.]+$/,
It should ignore "C:\DumpStack.log.tmp"
