### ISSUE TITLE
Consider watching AST changes

### ISSUE THREAD

**Issue by bernardoadc** [paulmillr/chokidar#1038]
It could be an option to pass as parameter, a "plugin" of some sort, or maybe even a new related tool (in other repository). Please let me know if this is of your interest, if have tried in the past, if you think there are good reasons not do so, etc.

With AST option on, small unmeaningful changes wouldn't trigger change event (";", spaces, changing variable names in some cases). This could be even put together with minification (which would ignore variable names, imports, filenames imported, etc), all with performance impacts for sure.

Since this lib is used by a lot of other tools, this could get pretty handy. E.g.: watch that causes to reload servers. It will reload only if "compiled" code is different. PS: rollup uses this logic internally.

I can do a PR with some guidance, if this proposal is accepted

**Comment by paulmillr** [comment]
That's out of scope for my Chokidar vision — sorry. Feel free to fork the project to your needs.
