### ISSUE TITLE
[macos] watchPath seems to be false

### ISSUE THREAD

**Issue by RoXuS** [paulmillr/chokidar#1040]
**Describe the bug**

I serve lot of files (about 430) and certain files are not watched for some obscur reason.
I added some log before `fsevent.watch`, for example for these two files (they are symlink):

- /Users/julienrousseau/Documents/insight/monorepo/node_modules/@doubletrade/dt-queries-utils/dt-queries-table.js
- /Users/julienrousseau/Documents/insight/monorepo/node_modules/@doubletrade/dt-app/dt-notification.ts

The watch folder is `/Users/julienrousseau/Documents/insight/monorepo/node_modules/@doubletrade` after:
````
  if (couldConsolidate(parentPath)) {
    watchPath = parentPath;
  }
````
But only change on `dt-notification.ts` emit change event.

I don't understand why...

If I comment this:
````
  if (couldConsolidate(parentPath)) {
    watchPath = parentPath;
  }
`````

All my files are correctly watched.

**Versions (please complete the following information):**
 - Chokidar version ^3.4.0
 - Node version 12/13/14
 - OS version: Last macos

**To Reproduce:**

I don't know ...

**Comment by RoXuS** [comment]
More precision.

Two same folder but one is symlink:
`/Users/julienrousseau/Documents/insight/monorepo-new/packages` -> Launch event on `/Users/julienrousseau/Documents/insight/monorepo-new/packages/xx/x.js`
`/Users/julienrousseau/Documents/insight/monorepo-new/node_modules/@doubletrade` -> Doesn't launch event on `/Users/julienrousseau/Documents/insight/monorepo-new/node_modules/@doubletrade/xx/x.js`

**Comment by RoXuS** [comment]
Can ben solved by using the real path instead of symlink path, is it a good choice?
https://github.com/paulmillr/chokidar/pull/1041/files

**Comment by paulmillr** [comment]
the new tests at my mac keep failing. @RoXuS can you check this?

**Comment by RoXuS** [comment]
hi @paulmillr  on my mac it is ok?

Do you do something that special??
![Uploading image.png…]()

**Comment by paulmillr** [comment]
@RoXuS can you test it without .only?

**Comment by RoXuS** [comment]
yeah I get this error
![image](https://user-images.githubusercontent.com/3296671/111866718-bff7df00-896f-11eb-8a8c-b5fcedb54b99.png)

Tests doesn't seem to be unitary?
I check how to do that.

I have some other errors, you too?

**Comment by paulmillr** [comment]
yep...

**Comment by RoXuS** [comment]
these errors were present before my add?

**Comment by RoXuS** [comment]
ok on the previous commit I have these failed too... 

I'm trying to fix my test when we execute all tests.

**Comment by RoXuS** [comment]
I open a new PR about this issue -> https://github.com/paulmillr/chokidar/pull/1083
