### ISSUE TITLE
Apple M1 support?

### ISSUE THREAD

**Issue by camhart** [paulmillr/chokidar#1048]
Can anyone confirm whether this package works on Apples new m1 based machines (arm64)?

**Comment by 0xdeafcafe** [comment]
Yeah, I haven't run into any issues as of yet.

**Comment by paulmillr** [comment]
the most recent release supports native ARM fsevent tracking

**Comment by yibingxiong** [comment]
> the most recent release supports native ARM fsevent tracking

Hello! What changes you do to support M1? And which version?
