### ISSUE TITLE
tensorflow.js, chokidar, and gatsby.js

### ISSUE THREAD

**Issue by Hewlbern** [paulmillr/chokidar#1049]
**Describe the bug**

I'm trying to run tensorflow.js at the moment in gatsby. I am receiving a limit for file watchers error.

**To Reproduce:**

use gatsby. 

Install import * as bodyPix from '@tensorflow-models/body-pix'; 

Then load the npm module and run as below,

import * as bodyPix from '@tensorflow-models/body-pix'; 

async function loadAndUseBodyPix() {
  const net = await bodyPix.load();
  // BodyPix model loaded
}

This returns,

warning Error from chokidar (/home/incompleteness_hewlbern/Documents/Code_Projects/AR_Work/esatta-app/node_modules/timers-browserify): Error: ENOSPC: System limit for number of file watchers reached, watch '/home/incompleteness_hewlbern/Documents/Code_Projects/AR_Work/esatta-app/node_modules/timers-browserify/package.json'

**Expected behavior**
Just loads it lol
**Additional context**
very annoying

**Comment by paulmillr** [comment]
see readme
