### ISSUE TITLE
watcher.getWatched() returns {}, supposed to Returns an object representing all the paths on the file system being watched

### ISSUE THREAD

**Issue by miraclesumail** [paulmillr/chokidar#1050]
const watcher = chokidar.watch(".", {
  ignoreInitial: true,
  interval: 1000,
});

console.log(watcher.getWatched());
// output {}
why

**Comment by paulmillr** [comment]
because chokidar is asynchronous and won't immediately return watched paths

**Comment by ve3** [comment]
For anyone who may searching for how to make this work while it is always return `{}`.  
Here is the working sample.
```
watcher.on('ready', async () => {
    console.log(watcher.getWatched());
});
```

Just put it in `ready` event, that's all. 😀
