### ISSUE TITLE
await watcher.unwatch(path); not unlinking as expected

### ISSUE THREAD

**Issue by Abhishek150995** [paulmillr/chokidar#1054]
**Versions (please complete the following information):**
 - Chokidar version [^3.4.3]
 - Node version [v12.13.1]
 - OS version: [Windows 10]

**To Reproduce:**

I added a path to watching using **watcher.add(path)** -> it fired **'addDir'** event

but when I unwatched the same directory using **await watcher.unwatch(path);** watching is removed

But if I try to adding the path again to filewatch,-> it fired **'addDir'** event, but does not work on watching changes in directory.

Ideally prove a problem by isolating and making it reproducible with a very short sample program, which you could paste here:

```
Mentioned above
```

**Expected behavior**
Adding a path again for file watching should work (Add->Remove->Again Add)

**Comment by Abhishek150995** [comment]
@paulmillr Please suggest.
I simply want to add and remove same path from File watching recursively 
But if I add a path to File watching once and remove it
It does not respond as expected the next time I add the same path to FileWatching

**Comment by paulmillr** [comment]
update to chokidar 3.5
