### ISSUE TITLE
High CPU usage inside Docker Container

### ISSUE THREAD

**Issue by georgedbarr** [paulmillr/chokidar#1057]
**Describe the bug**

Hi all,

Noticed a potential bug in production where high CPU usage is causing the event loop to lock up. Chokidar is being run in a Docker Container inside a Kubernetes Cluster. This has been replicated in a local dev environment when running Chokidar with Node in a Docker Container.

It seems to be related to the number of files in the directory that is being watched, i.e. 10k files causes high CPU. Files size seems to not have an effect.

We are using polling as it is a network drive being watched.

**Versions (please complete the following information):**
 - Chokidar version 3.4.3
 - Node version: 12.15.0-alpine
 - OS version: Alpine Linux

**To Reproduce:**

Config values:
```
usePolling: true,
awaitWriteFinish: {
  stabilityThreshold: 5000,
  pollInterval: 250,
}
```

Watcher:
```
this.watcher = chokidar
  .watch(this.config.foldersPaths, this.watcherConfig)
  .on('add', () => {})
  .on('change', () => {})
  .on('unlink', () => {})
  .on('ready', () => {})
  .on('error', error => {});
```

Start the docker container with no files in the directory. CPU usage is normal. Run the above command to generate files and CPU spikes and stays high. Changing the files size seems to have no effect, nor does pollInterval.

Restarting the service with the files already in the directory also causes the CPU usage to stay high.

Removing the files leads to the CPU decreasing back down to normal levels.

**Expected behavior**
CPU usage to stay constant at low value.

Any help/ideas would be greatly appreciated!

**Comment by akmolina28** [comment]
Can confirm I am seeing this as well, in Docker for Windows as well as Debian.

**Comment by ElliotG** [comment]
Can confirm as well. It gets really bad at >500k files. Pretty much need a 3 cores dedicated to this problem. Would absolutely love an investment here.

**Comment by paulmillr** [comment]
@ElliotG if you'd "love an investment here", write some code for it. Or, "invest" into someone who writes code.

**Comment by ingles98** [comment]
Well I'm getting that with over 100k files on both linux docker container (on windows host) and directly on the host as well. Performance gets so bad with or without polling. With polling It goes a lot faster for the initial scan but uses a lot of resources and ends up hanging the app later on execution. Without polling it takes over 5 minutes for the initial scan and while it uses less resources it still ends up hanging the execution at some point.
