### ISSUE TITLE
Previously deleted folders don't get watched

### ISSUE THREAD

**Issue by BRA1L0R** [paulmillr/chokidar#1059]
**Describe the bug**

Previously deleted folders get completely ignored by chokidar

**Versions (please complete the following information):**
 - Chokidar version: 3.4.3
 - Node version 15.5.0
 - OS version: 5.10.3-arch1-1 (Arch linux with kernel 5.10)

**To Reproduce:**

chokidar config:
```js
chokidar
      .watch('.', {
        ignored: /.+\.(css)/,
        cwd: this.config.pagesDir,  // relative path
      })
```
(i also tried wit polling and fsEvents)

Reproducing is very easy:
- watch over a folder with chokidar
- create a folder (triggers event)
- create a file in the folder (triggers event)
- delete the folder without deleting the file first (triggers both events)
- recreate the same folder with the same name (triggers event)
- create a file with a random name in it (does not trigger any event)

even changing the file name does not trigger any event

am I missing something?

```
const chokidar = require('chokidar');
const fs = require('fs');
// One-liner for files and directories starting with 'test'
chokidar.watch('.', {}).on('all', (event, path) => {
  console.log(event, path);
});

fs.mkdirSync('folder')  // triggers event
fs.writeFileSync('folder/test.txt', 'testing 1'); // triggers event
fs.rmdirSync('folder', { recursive: true }) // triggers two events
fs.mkdirSync('folder') // triggers event
fs.writeFileSync('folder/test.txt') // SHOULD trigger an event DOES NOT trigger any event
// In a comment describe expected output versus observed problem
```

**Expected behavior**
Should trigger an event when a file is created in a folder that has previously been deleted and recreated

**Comment by paulmillr** [comment]
Have you tried using `master`?

**Comment by BRA1L0R** [comment]
Hey thanks for the suggestion, yeah it works by installing version `3.4.4`
