### ISSUE TITLE
change events triggered multiple times when writeFileSync is called

### ISSUE THREAD

**Issue by avaberlin** [paulmillr/chokidar#1066]
**Describe the bug**

**Versions (please complete the following information):**
 - Chokidar version    3.5.1
 - Node version  12.19.0
 - OS version:   Windows 10
**To Reproduce:**
   It is not every time to be reproduced. When files were written with 'fs.writeFileSync', sometimes multiple change events were triggered from chokidar with following statement:
  watcher.on('change', path => console.log(i++ + ' => ' + path));
  If 'usePolling' is turned on, then the problem is solved, only one change event is triggered. However, as you know, polling costs too much CPU.

**Expected behavior**
   one one change event is triggered when a file is changed. Or any ways to work around this issue.

**Comment by aleclarson** [comment]
This should be impossible in [filespy](https://github.com/alloc/filespy/) (an alternative to chokidar), thanks to event throttling.

**Comment by paulmillr** [comment]
@aleclarson you should add some benchmarks to your library. Also, even if this particular bug isn't present, you should add more tests :) We have like tons of tests on different platforms here.
