### ISSUE TITLE
Sub 1ms polling interval time?

### ISSUE THREAD

**Issue by MasterIO02** [paulmillr/chokidar#1068]
Hi, I'm here because of an issue I have with fs.watch in nodejs where it can't watch for a file correctly on Windows when it is used by another process (probably). The thing is that I need to have nearly instant report when the file has been changed, because sometimes it can be modified really fast and I can only get the last line of the text file.
I achieved this with fs.watch and 0.5ms interval but it is only working correctly on Linux. fs.watchFile however works on Windows but I can't set the interval below 1ms. Chokidar is the same. 
So, will there be a way to set the interval of chokidar below 1ms? I don't care for the CPU usage, I just need something that works on Windows.

**Comment by paulmillr** [comment]
not really, since we are using fs.watch/fs.watchFile
