### ISSUE TITLE
Events not emitted on IBM i platform

### ISSUE THREAD

**Issue by ThePrez** [paulmillr/chokidar#1069]
**Describe the bug**

Events not emitted at all on IBM i platform.

**Versions (please complete the following information):**
 - Chokidar version 3.2.1
 - Node version 10.23.1
 - OS version: IBM i 7.4

**To Reproduce:**
To reproduce, attempt to use the chokidar library on the IBM i platform. Events seem to be not emitted at all. 
This causes several things to not work properly, for instance the `--watch` parameter of PM2. 

**Expected behavior**
Events are expected to be emitted as documented. 

**Additional context**
I believe the underlying root cause is simply that the underlying `fs.watch()` support [is not available on the IBM i platform](https://nodejs.org/docs/latest/api/fs.html#fs_availability). A simple workaround is to use polling mode via `CHOKIDAR_USEPOLLING=1`, but I'll work on a small PR that defaults the behavior to polling mode for this platform.

**Comment by paulmillr** [comment]
ok
