### ISSUE TITLE
Flatten symlinks?

### ISSUE THREAD

**Issue by mihkeleidast** [paulmillr/chokidar#1072]
Context: I have a quite large monorepo that has a lot of nested and symlinked node_modules directories.

For a better visualized example, look at this file tree:
```
shared
  module_a
    node_modules
    index.js
modules
  module_b
    node_modules
      module_a
        .this_is_symlinked
        node_modules
        index.js
    index.js
  module_c
    node_modules
      module_a
        .this_is_symlinked
        node_modules
        index.js
    index.js
```

With this tree, when using `followSymlinks: true,` and watching the `modules` dir, the `module_a` directory (with all it's own dependencies in node_modules) is added to the file watcher twice. Note that this is a really simple example, in my actual project chokidar is watching approx 15000 directories, most of those are duplicate symlinked modules in node_modules directories.

What I'm asking - is it possible to flatten the watched symlinked dirs - so that the `module_a` directory is added to the file watcher only once? Or, would it even be more performant? Currently, if I change something in `module_a`, the change events are also emitted multiple times (since chokidar is watching essentially the same files multiple times).

**Comment by paulmillr** [comment]
It is possible, but requires some smart code. Unfortunately the code underneath is quite complicated and any edit could break cases of other people. Contributions are welcome, of course.
