### ISSUE TITLE
"depth" param in options has no effect

### ISSUE THREAD

**Issue by simann** [paulmillr/chokidar#1073]
Greetings everyone!

I am using chokidar in my electron application to watch a folder on my disk.

The folder i am watching is: "C:/data/"

I wanted to limit the depth  to 2 subdirectories and changed the "depth" param to 2

### Code

```
const folderToWatch = join('C:', 'data');

const watcher = chokidar.watch(folderToWatch, {
    ignored: /^\./,
    persistent: true,
    awaitWriteFinish: true,
    depth: 2,
});
```

### Folder Structure

```
data
│   tree.jpg
│
└───pictures
│   │   cat.jpg
│   │
│   └───sky
│       │   cloud.jpg
│       │
│       └───space
│       │     │   iss.jpg

```

### Expected Behavior
Only tree.jpg, cat.jpg and cloud.jpg are added

### Actual Behavior
tree.jpg, cat.jpg, cloud.jpg and iss.jpg are added.

These logs are coming from the 'add' event

```
 3.2.2021, 11:48:36 [CData] tree.jpg added
 3.2.2021, 11:48:36 [CData] pictures\cat.jpg added
 3.2.2021, 11:48:36 [CData] pictures\sky\cloud.jpg added
 3.2.2021, 11:48:36 [CData] pictures\sky\space\iss.jpg added
```

Starting with data as root(depth 0). I would expect everything till "sky"(depth 2) to be added but everything under "space" (depth 3) is added aswell. Can anyone confirm or is my usage of the parameter wrong?

Thanks in advance

**Comment by paulmillr** [comment]
try maybe depth 1

**Comment by simann** [comment]
I reinstalled the module and it is working now.

Looks like  there was an error in my node_modules. Anyway this can be closed.

Sorry for the inconvenience.
