### ISSUE TITLE
watcher.getWatched() not returning Updated List 

### ISSUE THREAD

**Issue by Abhishek150995** [paulmillr/chokidar#1075]
When I add a Directory path to watching the list returned by watcher.getWatched() is has updated Directory path

But if I remove a Directory path from watching by await watcher.unwatch('dirpath'); watcher.getWatched() does not remove the dir path being unwatched watching

@paulmillr Please suggest, Thanks in advance

**Comment by paulmillr** [comment]
add operation is asyncronous, you need to listen to `add` event etc
