### ISSUE TITLE
Create event for `changeDir`

### ISSUE THREAD

**Issue by bogca** [paulmillr/chokidar#1078]
Create an event for changeDir. Because when you delete a directory, it publishes two events. One for 'unlinkDir' the older dir, and other 'addDir' for the new one.

This can even done?

**Comment by paulmillr** [comment]
example?

If `addDir` is getting published when a dir is removed, then it's a bug

**Comment by bogca** [comment]
When I change a dir name, I receive two consecutive event changes. `unlinkDir` with the old name and then `addDir` with the new name.
Is this expected behaviour?

**Comment by paulmillr** [comment]
yes, expected

I don't see an easy way to add `changeDir` event.
