### ISSUE TITLE
TypeError: The "original" argument must be of type Function

### ISSUE THREAD

**Issue by finnmerlett** [paulmillr/chokidar#1086]
**Describe the bug**

Tried the basic one-liner for current directory, in my create-react-app project. Got a TypeError immediately.

**Versions (please complete the following information):**
 - Chokidar version 3.5.1
 - Node version 14.5.0
 - OS version: Ubuntu 20.04.2 LTS

**To Reproduce:**

Open terminal in a new folder
Run `npx create-react-app test-app`
Run `cd test-app`
Run `npm i chokidar`
Open `./src/index.js`
Paste in the basic example usage under the imports
```javascript
const chokidar = require('chokidar');

// One-liner for current directory
chokidar.watch('.').on('all', (event, path) => {
  console.log(event, path);
});
```
Back to terminal and run `npm start`
Observe immediate error
![image](https://user-images.githubusercontent.com/49064567/113293108-422bc000-92ed-11eb-9752-f33024c5f22c.png)

**Expected behaviour**
No error.

I feel like I'm missing something obvious here, but I can't see what it could be.

**Comment by paulmillr** [comment]
Chokidar is for nodejs, not for browser react apps
