### ISSUE TITLE
If UNC folder connection is interrupted and connected again, chokidar uploads all the files

### ISSUE THREAD

**Issue by suhas2390** [paulmillr/chokidar#1089]
I need to watch a shared folder hosted on remote machine(window machine). I have updated my code using **usePolling : true** to keep watching on shared folder. I am facing an issue getting list of updated files when network connection is interrupted. 
I could see an issue like when network connection is interrupted and after it reconnected, Chokidar notifies for all the files inside that shared folder if any of the file is updated in that down time.

Expected behavior is like when network is reconnected, it should notify only for those files which are updated in that down time. 

Is there a configuration or code change which I have to made to handle this case?

Thanks for the help!

**Comment by suhas2390** [comment]
Hi @paulmillr 
Is there any solution for this issue available?
Thanks!

**Comment by paulmillr** [comment]
Any improvements would be welcome. Personally, I don't have much time to work on the issue.
