### ISSUE TITLE
Setting depth 0 doesn't report changes

### ISSUE THREAD

**Issue by Nokel81** [paulmillr/chokidar#1095]
**Describe the bug**

Setting `depth: 0` while watching a single file for changes does not report changes. Even though `raw` does.

**Versions (please complete the following information):**
 - Chokidar version: 3.5.1
 - Node version: v12.20.1
 - OS version: macOS 10.15.7

**To Reproduce:**

```
const chokidar = require('chokidar');
const fs = require('fs');
// One-liner for files and directories starting with 'test'
chokidar.watch('/path/to/file', {
    followSymlinks: true,
    depth: 0, // shallow
    disableGlobbing: true,
}).on('change', (event, path) => {
  // never fires
  console.log(event, path);
});
fs.writeFileSync('test.txt', 'testing 1');
// In a comment describe expected output versus observed problem
```

**Expected behavior**
`depth: 0` should only apply to folders being watched not files.

**Comment by Nokel81** [comment]
@paulmillr If this is completed which PR fixed it?

**Comment by paulmillr** [comment]
https://github.com/paulmillr/chokidar/issues/1336
