### ISSUE TITLE
persistent true holds main process

### ISSUE THREAD

**Issue by zenz34** [paulmillr/chokidar#1106]
**Describe the bug**

If set persistent to be true, when the main process ends, it still holds the process.

**Versions (please complete the following information):**
 - Chokidar version 3.5.1
 - Node version 12.18.3
 - OS version: Mac OS 10.15.7

**To Reproduce:**
```
    const chokidar = require('chokidar');
    watcher = chokidar.watch(this._options.path, {
      persistent: true,
      ignoreInitial: true,
      followSymlinks: false,
      awaitWriteFinish: true
    });

    watcher.on("all", () => {
      clearTimeout(this._timer);
      this._timer = setTimeout(somf_fuc(this), 5000).unref();
      return;
    });
.....
 ```

And when the main process is ended, chokidar still holds the process.

**Expected behavior**
Not hold the process.

**Comment by paulmillr** [comment]
set persistent to false then. that's like the only purpose of this property.
