### ISSUE TITLE
UNC folder watch triggers only 'raw' event, on 'add' or 'change' are never triggered

### ISSUE THREAD

**Issue by Cinezaster** [paulmillr/chokidar#1114]
**Describe the bug**

We're watching a unc mounted folder for added xml files.
'ready' event triggers after initiation
On adding xml files to the folder no other events are triggered except 'raw' which trigger 'change' event.
The raw event is triggered on all files in the folder and ignores the glob, but I expect this to be expected behaviour.

For testing purpose we also added fs.watch on the folder and it triggers the same changes as we see in raw.

**Versions:**

 - Chokidar version: 3.5.1
 - Node version: 16
 - OS version: Windows 10

**Comment by paulmillr** [comment]
No test case?

**Comment by Cinezaster** [comment]
@paulmillr it magically fixed itself. 
Chokidar watches the files on the UNC folder but I can't fs.read them anymore, can find the drive, something is off with the server I'm working on. Not a chokidar problem.
