### ISSUE TITLE
The library is old so I want you to update it.

### ISSUE THREAD

**Issue by famibee** [paulmillr/chokidar#1115]
Due to security issues, the library is out of date and I would like you to update it.
セキュリティの問題から、ライブラリが古いので更新して欲しいです。

| Lib | Now | Latest |
|---|---|---|
| glob-parent | ~5.1.0 | 6.0.0 |

https://david-dm.org/paulmillr/chokidar

| Lib | Now | Latest |
|---|---|---|
| @types/node | ^14 | 15.12.2 |
| dtslint | ^3.3.0 | 4.1.0 |
| mocha | ^7.0.0 | 9.0.0 |
| sinon | ^9.0.1 | 11.1.1 |
| upath | ^1.2.0 | 2.0.1 |

https://david-dm.org/paulmillr/chokidar?type=dev

**Comment by paulmillr** [comment]
glob-parent 6 does not support nodejs 8

**Comment by famibee** [comment]
Thank you for your answer.
