### ISSUE TITLE
Events may be lost when Use in React + Electron + Webpack

### ISSUE THREAD

**Issue by zhangxuyang950313** [paulmillr/chokidar#1122]
**Describe the bug**

**Versions (please complete the following information):**
 - Chokidar version 3.5.2
 - Node version v12.8.3
 - OS version: MacOS 11.4

**To Reproduce:**

Steps to reproduce the behavior. Include filename and chokidar config.

Ideally prove a problem by isolating and making it reproducible with a very short sample program, which you could paste here:

```
const chokidar = require('chokidar');
const fs = require('fs');
// One-liner for files and directories starting with 'test'
chokidar.watch('test*', {})
.on('add', (event, path) => {
  console.log(event, path);
})
.on("unlink", (event, path) => {
 console.log(event, path)
});
fs.writeFileSync('test.txt', 'testing 1');
// In a comment describe expected output versus observed problem
The same code above, in React + Electron could be lost events, but in node it could not
```

Most valuable could be one or more test cases for [test.js](https://github.com/paulmillr/chokidar/blob/master/test.js) to demonstrate the problem.

**Expected behavior**
A clear and concise description of what you expect to happen.

**Additional context**
Optionally nice to know what project you are working on.

**Comment by davidliudev** [comment]
i seem to run into similar issues above.
is this ticket being investigated since it has been a full year since this ticket was last updated

**Comment by davidliudev** [comment]
i could provide more information on my end:

when I introduced 100ms delay between chokidar.watch using setTimeout and async await, then the file will not be missed.

It seems that when you add a watcher and then create a file immediately after, the event will always be lost in React+Electron environment.

**Comment by davidliudev** [comment]
And this also only shows up in electron+react and works normally in nodejs.

**Comment by davidliudev** [comment]
Chokidar version 3.5.3
"electron": "^19.0.11",
"react": "^18.1.0",
macos: 12.3.1
