### ISSUE TITLE
any recommended way of running this in the bg?

### ISSUE THREAD

**Issue by noahehall** [paulmillr/chokidar#1124]
not a bug - dont fault for me deleting the template.

I am using this with [ultra runner](https://github.com/folke/ultra-runner)

thus:
 - when using the chokidar node api to watch files, it creates a long running process
 - the chokidar proces never exits (as expected)
 - the ultra-runner is unable to display the remaining scripts stdout/errs

I was thinking of using a child process to invoke the chokidar watch, then use ultra-runner to monitor whats happening.

However, does anyone have a better/simpler approach?

Thx!
you can [see my logic here if  that helps](https://github.com/noahehall/nodeproto/tree/setup-inception/tools/inception/index.mjs)

**Comment by paulmillr** [comment]
use `persistent: false`

**Comment by noahehall** [comment]
Hi @paulmillr 

unfortunatley `perisstent: false` does not evoke the watcher on file change?

here is my chokidar config:
`
import path from 'path';

export const chokidarConfigDefault = {
    alwaysStat: true,
    atomic: true,
    awaitWriteFinish: { stabilityThreshold: 2000, pollInterval: 100 },
    binaryInterval: 300,
    cwd: path.resolve('..'),
    depth: 99,
    disableGlobbing: false,
    ignored: path => [
      /\/(dist|test|node_modules)\//,
      /\.test\./, // files containing .test.filetype
      /(^|[\/\\])\../, // dotfiles
    ].some(regex => regex.test(path)),
    ignoreInitial: true,
    ignorePermissionErrors: false,
    interval: 100,
    persistent: false,
    awaitWriteFinish: true,
    useFsEvents: false,
    usePolling: true,
    usePolling: false,
  }
`

**Comment by noahehall** [comment]
ahh nevermind it does work! i just dont get the logs in cli (of course)

thx!
