### ISSUE TITLE
How to find PID of process running chokidar when `persistence:false`  ?

### ISSUE THREAD

**Issue by noahehall** [paulmillr/chokidar#1125]
This is not a bug, im sure its just my ignorance...

How do I find the PID of the process running chokidar when using `persistence:false` in the chokidar config?
I've tried searching `ps aux | grep node` and its not there

what am I doing wrong?

**Versions (please complete the following information):**
 - Chokidar version [e.g. 3.2.1 or commit hash] latest
 - Node version [e.g. 12.11.0, ensure you are using the latest node.js] latest
 - OS version: [e.g. Ubuntu 19.04 or MacOS 10.15 or Windows 10] ubuntu 21.04

**To Reproduce:**
[you can run this file](https://github.com/noahehall/nodeproto/blob/setup-inception/tools/inception/index.mjs)

**Comment by paulmillr** [comment]
https://lmgtfy.app/?q=nodejs+print+process+pid
