### ISSUE TITLE
Doesn't work with relative paths

### ISSUE THREAD

**Issue by esfomeado** [paulmillr/chokidar#1126]
**Describe the bug**

I'm trying to listening for changes in a set of .yaml files on a config folder. So I have set the path to relative ./config but it only checks on the root folder for changes and not on the config folder.

**Versions (please complete the following information):**
 - Chokidar version: 3.5.2
 - Node version: v16.1.0
 - OS version: Windows 10

**To Reproduce:**

Steps to reproduce the behavior. Include filename and chokidar config.

Ideally prove a problem by isolating and making it reproducible with a very short sample program, which you could paste here:

```
const chokidar = require('chokidar');
const watcher = chokidar.watch('./config', {
    persistent: true,
    ignored: (filename: string) => path.extname(filename) !== '.yaml',
    awaitWriteFinish: true
})
```

Most valuable could be one or more test cases for [test.js](https://github.com/paulmillr/chokidar/blob/master/test.js) to demonstrate the problem.

**Expected behavior**
Should listen for file changes on the config folder instead of the root one.

**Additional context**
The watcher is on a package that I created with a cli command that I can run anywhere from my laptop. It works fine with fs but not with chokidar.

**Comment by paulmillr** [comment]
does it work with absolute path? if not, then it's a problem isolated to your system

**Comment by esfomeado** [comment]
@paulmillr It does work fine with absolute path.

**Comment by esfomeado** [comment]
Found the issue but discovered another.

`ignored: (filename: string) => path.extname(filename) !== '.yaml',`

I thought that this was suppose to ignore all the files that don't end with the .yaml extension but it doesn't.
It will compare the folder name that in this case is called config and since it doesn't have the .yaml at the end it will fail and not add it which makes this feature kind useless if you only want to filter by a file type.
