### ISSUE TITLE
Issue: Installing Chokidar on Node 15 installs v2, then warns it's not compatible

### ISSUE THREAD

**Issue by Sunhat** [paulmillr/chokidar#1133]
**Describe the bug**

Installing Chokidar with Node 15 installs v2 and says v2 will break on Node 14+
Installing Chokidar with Node 16 does not
Installing Chokidar on Node 15 and specifying latest version of 3.5.2 also doesn't work with current app (laravel octane) and warns of package normalize-path not installed. Doesn't happen on Node 16.

**Versions (please complete the following information):**
 - Chokidar version v2,v3
 - Node version: 14,15,16
 - OS version: Docker (Not sure on dist, apline or ubuntu)

**To Reproduce:**

1. nvm use 15
2. npm install chokidar --save-dev
3. lol

**Expected behavior**
Version 3 is installed, not version 3. And for version 3 to work with Node 15 as Chokidar says it does

**Comment by paulmillr** [comment]
Nodejs v15 is officially unsupported. Use v16.

**Comment by paulmillr** [comment]
I mean unsupported by nodejs, not by chokidar. Only v12, v14, v16 are supported. Others may have terrible bugs
