### ISSUE TITLE
Question: is there a way to fire synthetic events?

### ISSUE THREAD

**Issue by joaotavora** [paulmillr/chokidar#1134]
I need to interpret certain events to certain files A _as if_ they were change events to some other file B, who is also on a separate watcher. Currently, I do this by watching A and then touching B - in the actual file system - from A's handler. This works, but it'd be nicer to programatically fire this event to B's watcher.

**Comment by paulmillr** [comment]
.emit()

**Comment by joaotavora** [comment]
I see. It's an EventEmitter! Next best thing would be another word on what to call it with so that the watcher client doesn't know it's fake.  Any docs on that?  What do I call `.emit()` with so that the client sees a "change" event?

**Comment by joaotavora** [comment]
Seems that at least three separate calls to `watcher.emit()` are needed:

- One with `raw`, `change` and `{watchedPath: <absdir>}` args
- Another with `all`, `change`, `<abspath>`, `<Stats>`
- Another with `change`, `<abspath>`, `<Stats>`

Maybe more, who knows.  Anyway this works. Think it'd make sense for chokidar to have some kind of `fakeEmit()` to hide this complexity.
