### ISSUE TITLE
Chokidar doesn't find files on network drive while running with PM2

### ISSUE THREAD

**Issue by sashmaaan** [paulmillr/chokidar#1135]
## Description
Watching a directory on your local computer works with both: starting your app regulary with node or with PM2, but if the directory is on another server then it only works with the regular node start, but not with PM2.

## Versions:
Windows 10
node: v14.17.0
chokidar: 3.5.2

## To Reproduce:
Simply watching script with a path to a network drive.
```
const chokidar = require('chokidar');

const path = 'L:/**/*.*'; // network drive to \\file01\EDV\I-SAS001\watchDir

chokidar.watch(path, {
    usePolling: true,
    awaitWriteFinish: true,
})
.on('add', (path, stats) => console.log(`${path} added`))
.on('ready', () => console.log(`Initial scan complete. Ready for changes`));
```

Executing this with 
```
node test.js
```
works like expected. All the files inside recursively will be found and listesd with the initial scan.

Executing it with
```
pm2 start test.js
```
and read the logs i only get the "Initial scan complete. Ready for changes" log message.

Sames happens if i install the node script with [node-windows](https://github.com/coreybutler/node-windows)

**Comment by paulmillr** [comment]
Yeah we have tons of issues for network drives

**Comment by sashmaaan** [comment]
I made some more tests and this is not about network drives!

Even when i use a local directory i dont get any events fired **when this will be started from a windows service or from PM2.**
