### ISSUE TITLE
Bump glob-parent to resolve ReDos Vulnerability

### ISSUE THREAD

**Issue by chaymankala** [paulmillr/chokidar#1136]
Please upgrade glob-parent to v6.0.1, as they resolved the ReDos Vulnerability, in this version
Reference: 
- https://github.com/gulpjs/glob-parent/releases/tag/v6.0.1
- https://github.com/gulpjs/glob-parent/pull/49

**Comment by paulmillr** [comment]
https://overreacted.io/npm-audit-broken-by-design/
