### ISSUE TITLE
Dependency vulnerability - Glob-parent

### ISSUE THREAD

**Issue by gustavocaspirro-mb** [paulmillr/chokidar#1137]
Hi, I would like to update the glob-parent version in the project.

Below, we have a print of vulnerability presented through of npm audit.

<img width="697" alt="Screen Shot 2021-08-03 at 14 45 36" src="https://user-images.githubusercontent.com/74983760/128063236-b0daaade-975e-41f9-96be-d6874ae0a713.png">

**Comment by paulmillr** [comment]
https://overreacted.io/npm-audit-broken-by-design/
