### ISSUE TITLE
deprecation notice says "less" when you mean "fewer"

### ISSUE THREAD

**Issue by kevinburke** [paulmillr/chokidar#1141]
If you try to install an old version of Chokidar, you get a message that reads:

```
Chokidar 2 will break on node v14+.
Upgrade to chokidar 3 with 15x less dependencies.
```

You want to use "fewer" here, not "less". Less is for things that aren't countable, like "there's less orange juice in my glass than in your glass." Fewer should be used for things that are countable, like the number of dependencies. "Alice has fewer pets than Bob."

**Comment by paulmillr** [comment]
Thanks Kevin, i'll update this

**Comment by jethas-bennettjones** [comment]
*bump*

**Comment by paulmillr** [comment]
Fixed
