### ISSUE TITLE
Possible size event - Detect filesize increase over time

### ISSUE THREAD

**Issue by samueleastdev** [paulmillr/chokidar#1146]
Hi,

I am looking to for a file size change event something like this.

```
const watcher = chokidar.watch('/Users');

watcher.on('filesize', (path, stats) => {

    console.log('File size: ', path);

});
```

Basically i am looking to scan the system for media files that are increasing in size in realtime. 

I can test with the following if I run ffmpeg on a file and convert it to webm with the slow preset like this.

`ffmpeg -i sky.mp4 -preset slow incremented.webm`

When this is running I can run.

`watch "lsof | grep webm" `

And it finds it the filesize is zero and if I keep running it you can see the file size change this is the event I am looking to trigger.

First run
```
drwxr-xr-x   4 picca  staff       128  9 Sep 08:49 .
drwx------@ 90 picca  staff      2880  9 Sep 08:48 ..
-rw-r--r--   1 picca  staff         0  9 Sep 08:49 incremented.webm
-rw-r--r--@  1 picca  staff  54719880 16 Jun 08:38 sky.mp4
```

Second run
```
drwxr-xr-x   4 picca  staff       128  9 Sep 08:49 .
drwx------@ 90 picca  staff      2880  9 Sep 08:48 ..
-rw-r--r--   1 picca  staff   2097152  9 Sep 08:50 incremented.webm
-rw-r--r--@  1 picca  staff  54719880 16 Jun 08:38 sky.mp4
```

Filesize has changed from 0 to 2097152 on the incremented.webm.

I was hoping to get this information for the change event using stats but I cannot seem to find a way to do this.

Is this possible somehow with this package I am going to keep looking into ways to do this.

Thanks

**Comment by paulmillr** [comment]
https://stackoverflow.com/questions/42363140/how-to-find-the-size-of-the-file-in-node-js
