### ISSUE TITLE
Ready never called with empty watcher

### ISSUE THREAD

**Issue by ccorcos** [paulmillr/chokidar#1148]
**Describe the bug**

When creating an empty watcher, the "ready"/"error" events are never called. I'd like to create the watcher and the add and remove paths dynamically.

**Versions (please complete the following information):**
-  "chokidar": "^3.5.2",
 - Node version v12.21.0
 - OS version: 
ProductName:	macOS
ProductVersion:	11.5
BuildVersion:	20G5023d
 

**To Reproduce:**

```
watcher = require("chokidar").watch([]).on("change", console.log).on("ready", () => console.log("ready")).on("error", () => console.log("error"))
```

**Expected behavior**
I would expect this watcher to become ready basically immediately. And I'd also expect `watcher.add` to return a promise that resolves once that path has been traversed and is ready again.

**Additional context**
My app has a sidebar, similar to VSCode or Finder, and I'm just trying to watch for files added or removed. The main process of the Electron app creates a watcher and the renderer process will add and remove things based on the sidebar state.

**Comment by zac-jacobson** [comment]
This would be great!
> And I'd also expect watcher.add to return a promise that resolves once that path has been traversed and is ready again.
