### ISSUE TITLE
EMFILE: too many open files when using yarn serve

### ISSUE THREAD

**Issue by gregfr** [paulmillr/chokidar#1155]
Greetings
I'm trying to learn VueJS and wrote a very simple project - therefore I don't understand everything under the hood, so forgive me if it's a dumb question.
Last time I ran the project a few days ago, everything was ok. When I start it today, I have:

```
Error: EMFILE: too many open files, watch '/myproject/public'
    at FSWatcher.<computed> (internal/fs/watchers.js:218:26)
    at Object.watch (fs.js:1525:34)
    at createFsWatchInstance (/myproject/node_modules/chokidar/lib/nodefs-handler.js:38:15)
```

I'm using linux Ubuntu, my `ulimit` is 1 million files, about 500k are actually open according to `lsof`, and the `public` folder contains 2 files.

What can I do?
Thanks in advance
Regards

**Comment by gregfr** [comment]
After trying about 20 times, `yarn serve` finally started....

**Comment by amitech** [comment]
Same problem and after restart system it works.
