### ISSUE TITLE
Add `disableCwdGlobbing` option to watcher

### ISSUE THREAD

**Issue by felipecrs** [paulmillr/chokidar#1168]
This is a follow-up of https://github.com/paulmillr/chokidar/issues/300, which is well explained by @appelgran at https://github.com/paulmillr/chokidar/issues/300#issuecomment-863199255.

The workaround is to `disableGlobbing` for everything and later I apply the glob on the file name by myself, which of course is not optimal.

**Comment by paulmillr** [comment]
#1195 will disable globs altogether
