### ISSUE TITLE
With Electron production

### ISSUE THREAD

**Issue by Xsaven** [paulmillr/chokidar#1170]
After I build the application in the production of it starts to write what this module is not
![image](https://user-images.githubusercontent.com/1726771/141816228-d002a4d8-60a2-414a-aea1-f15563a47622.png)
The initialization of the module is in the file of the electron index.
![image](https://user-images.githubusercontent.com/1726771/141816426-b8b3b7ed-39e2-4951-abd0-05280912904a.png)
Help me please!

P.S. - In the virginal mode, everything works bad too, when Devtool is open, then votes from time to time

**Comment by paulmillr** [comment]
Not chokidar problem
