### ISSUE TITLE
Does not call 'add' event for all existing files at startup

### ISSUE THREAD

**Issue by pyrsmk** [paulmillr/chokidar#1183]
**Describe the bug**

I'm in a situation where I have 8000+ files to process at chokidar startup. The problem is that the library wrongly handles only a subset of these files (which seems to be roughly a half of all existing files).

The files are located in subdirectories of the watched directory.

**Versions (please complete the following information):**
 - Chokidar version : 3.5.2
 - Node version : 8.15.1 (yeah, I know, it's old, but this is the version on our servers and we can't update it)
 - OS version : Ubuntu under WSL

**To Reproduce:**

Create a whole bunch of files in different subdirectories of the watched directory.

```js
const chokidar = require('chokidar')

let count = 0

chokidar.watch('some/directory/')
        .on('add', () => console.log(++count))
```

**Expected behavior**

To call the `add` event for each existing file.

edit: after some tests, the same happens on `add` event

**Comment by paulmillr** [comment]
Sorry — we don't support 8.15, the minimum supported version is 8.16 since 3.0, which has some important changes from earlier versions, including changes in abi etc.

Try using earlier chokidar versions.
