### ISSUE TITLE
Using chokidar to watch a filesystem - causing strange errors, if dirs do not exist while the watcher is created and then afterwards the dir is created

### ISSUE THREAD

**Issue by lost-bits** [paulmillr/chokidar#1201]
I am using the following Node RED Node: **node-red-contrib-watchdirectory**

This node uses chokidar to watch network folders too. it works so far, until you try to monitor a dir, which is not existing and as soon as this dir is created (or network restores), you receive an error like this:

I also created a issue at the node owner, but we did not figure out a solution:
https://github.com/fatoldsun00/node-red-contrib-watchdirectory/issues/8

this is the error, which is created (I think by chokidar) and caught by the code line no 66.

```
[Error: EBUSY: resource busy or locked, lstat 'c:\hiberfil.sys'] {
  errno: -4082,
  code: 'EBUSY',
  syscall: 'lstat',
  path: 'c:\\hiberfil.sys',
  _msgid: '99f550d09efdd4ca'
}
```

**Versions:**
 - Chokidar version 3.5.3
 - Node version  14.16.0
 - OS version: Windows 10
**To Reproduce:**
- install node red 2.2 (or similar)
- install the node: node-red-contrib-watchdirectory
- add the following flow:
`[{"id":"732eb1b2cec2ff51","type":"tab","label":"Flow 1","disabled":false,"info":"","env":[]},{"id":"b360be8a107d9597","type":"watch-directory","z":"732eb1b2cec2ff51","folder":"c:\\testDir","recursive":"2","typeEvent":"create","ignoreInitial":true,"ignoredFiles":"","ignoredFilesType":"re","name":"","x":160,"y":140,"wires":[["a736716f665f5a3e"]]},{"id":"a736716f665f5a3e","type":"debug","z":"732eb1b2cec2ff51","name":"File","active":true,"tosidebar":true,"console":true,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":450,"y":100,"wires":[]},{"id":"0f6b1f91f710916a","type":"catch","z":"732eb1b2cec2ff51","name":"","scope":null,"uncaught":false,"x":140,"y":260,"wires":[["ce42d3d28e8bac7c"]]},{"id":"ce42d3d28e8bac7c","type":"debug","z":"732eb1b2cec2ff51","name":"Err","active":true,"tosidebar":true,"console":true,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":550,"y":220,"wires":[]}]`

modify the original js file from the node to this:

the change in line 66 of throw(err) to node.error(err) and node.send(err) now shows the full error instead of just killing node RED
![image](https://user-images.githubusercontent.com/75374180/151985721-fd78e5c1-e237-4896-988c-6aac0871c1f4.png)

my current code is here (i think the problem might be caused by the way the watcher is defined:
```
module.exports = function(RED) {
    const chokidar = require('chokidar')
    const path = require('path');

  function  WatchDirectory(config) {
    RED.nodes.createNode(this,config);
    this.folder = path.normalize(config.folder)
    this.recursive = config.recursive;
    this.typeEvent = config.typeEvent;
    this.ignoreInitial = config.ignoreInitial;
    this.ignoredFiles = config.ignoredFiles || false;
    this.startListening();  
  }

  WatchDirectory.prototype.startListening = function() {
    var node = this;
    // Initialize watcher.
    const watcher = chokidar.watch(node.folder, {
      ignored: (filename) => {
        filename = path.normalize( filename )
        let file = path.basename(filename) 
        if (file && file.length && node.ignoredFiles.length){ 
          re = new RegExp(node.ignoredFiles)
          return re.test(file)
        }      
      },
      persistent: true,
      depth: node.recursive,
      ignoreInitial: node.ignoreInitial,
      awaitWriteFinish:true,
      usePolling:true,
      alwaysStat: true, 
    });

    let payload
    switch (node.typeEvent) {
      case 'create': 
        watcher.on('add', (filename, stats) => {
          payload = node.createMSG(filename, stats) 
          node.send(payload)
          node.status({fill:"green", shape: "dot", text: "add "+filename})
        })
        break;
      case 'update': 
        watcher.on('change', (filename, stats) => {
          payload = node.createMSG(filename, stats) 
          node.send(payload)
          node.status({fill:"green", shape: "dot", text: "update "+filename})
        })
        break;
      case 'delete': 
        watcher.on('unlink',(filename) => {
          payload = node.createMSG(filename) 
          node.send(payload)
          node.status({fill:"green", shape: "dot", text: "delete "+filename})
      })
      break;
    }

    watcher.on('ready', () => {
      setTimeout(() => {
        node.status({fill:"yellow", shape: "ring", text: "Listening..."})
      }, 10000)
    }).on('error', (err) => {
      node.status({fill:"red", shape: "dot", text: "Error : "+err.message})
//      throw(err)
       node.error(err)
node.send(err);
    })

    //on close
    node.on('close', () => {
      watcher.close()
    })
  }

  WatchDirectory.prototype.createMSG = function(filename, stats) {
      filename = path.normalize( filename )
      const file = path.basename(filename) 
      const filedir = path.dirname(filename) 
      return {file,filedir,filename, payload: filename, size: stats?stats.size:0}
  }

  RED.nodes.registerType("watch-directory",WatchDirectory);
}

```
- ensure C:\TestDir does not exist
- apply the flow
- create the dir (and get the error)

The node should find the new dir and start watching (and not create a error and do not watch).

I am working on a project watching a measurement PC and reading logs from the pc. Since standard node red does not work well with event driven watches in the network, chokidar in combination with node-red-contrib-dirwatcher could be a good solution.

**Comment by theirongiant** [comment]
I've been digging into this a little as I was seeing the a similar issue, it appears that if you pass a path that doesn't exist then it will start watching at the deepest part of the path that does exist. For cases where C:/ is the deepest existing part this is causing issues with system protected files.

This can be tested with this:

`const chokidar = require('chokidar');

const watcher = chokidar.watch('/does-not-exist');`

and triggered by changing a file sitting C:/  (I couldn't create one directly but had to create a blank text file in a directory and then dragged it into C:).

I added some logging to follow what was happening

`λ node index.js
index.add params {
  paths_: '/does-not-exist',
  _origAdd: undefined,
  _internal: undefined
}
nodef-handler._addToNodeFs params {
  path: '/does-not-exist',
  initialAdd: true,
  priorWh: 0,
  depth: 0,
  target: undefined
}
index.add params { paths_: '/', _origAdd: 'does-not-exist', _internal: undefined }
nodef-handler._addToNodeFs params {
  path: '/',
  initialAdd: true,
  priorWh: 0,
  depth: 0,
  target: 'does-not-exist'
}
nodefs-handler._watchWithNodeFs params { path: '/' }
nodefs-handler._watchWithNodeFs with opts.usePolling (false) setFsWatchListener params { path: '/', absolutePath: 'C:\\', options: { persistent: true } }

** manually edit text file in C: to trigger error **

node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: EBUSY: resource busy or locked, lstat 'C:\DumpStack.log.tmp'
Emitted 'error' event on FSWatcher instance at:
    at FSWatcher._handleError (C:\work\nodejs\scratch\chok-test\node_modules\chokidar\index.js:650:10)
    at NodeFsHandler._boundHandleError (C:\work\nodejs\scratch\chok-test\node_modules\chokidar\lib\nodefs-handler.js:303:43)
    at ReaddirpStream.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -4082,
  code: 'EBUSY',
  syscall: 'lstat',
  path: 'C:\\DumpStack.log.tmp'
}

Node.js v18.12.1`

Not sure if this is intended behaviour but I believe this is the cause of all the EBUSY related issues ([#1037](#1037)), ([#1237](#1237)) and others.
