### ISSUE TITLE
Module parse failed: Unexpected character for Electron + Angular

### ISSUE THREAD

**Issue by gh-amb** [paulmillr/chokidar#1202]
For a combination of Angular, Electron and Chokidar I get this error, when I'm trying to start the project:
> ./node_modules/fsevents/fsevents.node:1:0 - Error: Module parse failed: Unexpected character '�' (1:0)

Having read the similar topics from issues I get the problem, the native file is trying to be handled as a `.ts` or something, but it's not clear how to solve it for this particular stack.

What I've tried:
- Adding `**/*.node` in the `tsconfig.json` and `tsconfig.app.json` files (`exclude` property).
- Adding an asset configuration in the `angular.json` file.

 - Chokidar version 3.5.3
 - Node version 16.4.0
 - OS version: Mac OS 12.1
 - Angular 12

**Comment by paulmillr** [comment]
This is not chokidar issue

**Comment by gh-amb** [comment]
So do I understand it correctly that these 2 issues were chokidar issues since they got attention, help and were resolved?
https://github.com/paulmillr/chokidar/issues/1000
https://github.com/paulmillr/chokidar/issues/986

It's a third issue that appears here by the same reason, maybe it's possible to provide some guide for one of the most used frameworks?

**Comment by paulmillr** [comment]
@gh-amb no they did not receive any attention, I have also closed them just like i'm closing this one. 

If you want some guides, feel free to work on them and contribute a pull request.

**Comment by gh-amb** [comment]
That's very kind, thank you.

**Comment by paulmillr** [comment]
Yeah no one pays me to develop & maintain this software, you should appreciate that it even exists.

**Comment by 51n7** [comment]
To fix this issue in Vite React I needed to add this to the main config, hopefully this gives a clue to helping Angular or Vue.
```
export default defineConfig({
  build: {
    rollupOptions: {
      external: ["fsevents"]
    }
  },
  …
});
```

**Comment by TiagoSilvaPereira** [comment]
> To fix this issue in Electron + Vite React I needed to add this to the main config:
> 
> ```
> export default defineConfig({
>   build: {
>     rollupOptions: {
>       external: ["fsevents"]
>     }
>   },
> });
> ```
> 
> Hopefully this gives a clue to helping fix Angular or Vue.

Thank you very much!!! I had the following error:

```
could not load fsevents.node?commonjs-proxy (imported by node_modules/fsevents/fsevents.js): the argument 'path' must be a string or uint8array without null bytes. received './node_modules/fsevents/fsevents.node' error during build:
```
And your solution worked very well!! Thanks
