### ISSUE TITLE
9P filesystems are not working

### ISSUE THREAD

**Issue by zem** [paulmillr/chokidar#1206]
I have a problem on peertube that the lifestream is not starting. 

The Problem itself is very similar to this one https://github.com/Chocobozzz/PeerTube/issues/4308 .
 
Except that I did not run peertube on WSL but in a container on a KVM/libvirt VM for storage reasons my peertube instance is hosted on a big 9p pass through filesystem, mounted like this: 

`
stream /var/lib/containers/storage/volumes 9p trans=virtio,version=9p2000.L,rw 0 0 
`

It looks as if chokidar does not work on 9p filesystems.
As soon as I configure the affected path over on an ext4 filesystem streaming does work. 

As https://github.com/Chocobozzz/PeerTube/issues/4308 states that chokidar is looking for some files and playlists, I guess the root cause of the problem is a lack of support for 9p filesystems.

**Comment by rndevfx** [comment]
I just stumbled across this and even though it is a bit older, a short answer: the problem with 9p is that inotify is not supported. The solution is to use polling; just set the environment var `CHOKIDAR_USEPOLLING=true` for that.

For peertube (docker-compose) this can be done in the .env file which is used by docker compose and then it works fine.

https://github.com/libfuse/libfuse/wiki/Fsnotify-and-FUSE

**Comment by magoerlich** [comment]
"just disable the non-working feature" is a workaround, but not a solution.

Thanks for a workaround so far, but would be really great if the community could find an actual solution to this issue.
Not everyone has spare CPU time to waste on polling.
