### ISSUE TITLE
Adding require "chokidar" generates Uncaught TypeError: The "original" argument must be of type Function

### ISSUE THREAD

**Issue by dalgharib** [paulmillr/chokidar#1219]
**chokidar issue at JS code in Linux Centos 7:**

Trying to use chokidar to watch on file change. So I used the code: `const chokidar = require('chokidar');`
And when I run the process with `npm run start`, I got the following in the terminal:

>Compiled with warnings
>./node_modules/chokidar/lib/fsevents-handler.js
>Module not found: Error: Can't resolve 'fsevents' in '/node_modules/chokidar/lib'
>Search for the keywords to learn more about each warning.
>To ignore, add // eslint-disable-next-line to the line before

Then I run the following command:
`npm i fsevents@latest -f --save-optional`

And after that, the npm run start works fine, but trying to open the application, I got the following issue in the browser Console:

`Uncaught TypeError: The "original" argument must be of type Function`

In package.json -version:
`"chokidar": "^3.5.3",`

And I`m not planning to upgrade my Node version due to other reasons:
```
Node: v10.24.1
NPM: v6.14.12
```

**Please help!**

**Comment by RowinRuizendaal** [comment]
Any update o this?
