### ISSUE TITLE
glob-parent before 6.0.1 vulnerable to Regular Expression Denial of Service

### ISSUE THREAD

**Issue by swhite-oreilly** [paulmillr/chokidar#1230]
Seeing from dependabot: 

The latest possible version that can be installed is 5.1.2 because of the following conflicting dependencies:

-- requires glob-parent@~5.1.2 via a transitive dependency on chokidar@3.5.3
-- requires glob-parent@~5.1.2 via a transitive dependency on chokidar@3.5.3
-- requires glob-parent@~5.1.2 via chokidar@3.5.3
nodemon@2.0.19 requires glob-parent@~5.1.2 via chokidar@3.5.3
nunjucks@3.2.3 requires glob-parent@~5.1.2 via chokidar@3.5.3

The earliest fixed version is 6.0.1.

Resolution: Update glob-parent>=6.0.1

**Comment by ripwin** [comment]
#1191
