### ISSUE TITLE
Moderate vulnerability

### ISSUE THREAD

**Issue by opravil-jan** [paulmillr/chokidar#1231]
Regular Expression Denial Of Service (ReDoS)

glob-parent is vulnerable to Regular expression denial of service. The vulnerability exists due to an incorrect regex implementation on the enclosure variable. This vulnerability is caused by an incomplete fix of https://github.com/advisories/GHSA-ww39-953v-wcq6

Versions

    Chokidar version 3.5.3
    Node version 12.20.0
    glob parent current version : 5.1.2
    glob parent latest version: 6.0.2

To Reproduce:
Run a coverity scan on your package

Expected behavior
Chokidar with 0 vulnerability

Please update glob-parent dependency to latest/safe version

**Comment by zbryikt** [comment]
it seems that this is a false alarm?

https://github.com/paulmillr/chokidar/issues/1191
