### ISSUE TITLE
Update glob-parent dependency

### ISSUE THREAD

**Issue by Nnanyielugo** [paulmillr/chokidar#1232]
**Update `glob-parent` dependency**

`glob-parent` before 6.0.1  is vulnerable to Regular Expression Denial of Service (ReDoS). 

**Versions (please complete the following information):**
 - Chokidar version 3.5.3

**Additional context**
This issue gets caught by github actions package audit. `chokidar` currently uses `glob-parent` `5xx`.
More here: https://snyk.io/vuln/npm:glob-parent

**Comment by ovideozn** [comment]
Why was this issue closed as soon as it was opened? We're having the same issue and `npm audit fix` is not able to find a fix for it

**Comment by Nnanyielugo** [comment]
Because I saw this issue that directly references the problem: https://github.com/paulmillr/chokidar/issues/1191. So it seems like the problem does not actually exist and should be an issue with the build tool @ovideozn

**Comment by Nnanyielugo** [comment]
I can reopen if you think that would be useful.
