### ISSUE TITLE
Chokidar Vulnerability

### ISSUE THREAD

**Issue by lounsbrough** [paulmillr/chokidar#1233]
Need to update chokidar version to fix vulnerability: https://github.com/advisories/GHSA-cj88-88mr-972w

https://github.com/paulmillr/chokidar/blob/614748746c0f36e39f11145301df0bea3dafeeea/package.json#L19

**Comment by lounsbrough** [comment]
I put up a PR to bump the version, there are no contribution docs, and tests are failing in CI, so not sure how to move forward with this, but would defer to past contributors. https://github.com/paulmillr/chokidar/pull/1234

**Comment by paulmillr** [comment]
it would be great if you've spent more than one minute with this

**Comment by lounsbrough** [comment]
If you have any recommendations on next steps for testing or contributing let me know, I was just bringing visibility to the issue.

**Comment by paulmillr** [comment]
There is no vulnerability. I have created and pinned issue many months ago. https://github.com/paulmillr/chokidar/issues/1191

**Comment by lounsbrough** [comment]
I see, apologies.
