### ISSUE TITLE
Features: multiple events options for `.on()`

### ISSUE THREAD

**Issue by sudoaugustin** [paulmillr/chokidar#1249]
Sometimes we want to apply the same functions for different events. So I think it would be great if the `on` method accept multiple events

`chokidar.watch("some/paths").on('change, add', () => someFunc());`

(or)

`chokidar.watch("some/paths").on(["change", "add"], () => someFunc());`

**Comment by paulmillr** [comment]
Use `'all'` event, or do it manually with loop
