### ISSUE TITLE
CHOKIDAR_USEPOLLING and options.usePolling inconsistent on macOS

### ISSUE THREAD

**Issue by markphilpot** [paulmillr/chokidar#1251]
On macOS, when the option `usePolling` is set to true, `useFsEvents` is set to false (as a side effect).

When the env variable `CHOKIDAR_USEPOLLING=1` is set, it sets `usePolling` to true, but leaves `useFsEvents` as true.

Currently, I'm running into an issue in gatsby's source-filesystem plugin in how chokidar deals with hard links.  I specifically need `usePolling` to be true and `useFsEvents` to be false. (See https://github.com/gatsbyjs/gatsby/issues/36877 and https://github.com/gatsbyjs/gatsby/pull/36975)

The easiest solution would be to add a CHOKIDAR_USEFSEVENTS env variable so I can correctly emulate the behavior when using the options.

Another option would be to mimic the options behavior (`usePolling=true, useFsEvents=false`) when using the env variable.  The danger here would be anyone using the existing behavior.

If I can get some direction on which direction is better I can submit a PR that does it.

**Comment by paulmillr** [comment]
>Another option would be to mimic the options behavior (usePolling=true, useFsEvents=false) when using the env variable. The danger here would be anyone using the existing behavior.

that should be ok
