### ISSUE TITLE
glob-parent Regular Expression Denial of Service (ReDoS)

### ISSUE THREAD

**Issue by W0nderMuffin** [paulmillr/chokidar#1260]
Affecting [glob-parent](https://security.snyk.io/package/npm/glob-parent) package, versions >=6.0.0 <6.0.1

https://security.snyk.io/vuln/SNYK-JS-GLOBPARENT-1314294

**Comment by paulmillr** [comment]
@W0nderMuffin 😂

**Comment by Bartlebyy** [comment]
https://github.com/paulmillr/chokidar/issues/1191
