### ISSUE TITLE
Watching multiple non-existing files in the same directory results in all files other than the first one being ignored

### ISSUE THREAD

**Issue by vilicvane** [paulmillr/chokidar#1276]
**Versions (please complete the following information):**
 - Chokidar version 3.5.3

**To Reproduce:**

```js
const FS = require("fs");
const Chokidar = require("chokidar");

const watcher = Chokidar.watch(["file-1", "file-2"]);

watcher.on("add", (path) => console.log(path));

// BTW, on("ready") doesn't work either.
setTimeout(() => {
  FS.writeFileSync("file-2", ""); // file-1 would work.
}, 1000);
```

**Expected behavior**

All previously non-existing files should receive "add" event on creation.

**Additional context**

I traced down to the `NodeFsHandler#_handleRead()` method and the way it throttles is the cause:

https://github.com/paulmillr/chokidar/blob/0f163b89f3ae76607900aa48fec9fa3fdefd7ca1/lib/nodefs-handler.js#L456-L463

**Comment by ineshbose** [comment]
Has there been a workaround for this yet?
