### ISSUE TITLE
Module not found: Error: Can't resolve 'fsevents' in '..\chokidar\lib'

### ISSUE THREAD

**Issue by Yana-Work** [paulmillr/chokidar#1279]
Please help me with the following error:

WARNING in ./node_modules/glob-watcher/node_modules/chokidar/lib/fsevents-handler.js 7:17-36
Module not found: Error: Can't resolve 'fsevents' in 'C:\..\node_modules\glob-watcher\node_modules\chokidar\lib'

- Chokidar version : "^3.5.3"
- OS version: Windows 10 Pro N
- npm v9.3.1

**Comment by b-mendoza** [comment]
Are there any updates about this issue?

I'm having the same issue when using it on a M2 Mac

**Comment by JDESTM** [comment]
Same here on Windows with version 3.5.3.

**Comment by ablack34** [comment]
Also same issue, any resolution?

**Comment by MrFiregore** [comment]
+1

**Comment by ppcola** [comment]
+1

**Comment by paulmillr** [comment]
-1
