### ISSUE TITLE
Folder rename is not reported when using a pattern

### ISSUE THREAD

**Issue by Janpot** [paulmillr/chokidar#1285]
**Describe the bug**

When a folder is renamed and the original and new folder is part of a path that is covered by a glob that chokidar is watching, no events are fired.

**Versions:**
 - Chokidar version: 3.5.3
 - Node version: 18.16.0
 - OS version: MacOs 13.5

**To Reproduce:**

1. create a file `./hello/foo/file.txt`
2. run 
    ```ts
    const path = require('path');
    const chokidar = require('chokidar');

    chokidar.watch(path.resolve(__dirname, './hello/*/file.txt')).on('all', (event, filePath) => {
      console.log(event, filePath);
    });
    ```
3. run `mv ./hello/foo ./hello/bar`
4. no events are being fired

**Expected behavior**

an `unlink` and `add` event is fired for the rename. (This does happen when using `usePolling`)

**Comment by AlynxZhou** [comment]
I also reproduced this problem with @Janpot 's example but a little bit differently, I could get `add` event when moving a dir, but no `unlink` event.

**Comment by denysdovhan** [comment]
We experience a very similar problem, but with folder deletion. We use `chokidar` like this:

```ts
chokidar.watch([
  'src/dashboards/**/file.json',
  'src/site/**/file.json'
], {
  useFsEvents: false, // <-- THIS SOLVES THE PROBLEM
  ignoreInitial: true,
}).on('all', (eventName, path) => console.log({eventName, path}))
```

When we delete `dashboard` or `site` folders, neither `unlink` nor `unlinkDir` are emitted. The reason for that is this line:

https://github.com/paulmillr/chokidar/blob/7c50e25d10a497ce4409f6e52eb630f0d7647b97/lib/fsevents-handler.js#L316

When a file patter contains a glob, it gets returned, so update is not reported.

The solution for us is to set `useFsEvents: false`. It also [seems to be used widely by other various libraries](https://github.com/search?q=useFsEvents%3A+false&type=code).
