### ISSUE TITLE
Not Detecting New Files on External Drive in macOS

### ISSUE THREAD

**Issue by alminQSD** [paulmillr/chokidar#1296]
Environment:
- OS: macOS Sonoma 14.2.1 (23C71)
- Node.js version: v14.17.0
- Chokidar version: 3.5.3

Issue:
Chokidar fails to detect new files added to external and network drives on macOS. It functions correctly for local paths (e.g., `/Users/myUser/Downloads/testFolder`) and also works as expected on Windows for both local, network, and external drives. However, on macOS, it does not trigger 'add' events for new files in `/Volumes/MyExternalDrive`.

Steps to Reproduce:
1. Set up Chokidar to watch a path on an external or network drive.
2. Add new files to this path.
3. Observe that Chokidar does not emit 'add' events on macOS.

Expected Behavior:
Chokidar should detect and emit events for new files on external and network drives, similar to its behavior with local directories and as it does on Windows.

Additional Context:
- The issue persists even with `usePolling: true`.
- The external drive is formatted as exFAT.
- When the external drive is formatted as APFS, it functions properly.
- This issue is specific to macOS; the same setup works on Windows.

Any insights or suggestions would be greatly appreciated.

**Comment by mdivkovic-speech** [comment]
Bump. @paulmillr is this on the radar?

**Comment by paulmillr** [comment]
@mdivkovic-speech no. Why would it be?

**Comment by paulmillr** [comment]
#1305
