### ISSUE TITLE
Update brace module dependency

### ISSUE THREAD

**Issue by hmnelson13** [paulmillr/chokidar#1334]
**Describe the bug**

There is a vulnerability with braces 3.0.2 that has been patched with 3.0.3. Please upgrade the dependency to resolve this vulnerability.
[See more here.](https://github.com/advisories/GHSA-grv7-fg5c-xmjg)

**Versions (please complete the following information):**
 - Chokidar version 3.6.0
 - Node version N/A
 - OS version: N/A

**Comment by SethArchambault** [comment]
@paulmillr I know you've decided to focus on v4, but simply by changing the brace dependency from `3.0.2` to `3.0.3` you would instantly fix security vulnerabilities for all current users of `Mocha`. 

If you require a major upgrade, all the users of Mocha will need to wait for Mocha to do this upgrade, and all existing installations of Mocha will continue to have this vulnerability - so seems like the cost / reward ratio for putting out a quick security patch for chokidar is extremely high!
