### ISSUE TITLE
Release v4

### ISSUE THREAD

**Issue by paulmillr** [paulmillr/chokidar#1347]
- [x] Fix test errors
- [x] Fix test timeouts / implement timeouts correctly
- [x] Do a sanity check on code changes

cc @43081j - may need your help here

**Comment by 43081j** [comment]
I'm off the grid a lot for the next few days but I'll take a look when I can 👍

**Comment by 43081j** [comment]
@paulmillr looking into this, it seems the latest node 16.x has a couple of problems with the test runner:

1. nested `beforeEach` seem to cause only the deepest one to run, so all tests fail
2. on Linux and Mac, the test runner hangs before it even manages to run our code

seems fine on all later versions (18, 20, 22, in our case)

I don't really want to introduce hacky code to make the tests run on 16. do you think we need to support it?

**Comment by paulmillr** [comment]
If it’s “test runner problem”, we prob should not hack it

**Comment by 43081j** [comment]
I agree

I'll try fix the hanging ci runs

We will probably have to drop 16.x from ci at least (it is eol anyway)

**Comment by 43081j** [comment]
I seem to have fixed the hanging tests runs now, so if we have any failures, they should fail fast

**Comment by paulmillr** [comment]
I just saw macos tests which ran for 19 mins, and cancelled it. Probably not all issues have been resolved

**Comment by 43081j** [comment]
Do you have a link to a ci run that did this?

The ones I fixed were dangling async tasks. It's possible we still have some
