### ISSUE TITLE
right cleanup

### ISSUE THREAD

**Issue by celevra** [paulmillr/chokidar#1353]
Hi,

we are using chokidar to watch for unlink events but i'm not sure how to cleanup chokidar after the event is happened.
I'm using this
```
const watcher = chokidar.watch(FILENAME + ".json.lock").on('unlink', (path) => {
                                watcher.unwatch(path)
});
```

but it feels as of time (we have many watches and changes) the cpu time gets up and up and up.

regards

**Comment by paulmillr** [comment]
await watcher.close()

**Comment by celevra** [comment]
We are not working with promises as seen in the example
