### ISSUE TITLE
v4: types and jsdoc do not align

### ISSUE THREAD

**Issue by benmccann** [paulmillr/chokidar#1355]
**Describe the bug**

The `index.d.ts` file has:
```
    /**
     * Close watchers and remove all listeners from watched paths.
     * @returns {Promise<void>}.
     */
    close(): Promise<void> | undefined;
```

**Versions (please complete the following information):**
 - Chokidar version: 4.0.0

**To Reproduce:**

Open `index.d.ts`

**Expected behavior**

Types and docs should match

**Additional context**

This prevents `wrangler` from upgrading because it expects a `Promise<void>` to be returned:
```
src/dev/use-esbuild.ts(226,4): error TS2322: Type '() => Promise<void> | undefined' is not assignable to type '() => Promise<void>'.
```

**Comment by 43081j** [comment]
I think it should be `Promise<void>`

It may be worth annotating the return type in the source so we're certain it's always a promise (i.e to catch where we forgot to return one)
