### ISSUE TITLE
Discrepancy in provided types, `ChokidarOptions.ignore` is still of type `string | ((path: string) => boolean) | undefined`

### ISSUE THREAD

**Issue by Atulin** [paulmillr/chokidar#1358]
**Describe the bug**

![image](https://github.com/user-attachments/assets/8cb59627-fa51-4a3e-b70a-af31b7de916c)

And, sure enough, `./node_modules/chokidar/esm/index.d.ts` defines `ChokidarOptions` as follows:

```ts
export type ChokidarOptions = Partial<BasicOpts & {
    ignored: string | ((path: string) => boolean);
    awaitWriteFinish: boolean | Partial<AWF>;
}>;
```

**Versions (please complete the following information):**
 - Chokidar version: **4.0.0**
 - Node version: **Bun 1.1.28**
 - OS version: **Windows 10**

**To Reproduce:**

1. Install Chokidar with `bun i -d chokidar`
2. Create a simple watcher
    ```ts
    const watcher = chokidar.watch(base, {
	ignored: (path, stats) => stats?.isFile() && !path.endsWith('scss')
    });
    ```
3. Watch as your IDE of choice pops an error telling you the type of `ignored` is incorrect

**Expected behavior**

No red squiggly

**Comment by paulmillr** [comment]
Was fixed

**Comment by Atulin** [comment]
Nice, I'll be waiting for the next release
