### ISSUE TITLE
Sass is crashing with Error: EMFILE: too many open files, watch using chokidar 4

### ISSUE THREAD

**Issue by stevenchanin** [paulmillr/chokidar#1369]
**Describe the bug**
On a ruby project, we start a sass task to watch for changes to CSS files:
```
sass ./app/assets/stylesheets/application.scss:./app/assets/builds/application.css --no-source-map --load-path=node_modules --watch
```
This works fine with chokidar 3.x, but crashes with chokidar 4.x
```
09:24:02 css.1  | Sass is watching for changes. Press Ctrl-C to stop.
09:24:02 css.1  |
09:24:02 css.1  | Unexpected exception:
09:24:02 css.1  | Error: EMFILE: too many open files, watch
09:24:02 css.1  |
09:24:02 css.1  |
09:24:02 css.1  |
09:24:02 css.1  | error Command failed with exit code 255.
09:24:02 css.1  | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
09:24:03 css.1  | exited with code 255
09:24:03 system | sending SIGTERM to all processes
09:24:03 js.1   | terminated by SIGTERM
```

This issue was originally reported by @ryanb as https://github.com/sass/sass/issues/3942 and then moved to https://github.com/sass/dart-sass/issues/2362. In the comments about 2362, @nex3 mentioned that it should be reported to chokidar.

From reading the issues / release notes, I wonder if this has something to do with globbing where maybe sass  / dart-sass needs to do something differently in specifying what to ignore than they did in v3? Or maybe something is going wrong in chokidar.

I hope that opening an issue here is helpful.

**Versions (please complete the following information):**
 - Chokidar version [e.g. 3.2.1 or commit hash]
   - 4.0.0 and 4.0.1
 - Node version [e.g. 12.11.0, ensure you are using the latest node.js]
   - 18.16.0
 - OS version: [e.g. Ubuntu 19.04 or MacOS 10.15 or Windows 10]
   - Mac 14.6.1

**To Reproduce:**

Steps to reproduce the behavior. Include filename and chokidar config.
```
sass ./app/assets/stylesheets/application.scss:./app/assets/builds/application.css --no-source-map --load-path=node_modules --watch
```

Ideally prove a problem by isolating and making it reproducible with a very short sample program, which you could paste here:
-- I'm sorry, I don't know enough about what sass is doing to produce a short sample

**Expected behavior**
When sass depends on chokidar 3.x that scan at the start of the `--watch` is pretty fast and doesn't error out. With 4.x, it takes about 30 seconds and then SIGTERM's with the too many files error.

**Additional context**
This is a Rails 7.1.4 project. It's private repo for a company's website.

**Comment by paulmillr** [comment]
before, chokidar was using fsevents (custom module) backend. Now it is using built-in `fs.watch` or `fs.watchFile`. Can you add some `console.log` into `watch` method of your `node_modules/chokidar/index.js` or `esm/index.js` and see what options are passed inside?

**Comment by davidfirst** [comment]
It happens to me as well, I just upgraded from 3.x to 4.01. Here is the option object from chokidar/index.js:
```
{
  ignoreInitial: true,
  ignored: [ [Function: ignoreLocalScope] ],
  usePolling: false,
  persistent: true
}
```
In the past I got this EMFILE error on different fs calls. Once I moved from `fs` to `fs-extra`, all those issues disappeared. (`fs-extra` uses `graceful-fs` which overcome this issue).

**Comment by paulmillr** [comment]
https://github.com/paulmillr/chokidar?tab=readme-ov-file#troubleshooting sysctl change should help

**Comment by davidfirst** [comment]
For us (at Bit), changing sysctl wouldn't be practical because we ship our tool with a watcher. So our users will need to run this on their machines to avoid the error. 
For some reason, this EMFILE error is not consistent. On this workspace I got the error, I tried changing some stuff in chokidar source code, I got the error about 15 times. Then, at some point, the error disappeared and it worked properly, although I reverted all my changes. 
If I get the error again on my local, I'll try some more troubleshooting.

**Comment by paulmillr** [comment]
I don't think we can do much because we won't go back to 3rd-party fsevents module.

Added docs to README: 710ee7c.

In the future, we can revisit this with `recursive: true` option of `fs.watch`, but it has its own disadvantages.

**Comment by paulmillr** [comment]
One thing that would improve the situation is new release of sub-dependency readdirp. So, update it to 4.0.2 (npm update)

**Comment by davidfirst** [comment]
@paulmillr , I see the following suggestion in the commit above:
> If executing the command isn't possible, use [graceful-fs](https://www.npmjs.com/package/graceful-fs)

Not sure how it could help. Is it possible to inject a different FS implementation to Chokidar or to the readdirp? 

I got the error again, and tried to replace the "fs" with "fs-extra" directly in index.js and handler.js, it didn't help. Next time I get the error, I'll try your suggestion of updating readdirp, and maybe also replacing the fs implementation there.

**Comment by paulmillr** [comment]
Graceful-fs does monkey-patching, so if you use it, it would be auto applied to chokidar and fsevents.

**Comment by davidfirst** [comment]
@paulmillr , unfortunately, this doesn't seem to work.
I added the following first thing in my code:
```
import fs from 'fs';
import gracefulFs from 'graceful-fs';
gracefulFs.gracefulify(fs);
```
Still, I'm getting this error:
```
err: {
      "type": "Error",
      "message": "EMFILE: too many open files, watch",
      "stack":
          Error: EMFILE: too many open files, watch
              at FSWatcher._handle.onchange (node:internal/fs/watchers:207:21)
      "errno": -24,
      "syscall": "watch",
      "code": "EMFILE",
      "filename": null
    }
```

**Comment by paulmillr** [comment]
There is a separate limit for `fs.watch` in node.js which can't be adjusted. One way to solve this is to use usePolling: true, but that would consume more resources.
