### ISSUE TITLE
Missing types for event callbacks

### ISSUE THREAD

**Issue by ArnaudBarre** [paulmillr/chokidar#1372]
- Chokidar  v4.0.1
- TS v5.5

```ts
import chokidar from "chokidar";

chokidar.watch("src").on('change', (path) => {
  //                                 ^ this is any for me in v4
});
```

v3 types have `implements fs.FSWatcher` on `FSWatcher`  which made things better typed it seems

**Comment by 43081j** [comment]
We probably shouldn't just mimick FSWatcher again but should strongly type our event handlers

I don't think we have many, so it should be easy to do

**Comment by aleclarson** [comment]
FYI: `@types/node` recently added generics to EventEmitter
