### ISSUE TITLE
If a replace a file with the same file in the watched directory nothing happens

### ISSUE THREAD

**Issue by malee1975** [paulmillr/chokidar#1373]
This is possibly an edge case. If I add a file to the watched directory and if the same file already exists in the watched directory no change is detected. The file is identical, same file extension, content and last modified date.

I am monitoring the directory for add and change events.

**Chokidar Options**

```
const options:  = {
	persistent: true,
	ignoreInitial: true,
	awaitWriteFinish: true,
	usePolling: true,
	alwaysStat: true,
	useFsEvents: true,
	binaryInterval: 100
};
```

**Expected behavior**
The action of pasting a file into the directory is observed

**Comment by paulmillr** [comment]
Disable awaitwritefinish
