### ISSUE TITLE
Changes to the same file are not detected

### ISSUE THREAD

**Issue by tnguyen14** [paulmillr/chokidar#138]
I'm having an issue where the watcher can detect changes in a file for the first time, but after that subsequent changes are not detected, no matter how long the interval is.

I am running Yosemite beta on my Macbook, I'm not sure if that has anything to do with it.

Is anyone facing the same issue?

**Comment by kirillrdy** [comment]
I hope this saves someone some time. I've had same issue as @tnguyen14  changes to file were only detected once, and never for subsequent changes.
Turned out it was because of vim. It would create a different file. chokidar would catch unlink event and remove file from watch list.
:cry:

**Comment by jugheadjones10** [comment]
@kirillrdy  
Your comment saved my life…I’ve been trying to figure this out for like one week. [This](https://github.com/webpack/docs/wiki/troubleshooting#vim) has the solution that worked for me.
