### ISSUE TITLE
How to pause the watcher?

### ISSUE THREAD

**Issue by Gwill** [paulmillr/chokidar#155]
How to pause the watcher? It is expensive to close and  regenerate a wather for pausing.

**Comment by kingces95** [comment]
Bummer. 

Node `stream` offers `pause` and `resume` which come in handy when applying back pressure to an `rx` stream. 

Similarly, my use case for a file watcher is to pause while I take action in response to a watched file event generated manually that may itself generate an even on that watched file. To prevent a loop, I'd like to pause the watcher while the automated file updates occur then resume to continue capturing manual events (e.g. from the IDE).

**Comment by paulmillr** [comment]
Go ahead and make a pull request if that won't bring in super complex architecture.

**Comment by tstewart-klaudhaus** [comment]
It seems to me that this would already be supported by the `unwatch` and `add` methods of the watcher. Passing the watched path to these methods would effectively seem to pause and resume the watching.
