### ISSUE TITLE
watcher firing 'add' events for existing files

### ISSUE THREAD

**Issue by shime** [paulmillr/chokidar#157]
this will list all current files in a directory

``` javascript
var chokidar = require('chokidar')
var watcher  = chokidar.watch('./public/images', {persistent: true})

watcher.on('add', function(path){
  console.log(path, ' added')
})
```

if I use the `ignoreInitial` option like so, it will skip initial files, but will print them again when a new file is added 

``` javascript
var chokidar = require('chokidar')
var watcher  = chokidar.watch('./public/images', {persistent: true, ignoreInitial: true})

watcher.on('add', function(path){
  console.log(path, ' added')
})
```

related to #110, I'm using linux

**Comment by bjesuiter** [comment]
I have the same issue on macOS currently. 

With the code
`    watcher.on('add', path => {
        logger.debug('added file %s', path);
    });`
I do get: 
- all files in the watched folder, when one file is added
- all remaining files, when one file is deleted

When I add ignoreInitial (even given I don't want this for my case), it ignores the first watch round, but gives me all files when a file is added or removed.
