### ISSUE TITLE
Glob support

### ISSUE THREAD

**Issue by es128** [paulmillr/chokidar#190]
I don't see why this shouldn't be baked in so that downstream users like karma don't need to roll their own.

Also, as part of this, incorporate [anymatch](https://github.com/es128/anymatch) support for the `ignored` setting.

**Comment by es128** [comment]
Just checked in an initial crack at the glob implementation. It's not very well vetted yet, so I assume there are still bugs and unmet use cases. Would appreciate help looking for cases that do not behave as expected. PRs with failing tests would be awesome.

**Comment by contra** [comment]
@es128 Always open to new things :wink:

**Comment by es128** [comment]
I haven't been able to find any more ways to break it. Going to call this one done :zap:

But please! everyone else try to break it too and open new issues if you find anything.

**Comment by contra** [comment]
Hmm I was thinking of an API more like `.watch(globs)` instead of `.watch(folder, {ignore: ignoredGlobs})

**Comment by es128** [comment]
Both ways should work. The `!` negation syntax if passed within `globs` gets handled.

**Comment by contra** [comment]
@es128 Oh I didn't see any docs on positive globs. Do you have any benchmarks of this in chokidar vs. gaze? If I can see that it works cross-platform and has better perf I could switch it out tonight

**Comment by es128** [comment]
No, haven't evaluated comparative perf yet. Also, I've got a bit more to do before publishing as 1.0, trying to get it done over the long weekend.

Writing docs about the glob support would be one of the things that still needs to be done.

**Comment by paulmillr** [comment]
Besides performance, also keep in mind the [bugs in Gaze](https://github.com/shama/gaze/issues) :wink:
