### ISSUE TITLE
Gulp wrapper

### ISSUE THREAD

**Issue by TrySound** [paulmillr/chokidar#200]
Hi, guys.
I was impressed by chokidar and wrote a wrapper for gulp (optional) with globs.
https://github.com/TrySound/gulp-chokidar
What do you think about it?

**Comment by lmartins** [comment]
Cool, looking forward for the gulp version.

**Comment by es128** [comment]
@lmartins See https://github.com/floatdrop/gulp-watch and https://github.com/wearefractal/glob-watcher/pull/13

**Comment by lmartins** [comment]
thanks @es128 trying it out now.
