### ISSUE TITLE
Possible issue with NFS watching

### ISSUE THREAD

**Issue by blopker** [paulmillr/chokidar#201]
See: https://github.com/substack/watchify/issues/120

Looks like the only related change from Watchify 2.1.1 (works) to 2.2.1 (Doesn't work) was this commit: https://github.com/substack/watchify/commit/dea0171335ca8ff2915c67f9527dbc404c51be7f

**Comment by MartinMuzatko** [comment]
Just for the record: this helped me to fix a bug in 2020 :3
