### ISSUE TITLE
Watching folders seems to lock them

### ISSUE THREAD

**Issue by bpasero** [paulmillr/chokidar#204]
I notice that sometimes chokidar seems to lock a folder for watching. This could obviously also originate from the fs watcher being used from node.js and not chokidars fault. I am on windows.

It is easily reproducible by watching a folder with a .git folder inside using chokidar and then trying to delete the .git folder using windows explorer. You will notice this to fail because chokidar is holding a lock onto the .git folder.

```
var chokidar = require("chokidar");

var watcher = chokidar.watch('PATH', {
	persistent: true, 
	ignoreInitial: true,
	ignorePermissionErrors: true,
	followSymlinks: false
});

watcher.on('all', function(type, path) {
	console.log(path, type);
});

watcher.on('error', function(error) {
	console.error(error);
});
```

In my example I am using a checked out version of Express for node.js.

I am not really understanding though why this happens for the ".git" folder. I can easily delete other folders.

**Comment by es128** [comment]
I don't think there's anything chokidar would be able to do differently here to impact this behavior.

**Comment by es128** [comment]
I'd suggest creating a reproducible case using plain `fs.watch` and reporting to node.js

Also, how did you rule out that the lock might be coming from some other process?

Closing this issue, as there's nothing to be done about it here.
