### ISSUE TITLE
`ignoreInitial: false` not respected when using `add` after instantiation

### ISSUE THREAD

**Issue by matthew-dean** [paulmillr/chokidar#207]
If I already have a watcher, why does the .add() method fire an 'addDir' event as if that directory was created? It fires a file creation event even though it should be an event for adding a file / dir to be watched (although preferably no event would be fired at all).

**Comment by es128** [comment]
Use the `ignoreInitial` option

**Comment by matthew-dean** [comment]
I have. It doesn't apply to using the .add() method later.

**Comment by es128** [comment]
Confirmed. This is a bug. It actually behaves differently (both wrong) in fsevents vs nodefs modes.

**Comment by matthew-dean** [comment]
In other words: 

```
if(watcher) {
		console.log('Adding...',data.path);
		watcher.add(data.path);
	}
	else {
		console.log('Watching...',data.path);
		watcher = chokidar.watch(data.path, {
			ignored: ['.git', '.DS_Store', 'node_modules']
			, depth: 1 
			, ignoreInitial: true
		});

		watcher
			.on('all', capture)
			.on('error', onError);

	}
```
Watcher should... Oops you just posted something.

**Comment by matthew-dean** [comment]
Also, I noticed that if you use "add" on a watcher object, it doesn't seem to respect the options set with .watch(). (As in, it reports changes to .git.)
