### ISSUE TITLE
Add Travis

### ISSUE THREAD

**Issue by es128** [paulmillr/chokidar#209]
and maybe coveralls also

@paulmillr I'm pretty sure you're the only one who can flip the switch on the 3rd-party CI services

**Comment by es128** [comment]
Unfortunately it won't be able to test the fsevents side of things at all, but still... won't hurt to have it.

**Comment by es128** [comment]
Or maybe it actually could:

http://docs.travis-ci.com/user/multi-os/
http://docs.travis-ci.com/user/osx-ci-environment/

**Comment by paulmillr** [comment]
also add travis yml

**Comment by es128** [comment]
Not going to do coveralls for now since it won't be meaningful without being able to include an OS X test environment.

E-mailed travis support about enabling multi-os, but they said they can't due to travis-ci/travis-ci#2311

**Comment by es128** [comment]
For the record, our coverage is pretty good:

```
=============================== Coverage summary ===============================
Statements   : 96.15% ( 1149/1195 )
Branches     : 84.85% ( 336/396 )
Functions    : 97.27% ( 249/256 )
Lines        : 97.17% ( 1066/1097 )
================================================================================
```
