### ISSUE TITLE
.add() method not respecting .watch() method settings

### ISSUE THREAD

**Issue by matthew-dean** [paulmillr/chokidar#210]
I thought I'd make this a separate issue. Based on my code in #207, when I use the .add() method later on a watcher, it doesn't seem to respect the options set in .watch(). Is that a bug?

**Comment by es128** [comment]
Sounds like it. Good chance it's the same bug. Will work on it this afternoon.

**Comment by es128** [comment]
I'm not able to reproduce this. The way `ignoreInitial` was implemented had problems, but all the other options (such as `ignored` are behaving the way I'd expect).

Using this test code (modified from [example.js](https://github.com/paulmillr/chokidar/blob/master/example.js), I don't get events for `node_modules` or `.git` stuff in either directory:

```js
var watcher = require('./').watch('../brunch', {
  ignored: /node_modules|\.git/,
  persistent: true,
  //followSymlinks: false,
  //useFsEvents: false,
  //usePolling: false
}).on('all', function(event, path) {
  console.log(event, path);
}).on('ready', function() {
  console.log('ready');
  setTimeout(function(){watcher.add('.')}, 1000)
})
```

**Comment by es128** [comment]
The way you set your `ignored` in the other thread is going to calculate those paths relative only to `cwd`, which is most likely the cause of the issue you observed. If you want it to behave as a pattern that applies to any directory you add, convert those strings to one or more regexes or glob patterns like:

```js
ignored: /\.git|\.DS_Store|node_modules/
```
