### ISSUE TITLE
Not issue : Just info

### ISSUE THREAD

**Issue by codeyash** [paulmillr/chokidar#211]
In hindi Chokidar means Guard who watches bad people and protects us in day and night.

No idea where to share so I started here itself.

Thanks,
Yash

**Comment by es128** [comment]
Uh yeah, it's a file watching module. The name wasn't accidental.

But thanks for sharing.

**Comment by codeyash** [comment]
Ohh you're Indian. Cool. Love it. And you have highest commits. Great job buddy. 
But you don't look at all. I don't want to go in history. 

Thanks,
Yash

**Comment by es128** [comment]
I'm not Indian (my last name being a common one in India is a coincidence), and I didn't pick the name of this module. I don't know how @paulmillr chose it, I assume by just googling for terms related to "watcher".

**Comment by codeyash** [comment]
ok No problem. Sorry for comments.

Still great job guys.

-Yash
