### ISSUE TITLE
usePolling default value for linux is false?

### ISSUE THREAD

**Issue by mikesimkin** [paulmillr/chokidar#212]
The README file states "options.usePolling (default: false on Windows, true on Linux and OS X)" but the code indicates that polling is true by default only for OS X:

    // Use polling on Mac if not using fsevents.
    // Other platforms use non-polling fs.watch.
    if (undef('usePolling') && !opts.useFsEvents) {
      opts.usePolling = platform === 'darwin';
    }

I'm using watchify that uses chokidar on RedHat (CentOS release 6.3 (Final)) but the update event does not trigger for files that are modified over samba shares without usePolling.

Is the documentation wrong and you're planning to usePolling only for OS X in which case I'll open an issue with watchify or will you update the code base and set usePolling to true by default for Linux also?

Thanks!

**Comment by es128** [comment]
As of 0.12 the default for linux is non-polling. The docs in the master branch have been updated to reflect this, but looks I inadvertently did not apply that to the readme in the 0.12 branch.

There is already a PR open at watchify to allow chokidar options to be passed through, motivated by the exact same situation of wanting to enable polling for watching network shares: https://github.com/substack/watchify/pull/126

**Comment by mikesimkin** [comment]
Thanks!
