### ISSUE TITLE
Change event referencing deleted files when watching a directory

### ISSUE THREAD

**Issue by javorosas** [paulmillr/chokidar#213]
I'm using Ubuntu, node-webkit 0.10.4 and chokidar 0.12.6

Here's what I did:

1. I watched a directory in my user folder

        require('chokidar').watch('/home/javo/test/', { persistent: false, ignored: /[\/\\]\./}).on('all', function(event, path) {
          console.log(event, path);
        });

2. Went to the folder and created a file called "something"

3. Renamed the file to "something else"

This far the console was firing two change events: one for "something" and one for "something else".

I deleted the file, and created a new one called "new". Then again three events fired, one for every file early mentioned, even when one of them was already deleted.

Repeated this for a bunch of files and the same happened. Even when I close the process, it keeps firing the whole history of the folder every time something changes inside.

**Comment by es128** [comment]
> Even when I close the process, it keeps firing 

wut?

**Comment by es128** [comment]
Try logging out the `raw` events from chokidar to see if that helps shed light on what's going on.

**Comment by javorosas** [comment]
Sorry, I meant after closing the process and running it again, my bad

**Comment by javorosas** [comment]
Ok, so, logging raw events seem to work as it should. It's the 'change' and 'all' that's missbehaving.

Here's my output for 'all' event:

    addDir /home/javo/test/
    change 89###
    change dsafasdfdas
    change dsfafasd
    change dsfa
    change fadsfdsaf
    change fasdfasddsafasd
    change fasdfasd
    change fsdafsdaf
    change sadsaDASDSA
    change  sadsaDASDSAsdafa
    add /home/javo/test/ffasdfasd

and when I run `ls` in that dir:

    89###~        dsfa   dsfafasd~   fasdfasd~         ffasdfasd   sadsaDASDSA~
    dsafasdfdas~  dsfa~  fadsfdsaf~  fasdfasddsafasd~  fsdafsdaf~  sadsaDASDSAsdafa~


.... ok, now I get it. I'm just documenting this for the record. I edited those files with gedit and created those hidden files. Everything was there all along.

**Comment by es128** [comment]
If you want, you can set `atomic: false` to get separate events for those tilde files and get a better recognition of the deletes.
