### ISSUE TITLE
Add called before file fully uploaded

### ISSUE THREAD

**Issue by radfordbw** [paulmillr/chokidar#215]
I am watching a directory, but the add file code is being called before the file is fully uploaded and so the code tries to process the file before it is fully uploaded and is missing some of the content.  Is there an easy way to adjust code to make it only kick off add file calls when the file is no longer in the process of uploading?

**Comment by es128** [comment]
How do the `change` events look in this situation?

**Comment by radfordbw** [comment]
After a file has been SFTP-ed to the directory, I see 
1.  Add new file
2.  Change - size = 0 bytes, with current timestamp
3.  Change - size = full size
4.  Change - size = full size but timestamp gets updated to original file timestamp

i can add code to ignore the 0 bytes change after the add, but I am not sure how to tell the difference between the last two change events since sometimes the timestamp may not be updated (if it is a new file)

To get around this for now, I am using the Add event, and then have a setTimeout watching to see when the file stops changing sizes and then process it.  But I was curious if there was a better way to do this inside the code.

thank you!  and great library!

**Comment by es128** [comment]
The solution you've come up with sounds about as good as anything I might have suggested.
