### ISSUE TITLE
On OS X Yosemite chokidar reports the first change as `add` event.

### ISSUE THREAD

**Issue by sokra** [paulmillr/chokidar#216]
Repro repo: https://github.com/sokra/watchpack-issue

Discussion: https://gitter.im/sokra/watchpack-issue

Propably related to `ignoreInitial: true`, but I'm not sure.

Result on Windows: (correct)

```
# change file 'b'
change fixtures\b { ... }
# create file 'a'
add fixtures\a { ... }
# change file 'b'
change fixtures\b { ... }
# change file 'a'
change fixtures\a { ... }
```

Result on OS X: (wrong)

```
# change file 'b'
add fixtures/b undefined
# create file 'a'
add fixtures/a undefined
# change file 'b'
change fixtures/b undefined
# change file 'a'
change fixtures/a undefined
^C
```

webpack/webpack#703

**Comment by sokra** [comment]
@es128 and the process doesn't exit on OS X.

**Comment by es128** [comment]
This change/add thing may have already been fixed in the master branch. Have you tried it?

> and the process doesn't exit on OS X

It isn't supposed to with `persistent: true`.

**Comment by sokra** [comment]
> It isn't supposed to with persistent: true.

I'm closing the watcher at the end... And it exits fine on windows.

**Comment by es128** [comment]
Yes, it should after you close the watcher... will give your test repo a try.

**Comment by es128** [comment]
The original issue is resolved and the issue with the process staying open has been reported to fsevents: https://github.com/pipobscure/fsevents/issues/50
