### ISSUE TITLE
ready event never be emitted

### ISSUE THREAD

**Issue by terasaka2k** [paulmillr/chokidar#224]
Is this correct behavior?
```javascript
const chokidar = require('chokidar');

const watcher = chokidar.watch([
  'node_modules/chokidar/package.json',
  'node_modules/chokidar/*',
]);

watcher.on('ready', function() { console.log('ready', arguments); }); // never output
```

**Comment by terasaka2k** [comment]
Possibly because `readdirp` never emits 'end' event.

**Comment by es128** [comment]
Your example is working exactly as expected for me - it outputs `ready {}`.

If there's actually a problem, you're going to have to describe the situation in more detail.

**Comment by terasaka2k** [comment]
Would you run the `test.js` from my forked repo?

On Linux (or disable fsevents)
```Javascript
git clone --depth=1 https://github.com/paulmillr/chokidar.git
cd chokidar
wget -O test.js https://raw.githubusercontent.com/terasaka2k/chokidar/master/test.js
npm i
./node_modules/.bin/mocha -C -g 'specific'
```

It would produce very unstable results.

**Comment by es128** [comment]
You're right, there was an issue. Should be fixed now. Thanks for reporting.
