### ISSUE TITLE
Watching Windows folder on network

### ISSUE THREAD

**Issue by Verhaeg** [paulmillr/chokidar#225]
Hi
I'm trying to write an app that reads XML files from any folder provided by the user, but I'm having great issues with network folders.
For instance: \\shared\files
This throws an error and forces my application to close without any messages..

my code looks like:

    try {
        $rootScope.folderWatcher = require('chokidar').watch(current_folder, {persistent: true, ignoreInitial: true});
        ... some other stuff and events added
    } catch (err) {
        $rootScope.errorHandler('Monitor', 'show error', err);
    }

Do you have any clues on why this happens, as it only happens on certain windows 7 computers using network folders

Thanks

**Comment by es128** [comment]
Add the `usePolling: true` option to watch network folders.

**Comment by Verhaeg** [comment]
Thanks for the help \o/
I only found this option related to OS X...

**Comment by es128** [comment]
It's mentioned in the docs: https://github.com/paulmillr/chokidar#performance

but a common enough situation that it probably ought to be called out in a more obvious way

**Comment by es128** [comment]
63059b9e7711f1c00e0efacc2f29504de571bdf2

**Comment by rfossella** [comment]
Hi.  I am having issues trying to watch network folders on Windows (7).  I am setting up the watch folders using ip addresses - e.g. \\\\10.20.55.999\\apps\\client\\data\\today.

I'm using a try/catch and get no errors.  Also set usePolling: true (per this post):
```
var chokidar = require('chokidar');
try {
    	watcher = chokidar.watch(folders, 
	                {ignored: /[\/\\]\./, persistent: true, usePolling: true});
		} 
	catch (err) {
    			chokidar.errorHandler('Monitor', 'show error', err);
				}
```

When I check **._watched** it correctly displays the folders I wish to watch, although **._items** is always empty even though files exist.  Anything done in those folders has no effect - e.g. console msgs never fired.

Is there something obvious I'm missing here?  Is there a way to know (via chokidar) if this is possibly a permission issue?

Any guidance is appreciated.

Thanks.
Robert

**Comment by es128** [comment]
Try doing regular node `fs` operations on these network paths, like `readdir`, `read`, and `stat`. If they don't behave as expected it may be a permissions issue, or it may be an issue in node.

Perhaps you'd have more success if you mapped the network path to a drive letter.

Side notes: `chokidar.errorHandler` isn't a valid method. Generally, you should be adding a listener for the `error` event to catch errors coming out of chokidar. The try/catch would only apply to errors thrown during the instantiation of the watcher, shouldn't ever really be the case.

**Comment by rfossella** [comment]
I have some new observations:
1) I successfully performed fs.readdirSync() on the network directories in question.  
2) I do use the **on** error handler, but with no error firing.  Thanks for reminding me -).
```
.on('error', function(error) 
	    { 
	        console.log('Error occurred ' + error);
	    })
```
3) the __usePolling:true__ spikes CPU on node.exe
4) I use a configuration file with my network ips and (per your suggestion)  changed it to map to a drive and **THIS ** does work.

The mapping is a little difficult for me as my web app has to be dynamic based on network IPs provided by another person (admin).  Might you have any other suggestions for using the IP?  Should I use some sort of node exec to map drive on the fly (not yet sure if node has such a module to to this).

Thanks again for your time.
Robert

**Comment by es128** [comment]
How about `fs.stat` on one of the files?

**Comment by rfossella** [comment]
When I fs.stat one of the files using full IP I get success.  
```
{ dev: 0,                                                            
  mode: 33206,                                                       
  nlink: 1,                                                          
  uid: 0,                                                            
  gid: 0,                                                            
  rdev: 0,                                                           
  ino: 0,                                                            
  size: 10942,                                                       
  atime: Thu Apr 23 2015 13:18:02 GMT-0400 (Eastern Daylight Time),  
  mtime: Tue Mar 31 2015 21:44:22 GMT-0400 (Eastern Daylight Time),  
  ctime: Thu Apr 23 2015 13:18:02 GMT-0400 (Eastern Daylight Time) } 
``` 

 I also tried fs.realpathSync(mydir) to see if it had any effect resolving, but again, it only worked with mapped drive.

**Comment by es128** [comment]
Interesting. Can you try the readdirp module directly? Still trying to understand which layer fails to deal with the ip-based paths.

**Comment by rfossella** [comment]
I'm not familiar with the readdirp module but will look into it.  What does it replace?

Also - kind of related - when watching my network folders with mapped drive I get tons of messages in console that read **"watch error occurred Error: watch UNKNOWN".**  I do not get these while watching local files, although network has about 5000 files.  Is the size an issue I need to be concerned with?

Thanks

**Comment by es128** [comment]
readdirp is the module chokidar uses for recursive readdir - to scan the file tree. `_items` always being empty as you mentioned above indicates that even just scanning for the file list is failing somewhere. Does `_watched` manage to reflect any subdirs, or only the dirs you passed into chokidar to be watched?

The watch error you just mentioned indicates that `fs.watchFile`, which is what is used in polling mode, is unable to read/watch these files at all. It may be a permissions problem, a problem in node, or a problem in windows. I doubt the size has an impact. You could try turning off polling mode I guess, but I doubt it would help. 

If you can't successfully watch any of these files by using `fs.watch` or `fs.watchFile` directly, then chokidar isn't going to work either. If either of those methods do work, then we can keep digging for where the failure actually is and see whether there's a possible solution.

I can't reproduce the environment, so there's only so much I can do to help here.

**Comment by rfossella** [comment]
Hi.  I tried using readdirp directly with success
```
var count = 0;
var dir = "\\\\10.20.55.999\\\apps"

	readdirp({ root: dir })
	  .on('data', function (entry) {
	    	console.log(entry.fullPath);
	    	count++;
	  })
	  .on('end', function () {
	    	console.log("Done.  Count= " + count, "green");
	  });
```

In this example the log correctly displays all recursive levels of folders and files with a final count of 8000 files.  Does this help in your analysis?
Thanks.

**Comment by es128** [comment]
Yes it helps to narrow down what works and what doesn't.

I suppose what's left is to try using `fs.watchFile` directly on some of these paths in a little test script and seeing what happens. If that works too, then there probably is a bug in chokidar somewhere that can hopefully be identified and fixed. If it doesn't (and `fs.watch` doesn't either), then chokidar is not going to work for this situation - unless maybe there's some sort of file permissions thing that can be changed.

**Comment by Danny-Engelman** [comment]
I moved everything from a _shared Network drive_ **W:** , to **C:** 

and now Chokidar no longer complains
