### ISSUE TITLE
webpack file watcher doesn't catch Vim write events

### ISSUE THREAD

**Issue by michaeldye** [paulmillr/chokidar#226]
Vim writes (:w) on Linux don't trigger watches (I'm using webpack-dev-server --watch): inotify shows "CLOSE_NOWRITE,CLOSE" for that action. Another editor I tried, light table, sends "CLOSE_WRITE" on save.

**Comment by es128** [comment]
`npm ls | grep chokidar` ?

**Comment by michaeldye** [comment]
chokidar@1.0.0-rc3 <- watchpack@0.2.3 <- webpack@1.5.3

**Comment by es128** [comment]
This particular problem was focused on for the 0.12 release, and I can't reproduce the issue anymore using chokidar's simple example script.

Can you try to reproduce the issue using just checking out the chokidar repo and running [example.js](https://github.com/paulmillr/chokidar/blob/master/example.js)? If you can, please run it with the logging of raw events uncommented and provide the results.

**Comment by michaeldye** [comment]
The example runs properly, events from Vim writes are detected by Chokidar but not the webpack-dev-server.

I'll close this issue; I've reported the problem to webpack: webpack/webpack#781
