### ISSUE TITLE
`Interval` option doesnt work as expected.

### ISSUE THREAD

**Issue by gyandeeps** [paulmillr/chokidar#227]
I use this module with this setting and it still emits events as soon as i change the file. Like right that second. Most of the times it emits 2 events for it.

```.js
var chokidar = require("chokidar");
var cnt = 0;
var watcher = chokidar.watch(["./test.js"], {
    persistent: true,
    interval: 100000
});
watcher.on("change", function(fp){
    console.log(++cnt);
});  
```

Try changing things in test file past and hit `ctrl + s` fast too. You would see what I am talking about.
OS: Windows 7
Chokidar version: 0.12.6
Node: 0.12.0

**Comment by es128** [comment]
The `interval` option only applies to polling. Set `usePolling: true` to make it take effect.

**Comment by gyandeeps** [comment]
Thanks for updating the docs. :+1:
