### ISSUE TITLE
Endless loop when filename contains brackets

### ISSUE THREAD

**Issue by bpasero** [paulmillr/chokidar#230]
- using latest chokidar on windows
- have a folder with a file inprogress[00].txt
- use the following code:

```javascript
var chokidar = require("chokidar");

console.log("before watch");

var watcher = chokidar.watch("the path", { 
    ignoreInitial: false,
    persistent: true
});

console.log("after watch");

watcher.on("all", function(type, path) {
    console.log(type, path);
});

watcher.on("ready", function () {
	console.log("ready");
});

watcher.on("error", function(error) {
    console.log("error handler ", error);
});

process.on('uncaughtException', function(error) {
    console.log("uncaughtException: ", error);
});
```

I see repeaded calls to nodefs-handler#_addToNodeFs(). 

This seems to have worked fine in 0.12.x

**Comment by es128** [comment]
Yep, reproduced. That's pretty crazy.

**Comment by es128** [comment]
Ok I see what it is. The brackets are being recognized as a glob pattern so it keeps opening watchers against the directory when it wants one for the file. Fix forthcoming.
