### ISSUE TITLE
Ignoring Files on Ubuntu With chokidar version 1.0.0-rc3

### ISSUE THREAD

**Issue by maestroh** [paulmillr/chokidar#233]
I'm trying to ignore specific files within folders. I'm sure the syntax for the ignore path is incorrect, but I can't seem to find the problem. I've tried all combinations of strings, globs, and arrays. I'd appreciate if someone would point me in the right direction.

Here's a quick example of the problem. I'm trying to ignore ignore.js, but since the folder is being watched, console.log is executed when both writing and deleting the file.

```
    var chokidar = require('chokidar');
    var fs = require('fs');
    var path = require('path');

    var watcher = chokidar.watch('./test', {
      ignored: './test/ignore.js', 
      persistent: true,
      ignoreInitial: true,
      alwaysState: true
    });

    watcher.on('all',console.log);

    setTimeout(function(){fs.writeFile('./test/ignore.js', 'w');}, 200);
    setTimeout(function(){fs.unlink('./test/ignore.js');}, 300);
```
Thanks for any help!

**Comment by es128** [comment]
Drop the `path.resolve` unless you're going to use it on your watch path as well.

**Comment by maestroh** [comment]
That was the original version. I tried the path.resolve to test the 'whole path'.

**Comment by es128** [comment]
'Whole path' in the docs just means it's not only the base name, not that it gets fully resolved. 

Btw, unrelated, but you have a typo on `alwaysStat`

**Comment by es128** [comment]
What exactly is getting logged in the console?

**Comment by maestroh** [comment]
Here's the console.log output. Thanks for the heads up on the typo.
```
add test/ignore.js { dev: 2054,
  mode: 33188,
  nlink: 1,
  uid: 1000,
  gid: 1000,
  rdev: 0,
  blksize: 4096,
  ino: 8675,
  size: 1,
  blocks: 8,
  atime: Sun Feb 15 2015 12:10:52 GMT-0500 (EST),
  mtime: Sun Feb 15 2015 12:10:52 GMT-0500 (EST),
  ctime: Sun Feb 15 2015 12:10:52 GMT-0500 (EST) }
unlink test/ignore.js
```

**Comment by es128** [comment]
Ah, drop the `./`

**Comment by maestroh** [comment]
I was just about to type that. Thanks for the help!
