### ISSUE TITLE
unlink event on nonexistent files after moving file multiple times

### ISSUE THREAD

**Issue by mixxen** [paulmillr/chokidar#236]
Not sure if this is expected behavior.... To reproduce, run chokidar:

```
var chokidar = require('chokidar');
chokidar.watch('.', {ignoreInitial: true})
.on('all', function(event, path) {
  console.log('file event: ' + event + ',' + path);
});
```

Open a terminal to the watched directory and run these commands:

```
touch test
mv test test2
mv test2 test3
mv test3 test4
```

The output will look like this:

```
file event: add,test
file event: add,test2
file event: unlink,test
file event: add,test3
file event: unlink,test2
file event: unlink,test
file event: add,test4
file event: unlink,test3
file event: unlink,test
file event: unlink,test2
```

Notice that unlink is being called again on old moves. Running on node v0.10.36, Ubuntu 14.04.

**Comment by es128** [comment]
Yep, reproduced. It's a bug (in fs.watch, but chokidar should be able to do something about it)
