### ISSUE TITLE
Modifications to files below ignored directories are not being ignored on OSX

### ISSUE THREAD

**Issue by patrick-steele-idem** [paulmillr/chokidar#239]
With the latest version of chokidar I am noticing that modifications to files below an ignored directory are not being ignored. I'm not sure why your test cases aren't catching the problem, but I created a really simple project that you can test with to easily reproduce the problem on OSX:

https://github.com/patrick-steele-idem/chokidar-bug/

I also tested with the latest code on master and I am seeing the same problem. If I switch back to the pre-1.0 version of chokidar the problem does not exist.

Please let me know if you need more details. Thank you for looking into this problem!

**Comment by es128** [comment]
Haven't tried to run it yet, but I think I see what's happening in reviewing your code. Your `ignore` definition is very specific to the directory itself, as opposed to being defined as a regex or glob that would match on all the directory's contents. 

The directory's path is being filtered out by the initial readdirp scan, so it's never tested against your `ignored` setting, so the code that ignores all children of an ignored dir does not kick in. If you were to create the directory after the watcher was instantiated (after the `ready` event), it would probably work as you expect.

So if all my assumptions are correct, then yes I agree it's a bug. But one that should be pretty easy to fix.

**Comment by patrick-steele-idem** [comment]
Thanks for the quick response @es128! I look forward to trying out the fix as soon as it is ready. I hope the project I shared makes things a little easier for you, but let me know if I can help in some way.

FYI, this bug broke the [ignoring-watcher](https://github.com/patrick-steele-idem/ignoring-watcher) module that I use as the basis for various modules. That module uses `.gitignore`-style ignores that match directories (not individual files) so ignoring directories is important.

**Comment by philidem** [comment]
:+1:
