### ISSUE TITLE
Brace-wrapped glob patterns not emitting

### ISSUE THREAD

**Issue by jasperkuperus** [paulmillr/chokidar#241]
When you add a glob that contains braced sections, the watch isn't registered correctly:

```
globs = ['{./src/**/*.coffee,./bin/**/*.coffee}'];
chokidar.watch(globs, opts);
```

It narrows it down to `.`, while it should register a watch for both `src` and `bin`.

I've been debugging the code and found that the resolution of the glob to `.` happens on [line 214 of index.js](https://github.com/paulmillr/chokidar/blob/master/lib/index.js#L214). Here, `glob-parent` is called and performs the resolution. If you look at the documentation of `glob-parent`, you will also see it does not provide an example for braced sections.

I ran into this issue while using gulp-watch, which [doesn't work anymore since version 4](https://github.com/floatdrop/gulp-watch/issues/140).

**Comment by es128** [comment]
Well, `.` _is_ the common parent for that glob pattern. You haven't described what actually goes wrong in your events - it looks as if it should watch `.` recursively, then filter events to those that match your pattern. 

Also, I'd appreciate if you could explain the benefit of using that syntax over an array with two separate glob strings.

**Comment by es128** [comment]
Or even `'./{src,bin}/**/*.coffee'`

**Comment by jasperkuperus** [comment]
Ok, well there is no benefit using this over an array. Actually, I'm doing that right now, which I believe is better. However, in our setup `{./src/**/*.coffee,./bin/**/*.coffee}` was (a simplified, legacy, version of) a glob we were using. This worked with gulp-watch v3, but failed with gulp-watch v4. Apparently they switched from gaze to chokidar, where this glob worked for gaze, but not for chokidar.

**However**, I did a clean test now without gulp-watch, using chokidar directly. There are no problems at all, chokidar reports all changes as it should. So there is no issue here, sorry :) It seems the error is in gulp-watch after all!
