### ISSUE TITLE
run in parallel?

### ISSUE THREAD

**Issue by sandric** [paulmillr/chokidar#243]
Hi, I try to use chokidar for full system monitoring, and it take quite a bit of time to add all files to watch. But instead of whole process loaded 100%, top gives me 100% load only on one core, while second is only 30% loaded. Is it me wrong, or is it really not parallel? Can you enable parallel execution somehow? thx.

**Comment by es128** [comment]
No. Node.js processes are single threaded. There are no plans to try to make chokidar leverage multiple processes for a single watcher instance.

**Comment by paulmillr** [comment]
long story short: there would be no perf benefit

**Comment by sandric** [comment]
@paulmillr well there may be a dispute actually. When using non-blocking calls in event pull after all the files are loaded - may be. But on my machine I can clearly see how while loading stage my second core just hanging around doing nothing while other loaded for a 100 percent and scheduler just waiting for system time and not giving other files to get processed.

Anyway, I tried out filewather lib written in ruby and looks like it works 10 or even 100 faster on the stage of adding files to watch, with no offense to chokidar, so I stick with it.
