### ISSUE TITLE
Rewrite in ES6, Maybe?

### ISSUE THREAD

**Issue by steelbrain** [paulmillr/chokidar#244]
Because Chokidar doesn't provide individual functions and acts like a class,
```js
class Chokidar{
  watch(Path){
    // Do Something
  }
  unwatch(Path){
    // Do Something
  }
}
```
This will make the code a lot more easier to read, maintain and enhance.

**Comment by es128** [comment]
> a lot more easier

Um, a little bit easier, maybe. But then we'd have to go back to dealing with all the transpilation issues we used to deal with when it was coffeescript. 

IMHO, not the right time for this with chokidar.

**Comment by es128** [comment]
Closing because it isn't an issue, but feel free to continue discussing.

**Comment by steelbrain** [comment]
> But then we'd have to go back to dealing with all the transpilation issues

I agree that we have to transpile the file after every change, But I don't think of it as an __issue__.
Is there any other than the transpilation?

**Comment by es128** [comment]
As @paulmillr and I know all too well, maintaining a library that involves a transpilation step can be a PITA, and I don't think the benefits justify the cost in this case. 

Yes that's probably the only substantial issue. If all platforms chokidar is meant to run on supported es6 natively it would be an easier transition. The only other concern that comes to mind is the time/effort for conversion, but I'd get around to it if that were the only barrier.

**Comment by steelbrain** [comment]
>The only other concern that comes to mind is the time/effort for conversion

I feel like I am gonna send a PR soon.

**Comment by es128** [comment]
Haha alright. I'd be happy to review it. 

Consider how to make sure everything works whether a user installs from npm or git, but don't use a `postinstall` hook and try to avoid needing to commit the transpiled code.

**Comment by es128** [comment]
There's definitely been plenty of times when working with chokidar when I've missed the conveniences of things like destructuring assignments and fat arrows.
