### ISSUE TITLE
Release a new RC?

### ISSUE THREAD

**Issue by silverwind** [paulmillr/chokidar#245]
Any chance for a new Release Candidate?

I'm seeing an weird issue on Windows while watching a directory with a file called `[file]` that leads to chokidar consuming half my CPU, which does appear to be fixed on HEAD.

**Comment by es128** [comment]
Yeah ok. Once I fix the currently failing test I'll put out rc4

**Comment by silverwind** [comment]
:+1:

**Comment by silverwind** [comment]
Appears that `[file]` bug affects OS X too. I wonder how that came to be. No errors thrown or anything, probably looping somewhere.

**Comment by es128** [comment]
Yes, it's because it looks like a glob pattern. So that triggered a new watcher that was meant to be for the parent, but it just keeps trying to watch the file again.

**Comment by es128** [comment]
was fixed in https://github.com/paulmillr/chokidar/commit/d0b755fa7ff8f336cd07f758302d8d89f0e7c05c

**Comment by silverwind** [comment]
Might be good to test for abnormal high cpu usage, if that's possible. We usually don't notice these easily.

**Comment by es128** [comment]
In the test script? No, I don't see how it can be done in a meaningful way, and even so this bug wouldn't have been caught that way. No test had been written to watch a file with a glob-like name prior to the issue being reported.

**Comment by es128** [comment]
published rc4
