### ISSUE TITLE
Are there alternatives to the fsevents?

### ISSUE THREAD

**Issue by monolithed** [paulmillr/chokidar#246]
I can not install many packages because they use `chokidar` 

```
> fsevents@0.3.1 install /usr/local/www/node_modules/grunt-polyfill-service/node_modules/polyfill-service/node_modules/6to5/node_modules/chokidar/node_modules/fsevents
> node-gyp rebuild

gyp ERR! configure error 
ERR! stack Error: Python executable "python" is v3.4.1, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
```
`fsevents` depends on `node-gyp` which depends on [outdated](https://code.google.com/p/gyp/issues/detail?id=36) `gyp`

Some people start [petitions](https://www.change.org/petitions/google-inc-upgrade-gyp-to-support-phyton-3) to update the `gyp`, but it's useless because the Google has released a new project builder [gn](https://code.google.com/p/chromium/wiki/gn)

Python 3 was released in 2008, and I don't want to replace my work environment with Python 2 and no one wants!

**Comment by es128** [comment]
Fsevents is an optional dependency. Just ignore the warning messages and chokidar will work fine without it.

**Comment by monolithed** [comment]
It breaks my deploy with CI because `npm` writes to the stderr

**Comment by es128** [comment]
Ask npm to fix that bug for optional deps

**Comment by paulmillr** [comment]
If this is a common error we can look for a temp workaround.

**Comment by monolithed** [comment]
The problem has been solved, partially:

```
npm config set python python2.7
```

But i don't know what is:

```
> fsevents@0.3.1 install /usr/local/www/node_modules/grunt-polyfill-service/node_modules/polyfill-service/node_modules/6to5/node_modules/chokidar/node_modules/fsevents
> node-gyp rebuild

child_process: customFds option is deprecated, use stdio instead.
  SOLINK_MODULE(target) Release/.node
  SOLINK_MODULE(target) Release/.node: Finished
  CXX(target) Release/obj.target/fse/fsevents.o
  SOLINK_MODULE(target) Release/fse.node
  SOLINK_MODULE(target) Release/fse.node: Finished
```

**Comment by es128** [comment]
The stdio thing? That's coming out of node-gyp and also is not a problem.

**Comment by paulmillr** [comment]
@monolithed great to hear you've fixed the problem! I'll add the solution to README.
