### ISSUE TITLE
fsevents with node 0.12 - no events

### ISSUE THREAD

**Issue by soyuka** [paulmillr/chokidar#247]
Related to https://github.com/Unitech/PM2/issues/1062

Without the optional `fsevents` module, chokidar works just fine with node 0.12. When `fsevents` is enabled I don't receive any events from chokidar. `fsevents` seems to compile just fine with a deprecation warning: `child_process: customFds option is deprecated, use stdio instead.`.

Using node 0.12 and chokidar@0.12.6, also tried your latest 1.0.0-rc.

**Comment by es128** [comment]
Are you watching a network mount or a regular path on your hard disk?

You can always pass in the option `useFsEvents: false` if it's giving you trouble.

**Comment by soyuka** [comment]
Yes I knew that but I think it's only a temporary solution. 

Regular path atm, I'll dig a bit more ; chokidar tests with fsevents (1.0.0-rc) are going well.

**Comment by es128** [comment]
> When fsevents is enabled I don't receive any events from chokidar

Can you provide steps to reproduce? It works in general... need to narrow down to what's distinct about your implementation or the environment you're testing in.

**Comment by soyuka** [comment]
I'm trying hard to reproduce, but without `pm2` I can't.

I receive the `ready` event but my watcher don't seem to watch anything:

```
Ready: {"_watched":{},"_watchers":[],"_ignoredPaths":{},"closed":false,"_throttled":{},"_symlinkPaths":{},"enableBinaryInterval":true,"options":{"ignored":{},"persistent":false,"ignoreInitial":true,"useFsEvents":true,"ignorePermissionErrors":false,"interval":100,"binaryInterval":300,"atomic":false,"followSymlinks":true},"_initialAdd":false,"_readyCount":1,"_events":{},"restarting":false}
```

On the other hand when I try using [chokidar alone](https://gist.github.com/soyuka/dc0bfbcb2093d33c69cf) `_watched` is populated.

You are not using the [debug](https://github.com/visionmedia/debug) module, could be handy in this case :/.

I'll let you know if I find something useful.

**Comment by es128** [comment]
Are you sure you're passing in the path(s) to be watched the same way within PM2 as in your test script? There has to be some sort of difference in the implementation.

**Comment by soyuka** [comment]
Yes I'm sure, it definitely comes from pm2 thanks for you help. Closing for now.
