### ISSUE TITLE
Watching a file whose modified date doesnt get changed doesnt emit change[Polling Mode][Windows]

### ISSUE THREAD

**Issue by edi9999** [paulmillr/chokidar#248]
When using some specific software, the watches never get triggered for changes:

It works with notepad, sublime_text, ...

If I open the folder that contain those files, I can see that the modified Date doesn't change, but the size of the file does change.

I'm using the 1.x release, but the "misbehaviour" is also happening on 0.12.6. 

Here's my code:

    options=
      ignored:@ignoredFun
      persistent:true

    watcher = chokidar.watch(path,options)

    watcher
      .on('add', callbackAdded)
      .on('change', callbackAdded)
      .on('unlink', (path) ->console.info('File', path, 'has been removed');)
      .on('error', (error)-> console.error('Error happened', error))
      .on 'ready',()->console.log('watching files ...')

I've also tried to use:

      interval:1000
      binaryInterval:1000
      depth:5
      usePolling:true
      ignoreInitial:false

but this didn't help solve this issue.

I'm taking a guess that the polling option uses the **modification date** under the hood. Is they maybe an option to watch for filesize instead of modification date ? Or how would you tackle this issue ?

**Comment by edi9999** [comment]
I'm taking the guess that the code responsible for the modification date test is here:

https://github.com/paulmillr/chokidar/blob/e2f8fb9bef8e05a837ad41a4a8516bb1fffdb405/lib/nodefs-handler.js#L170-L171

Is that right ?

**Comment by es128** [comment]
Chokidar doesn't implement the actual polling mechanism - it comes from the node core method `fs.watchFile`. So basing the comparison on file size would not be an option here.

Polling is not the default behavior - on windows it would be to rely on `fs.watch`, which is built upon the `ReadDirectoryChangesW` native API.

The lines of code you pointed to only apply in polling mode, but yes they would filter out events for files whose `mtime` hasn't changed. If chokidar didn't do that, `change` events might be emitted every time the file is accessed.

You haven't indicated which software you're finding problematic, only some examples of ones that do work. If you want to get help in resolving your issue, you need to describe a way to reproduce the behavior you're observing.

You may also want to try listening to the `raw` event emitted by chokidar to get a better idea of what's happening under the hood, or perhaps it's something you can actually leverage to solve the problem you're experiencing in your environment.

**Comment by edi9999** [comment]
Ok, I get it, I was indeed using polling mode at the end to find a way to solve this issue. I've created a pull request (#249) to add the size change. If it's not ok for you to merge it, I'm going to use raw events.

**Comment by es128** [comment]
#249 merged
