### ISSUE TITLE
Collaboration with gaze/sane?

### ISSUE THREAD

**Issue by jzaefferer** [paulmillr/chokidar#250]
I had done some research trying to figure out what the best `fs.watch` wrapper might be. Apart from this project, both `gaze` and `sane` look like viable alternatives. Due to this project having by far the most modules depend on it, I had asked the [other](https://github.com/amasad/sane/issues/45) [two](https://github.com/shama/gaze/issues/182) about their status (more or less). It looks likes both projects admit some overlap, but neither sees chokidar as a viable alternative either.

I wonder if you could look into a bit more active collaboration. Maybe set up a meeting with the other authors (@shama, @amasad) to discuss the future of these projects?

The node community would surely profit from not having to evaluate multiple libraries again and again, instead having one well-maintained solution that gets all the attention. At least one node module with multiple backends like [watchman](https://github.com/facebook/watchman) or [navelgazer](https://github.com/shama/navelgazer).

**Comment by es128** [comment]
> figure out what the best `fs.watch` wrapper might be

It is inaccurate at this point to minimize any of these to being just an `fs.watch` wrapper. Apparently `fs.watch` on its own still has too many problems to be able to be manipulated into providing a reliable cross-platform solution.

> node community would surely profit from not having to evaluate multiple libraries again and again, instead having one well-maintained solution that gets all the attention

IMHO that would happen naturally if there was one clearly "best" option, but there isn't. This is a hard problem to get right, and both @shama and @amasad had very valid reasons for creating competing libraries at the time they did. At this point the underlying methodologies have diverged quite a bit as well. Your perspective also substantially underappreciates the positive impact competition has had on the quality of all these solutions.

That said, I [continue to welcome collaboration](https://github.com/paulmillr/chokidar/issues/138#issuecomment-58018439) with @shama, @amasad, and anyone else interested to make valuable contributions. In the past few months I've addressed the major faults chokidar had that inspired them to make alternate solutions to begin with, so it may be possible now to get chokidar to a point where they find it meets their needs if they're interested in engaging with the project. I wouldn't be totally opposed to allowing watchman and/or navelgazer interfaces in chokidar either, except that native extensions (even when optional) confuse and cause problems for a lot of people, so it would have to be approached carefully.

> one well-maintained solution that gets all the attention

![image](https://cloud.githubusercontent.com/assets/1740641/6487868/a6a93d54-c261-11e4-8025-140d1d6fc1bd.png)

**Comment by shama** [comment]
Well said @es128 :)

IMO, the true hero will be whoever fixes issues in `fs.watch` well enough to make all our watch libraries obsolete.

**Comment by es128** [comment]
Agree, but unfortunately that seems to be a long long way off.

**Comment by amasad** [comment]
I also welcome any ideas on how to collaborate. And I agree that native extension is a hassle, we've had success asking users to install watchman on their own to get the stability and perf benefits.

>IMO, the true hero will be whoever fixes issues in fs.watch well enough to make all our watch libraries obsolete.

:+1: Maybe the io.js folks are on it?
