### ISSUE TITLE
Sublime and atomic save triggering change

### ISSUE THREAD

**Issue by rentalhost** [paulmillr/chokidar#253]
On Windows, ST3, when `atomic_save` is enabled (default), chokidar is triggering `change` event on save files. Check here: http://stackoverflow.com/questions/28912513/sublime-is-touching-files-from-back-directory

Basically, if I change `/default/file.txt` with atomic save enabled, chokidar will trigger change to all `/default.*` files (yes, in back directory).

**Comment by rentalhost** [comment]
I guess that is possible check if file was really changed if time is different of first scan (from Stats).

**Comment by paulmillr** [comment]
Yeah, we are doing the stat comparison already. Are you using polling?

**Comment by rentalhost** [comment]
I tried some settings, but I don't tried to put `usePolling` to true. On really, I set it to `false`. :( Well, seems that it works now. I open case if need. Thanks!
