### ISSUE TITLE
Trigger event after all events run.

### ISSUE THREAD

**Issue by rentalhost** [paulmillr/chokidar#254]
Create a new event trigger that will run after all events run. If it's not possible, can trigger event after 10ms without events, for instance. If I do `unlink` after 10ms it'll trigger `done`, for instance. If I remove 1000 files without create this gap, `done` not will be trigged, but after 10ms after the last event, it'll be triggered.

Real case: for instance, if I watch `.less` files, and I have a folder with it and I remove it, it'll trigger `unlink` for each file first, and lastly `unlinkDir`. But if I do it with a lot dir on same time, it'll mix events between `unlink` and `unlinkDir`. And I like run a code after all events (rebuild my index, from my code, and I need that no events is running).

**Comment by es128** [comment]
I don't see how this is something chokidar ought to provide. You're just asking for a timer to fire when there haven't been events in a little while, which you can easily implement yourself.

What meaning does it have anyway? Who's to say that right after the event you're asking for is fired, 11ms after the prior event, another legit change event won't happen?

If chokidar's events trigger a long-running process in your implementation, you should have events that occur during that processing just flip a dirty bit so your process can know it has to run again after the prior cycle is done.
