### ISSUE TITLE
Deleting directory fire addDir events instead of unlinkDir on windows with depth=0

### ISSUE THREAD

**Issue by felicienfrancois** [paulmillr/chokidar#256]
On windows with depth=0, the `unlinkDir` event is not fired.
Instead one `addDir` event per remaining dir is fired.

```
> watched_dir
   > dir1
   > dir2  <- deleting this one
   > dir3
   > dir4
```

Events with depth=1:
```
unlinkDir dir2
```

Events with depth=0:
```
addDir dir1
addDir dir3
addDir dir4
```

Tested on Windows 8.1 with IO.JS 1.4.3

**Comment by felicienfrancois** [comment]
Probably related to this:

When renaming a directory with depth=0, only the addDir event is fired, not the unlinkDir one.
Works with depth=1

**Comment by es128** [comment]
Recently fixed some bugs that may be related. Please try with the master branch if you haven't already.

**Comment by felicienfrancois** [comment]
I still get the 2 issues with the head of master branch

**Comment by es128** [comment]
Ok thanks for the feedback. Can you also show me how you're passing the paths/patterns to be watched and which options you're using?

**Comment by felicienfrancois** [comment]
For sure:

```javascript
var chokidar = require("chokidar");
var watcher = chokidar.watch(".", {
    persistent: true,
    depth: 0
}).on("all", function(event, path) {
    console.log(event + " "+path);
});
```
I get the same issues when passing an absolute path (anti-slashes separated);
