### ISSUE TITLE
Early emitting change event

### ISSUE THREAD

**Issue by floatdrop** [paulmillr/chokidar#257]
Some wierd stuff happens sometimes. `change` event is emitted, but file contents is empty:

```
change
<File "mobile/app.js" <Buffer 61 61 61 73 64 61 73 64 61 73 0a>>
  watch 51012352 +128ms
change
<File "mobile/app.js" <Buffer >>
  watch 51012352 +122ms
change
<File "mobile/app.js" <Buffer 61 61 61 73 64 61 73 64 61 73 0a>>
  watch 51012352 +108ms
```

I'm getting this in Atom with `ctrl+s` pressed constantly (it happens pretty rare thou). We workaround it with some delay before reading, because it could be just how IDE's work.

https://github.com/floatdrop/gulp-watch/issues/143

**Comment by floatdrop** [comment]
And it is not reproducing with bare `chokidar`.

**Comment by es128** [comment]
Yeah even if you could reproduce it I don't see how chokidar could help. Sounds like it's effectively a race condition between the editor and gulp task. Maybe vinyl could get some sort of retry logic if a file is unexpectedly empty.

**Comment by floatdrop** [comment]
@es128 but there is empty files (like when you erase whole file and save) on change event.

**Comment by es128** [comment]
Yeah, I'm suggesting maybe like a single retry after a short delay just in case of editor artifacts like what you observed in this case. It would be tricky to do without creating other race conditions/edge cases - but it's a potential avenue to explore if trying to automatically correct for this problem
