### ISSUE TITLE
unwatched file still trigger "all" event when modified

### ISSUE THREAD

**Issue by MoOx** [paulmillr/chokidar#258]
Here is my scenario:

I watch 2 files A & B, I add them & execute a function on "all" event. If I unwatch B & modify this B file, I still have the watcher triggering "all" event, is this on purpose ? Looks like a bug.

To reproduce here is a branch: https://github.com/cssnext/cssnext/tree/watch-imported

Here is the part that add/unwtach appropriate files 

https://github.com/cssnext/cssnext/blob/fbfaff5053180192e146cdde8d1986a39e0d3980/bin/cssnext.js#L107-L113

Here is the broken test https://github.com/cssnext/cssnext/blob/fbfaff5053180192e146cdde8d1986a39e0d3980/test/cli.js#L177-L189

I have also tried by hand. To reproduce:
1. clone the repo, checkout the branch `watch-imported`, then `npm install`
- run the following command `bin/cssnext.js --watch test/fixtures/cli.watch-import.css test/fixtures/cli.watch-import.actual.css`
- modify `test/fixtures/cli.watch-import.css` with `/**/ @import "cli.watch-import-import.css";`: you will see that the imported file has been added
- trigger a change in this imported file `test/fixtures/cli.watch-import-import.css` (_this is working as expected_)
- now modify `test/fixtures/cli.watch-import.css` with `/**/`: you will see that the file is _unwatch_ed
- trigger a change in this (now supposed to be unwatched) previously imported file `test/fixtures/cli.watch-import-import.css`: you got a change triggered by the watcher (_this is not what I expect_)

**Comment by es128** [comment]
Thanks for reporting. Can you please provide a script or procedure to reproduce using only chokidar? The example.js script in the repo is usually a good starting point.

**Comment by es128** [comment]
For reference, here are the passing tests for `unwatch`: https://github.com/paulmillr/chokidar/blob/master/test.js#L1109

Perhaps modifying one of them to act on individual files like in your scenario will expose the issue
