### ISSUE TITLE
Lost events with copy/move of many files using OS X Finder

### ISSUE THREAD

**Issue by CragVFX** [paulmillr/chokidar#259]
There seems to be an issue with the add event on this lib. When I drag and drop a large amount of files onto the watched dir, it grabs some of them, but the others don't fire the add event. If I then add another file, the watcher see the remaining files from before and the additional file that was added after the watcher got stuck.  I separated this issue and tested got the same result.

var chokidar = require('chokidar');

var watcher = chokidar.watch('/Users/johndoe/Desktop/files', {
    ignored: /[\/\]./,
    ignoreInitial: true,
    alwaysStat: true,
    useFsEvents: false,
    persistent: true
});

var count = 0;

watcher.on('add', function(filePath) {
    count++
    console.log('received: ', filePath, ' count #: ', count);
});

**Comment by es128** [comment]
Why is `useFsEvents: false`?

**Comment by CragVFX** [comment]
useFsEvents is false because I was testing out the configuration. Having this set to false did not make a difference, it had the same result.

**Comment by es128** [comment]
Is it reproducible using an `mv` command? Or only Finder drag-n-drop?

**Comment by CragVFX** [comment]
Well, after using the mv command it worked like it's supposed to... I appreciate the help.

**Comment by es128** [comment]
So yeah there's something going on with the finder move/copy operation. Will leave this open so it can eventually be investigated further for potential solutions.

**Comment by CragVFX** [comment]
So after further testing, it looks like this issue is also replicable via the mv commands. I have been moving around 600 files at a time and it seems like it is becoming stuck again and it remains stuck until another file is added.

**Comment by nono** [comment]
I looks like it can also happen on linux with node 0.10.32 and chokidar 1.3.0.
