### ISSUE TITLE
`change` events before `add` events for a file.

### ISSUE THREAD

**Issue by ohjames** [paulmillr/chokidar#261]
On Linux this is easily reproducible, not sure if it affects other OSs:
1. Watch `unlink`/`change`/`add` events for glob pattern such as `tmp/*.js`
2. Keep doing `touch tmp/file.js ; sleep 1 ; remove tmp/file.js` over and over.
3. You'll often see, after the `touch` that you'll get a `change` before the `add`.

This means users of chokidar have to second-guess what chokidar is telling them in order to be sure of the filesystem state, naively trusting the events leads you to think non-existing files have changed.

**Comment by nuisanceofcats** [comment]
I'm investigating this, it looks like an issue with `fs.watch` on Linux. My planned PR for #262 would fix this, the `buffering debounce` + `merge` stage would remove the change events.

**Comment by nuisanceofcats** [comment]
It seems to act different on node 0.12 and node 0.10 also.

**Comment by es128** [comment]
Chokidar already normalizes events (or at least attempts to) to ensure for instance it doesn't emit `change` before `add` on a newly observed file. If there's a case where it doesn't I consider it a bug in the existing code that shouldn't require a new buffering layer to fix. 

But I'm concerned that this report is just indicative of artificially created race conditions with the `touch` and `rm` commands being mixed together non-deterministically. I'll try it out myself when I get a chance to see what I can observe.

**Comment by mercmobily** [comment]
I can confirm that I am having the same problem: a 'change' event is fired right before the 'add' event when a file is moved out of the watched directory. I am not sure how to get around this problem at the moment in my own software...!

**Comment by ohjames** [comment]
Ah I kinda forgot about this, I think it was something to do with chokidar coalescing events watch by watch whereas my layer above had access to all watchers so could coalesce events between them all. I ended up writing `process-pool` so I could fork work over multiple CPUs ensuring the process using `chokidar` would never get janked.

**Comment by paulmillr** [comment]
Let us know if that still happens with the latest chokidar.
