### ISSUE TITLE
chokidar is time sensitive, can report invalid events when system is under stress.

### ISSUE THREAD

**Issue by nuisanceofcats** [paulmillr/chokidar#262]
In this example:

```javascript
var chokidar = require('chokidar')

var watcher = new chokidar.watch('src/*.js', { ignoreInitial: true })

; ['add', 'change', 'unlink'].forEach(function(type) {
  watcher.on(type, function(path) {
    console.log(Date.now(), type, path)
    for (var i = 0; i < 1000000000; ++i) {}
    return path
  })
})
```

If I create a file called `src/blah.js` then run this script, then append some content to the file:

```
1427029324428 'change' 'src/stream.js'
```

The second time I append content to the file (with the same script still running) I see:

```
1427029328111 'change' 'src/stream.js'
1427029329984 'change' 'src/stream.js'
1427029330936 'add' 'src/stream.js'
```

Now if I remove the busy loop:

```javascript
for (var i = 0; i < 1000000000; ++i) {}
```

Then every time I append to the file I see the single `change` event I expect.

**Comment by es128** [comment]
Well yeah, this is how node works. Not a chokidar issue. Don't block the event loop if you don't want bad things to happen.

**Comment by nuisanceofcats** [comment]
That was just a contrived example, any small amount of work, like the small amount of work you'd do in any reasonable application, can lead to the same thing. Please re-open this issue.

**Comment by es128** [comment]
Not without a reasonable example that actually points to an issue in chokidar. This is more of a complaint about the nature of node's single-threaded model.

**Comment by nuisanceofcats** [comment]
So you don't think that if your replace my for loop (which only takes 300ms BTW) with any other small amount of work, this would still be an issue?

You're talking down to me and assuming I don't know about node.js, blocking event models etc. I can assure you I do.

**Comment by nuisanceofcats** [comment]
We're seeing this issue here in production, obviously not using a for() {} loop, just by doing some compilations with `babel`.

**Comment by nuisanceofcats** [comment]
If that `for` loop offends you so, just replace it with the compilation of the file using `babel`.

**Comment by es128** [comment]
Then please describe an actual addressable issue. Doing 300ms of cpu-blocking work is a huge deal that will affect all your async stuff. Didn't mean any offense, but the nature of your questions points to some misunderstandings. If you understand the internals, then what do you propose that chokidar should do differently?

Assuming a non-contrived example, the implementation solution would be to offload your cpu-intensive work to a separate process via `child_process`, `cluster`, or a myriad of other ways and do enough orchestration to manage the potential races.

**Comment by nuisanceofcats** [comment]
I think you may be generalising a bit too much, whilst in most scenarios you would want to avoid large blocking tasks, there are certainly scenarios where it's not possible or desirable e.g. a compilation pipeline, if each output is the input for the next task you gain nothing but complexity by forking a sub process for each one.

I don't think it's unreasonable to assume that a file watcher could deal with this (e.g. EPOLL on linux can handle it) by queuing and merging events to avoid delivering an impossible event stream.

Maybe it's <1% of uses for chokidar though, and if you don't want to support such use cases that's totally understandable! At the same time I don't think it's logically necessary that bursts of synchronous activity will lead to "bad things" happening.

Have a good day!

**Comment by nuisanceofcats** [comment]
BTW just in case you are interested in a real-world application where this has been an issue:

A company I did some work for was using an old version of `gulp` with a `gulp.watch` plugin built on top of chokidar. Their build system was breaking due to some of the gulp tasks performing time-consuming synchronous tasks, leading to the gulp watcher to deliver invalid events.

**Comment by es128** [comment]
I would work on dealing with it if there were anything under chokidar's control that could be changed to help. But you haven't described any evidence of that being the case so far. 

Your suggestion regarding queuing and merging events seems to assume chokidar knows anything about whether the event loop is stressed or what has happened on the event listener side. Chokidar already suppresses duplicate events coming from the file system, but if they're received far enough apart then they come out as separate events. Regarding `add` being emitted after `change`, you've opened a separate issue for that and I'm still going to look into it.

**Comment by nuisanceofcats** [comment]
> Your suggestion regarding queuing and merging events seems to assume chokidar knows anything about whether the event loop is stressed or what has happened on the event listener side.

Chokidar wouldn't have to know how stressed the system is or about the event listener, if it did a "buffering debounce" where instead of taking the final event as the stream output, it buffers the events together, and then does a merge at this stage, you'd solve this problem.

I've put that on top of chokidar in the last 5 minutes and it works really well. It could also work inside of chokidar, but I completely understand if you aren't interested in that change.

**Comment by es128** [comment]
PR welcome

**Comment by mercmobily** [comment]
@ohjames I humbly encourage you to tell us about your wrapper around chokidar if it helps fixing this issue...!
