### ISSUE TITLE
Timescale for 1.0.0 release?

### ISSUE THREAD

**Issue by shakyShane** [paulmillr/chokidar#264]
I'm intending to use Chokidar in a project of mine, but I'm very much reliant on a few fixed you've done since the `rc4`.

In particular I absolutely love the support for this syntax when ignoring certain patterns. It's possible in the latest master, but the same thing requires  the use of Regex literals in `rc4`.

```js
ignored: ["**/*.css", "**/*.scss"]
```

So, I'm just wondering if there's any idea of timescales re: either a `1.0.0`, or the next `rc` ?

Thanks :)

**Comment by es128** [comment]
https://github.com/paulmillr/chokidar/issues/231#issuecomment-83789540

I'll publish within the next day or two. Probably another rc.

**Comment by es128** [comment]
Well maybe 1.0.0, despite a few open bugs remaining. I'll think about it.

**Comment by shakyShane** [comment]
Awesome - looking forward to it :)
