### ISSUE TITLE
PathTooLongException on windows because of node dependency directory tree

### ISSUE THREAD

**Issue by Zazcallabah** [paulmillr/chokidar#267]
The anymatch dependency added here https://github.com/paulmillr/chokidar/commit/1b9a73d6793b40b2189b525c2bdd8a007158a2d9
generates such a deep dependency tree that it becomes very unwieldy to handle in windows, with folders that can't be removed etc.

The deepest one I found was anymatch\node_modules\
micromatch\node_modules\regex-cache\node_modules\benchmarked\node_modules\
file-reader\node_modules\read-yaml\node_modules\js-yaml\node_modules\argparse\node_modules\lodash

I don't really have a solution to the problem to suggest, I just wanted to alert you that this library has suddenly become very hard to use on windows.

**Comment by es128** [comment]
When exactly do you encounter the error? Does it prevent the program from running?

This has the potential to happen with lots of node programs - deep dependency trees are common.

There are extensive discussions on this topic in the node and npm issue trackers which cover various workarounds. 

One which should work easily in this case is to lock anymatch at v1.1.0 either by including it in your package.json and using `npm dedupe` or with a shrinkwrap file. 

/cc @jonschlinkert

**Comment by es128** [comment]
Also the particular path you pointed out is the result of dev dependencies. Perhaps `npm prune --production` has a positive impact?

**Comment by Zazcallabah** [comment]
It is stupid really, we run karma tests as a part of our build process. Now the tests run as they are supposed to, but afterwards we get exceptions from powershell when trying to list/move/copy files. Also git stops being able to clean the repo.

I think I solved it by running npm uninstall after the tests have run. npm could create the folders, it can obviously remove them as well.

**Comment by es128** [comment]
I would suggest `npm prune --production` after the tests run if there are any dependencies you do need to keep around.
