### ISSUE TITLE
Mac: no event triggering

### ISSUE THREAD

**Issue by molerat619** [paulmillr/chokidar#268]
Hi there,

maybe I'm doing it wrong, but following code does not trigger any events, when I add a txt-file to one of the watched directories. Just for testing, I required test.js which logs something in the console, just to prove that the path is right.

Here's my code:

var chokidar = require('chokidar');

var watcher = chokidar.watch('file or dir', {
    persistent: true
});

var log = console.log.bind(console);

watcher
    .on('add', function(path) { console.log('teeest'); log('File', path, 'has been added'); })
    .on('addDir', function(path) { console.log('teeest');  log('Directory', path, 'has been added'); })
    .on('change', function(path) { log('File', path, 'has been changed'); })
    .on('unlink', function(path) { log('File', path, 'has been removed'); })
    .on('unlinkDir', function(path) { log('Directory', path, 'has been removed'); })
    .on('error', function(error) { log('Error happened', error); })
    .on('ready', function() { log('######## Initial scan complete. Ready for changes.'); })
    .on('raw', function(event, path, details) { log('Raw event info:', event, path, details); })
    .on('all', function(event, path) {
        console.log('something happened');
        console.log(event, path);
    });

// 'add', 'addDir' and 'change' events also receive stat() results as second
// argument when available: http://nodejs.org/api/fs.html#fs_class_fs_stats
watcher.on('change', function(path, stats) {
    console.log('change triggered');
    if (stats) console.log('File', path, 'changed size to', stats.size);
});

// Watch new files.
watcher.add('test/test.txt');
watcher.add('test/');
watcher.add('test');
watcher.add('/test');
watcher.add('../../pnr/');
watcher.add('../../pnr');

require('../../pnr/test.js');

The ready-event is triggered and I can see '######## Initial scan complete. Ready for changes.' in my console.

Thx for your help :)

**Comment by es128** [comment]
Replace the part that says `'file or dir'` with an actual path.

**Comment by molerat619** [comment]
Thanks for your fast answer. After replacing `'file or dir'` with a path like those that I added to the watcher, I still don't get any log messages after creating text-files.

Assume that I have following structure:

server
    > api
    > components
         > pnr_sync
              > pnr_sync.js      <----- the file containing the code I just showed to you in my post
    > pnr                 <----- I want to watch this one for new files


What would you provide as a path for the pnr-folder? I got '../../pnr' and it's not working

**Comment by es128** [comment]
Depends on what `cwd` is when you run your script. If you want it to be based on the location of `pnr_sync.js` you could use something like

```js
var path = require('path')
chokidar.watch(path.join(__dirname, '../../pnr'))
```

**Comment by molerat619** [comment]
Thank you very much, that did it! Awesome support, I am very happy about this
--
Mit freundlichen Grüßen, 
Marcel Izgin 
Freitag, 27 März 2015, 02:21Nachm. +01:00 von Elan Shanker <notifications@github.com>:

**Comment by es128** [comment]
Good to hear.

https://twitter.com/mistydemeo/status/580786410342342656 :smile:
