### ISSUE TITLE
gitter channel

### ISSUE THREAD

**Issue by shakyShane** [paulmillr/chokidar#276]
Have you guys considered creating a [gitter chanel](https://gitter.im) for chokidar? I've recently done it for a couple of projects - takes zero maintenance + gives people a chance to chat to other users.

**Comment by es128** [comment]
I've participated in Babel's a bit, but didn't realize there would be enough interest to justify one for chokidar. Plus there's no way I could hang out in there as much as Sebastian does. 

But if you think it would be worthwhile there's no harm in giving it a shot I guess. Plus now that you bring it up it makes even more sense to me to set one up for Brunch.  

Thanks for the suggestion :smile:

**Comment by es128** [comment]
Alrighty I created it. https://gitter.im/paulmillr/chokidar

we'll see what happens
