### ISSUE TITLE
Expose version in exports

### ISSUE THREAD

**Issue by kimmobrunfeldt** [paulmillr/chokidar#285]
I'm creating a cli tool for chokidar and I'd like to add chokidar's version also in the --help. Can you expose version like this: ```var version = require('chokidar').version;``` ?

You can internally do it by requiring package.json:

```javascript
module.exports = {
    // ... other stuff ...
    version: require('../package.json').version
}
```

**Comment by es128** [comment]
I guess, but then you're requiring your users to only use versions of chokidar that come after that change is made. What if you were to just

```js
exports.chokidarVersion = require('chokidar/package').version;
```

**Comment by kimmobrunfeldt** [comment]
That's a better way indeed. Will use that one, thanks!
