### ISSUE TITLE
ready event fired multiple times

### ISSUE THREAD

**Issue by kimmobrunfeldt** [paulmillr/chokidar#286]
Is it intended behavior that `'ready'`event fires multiple times ?

To reproduce:

```javascript
var chokidar = require('chokidar');

var watcher = chokidar.watch([ '**', 'a', 'ak', '**.js*' ]);

watcher.on('ready', function() {
    console.log('ready');
});
```

chokidar version 1.0.1

**Comment by kimmobrunfeldt** [comment]
For a temp hack I'll add a debounce for the callback:

```javascript
    watcher.on('ready', _.debounce(function() {
        // stuff
    }, 500));
```

**Comment by es128** [comment]
Hmm, I think it's a bug, but I haven't really thought about it in the context of an array of watch patterns. Will need to look into it.

A better temp hack may be `watcher.once('ready', ...`

**Comment by kimmobrunfeldt** [comment]
Ok good to know. Yeah that's definitely a better temp hack.

**Comment by es128** [comment]
This has been reported again in #338. Will close this one and allow discussion on the topic to resume in the newer thread.
