### ISSUE TITLE
Problem with braced glob patterns that match subdir contents, but not the subdir

### ISSUE THREAD

**Issue by ohjames** [paulmillr/chokidar#287]
Things like `build/{,test/}*.js` can sometimes be useful... when you have a project with lots of nested directories then using `build/**/*.js` can really slow things down, in other cases it's just a neat shorthand. Some other watch libraries support it but all of those have too many issues to be reliable alternatives to chokidar.

I'm happy to work on the code if you think this would be useful.

**Comment by paulmillr** [comment]
Isn't this a micromatch issue?

**Comment by ohjames** [comment]
micromatch supports expanded glob patterns already. I couldn't find `micromatch` in chokidar's dependency list, is it including it via a different package? Maybe that package needs to upgrade it's micromatch dependency or something?

**Comment by es128** [comment]
micromatch is included via anymatch. All versions are at latest, although there are some in-progress improvements to micromatch that haven't been published quite yet (not sure whether that has an impact on your use case. 

Brace expansion is supported, but I haven't see an example yet with the leading comma like you showed. If you're having trouble with it in chokidar I suggest you open an issue there describing your pattern and the sorts of paths you expect it to match that aren't.

**Comment by es128** [comment]
Btw another option for expressing what you want to watch with more standard syntax would be `['build/*.js', 'build/test/*.js']`

**Comment by ohjames** [comment]
Thanks for the tip! I'm aware of that, I just saw the `{,optional-directory/}` pattern used in the angular-fullstack-generator and thought it was neat.

**Comment by es128** [comment]
I just tried your pattern, and it seems to already work. Did you try it with chokidar before opening this issue?

```js
~/Code/anymatch (1.2.1)
λ node
> am = require('./')
[Function]
> am('build/{,test/}*.js', 'build/foo.js')
true
> am('build/{,test/}*.js', 'build/test/foo.js')
true
> am('build/{,test/}*.js', 'build/otherdir/foo.js')
false
```

**Comment by ohjames** [comment]
@es128 Thanks for being so thorough with your help, yes I tested it with chokidar but not `1.0.1`, there's also of course the possibility I made a stupid mistake, I'll update this issue with my results in case you're interested, thanks again for your time.

**Comment by es128** [comment]
Yes, if you can demonstrate a problem I'd like to hear about it.

**Comment by ohjames** [comment]
@es128 here you go:

file: choki.js
```javascript
var chokidar = require('chokidar')
var watcher = chokidar.watch('src/{plugin/,}*.js')
watcher.on('all', function (ev, path) { console.log(path) })
```

Then in the shell:
```
npm install chokidar
mkdir -p src/plugin
touch src/file1.js
touch src/plugin/file2.js
node choki.js
```

You'll see the output:

```
src/file1.js
```

No `src/plugin/file2.js` as expected.

**Comment by ohjames** [comment]
```
grep version node_modules/chokidar/package.json
  "version": "1.0.1",
```

**Comment by ohjames** [comment]
In the shell it works as expected:

```
% echo src/{plugin/,}*.js
src/plugin/file2.js src/file1.js
```

**Comment by ohjames** [comment]
Yet it works in micromatch:

```javascript
var micromatch = require('micromatch')
console.log(micromatch(['src/file1.js', 'src/plugin/file2.js'], ['src/{plugin/,}*.js']))
```
Shows:

```
[ 'src/file1.js', 'src/plugin/file2.js' ]
```

So it works in micromatch but not in chokidar.

**Comment by ohjames** [comment]
Maybe should re-open this issue?

**Comment by es128** [comment]
Ok I'm pretty sure what's happening here is that the pattern does not match the directory `src/plugin` so chokidar does not bother to check its contents

**Comment by es128** [comment]
In fact, chokidar does detect changes to `src/plugin/file2.js`, it just misses it during the initial scan.

**Comment by es128** [comment]
Unfortunately, the likely solution to this is to recursively scan the entire file tree under the glob parent (`src/` in this case) for potential matches, which negates the performance impact you were seeking by using such a pattern to begin with.

**Comment by ohjames** [comment]
For me the improvement I was seeking was terseness rather than performance. You could limit the depth of filetree lookup to the depth of the longest sub-expression (in the case that no sub-expression is recursive). You could also post-process brace expressions to reduce them into multiple equivalent arguments.

**Comment by ohjames** [comment]
>In fact, chokidar does detect changes to src/plugin/file2.js, it just misses it during the initial scan.

I'm not seeing this... when I `touch src/plugin/file2.js` I get no chokidar events, so it's missed both during the initial scan and for updates.

**Comment by es128** [comment]
You haven't mentioned which OS you're on - there's likely a difference here between fsevents-mode on OS X and the others. Anyway, same root cause.

**Comment by ohjames** [comment]
> You haven't mentioned which OS you're on

Sorry I updated my previous comment right after I made it with that info, I'm using Linux.

**Comment by es128** [comment]
> You could limit the depth of filetree lookup to the depth of the longest sub-expression

I want to avoid adding a bunch of code to chokidar making it more directly aware of glob pattern contexts. 

Maybe micromatch or a different module intended for this purpose that has a good understanding of globs anyway could provide a way to determine whether, for a given directory path and glob pattern, there is a possibility for any of the directory's children to match the pattern. Until something like that becomes available, chokidar would need to stop filtering out any dirs under the glob parent to fix this issue.

**Comment by es128** [comment]
The problem is here: https://github.com/paulmillr/chokidar/blob/master/index.js#L244-L262

Simply splitting on the path separator won't work for these cases. Will be thinking about better ways to approach this. Would appreciate any ideas.

**Comment by ohjames** [comment]
Ah I see, you could make `getDirParts` first recursively expand brace expressions, but then you end up having to be more glob-pattern aware. Maybe if some of the micromatch private API was made public you could interrogate it for the directory parts?

**Comment by es128** [comment]
I think I would actually consider using https://github.com/jonschlinkert/braces to expand the pattern si tgat splitting on slashes is valid again - should be doable without adding too much complexity.

Although if path separators can also be embedded in other pattern parts like brackets and extglobs then I'm getting worried about how deep this rabbit hole can go. Will need to check into it.

**Comment by jonschlinkert** [comment]
> Although if path separators can also be embedded in other pattern parts like brackets and extglobs then I'm getting worried about how deep this rabbit hole can go. Will need to check into it.

just saw this. as a rule of thumb, braces go first since they can be "split" into multiple patterns. after that, it's not to complicated.

**Comment by iclanzan** [comment]
I have been struggling to understand why my patterns where not working with `chokidar` when they are working with `anymatch` until I found this issue.

Would appreciate if someone with the know-how could fix this.

**Comment by jonschlinkert** [comment]
> I have been struggling to understand why my patterns where not working with chokidar when they are working with anymatch until I found this issue.

@iclanzan can you paste the code you're using that isn't working? also a description of directory structure etc

**Comment by iclanzan** [comment]
Hope this helps:

```js
anymatch(
  '{modules/*,public/js}/test/*.test.js',
  'modules/utils/test/index.test.js'
)
// => true

chokidar.watch('{modules/*,public/js}/test/*.test.js').on('add', () => {
  // this never gets called
})

chokidar.watch('modules/*/test/*.test.js').on('add', () => {
  // this works
})
```

**Comment by jonschlinkert** [comment]
I assume there are other paths with `public/js` in them, would you mind adding a few other paths for reference? thanks

**Comment by iclanzan** [comment]
Here are a few paths I expected chokidar to watch with the above command:

```
modules/utils/test/index.test.js
modules/utils/test/functional.test.js
modules/user/test/auth.test.js
public/js/test/components.test.js
public/js/test/inlineStyle.test.js
```

**Comment by jonschlinkert** [comment]
One more question, sorry if you already mentioned this. what platform are you on?

**Comment by iclanzan** [comment]
I will answer as many questions as I can to help.
I am on `OS X 10.11.4`.

**Comment by jonschlinkert** [comment]
Ok, I played around with it for a bit and I have an idea about what's happening. 

This first pattern does not trigger `.add` events initially, but it does when a file changes. 

```js
chokidar.watch('{modules/*,public/js}/test/*.test.js').on('add', () => {
  // this never gets called
})
```

This pattern triggers `.add` events initially and when files change.

```js
chokidar.watch('modules/*/test/*.test.js').on('add', () => {
  // this works
})
```

Also, I'm not that familiar with the code yet but what I think is happening is the "glob parent" is using `.` (cwd) as the directory initially since the brace pattern isn't expanded (to get the glob parent from each resulting pattern). Then when a file changes in a child directory of `.`, it emits the event as expected.

> I'm getting worried about how deep this rabbit hole can go. Will need to check into it.

IMHO expanding braces seems like a reasonable solution. The braces lib is pretty fast, and creating working arounds might be even more of a rabbit hole - at least I can't think of any fs/path workarounds that wouldn't end up with the same issues. 

extglobs are a bit more complicated, since they don't get expanded into arrays of globs and matching is done by regex alone, so you wouldn't be able to resolve a different/better glob parent. But I think that's probably another issue. just my 2c

**Comment by es128** [comment]
PR welcome. I believe the problematic code can now be found at https://github.com/paulmillr/chokidar/blob/master/index.js#L402-L422. The braces lib needs to be introduced to expand braced sections of the pattern prior to splitting on the path separator.
