### ISSUE TITLE
Problems with .add() and ready event

### ISSUE THREAD

**Issue by caspervonb** [paulmillr/chokidar#288]
Example, the following test will fail (timeout)

```js
test('chokidar ready', function(t) {
  var tempdir = temp.mkdirSync('test');
  var filenames =  [
    path.join(tempdir, 'script1.js'),
    path.join(tempdir, 'script2.js')
  ];

  var watcher = chokidar.watch(__dirname);
  // both cases fail
  // var watcher = chokidar.watch(tempdir); 
  watcher.add(filenames);

  watcher.on('ready', function() {
    t.comment('ready');
    t.end();
  });

  watcher.on('add', function(filename) {
    t.ok(filename, 'add ' + filename);
  });

  fs.writeFileSync(filenames[0], '1');
  fs.writeFileSync(filenames[1], '2');
});
```

**Comment by es128** [comment]
It is designed to fire once per watcher instantiation, so it looks like by putting your call to `.add()` in between you may be binding your listener too late. Try binding your event listeners immediately when creating the watcher before doing any other operations.

**Comment by es128** [comment]
Although basically you're not going to get the behavior you're expecting unless you just `.watch(filenames)` instead of adding them later.

**Comment by caspervonb** [comment]
calling .add just stops ready from ever firing it seems, even if on('ready') is bound directly after chokidar.watch

**Comment by MoOx** [comment]
I am getting a similar issue where ready isn't fired at all if I use watch(input) and then 2 .add(). https://github.com/cssnext/cssnext/issues/123
I just investigated a little and I confirm it really seems related to chokidar.

**Comment by paulmillr** [comment]
Let us know if that still happens with the latest chokidar.

**Comment by bgradin** [comment]
I'm experiencing this on chokidar 1.6.1. Placement of `.add(...)` doesn't seem to affect the issue; `ready` doesn't trigger regardless.

**Comment by Stevemoretz** [comment]
It does even now not for a small directory but I'm using for WordPress structure and it never calls ready event.
