### ISSUE TITLE
No events for paths that were watched > unwatched > added again

### ISSUE THREAD

**Issue by mehiel** [paulmillr/chokidar#289]
I'm facing an issue of having some paths that are watched, I unwatch them and then I add them again for watching.

**OS**: Linux 3.19.3 on Debian stretch/sid
**filesystem**: ext4
**nodejs**: v0.10.29

He're is a patch adding a failing test case  in `test.js` (at least in my env):
```diff
diff --git a/test.js b/test.js
index 255359b..dd5437e 100644
--- a/test.js
+++ b/test.js
@@ -1234,6 +1234,24 @@ function runTests(options) {
           }));
       })();
     });
+    it('should watch paths the were unwatched and added again', function(done) {
+      var spy = sinon.spy();
+      var watchPaths = [getFixturePath('add.txt'), getFixturePath('change.txt')];
+      watcher = chokidar.watch(watchPaths, options)
+        .on('all', spy)
+        .on('ready', d(function() {
+          watcher.unwatch(getFixturePath('change.txt'));
+          watcher.add(getFixturePath('change.txt'));
+          fs.writeFileSync(getFixturePath('add.txt'), 'c');
+          fs.writeFileSync(getFixturePath('change.txt'), 'c');
+          waitFor([spy, 2], function() {
+            spy.should.have.been.calledWith('add', getFixturePath('add.txt'));
+            spy.should.have.been.calledWith('change', getFixturePath('change.txt'));
+            spy.should.have.been.calledTwice;
+            done();
+          });
+        }));
+    });
   });
   describe('close', function() {
     beforeEach(clean);
```

**Comment by es128** [comment]
Thanks for the report. Providing a test is particularly awesome :+1: :trophy: 

[This code](https://github.com/paulmillr/chokidar/blob/master/index.js#L385-L391) is intended to solve for this situation, but I'll look into the case you've provided.

**Comment by mehiel** [comment]
Hi @es128, thanks for pointing me there. I'll try to find some time tomorrow to run it under a debugger and see if I can find what's wrong myself.

**Comment by es128** [comment]
That would be great! Note the [corresponding ignore stuff in `unwatch`](https://github.com/paulmillr/chokidar/blob/master/index.js#L433-L438)

**Comment by mehiel** [comment]
I think it is a different execution path causing the issue. 

It seems that the line that prevents a path from being added again is: [nodefs-handler.js:252](https://github.com/paulmillr/chokidar/blob/master/lib/nodefs-handler.js#L252)

After unwatching `changed.txt` from the above test the `watcher._watched` map is still there and when we add the file back it is that line 252 that returns without actually adding the watcher. I'll dig deeper to check what closers do.

Does all this make any sense? Please correct me if I'm wrong here.

**Comment by es128** [comment]
Yeah seems totally plausible. The paths' keys ought to get destroyed after the closers are called to prevent this.

**Comment by jameslnewell** [comment]
I'm experiencing the same issue on Win7 with nodejs v0.12.1.

**Comment by jameslnewell** [comment]
Can you please do a release to get this in the wild?

**Comment by es128** [comment]
Need to first fix the issues with `unwatch` that this caused or exposed. Sorry I haven't the time lately to sort it out - hope to focus some time on it soon.
