### ISSUE TITLE
when i set depth is 4, it still triggered more than 4 levels

### ISSUE THREAD

**Issue by fyddaben** [paulmillr/chokidar#290]
this is my code
```
  var watcher = chokidar.watch(__dirname+'/15', {
  ignored: /[\/\\]\./, persistent: true,ignoreInitial:true,depth:4
});
```
then run `touch 15/03453/js/libs/libs/index.js`

it still trigger 

why? (´･_･`)

**Comment by es128** [comment]
It traversed exactly 4 levels of subdirectories from the watched path: `03453/js/libs/libs`. This is how it is expected to work. If there was another subdir under there (like `03453/js/libs/libs/foo`), you'd get the `addDir` for that subdir, but nothing for any files/paths deeper inside it.

**Comment by fyddaben** [comment]
ok.i know it .  Additionally,it helped me a lot ,thank u very much (★^O^★)
