### ISSUE TITLE
Missing some event on Travis CI

### ISSUE THREAD

**Issue by MoOx** [paulmillr/chokidar#292]
Here is a simple watcher server for metalsmith based on chokidar

Some event are not being properly fired on Travis like on my OS X setup

https://github.com/FWeinb/metalsmith-watch/tree/rebuild-sibling-mapping-CI

with this repo I am getting this locally

```console
$ npm test

> metalsmith-watch@1.0.0 prepublish /Users/MoOx/Sync/Development/metalsmith/watch
> babel src --out-dir dist

src/index.es -> dist/index.js
src/livereload.es -> dist/livereload.js

> metalsmith-watch@1.0.0 test /Users/MoOx/Sync/Development/metalsmith/watch
> npm run lint && npm run tape


> metalsmith-watch@1.0.0 lint /Users/MoOx/Sync/Development/metalsmith/watch
> eslint .


> metalsmith-watch@1.0.0 tape /Users/MoOx/Sync/Development/metalsmith/watch
> babel-tape-runner '__tests__/*.js'

TAP version 13
# metalsmith-server/watcher
# logs
## ✔︎ Watching src/**/*
yep
add /Users/MoOx/Sync/Development/metalsmith/watch/__tests__/tmp-logs/src/test src/test
## ✔︎ src/test added
test /Users/MoOx/Sync/Development/metalsmith/watch/__tests__/tmp-logs/src/test
update [ 'src/test' ] [ 'src/**/*' ] [ 'test' ] []
## - Updating 1 file...
ok 1 should logs things
# track create
[metalsmith-server] ✔︎ Watching src/**/*
yep
add /Users/MoOx/Sync/Development/metalsmith/watch/__tests__/tmp-create/src/test src/test
[metalsmith-server] ✔︎ src/test added
test /Users/MoOx/Sync/Development/metalsmith/watch/__tests__/tmp-create/src/test
update [ 'src/test' ] [ 'src/**/*' ] [ 'test' ] []
[metalsmith-server] - Updating 1 file...
ok 2 should rebuild on file creation
# track rename
[metalsmith-server] ✔︎ Watching src/**/*
yep
unlink /Users/MoOx/Sync/Development/metalsmith/watch/__tests__/tmp-rename/src/dummy src/dummy
[metalsmith-server] ✔︎ src/dummy removed
add /Users/MoOx/Sync/Development/metalsmith/watch/__tests__/tmp-rename/src/renamed src/renamed
[metalsmith-server] ✔︎ src/renamed added
renamed /Users/MoOx/Sync/Development/metalsmith/watch/__tests__/tmp-rename/src/renamed
update [ 'src/renamed' ] [ 'src/**/*' ] [ 'renamed' ] []
[metalsmith-server] - Updating 1 file...
ok 3 should keep track of renamed files
# rebuild sibling mapping
[metalsmith-server] ✔︎ Watching src/**/*
[metalsmith-server] ✔︎ Watching sibling/**/*
going to write /Users/MoOx/Sync/Development/metalsmith/watch/__tests__/tmp-sibling/sibling/test
yep
add /Users/MoOx/Sync/Development/metalsmith/watch/__tests__/tmp-sibling/sibling/test sibling/test
[metalsmith-server] ✔︎ sibling/test added
../sibling/test /Users/MoOx/Sync/Development/metalsmith/watch/__tests__/tmp-sibling/sibling/test
update [ 'sibling/test' ] [ 'src/**/*' ] [] [ 'sibling/**/*' ]
[metalsmith-server] - Updating 0 file...
ok 4 should rebuild if a mapped item get updated
# invalidate js cache
[metalsmith-server] ✔︎ Watching src/**/*
/Users/MoOx/Sync/Development/metalsmith/watch/__tests__/tmp-cache/src/thing.js ./tmp-cache/src/thing.js
ok 5 should get the exported value
add /Users/MoOx/Sync/Development/metalsmith/watch/__tests__/tmp-cache/src/thing.js src/thing.js
[metalsmith-server] ✔︎ src/thing.js added
thing.js /Users/MoOx/Sync/Development/metalsmith/watch/__tests__/tmp-cache/src/thing.js
[metalsmith-server] thing.js cache deleted
update [ 'src/thing.js' ] [ 'src/**/*' ] [ 'thing.js' ] []
[metalsmith-server] - Updating 1 file...
ok 6 should get the fresh exported value
# keep js cache
[metalsmith-server] ✔︎ Watching src/**/*
ok 7 should get the exported value
add /Users/MoOx/Sync/Development/metalsmith/watch/__tests__/tmp-keepcache/src/thing.js src/thing.js
[metalsmith-server] ✔︎ src/thing.js added
update [ 'src/thing.js' ] [ 'src/**/*' ] [ 'thing.js' ] []
[metalsmith-server] - Updating 1 file...
ok 8 should not update the cache

1..8
# tests 8
# pass  8

# ok
```

On travis the change on `.../__tests__/tmp-sibling/sibling/test` isn't detected so tests are waiting.
Since I am manually writing the file (the "yep" in the console show that the file is written) I don't really understand what is going on.

The particularity of this test is that I use an array of glob instead of a simple glob.
That said, I've tried like [a dozen of changes for this implementation](https://travis-ci.org/FWeinb/metalsmith-watch/builds) (multiple watchers with a glob each time vs a single watcher that gets an array of glob).

To (not) reproduce the failure of travis:

```console
$ git clone https://github.com/FWeinb/metalsmith-watch.git
$ cd metalsmith-watch
$ git checkout rebuild-sibling-mapping-CI
$ npm install
$ npm test
```
Tests should pass.

Can it be a linux related issue ?

**Comment by MoOx** [comment]
Sorry I just forget to tell you to `git checkout rebuild-sibling-mapping-CI` :)
Instructions updated.

**Comment by MoOx** [comment]
I get confirmation from a friend running linux that tests are not passing (waiting like linux).
Looks like a bug.

**Comment by es128** [comment]
Without having looked into this closely, it's probably a timing issue more so than a linux issue. These are integration tests involving the local file system, meaning there's a lot more variance between systems than in typical unit testing. The different watch modes used on different OSes are also a major factor. Modifying a file and listening for the change events within the same process is really tricky, and I still haven't been able to eliminate the sporadic false negatives on Travis for chokidar's test suite.

Not sure what you're doing to allow for time between writing the file and the event listener firing, but the issue is likely in that realm.

**Comment by MoOx** [comment]
I am not sure on what you are telling me. It doesn't look like a timing issue since I am listening to the even and never get it in my callback define using your API.

**Comment by es128** [comment]
Could be timing between tests, not just within the test that's failing. I'm saying this anecdotally as it has come up for myself and others before, I haven't actually investigated your code so far.

I can try to reproduce and debug later, but it's harder to figure out within your project as opposed to something that's been isolated to just chokidar.

Try working within a linux VM if you want to try to work on debugging it yourself in the meantime. I generally use VirtualBox and Ubuntu. If you can isolate a simpler example that exhibits the faulty behavior that would also be very helpful.

**Comment by MoOx** [comment]
So I tried with gaze to compare and after some debugging, I think both module are not happy with empty folder. If you start to watch folder/**/* when folder is empty and then you add a file, you do not receive the even. If folder contains one file and you add one more, it's working. chokidar don't get this issue on osx, but on linux/travis it has. gaze has this one osx.

**Comment by igoradamenko** [comment]
Just as note, @MoOx I get same bugs on Windows (Git Bash). If I start to watch folder when it's empty and then I create a new file, chokidar (and then gulp-watch too) does not see anything.

**Comment by caspervonb** [comment]
This is all about `fs.watch`, it doesn't pick up file changes within a watched directory. It does pick up renames, creates and deletes tho since those are changes to the directory.

However, `libinotify` should not behave this way as far as i remember `IM_MODIFY` picks up changes to files within the directory (https://github.com/libuv/libuv/blob/v1.x/src/unix/linux-inotify.c#L193-L200) 

https://github.com/caspervonb/amok/issues/83

**Comment by caspervonb** [comment]
Upstream related, issue on travis-ci https://github.com/travis-ci/travis-ci/issues/2342
