### ISSUE TITLE
files specified by pattern inside symlinked dir

### ISSUE THREAD

**Issue by ds82** [paulmillr/chokidar#293]
chokidar seems to not trigger events for files matched by a glob/pattern inside a symlinked dir.
File structure is:
```
./folder/symlinked/file.js
```
Working:
```js
  chokidar.watch('./folder/symlinked/file.js', {}).on('all', function(event, path) {
    console.log('trigger by chokidar', path);
  });
```
not working:
```js
  chokidar.watch('./folder/symlinked/*.js', {}).on('all', function(event, path) {
    console.log('trigger by chokidar', path);
  });
```

Am I missing something or this a bug?

What I really want to do is watch `./folder/**/*.js`. My `folder` contains dirs which are part symlinks and part regular dirs. That worked for regular dirs, but not for symlinks ..

**Comment by es128** [comment]
Appears to be a bug with the filtering on the initial readdirp file tree scan. In fsevents mode with a quick local test, the initial `add` events I would have expected did not happen, but after the `ready` event changing one of the files being watched through the symlink did trigger events (first an `add`, then `change`s)

**Comment by xlaywan** [comment]
+1 Same bug on windwos.

**Comment by RootMale** [comment]
++1 the same on linux and windows

**Comment by lookfirst** [comment]
+1 osx too. I just ran into this. =(

**Comment by clinuz** [comment]
+1 causing some headache (OS X, Windows, Linux), arguably unreliable to get the latent `add` event when it should actually be a `change`. Have to arbitrarily find the files and add them because of this which undermines chokidar's own features.

**Comment by sergeymakoveev** [comment]
+1

**Comment by stephenbunch** [comment]
+1

**Comment by alexpusch** [comment]
+1 
Ububtu 12.04

**Comment by alexpusch** [comment]
Trying to fix this. The eventual cause is that [filter passed to readdirp](https://github.com/paulmillr/chokidar/blob/master/index.js#L250)  matchs paths with the symlink names, while readdirp entry contains the actual physical name. I can't deiced weather this is a feature or a bug in readdirp... 

Any way I might have stumbled upon some other issues with symlink related code:
(1)[https://github.com/paulmillr/chokidar/blob/master/index.js#L279]
```js
 statMethod: this.options.followSymlinks ? 'stat' : 'lstat',
```
isn't it the other way around?

(2)[https://github.com/paulmillr/chokidar/blob/master/lib/nodefs-handler.js#L456] - it's weird if the symlink is the original path the user asked to watch since it watches the symlink parent.

what do you think?

**Comment by es128** [comment]
> isn't it the other way around?

No, it isn't. `stat` will return metadata about the target file when given a symlink. In other words it follows the link. `lstat` returns metadata about the symlink fd itself. 

Don't really understand your other question. 

You're right about the source of the problem, I mentioned the same thing in an earlier comment. The solution is probably to convert paths coming from readdirp to what they would be if the symlink hadn't been factored out and trying that result against the filters as well. If either passes then the path should be included.

**Comment by webdif** [comment]
Any progress or workaround on this matter?

**Comment by es128** [comment]
@webdif not yet, but I've been picking up my activity lately, so hopefully soon.

Workaround would be to watch the entire parent dir (see [glob-parent](https://github.com/es128/glob-parent)) without using a glob pattern, and then using the `ignored` option to filter as needed.

**Comment by webdif** [comment]
@es128 This workaround works fine with my situation. Thanks a lot!
