### ISSUE TITLE
FSE seems not working under io.js v1.6.3

### ISSUE THREAD

**Issue by finchen-ami** [paulmillr/chokidar#301]
I was having this message while using chokidar in my electron app which uses `io.js v1.6.3`
(The output of `process.version` is v1.6.3)

```
dyld: lazy symbol binding failed: Symbol not found: __ZN2v89Signature3NewEPNS_7IsolateENS_6HandleINS_16FunctionTemplateEEEiPS5_
  Referenced from: /node_modules/chokidar/node_modules/fsevents/build/Release/fse.node
  Expected in: dynamic lookup
```
I've removed whole node_modules and doing npm rebuild several times, same error.
The weird thing is if I rebuild under `node-0.12.2` it can run properly in the app

**Comment by es128** [comment]
Probably needs `npm rebuild`. If this is still a problem, report it to the fsevents repo.
