### ISSUE TITLE
Strange (intended?) behavior when directory containing file is added to a watched directory

### ISSUE THREAD

**Issue by billyjanitsch** [paulmillr/chokidar#302]
``` js
chokidar = require('chokidar');
watcher = chokidar
  .watch('foo')
  .on('addDir', function (path) {
    console.log('addDir', path);
  })
  .on('add', function (path) {
    console.log('add', path);
  });
```

Run this, then move folder `bar` containing `baz.txt` into `foo`. An `addDir` event fires for `foo/bar`, but not an `add` event for `foo/bar/baz.txt`. Using a glob (`watch('foo/**/*')`) has the same effect. I'm using OS X v10.10.3, io.js v2.2.1.

Is this intended behavior? If so, how can I reliably get an add event for `foo/bar/baz.txt` (assuming I don't know `bar` or `baz`)?

**Comment by egasimus** [comment]
As a workaround, why don't you list the contents of the directory and emit events manually?

Furthermore, I wonder what happens when you add a directory containing another directory (which might then contain a file).

**Comment by es128** [comment]
@billyjanitsch no, not intended. What is the output when you listen to the `raw` event?

**Comment by billyjanitsch** [comment]
```js
chokidar = require('chokidar');
watcher = chokidar
  .watch('foo')
  .on('addDir', function (path) {
    console.log('addDir', path);
  })
  .on('add', function (path) {
    console.log('add', path);
  })
  .on('raw', function () {
    console.log(arguments);
  });
```

Yields:
```
addDir foo
```
And when I copy the folder bar containing baz.txt into foo:
```
{ '0': 'moved',
  '1': '/Users/billy/projects/chokidar-test/foo/bar',
  '2': 
   { path: '/Users/billy/projects/chokidar-test/foo/bar',
     event: 'moved',
     type: 'directory',
     changes: { inode: false, finder: false, access: false, xattrs: false },
     flags: 133120 } }
addDir foo/bar
```

**Comment by es128** [comment]
Interesting, so the underlying fsevents interface is not emitting for the contained file(s). I would appreciate if you could test with the option `useFsEvents: false` just to validate that the issue is isolated there. 

Looks like the solution will be to trigger a readdir when a moved directory event is detected.

**Comment by billyjanitsch** [comment]
Looks like you're right. With `useFsEvents: false`:
```
addDir foo
{ '0': 'change',
  '1': '/Users/billy/projects/test/foo',
  '2': 
   { curr: 
      { dev: 16777220,
        mode: 16877,
        nlink: 3,
        uid: 501,
        gid: 20,
        rdev: 0,
        blksize: 4096,
        ino: 47833978,
        size: 102,
        blocks: 0,
        atime: Thu Jun 18 2015 12:28:33 GMT-0700 (PDT),
        mtime: Thu Jun 18 2015 12:28:41 GMT-0700 (PDT),
        ctime: Thu Jun 18 2015 12:28:41 GMT-0700 (PDT),
        birthtime: Thu Jun 18 2015 12:27:00 GMT-0700 (PDT) },
     prev: 
      { dev: 16777220,
        mode: 16877,
        nlink: 2,
        uid: 501,
        gid: 20,
        rdev: 0,
        blksize: 4096,
        ino: 47833978,
        size: 68,
        blocks: 0,
        atime: Thu Jun 18 2015 12:28:33 GMT-0700 (PDT),
        mtime: Thu Jun 18 2015 12:27:00 GMT-0700 (PDT),
        ctime: Thu Jun 18 2015 12:27:00 GMT-0700 (PDT),
        birthtime: Thu Jun 18 2015 12:27:00 GMT-0700 (PDT) } } }
addDir foo/bar
add foo/bar/baz.txt
```

Unfortunately I don't have time to work on a PR, but I appreciate your help debugging!

**Comment by es128** [comment]
Looks like the node core methods are also emitting only for the directory, but chokidar already does a readdir for most events on that side to correct for the lack of reliability underneath. 

Just need to do something similar on the fsevents side for this particular situation.

**Comment by ikrtolica** [comment]
We are also seeing a similar issue - chokidar used to send addDir events on startup for subdirectories with or without files - now if there are any files in subdirectories we do not get any addDir events at all.
