### ISSUE TITLE
listen to multiple events

### ISSUE THREAD

**Issue by Nirazul** [paulmillr/chokidar#305]
This is a feature request, not an issue (I haven't found any hint in the docu that this is possible):
It'd be great to have some sort of multi event listener to keep my files DRY (like jQuery):

**now**
```
        $$imageWatcher
            .on("add", optimizeDirty })
            .on("change", optimizeDirty })
            .on("unlink", optimizeClean });
```

**proposal**
```
        $$imageWatcher
            .on("add change", optimizeDirty })
            .on("unlink", optimizeClean });
```

**Comment by TrySound** [comment]
@Nirazul chokidar inherits event.EventEmitter which is node.js core constructor. So you suggestion is unlikely be executed.

**Comment by es128** [comment]
Thanks @TrySound I was just typing approximately the same thing. Perhaps there is (or someone could write) a wrapper library out there that could convert your `.on("add change", optimizeDirty })` preference into the proper event listeners.

Chokidar is the wrong place to do this kind of overloading on node's EventEmitter.

**Comment by Nirazul** [comment]
Ok, thanks for the explanation :)
