### ISSUE TITLE
Single backslash slash paths on windows

### ISSUE THREAD

**Issue by caspervonb** [paulmillr/chokidar#308]
Seems a bit counterintuitive, filenames on windows are reported with single backslashes, e.g `path\to\file.

Path handling in node generally deals with double backslashes, e.g path.normalize('foo/bar/car/) would return `foo\\bar\\bar`

Intended behaviour?

**Comment by es128** [comment]
When you see double-backslashes (such as in a node REPL) it generally just means you're looking at the escape character. The string itself still only contains a single backslash.

**Comment by es128** [comment]
```js
> path.win32.normalize('foo/bar/car/')
'foo\\bar\\car\\'
> console.log(path.win32.normalize('foo/bar/car/'))
foo\bar\car\
undefined
```

**Comment by caspervonb** [comment]
Ups you're right mismatch of util.inspect and util.debug logging, **facepalm**.
The actual issue I'm having is due to ~1 path truncating of the watched directory.

Thanks.
