### ISSUE TITLE
Chokidar crashes on windows

### ISSUE THREAD

**Issue by JBarna** [paulmillr/chokidar#312]
I first came across this issue when I was using Chokidar to watch files with NW.js. It works great on my MacBook pro, but crashes on my windows machine. But it's the weirdest thing, node just ends and there's absolutely no error reports or stack traces. I even installed node-debug to see what was going wrong, and still it wouldn't give me any answers. 

Here's the code: 
```javascript
var c = require('chokidar');
var path = require('path');
curdirpath = path.resolve('C:/Users/JBarna/');
var watch = c.watch(curdirpath);
```

The program crashes when c.watch(curdirpath) is executed.
I'm using IO.js v2.0.2.
I'm free to help debug. It's happened on two different window machines so far.

**Comment by paulmillr** [comment]
try

```
c.watch(curdirpath, {persistent: true})
```

**Comment by JBarna** [comment]
Unfortunately it's still not working. What I posted was just a simpler example but in my node-webkit app, the program shouldn't stop running even if I had set persistent to false. But the program stops completely without giving any details. Do you have any suggestions for debugging? It's strange.

**Comment by es128** [comment]
On windows chokidar is just using node's native `fs.watch`. Not likely there's anything within chokidar's control causing it.

Does this occur outside of `NW.js` (just running your script with `io.js` or `node`)? Sounds like it might need to be reported to that project.

**Comment by JBarna** [comment]
es128, good question.

This issues happens both with `NW.js` and outside of `NW.js` on both `io.js` and regular `node`. The script I posted initially ran on `io.js`, and if I had attached any listeners (for added files or directories) the program would exit before any would be called.

**Comment by es128** [comment]
I don't know. Can't reproduce, and seems like something more localized to what you're doing somehow. If chokidar suddenly stopped working or caused node processes to crash for all windows users (or even a significant segment of it), we'd be hearing about it from a lot of people. And we have heard from other users of NW.js on Windows along the way (having much more minor problems)

Perhaps there's a weirdly problematic fs entry where you're watching? What happens if you watch a much smaller directory in a completely different area of the system's file tree?

**Comment by JBarna** [comment]
When I get home I'll check it out on my windows machine with smaller directories. If we can't reproduce it after that then feel free to close the issue.

**Comment by es128** [comment]
Would be interested to know what happened @JBarna

**Comment by JBarna** [comment]
So it's still crashing on my machine. I tried hard to install node-segfault-handler and after installing Microsoft Visual Studio 2013, I found out that node-segfault-handler doesn't even work with windows :(.  So.... there's really no way for me to debug this issue sadly.

**Comment by snuggles08** [comment]
Happens for me too.

**Comment by JBarna** [comment]
Found an interesting article that might be relevant http://stackoverflow.com/a/8636001

**Comment by Spown** [comment]
Happens to me too. 1 in like 10 event catches crash the whole app. I get crash dumps, but I didn't manage to read them, since the ![documentation](https://github.com/nwjs/nw.js/wiki/Crash-dump) is kinda unclear and windows symbols file download link doesn't work...

**Comment by dmr** [comment]
Is this still an issue on windows? How did you resolve these/any other libraries to use cross platform?

**Comment by cmumad** [comment]
Me too.  I can watch single file or sub folder in running folder. But when I change to be full path, It does not work like your issue.
