### ISSUE TITLE
Remove fsevents?

### ISSUE THREAD

**Issue by caspervonb** [paulmillr/chokidar#313]
With 0.12 supporting fsevents directly, maybe removing fsevents from chokidar in the next major should be discussed?

**Comment by paulmillr** [comment]
Unfortunately this is simply not the case. Node's native file watcher has always been extremely awful. Nothing has changed since 0.10 as far as I know. Same amount of bugs, lack of low-level file watching APIs.

**Comment by es128** [comment]
@caspervonb while 0.12 utilizes the fsevents api, it does not provide the same access to it that chokidar needs to provide stable events. Feel free to disable/remove fsevents from a particular installation and take note of the problems that occur with wrong, missed, or duplicate events.

Plus, even if node had solved its problems, we would want to keep supporting 0.10 for a while to come.

Using fsevents brings some headaches, and believe me I'd love to drop it. But dropping it would lead to an even greater amount of issues.

What we may pursue for the next major is adding an interface for watchman. See https://github.com/facebook/react-native/issues/628
