### ISSUE TITLE
Watching file over network.

### ISSUE THREAD

**Issue by mustafamamun** [paulmillr/chokidar#315]
Is it possible to watch file creation over network. What I mean is if I have a server at "xxx.xxx.xxx.xxx"
can I watch file creation in "xxx.xxx.xxx.xxx:/home/admin"  directory? I am using to following configuration.

	var watcher =chokidar.watch('xxx.xxx.xxx.xxx:/home/admin', {
			           persistent: true,
			           ignoreInitial: true,
			           alwaysState: true,
                                   usePolling=true	
			  });

**Comment by paulmillr** [comment]
Not possible at this point. Feel free to create your own module that does this.

**Comment by es128** [comment]
Well, that depends actually. First of all, the syntax should have been `usePolling: true`. 

Secondly, if `xxx.xxx.xxx.xxx:/home/admin` is recognized by the OS as a valid dir path, then this might work with polling enabled. It may be necessary to map or mount the networked path, depending on your OS.

**Comment by mustafamamun** [comment]
Thanks for your reply. Ya that was a typo and the path is valid, I can upload file using that path. In the server side I have Red hat and in my local machine I am using CentOS. Now is there any way to get it working.

**Comment by es128** [comment]
If `usePolling: true` isn't working, then perhaps not. 

Try doing regular `fs` operations on files in these paths (like `fs.stat`). If that works, then polling ought to. If not, perhaps your path syntax needs to be tweaked or you need to mount the networked path differently.

**Comment by mustafamamun** [comment]
Thanks. With nfs mounting and UsePolling: true it is working.
