### ISSUE TITLE
Stuck after few file changes

### ISSUE THREAD

**Issue by Kureev** [paulmillr/chokidar#317]
Hi @paulmillr ! I faced an issue on my mac: I'm watching a file and after changes I send something thru websockets (doesn't matter, to be honest). The point is, that after few file changes in the file (mb around 20), it stucks for a few minutes and then works fine for the next 20 times. What it could be? I'm using default configuration.

https://github.com/Kureev/browserify-react-live/blob/master/server/index.js - That's the file where I listen for changes
https://github.com/Kureev/browserify-react-live/blob/master/server/makeWatcher.js - In this one I setup the watcher

I would appreciate any feedback about it, thanks!

**Comment by paulmillr** [comment]
You shouldn't probably be doing `readFileSync` — it may delay event loop for quite a bit. 

Try changing all calls to async ones — and report what happens then.

**Comment by Kureev** [comment]
Sure, thanks for so fast feedback! I'll keep you posted

**Comment by Kureev** [comment]
You know, it seems to be unrelated with this. It's more about fast re-saving. If I change file too often, it start freezing. Usually, this freeze lasts for ~2mins

**Comment by Kureev** [comment]
You know, maybe it's not related to chokidar and more related to watchify. I've just mentioned that I don't see my bundle to be updated...

**Comment by Kureev** [comment]
I'll investigate it deeper and let you know

**Comment by Kureev** [comment]
But as I see now it seems to be related anyway, 'cause watchify also use chokidar :smile:

**Comment by Kureev** [comment]
Ok, sorry for spamming there, but I found an issue why it happens. Seems to be a memory leak somewhere in EE. That hack works fine for me https://github.com/substack/watchify/blob/master/index.js#L110
