### ISSUE TITLE
Watch in a child process

### ISSUE THREAD

**Issue by es128** [paulmillr/chokidar#318]
Would mitigate #219 and probably help or solve stuff like #262 as well. Noticing several examples of others doing this kind of thing on their own, so perhaps it should be a built in option - even enabled by default maybe.

Opening this issue to hopefully solicit some discussion. Since I'm already leaning toward the idea that it would be a good idea to try this out and enable by default if the results are promising, I'm particularly interested to hear some objections articulated.

https://github.com/mcollina/chokidar-child
https://github.com/phated/charmeleon

cc/ @ohjames @phated @mcollina @floatdrop @zertosh @caspervonb

**Comment by paulmillr** [comment]
Let's try this.

**Comment by phated** [comment]
I think this is the easiest workaround to the huge bug in fsevents that is causing #219 - we need something to handle that segfault otherwise we wouldn't be able to use chokidar in gulp.  I got charmeleon quite far and would be willing to upstream anything that is desired.

**Comment by es128** [comment]
@phated just FYI about that, https://github.com/strongloop/fsevents/pull/74 also appears to be pretty effective at reducing the impact of #219. It'll hopefully be merged and published soon.

Nonetheless, I'm interested doing this to insulate chokidar from any other such effects and better deal with blocked event loops.

Would be absolutely happy to accept any contributions to this effort you can offer. In contrast to charmeleon we'll need to handle both the same-process and child-process options within the same codebase, but that shouldn't be very difficult.

**Comment by zertosh** [comment]
Sounds like a good idea

**Comment by ohjames** [comment]
Cool, should consider the fairly insignificant memory overhead and startup time for an extra node instance before deciding if it should be the default mode of operation. node seems to start up in around 0.3 seconds but given that `require` is synchronous you can start pushing 1 second or even more when you have a lot of dependencies (including transitive dependencies). I guess that wouldn't apply much to chokidar though but you might still want to be careful to isolate require calls depending on the mode of operation, you would only ever want the minimum number of requires to be called in each of the supervisor and watcher subprocesses.

**Comment by phated** [comment]
@ohjames the way that charmeleon works, you __only__ load chokidar and use message passing to kick off functions tied to watching, you don't actually load the end-user code

**Comment by ohjames** [comment]
@phated I figured that, it's the most sensible way for it to work. I just meant if chokidar was to support both watching in a subprocess or the main process then you'd just want to make sure the require calls are isolated to one or the other.

**Comment by es128** [comment]
Upon further reflection I think the better approach would be to introduce this behind a non-default option in a minor bump and see how it goes before considering making it the default in a future major version. 

Consumers (like gulp, for instance) would be free to enable it by default for all their users, and individual users of existing tools that allow for passing through chokidar options would have the ability to enable it for themselves.

**Comment by mcollina** [comment]
We have been using chokidar-child for quite some time, and it works great for us. It also fixes an issue on OS X on really big setups (watching 1000s of files). Startup time is not really measurable on my machine, because it loads only chokidar but I can see that as a problem on older laptops.

I'm in for doing a PR, or merging chokidar-child with charmeleon, or anything in between. I just think we should converge our efforts somewhere, and support that officially.

**Comment by phated** [comment]
In gulp, we don't like to change default options in our abstractions, as it makes people dig into multiple dependencies to find defaults.  Maybe this should stay userland (charmeleon) while we test out if it is a viable solution to use in gulp and then upstream it for a major bump.  Thoughts?

**Comment by es128** [comment]
Not sure I see how adding a whole new abstraction layer (charmeleon) makes the situation better or more understandable for users than setting `useChildProcess: true` by default in glob-watcher.

But considering that the segfault thing comes up rarely and is not *that* impactful for most use cases, perhaps even gulp could leave the defaults alone as they exist today - with an easy answer to give to anyone who runs into the segfault thing.

No matter where it happens, a child process based solution is going to be less battle tested than what we have, so I think it would be better to find out about problems from users who've opted in first than to just open the floodgates.

**Comment by mcollina** [comment]
I'm :+1: for having `useChildProcess: true`. As I see, `glob-watcher` uses gaze, is there a plan to move it to chokidar? In the latter case an approach similar to `chokidar-child` can work (copy-paste, or reuse that module), as it offers the same API of chokidar. I built it that way as an experiment, so I can swap in/out chokidar as needed.

**Comment by es128** [comment]
@mcollina FYI:
https://github.com/wearefractal/glob-watcher/pull/13
https://github.com/gulpjs/gulp/issues/651

I assume @phated's work on charmeleon is an indication that there is still interest in switching gulp from gaze to chokidar.
