### ISSUE TITLE
No error when trying to watch non-existent directory

### ISSUE THREAD

**Issue by CxRes** [paulmillr/chokidar#319]
When I try to watch a directory that does not exist, I do not get any error. Instead the ready event triggers.

on
Windows 7 x64
iojs v2.3.4
chokidar v1.0.5

**Comment by paulmillr** [comment]
Seems like right to me. Chokidar would not throw any errors — instead it will wait until the directory is created and then it would notify you about the creation.

**Comment by es128** [comment]
Yup, this is expected behavior. Use `fs.stat` or something like it if you need to know whether a path exists.

**Comment by CxRes** [comment]
Oh Ok!!

But wouldn't it be useful behaviour if it did - since it seems query the disk anyway (rather than querying the disk an extra time using `fs.stat`)? I am just trying to understand the motivation behind the design choice...

**Comment by es128** [comment]
The motivation is the ability to watch non-existent paths, anticipating their creation. Not sure how to expose via the API in a useful way when it is determined a watched path does not exist. Emitting an `error` would not be appropriate. Do you have any suggestions?

**Comment by es128** [comment]
With `ignoreInitial: false`, the absence of any `add` or `addDir` events before `ready` effectively tells you.

**Comment by CxRes** [comment]
seems reasonable...

As far as testing absence of `add`, its possible! But personally I would not prefer it - unnecessarily set a state variable in `add` and `addDir` which I then have to test in `ready`.

But it would be nice to set a boolean say, `exists`, might be in the `ready` event callback, just for convenience (though it would be doing the exact same thing inside). 

Let me know what you think...

**Comment by es128** [comment]
Maybe something returned with `ready`, but a boolean probably won't cut it since multiple paths and glob patterns can be passed to `watch`

**Comment by CxRes** [comment]
Sounds good...

**Comment by CxRes** [comment]
I was only worried about the check for if any match is made at all or not. Glob checking may return a list of matches or maybe only just check if the base directory has been matched and accessed?

**Comment by es128** [comment]
Something simple we could try would be passing `Object.keys[this._watched]` with the `ready` event. If you get an empty array, you know nothing was found.

**Comment by CxRes** [comment]
I was thinking along the same lines. But isn't this an overkill when compared to `Object.keys[this._watched].length`. I am wondering if there would be any other use cases for having the full list would required?
Also, I wonder if a full list deserves a separate function like `watcher.watched()` since then I would argue that we should make this information available anytime?

**Comment by es128** [comment]
The same processing and memory consumption is required to do `Object.keys(this._watched).length`, so no, I don't see how it's overkill to just pass the array pointer. Someone may have a use for the full list.

`watcher.watched()` may be a good idea too. I would favor naming it something more like `watcher.getWatchedList()` though.

**Comment by es128** [comment]
Although, if we do the latter, then is there any point to passing it with the `ready` event anymore? You'd be able to fulfill your use case just by calling the function.

```js
watcher.on('ready', function() {
  if (!watcher.getWatchedList().length) oopsThePathDoesntExist();
});

**Comment by CxRes** [comment]
I meant overkill in terms of Principle of Least Privilege. 

If you want to implement `watcher.watched()`/`watcher.getWatchedList()` (I like brevity but verbose names have their own merit), then I would think changing the `ready` event would become redundant. But imo its the better solution.

**Comment by CxRes** [comment]
You said the same think while my browser didn't refresh. Solution 2 it should be!

**Comment by es128** [comment]
@paulmillr any opinion on the method name?

**Comment by paulmillr** [comment]
watcher.getWatchedList sounds right. `watched` should be object / list if it exists

**Comment by es128** [comment]
It's currently tracked internally as the `this._watched` object

**Comment by CxRes** [comment]
Just another thought: It would be nice if the `watcher.getWatchedList()` subtracts the cwd `Object.keys(this._watched)`.
Alternatively `watcher.getWatchedList()` could carry a boolean parameter for enabling this.

**Comment by CxRes** [comment]
While testing, I found that `watcher._watched` seems to watch parent of the specified directory. Is this correct and is there any reason for that?

**Comment by es128** [comment]
Yes, that's how it can see whether the non-existent path gets added. Already a bit trickier than anticipated.

So the result probably needs to be run through the same filters that are used to determine whether to expose events that are detected.

**Comment by CxRes** [comment]
Sorry, I don't seem to understand why watching a parent is necessary to detect if the path is non existent. It seems to me that this means you are only able to watch contents of any directory and you need to watch the parent just to see if it contains the specified directory. Is that it? I thought  `fs.watch` watched the specified for?

**Comment by CxRes** [comment]
I meant specified folder (not for). Sorry

**Comment by es128** [comment]
No, this isn't about detecting that the path doesn't exist. 

Chokidar deliberately watches the parent in order to detect if the path gets created later.

https://github.com/paulmillr/chokidar/blob/master/test.js#L356-L392

**Comment by CxRes** [comment]
That can't be right. Here is a small test I performed:

I set chokidar too watch `C:\foo\bar` where `foo` exists and `foo\bar` does not! I then log `watcher._watched` in the `all` event all callback with the event. I also log in the `ready` callback. 

Initially my output is `[]` at `ready`,

When I add `bar` the outputs are `['C:\\','C:\\foo']`,

And only when I perform some other operation in foo does the output become  `['C:\\','C:\\foo','C:\\foo\\bar']`.

If Chokidar deliberately watches the parent in order to detect if the path gets created later, then `C:\\foo` should have been watched at the time `ready` event is triggered. What am I missing here?

**Comment by es128** [comment]
> Initially my output is [] at ready

This is a timing issue; `ready` event comes before the fallback to the parent is executed. Try adding a timeout around where you log `watcher._watched`. The relevant code that sets a watcher on the parent when a supplied path is not found is at https://github.com/paulmillr/chokidar/blob/master/index.js#L429-L433

I'm not sure why `C:\\` ends up being watched in the scenario you've described, although I doubt it's actually watching all of `C:\\` recursively (you'd notice the impact on your system resources).

**Comment by CxRes** [comment]
I did the timeout thing and that checks out.

The `C:\\`, however, does not. So I did it with one level deeper. Apparantly, it watches parent and grandparent directories. This is certainly odd...

**Comment by es128** [comment]
Yes it does seem odd. I'll have to try to reproduce and trace what's happening on a windows VM when I get a chance. Haven't reproduced it on OS X with `fsevents` disabled, which should be following the same flow of logic, but of course there are still going to be lots of platform differences.

We're substantially digressing from the original topic though. 

Seems that you could do this today to achieve a satisfactory resolution:
```js
watcher.on('ready', function() {
  if (!Object.keys(watcher._watched).length) oopsThePathDoesntExist();
});
```

And that we ought to add a `getWatchedList` method that will provide something similar, but also filter out artifacts of the internal implementation details.

**Comment by es128** [comment]
> This is a timing issue; `ready` event comes before the fallback to the parent is executed.

Btw, I may try to change this behavior too, so anyone implementing the above sample code using the internal `_watched` property should not be surprised if it stops working in a future version.

**Comment by CxRes** [comment]
This new thing was a consequence of the testing something along the lines above sample code, so I though I should point it out - yes, we are digressing but I think its relevant. Anyway, I will wait until the next version bump before I start implementing the above code. Thanks for looking into it!

**Comment by es128** [comment]
Well if you want it now, use the semver tilde operator for ~1.0.5 and that should be safe. Then with a minor bump (to 1.1.0 assuming I get to this before something else that necessitates a minor bump), you'll be able to switch it to `getWatchedList()`.

Yes the grandparent watching thing is good to know, and I appreciate that you've reported your observations.

**Comment by CxRes** [comment]
Really appreciate all your effort! Thanks a lot!!!!!

**Comment by rfossella** [comment]
Hi.  I'm unsure of whether or not chokidar can watch folders that don't exist yet?  My scenario on Windows:

watching folder *C:\reports\2014-09-03* -- a folder that doesn't exist yet.  If I manually create the folder there are no events fired.  Is *C:\reports* being watched? Should I receive an event when folder *2015-09-03* gets created?  Will it now be watched?

I am using entire event handling - i.e.
````
var watcher = chokidar.watch(['C:\reports\2014-09-03'], 
	                {ignored: /[\/\\]\./, persistent: true});

	watcher
	.on('add', function(path, stats) 
	    { 
			dirChange({type: 'File',  action: 'create', path: path , stats:stats });
	    })
	.on('addDir', function(path, stats) 
	    { 
			dirChange({type: 'Directory',  action: 'create', path: path , stats:stats });
	    })
	.on('change', function(path, stats) 
	    { 
			dirChange({type: 'File',  action: 'change', path: path , stats:stats });
	    })
	.on('unlink', function(path, stats) 
	    { 
			dirChange({type: 'File',  action: 'delete', path: path , stats:stats });
	    })
	.on('unlinkDir', function(path, stats) 
	    { 
			dirChange({type: 'Directory',  action: 'delete', path: path , stats:stats });
	    })
	.on('error', function(error) 
	    { 
	     console.log('chokidar watch error occurred ' + error);
	    })
	.on('ready', function() 
	    { 
			console.log('Initial scan complete. Ready for changes.');
	    })
````

**Comment by es128** [comment]
@rfossella the answer to all your questions should be yes. If you have evidence to the contrary please describe it in a new issue.

You could take a look at the ['watch non-existent paths'](https://github.com/paulmillr/chokidar/blob/master/test.js#L356-L392) section of the tests.
