### ISSUE TITLE
Chokidar exits when the watched folder is removed

### ISSUE THREAD

**Issue by CxRes** [paulmillr/chokidar#324]
Given our discussion in #319 , if Chokidar is happy about placing a watch on a non-existent directory at startup, symmetry should demand that it should continue watching even if the directory is removed after issuing an `unlink` event (of course, assuming `persistent: true`). Right now, the watcher stops when the path is deleted at least on Windows. 

I think the circumstances are identical in that a directory does not exist in both cases, why should they be treated differently?

**Comment by es128** [comment]
If it's behaving this way it is a bug, not by design.

**Comment by quetzalcoatl** [comment]
Unfortunately, yes it does. I'm on Windows too, and I battled with some meteor/sanjo:jasmine/karma issues, and I just traced one thing down to chokidar.

Karma uses chokidar to watch its files. When Meteor's builder renames/removes a directory with those files, and then creates/renames a new directory on the same place, Karma/Chokidar stops watching this directory for file changes.

**Comment by leoselig** [comment]
We are having this issue as well
Right now, we don't even have a satisfying workaround for it.

**Comment by kafoso** [comment]
This problem persists in release [1.5.2](https://github.com/paulmillr/chokidar/releases/tag/1.5.2) on Windows 7 Service Pack 1.

`unlinkDir` event never fires. Not when when listening for `all` events (`.on('all', ...)`). Chokidar barfs this error out:

    events.js:141                                            
          throw er; // Unhandled 'error' event               
          ^                                                  
                                                             
    Error: watch null EPERM                                  
        at exports._errnoException (util.js:874:11)          
        at FSEvent.FSWatcher._handle.onchange (fs.js:1217:21)

**Comment by lkraav** [comment]
I'm also wondering whether `.on( 'all' )` should or not catch `error` events?

**Comment by es128** [comment]
@lkraav from the readme:

> Additionally `all` is available which gets emitted with the underlying event name and path for every event other than `ready`, `raw`, and `error`.

**Comment by lkraav** [comment]
@es128 tyvm, I also happened to find this info at that time, but forgot to update the comment.

**Comment by lmoyrd** [comment]
when i ran script in debug mode in webstrom, it could catch error event.
but in git bash or cmd.exe (npm run dev) ,it just existed throw the error Error watching file for changes: EPERM
Any ideas?

**Comment by quetzalcoatl** [comment]
let me try out if meterjs/karma/velocity still break on windows due to exactly this issue :]

..but then, I don't even have them on this new machine, so that may take a while..
well, maybe 'unpopular' it really is..
