### ISSUE TITLE
EBUSY

### ISSUE THREAD

**Issue by TrySound** [paulmillr/chokidar#325]
Hi, guys! I think copying to `public` starts when copying to `app` not finished.
Is there any decision of this problem?

```
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: EBUSY, open 'D:\***\app\image\logo.png'
    at Error (native)
```

```js
var watch = require('gulp-watch');

gulp.task('image', function () {
	return gulp.src('app/image/**/*.{jpg,png,svg}')
		.pipe(gulp.dest('public/img'));
});

gulp.task('dev', function () {
	watch(conf.app + '/image/**/*.{jpg,png,svg}', function () {
		gulp.start('image');
	});
});
```

**Comment by es128** [comment]
Why is this chokidar's problem? 

Looks like `gulp.dest` is not doing the `graceful-fs` queuing thing for issues like this (not sure whether it ought to, but that appears to be where the error is coming from). 

You could do a simple debounce yourself if you want it to wait.

But also, why copy the entire directory whenever one file changes? Surely this can be done more efficiently.

**Comment by TrySound** [comment]
@es128 Thanks! Added `gulp-changed` and for now it works stable.
