### ISSUE TITLE
If the directory on which a watch is setup is created later, its contents are not added

### ISSUE THREAD

**Issue by CxRes** [paulmillr/chokidar#327]
Suppose I set up a watch on a directory that does not exist.

Now if I create that directory with child objects in it, such as by renaming another directory to the said directory, these child objects are not added. That is only one `add` event is emitted for the directory and thats it.

I expected that the behaviour would be to add everything in that directory because a watch on a directory, unlike a file, means a watching its contents.

**Comment by es128** [comment]
Observed on windows, I assume?

**Comment by CxRes** [comment]
Yes, windows 7 x64, iojs 3.0.0

**Comment by CxRes** [comment]
Are these problems Windows specific?

**Comment by es128** [comment]
I don't know for sure, but problems like this are often OS-specific and I recalled that you mentioned Windows in another issue.

**Comment by RCMax** [comment]
I concur! And yes, on Windows.

**Comment by eliseumds** [comment]
The same happening here, Node v0.12.7 on Mac OS 10.10.5.

**Comment by paulmillr** [comment]
Let us know if that still happens with the latest chokidar.

**Comment by CxRes** [comment]
Works... thanks!!!!
