### ISSUE TITLE
Feature Request: watch, unwatch, ready event for every new add

### ISSUE THREAD

**Issue by CxRes** [paulmillr/chokidar#330]
I guess I am starting to get a little annoying here by now...

It would be nice to get a watch & unwatch event every time a new path is added to/removed from the watch and ready when the first reads that meet the criterion is completed. My use case is where I trigger a the watch and some external condition becomes a true, a path/glob (eg: I am adding a new extension to the watch) gets read in some other object that has access to the watcher. I know I can read everything and keep filtering changes out, but this adds a certain convenience... especially when I am passing a watcher around.

**Comment by paulmillr** [comment]
Why not implement it by yourself in your app?

**Comment by CxRes** [comment]
Sure, I can but I would like to see it part of the library as it is a useful thing in general.

Also I am not sure about managing the timing of `ready` for the new path adds because I do not know how Chokidar decides the cut-off for it. How would I certainly know if the event is a result of that watch and not a new add on the file system?

**Comment by es128** [comment]
There are bugs right now with `ready` and `.add()` that need to be addressed.

As for `watch`/`unwatch` events.... maybe. If you know how you want it to work and can implement it in userland, I'd suggest you start there, and then we could look at it and consider for inclusion in the library

**Comment by CxRes** [comment]
Just checking if the bugs in `ready` and `.add()` have been resolved yet?

**Comment by es128** [comment]
Nope, not yet

**Comment by CxRes** [comment]
Any ETA?

**Comment by es128** [comment]
¯\_(ツ)_/¯

Whenever I get to focus on it for a while and fix it. I don't have quite as much open source time as I did a year ago.

See also #304

**Comment by CxRes** [comment]
I understand!!! 

Thanks for the reply...

**Comment by paulmillr** [comment]
I don't like the idea of adding those events to our core library — we have way too many events already.

The bugs would still need to be fixed though.

**Comment by es128** [comment]
#288 and #338 track the related bug
