### ISSUE TITLE
Strange behaviour with renames

### ISSUE THREAD

**Issue by qraynaud** [paulmillr/chokidar#331]
I found what I believe is a bug, but I might be doing something wrong here.

I set up a watcher the following way:

```js
var watcher = slides.watcher = chokidar.watch('**/*.md', {cwd: '/some/dir'});
```

Then I add an `all` event on it:
```js
watcher.on('all', function() {
  console.log('here');
});
```

Then I rename a folder in the watched directory from `name` to `name2`. I get 2 calls to my event. There is 2 files in my directory so this seems fine. Then I notice I renamed the wrong folder. So I rename it again, this time from `name2` to `name`.

And surprise: no event is fired at all this time.

Any ideas?

**Comment by es128** [comment]
This was likely fixed by #380. If you can still reproduce this issue with chokidar 1.3.0, please discuss in #404. Closing.
