### ISSUE TITLE
Installing chokidar hangs inside a docker container

### ISSUE THREAD

**Issue by AntouanK** [paulmillr/chokidar#333]
Have a CoreOS VM ( using Vagrant ) and I'm running docker containers for my services inside it.
My host machine is OSX.

I tried with `iojs` and `mhart/alpine-iojs` containers, both 2.5 and 3.0 versions.
On every case, installing babel always hange on chokidar.

Any idea on how to fix that?

that's the last part of the log I see with `npm i -d`
```
==> eic-01:  /home/docker/node_modules/babel/node_modules/chokidar/node_modules/anymatch/node_modules/micromatch/node_modules/braces
==> eic-01:
==> eic-01: npm info linkStuff braces@1.8.0
==> eic-01:
==> eic-01: npm info install
==> eic-01:  braces@1.8.0
==> eic-01:
==> eic-01: npm info postinstall braces@1.8.0
==> eic-01:
==> eic-01: npm info build
==> eic-01:  /home/docker/node_modules/babel/node_modules/chokidar/node_modules/anymatch/node_modules/micromatch
==> eic-01:
==> eic-01: npm info linkStuff
==> eic-01:  micromatch@2.2.0
==> eic-01:
==> eic-01: npm info install micromatch@2.2.0
==> eic-01:
==> eic-01: npm info
==> eic-01: postinstall micromatch@2.2.0
==> eic-01:
==> eic-01: npm info
==> eic-01:  build /home/docker/node_modules/babel/node_modules/chokidar/node_modules/anymatch
==> eic-01:
==> eic-01: npm info linkStuff anymatch@1.3.0
==> eic-01:
==> eic-01: npm info install anymatch@1.3.0
==> eic-01:
==> eic-01: npm
==> eic-01: info
==> eic-01: postinstall anymatch@1.3.0
==> eic-01:
==> eic-01: npm
==> eic-01: info build /home/docker/node_modules/babel/node_modules/chokidar
==> eic-01:
==> eic-01:
==> eic-01: npm info
==> eic-01:
==> eic-01: linkStuff chokidar@1.0.5
==> eic-01:
==> eic-01: npm info install chokidar@1.0.5
==> eic-01:
==> eic-01: npm info postinstall chokidar@1.0.5
==> eic-01:
```

**Comment by paulmillr** [comment]
The log doesn't really help us 😭 could you post more info about your env?

**Comment by AntouanK** [comment]
@paulmillr 
Well, I have the same problem, no way to see what's stopping it.

Like I said.
A CoreOS VM, started with Vagrant in an OSX machine.
In that VM, I make a container and I do `npm i` and one of the packages to install is `babel`. That's where `chokidar` tries to be installed and it hangs.

If it matters, the repo directory is mounted into the CoreOS VM from my OSX host via NFS ( that's standard way of mounting directories on Vagrant VMs I think, I always used that for the last 2 years ).

What more info do you need?

**Comment by es128** [comment]
Instead of `npm i -d` for the whole project, try just `npm i chokidar -d` and let's see if anything else is revealed.

**Comment by AntouanK** [comment]
@es128 That is a good idea.

So, running `npm i chokidar` in the container, everything is fine.
Running `npm i babel` though, makes it hang. So probably chokidar is not the issue.

![chokidar](https://cloud.githubusercontent.com/assets/4569111/9182081/85d21b66-3fa0-11e5-82fd-5ab9e85befa1.gif)

**Comment by es128** [comment]
Yeah seems like it finishes installing chokidar and then hangs on whatever is next. Closing the issue for now, but if you come up with any other evidence that points toward chokidar, let us know.

**Comment by AntouanK** [comment]
Thanks @es128
