### ISSUE TITLE
can't ignore first item via ignore function

### ISSUE THREAD

**Issue by adamcohen** [paulmillr/chokidar#335]
I'm noticing some strange behaviour when passing a function for the `ignored` parameter if the first call returns true.

```javascript
var chokidar = require('chokidar')
var count = 0

function ignored (file) {
  console.log('file', file)

  if (count++ === 0) { return true }
  return false
}

chokidar.watch('.', {
  ignored: function (file) { return ignored(file) }
}).on('all', function (event, path) {
  console.log(event, path)
})
```

Expected output: a list of files in the current directory as each one is passed to the `ignored` function
Actual output: `file .` then exit. No other files are examined

If I change the `count` conditional to something else, like `count === 2`, it causes the third item to be ignored as expected, and continues passing every other file in the current directory to the `ignored` function.

Unless I'm missing something here, it seems as though it's not possible to continue execution if you want to ignore the first item passed to the ignore function.

**Comment by paulmillr** [comment]
You're watching `.`

The directory is passed as a first item to watcher — and to `ignored` function. If you ignore it then no subdirectories would be served.

That sounds reasonable to me.

**Comment by adamcohen** [comment]
Thanks for getting back to me.  I was trying to chase down an issue in `forever-monitor` which started occurring after you switched the watch module to chokidir.  [This particular block of code](https://github.com/foreverjs/forever-monitor/blob/12e35fcd17f0e7beace9a62dfd949300fe4fb371/lib/forever-monitor/plugins/watch.js#L28-L30) in `forever-monitor` was preventing anything from being watched: 

```javascript
function ignored (file) {
  if (this.watchIgnoreDotFiles && path.basename(file)[0] === '.') {
    return false;
  }
}
```

The problem is that if you watch `.`, which is what most people probably use by default, then everything else is ignored by the above conditional.  It's definitely reasonable behaviour that if you ignore a directory that all subdirs are ignored. Now that I know this is the case, I'll submit a PR to `forever-monitor` to fix this issue.  Thanks again for your help

**Comment by paulmillr** [comment]
Prob just add the `&& path !== '.'` and that's it :+1:
