### ISSUE TITLE
watch causes add event to fire

### ISSUE THREAD

**Issue by jmls** [paulmillr/chokidar#340]
I have the following code

```javascript
chokidar.watch('/somefolder', {ignored: /[\/\\]\./})
            .on('all', function(event, path) {
                console.log(event, path);
            });
```

but when my app starts, it fires off an "add" event for every file in somefolder

I thought that the "add" event was for newly created files

Am I missing something obvious ?

**Comment by es128** [comment]
you want the `ignoreInitial: true` option

**Comment by jmls** [comment]
Indeed, I needed that ;) Thanks. Took me by surprise though - I would have thought it would make more sense to have that as a default option. However, fixed!

**Comment by es128** [comment]
I agree that there's probably more users at this point who would prefer it to default as `true`, but you know, history. I may consider it with the next major version bump.
