### ISSUE TITLE
too much node_modules

### ISSUE THREAD

**Issue by suboy** [paulmillr/chokidar#342]
could you reduce the node_modeles ?

**Comment by TrySound** [comment]
@suboy Did you see browserify? :))

**Comment by suboy** [comment]
chokidar@1.0.5
├─┬ anymatch@1.3.0
│ └─┬ micromatch@2.2.0
│   ├─┬ arr-diff@1.1.0
│   │ ├── arr-flatten@1.0.1
│   │ └── array-slice@0.2.3
│   ├── array-unique@0.2.1
│   ├─┬ braces@1.8.1
│   │ ├─┬ expand-range@1.8.1
│   │ │ └─┬ fill-range@2.2.2
│   │ │   ├── is-number@1.1.2
│   │ │   ├── isobject@1.0.2
│   │ │   ├── randomatic@1.1.0
│   │ │   └── repeat-string@1.5.2
│   │ ├── lazy-cache@0.2.3
│   │ ├── preserve@0.2.0
│   │ └── repeat-element@1.1.2
│   ├── expand-brackets@0.1.4
│   ├─┬ extglob@0.3.1
│   │ ├─┬ ansi-green@0.1.1
│   │ │ └── ansi-wrap@0.1.0
│   │ ├── is-extglob@1.0.0
│   │ └── success-symbol@0.1.0
│   ├── filename-regex@2.0.0
│   ├── kind-of@1.1.0
│   ├─┬ object.omit@1.1.0
│   │ ├─┬ for-own@0.1.3
│   │ │ └── for-in@0.1.4
│   │ └── isobject@1.0.2
│   ├─┬ parse-glob@3.0.2
│   │ ├── glob-base@0.2.0
│   │ ├── is-dotfile@1.0.1
│   │ └── is-extglob@1.0.0
│   └─┬ regex-cache@0.4.2
│     ├── is-equal-shallow@0.1.3
│     └── is-primitive@2.0.0
├── arrify@1.0.0
├── async-each@0.1.6
├── glob-parent@1.2.0
├─┬ is-binary-path@1.0.1
│ └── binary-extensions@1.3.1
├── is-glob@1.1.3
├── path-is-absolute@1.0.0
└─┬ readdirp@1.4.0
  ├── graceful-fs@4.1.2
  ├─┬ minimatch@0.2.14
  │ ├── lru-cache@2.6.5
  │ └── sigmund@1.0.1
  └─┬ readable-stream@1.0.33
    ├── core-util-is@1.0.1
    ├── inherits@2.0.1
    ├── isarray@0.0.1
    └── string_decoder@0.10.31

node_modules path is too long. So that, I can not delect it in Windows

**Comment by TrySound** [comment]
@suboy It's not too much. And windows processes long paths fine.

**Comment by es128** [comment]
@suboy use npm v3, it should eliminate whatever problem you're experiencing.

`npm i -g npm@3`
