### ISSUE TITLE
Linux: no change event

### ISSUE THREAD

**Issue by peteruithoven** [paulmillr/chokidar#343]
It doesn't seem to pick up change events on my Linux installation. It does pick up `add` and `unlink`.

I've tested this with the following example code:
``` javascript
var chokidar = require('chokidar');

chokidar.watch('.').on('all', function(event, path) {
  console.log(event, path);
});
```
node: v0.12.7
Linux: ElementaryOS 64bit
Partition: ext4
I'm using a live usb stick with more persistent memory through the [use of a separate partition](https://usbubuntu.wordpress.com/make-it-persistent/).

Is there anything I can check?

**Comment by es128** [comment]
log out the `raw` event, see if the OS is reporting anything

you could also try the `usePolling: true` option

**Comment by peteruithoven** [comment]
I don't receive `raw` events on content changes (I do on file add, remove, rename etc). 

Adding usePolling helps, then it does detect `change` events. What does that tell us? 

I'm looking into this to get Browsersync file watching working, I'll check if they support enabling this usePolling option.

**Comment by es128** [comment]
`usePolling` (which watches using stat polling) is often needed in situations with remotely mounted drives because the regular OS-level watching API doesn't work. Apparently this is the case with your setup too.

BrowserSync does let you pass the `usePolling` option to chokidar: http://www.browsersync.io/docs/options/#option-watchOptions

**Comment by peteruithoven** [comment]
You're right, thanks for the help!

**Comment by es128** [comment]
This issue does not impact Linux in general, just atypically mounted file systems.

Chokidar works fine out of the box on Linux for most situations.
