### ISSUE TITLE
Folder with parenthesis in the name can't be watched

### ISSUE THREAD

**Issue by javiergarmon** [paulmillr/chokidar#344]
I've a folder called `"/Users/Javier/Backup (2015)"`. I can't start a watcher to this folder because inside `FSWatcher._getWatchHelpers`, the library `globparent` transform that path to `"/Users/Javier"`.

Is this a bug? How can I watch folders with special chars like pathensis, brackets...?

Thank you!

**Comment by es128** [comment]
Duplicate of #300.

Yes it's a bug, but easiest resolution for now is to just rename your dir.
