### ISSUE TITLE
watchify (chokidar), in polling mode, keeps other watched tasks from running

### ISSUE THREAD

**Issue by noahgrant** [paulmillr/chokidar#345]
on watchify 3.4, chokidar 1.0.5 (and, for that matter many other versions of watchify and chokidar, as well as on both node 0.12.7 and 0.10.33), i have these two gulp tasks:

``` js
gulp.task('browserify', function() {
  // browserify bundle ....
  // ...
      bundler = watchify(bundler, {
        ignoreWatch: [
          '**/node_modules/**',
          '**/js/vendor/**'
        ],
        poll: 750
      });
      bundler.on('update', rebundle);
// ...
});
```

and some linters that watch the same files (using gulp.watch/gaze 0.5.x):

``` js
  gulp.task('lint-watcher', function() {
    gulp.watch(sources.scripts, function(file) {
      return gulp.src(file.path)
        .pipe(plumber())
        .pipe(jshint())
        .pipe(jscs())
        .pipe(jshint.reporter(stylish));
    });
  });
```

if i only run `gulp lint-watcher`, everything works as expected. however, if i run `gulp browserify lint-watcher`, then the linting watcher callback is executed `the first time` a file is saved, reporting any jshint or jscs errors. every other time that file is saved, however, the lint-watcher watching callback is not invoked.  it's as though chokidar, in polling mode, swallows up the other tasks. again, if i only run `gulp lint-watcher`, then the callback is invoked every time i save a file.

note that i'd love to not use the polling option for watchify, but we are plagued by the `segmentation fault: 11` issue, even in the latest chokidar (with the right fsevents module).

any insight on this would be much appreciated!!

**Comment by es128** [comment]
What happens if you run the two tasks as separate processes? `gulp lint-watcher` in one terminal and `grunt browserify` in the other?

**Comment by noahgrant** [comment]
@es128 then everything works as expected.  should i spawn a child process for the lint-watcher task or does that give you a clue as to something else that might be up?

**Comment by es128** [comment]
Chokidar does try to share `fs.watchFile` instances within the same process, so it seems something is going wrong with that in this case. If you can put together a repo with a reproducible case it would help tremendously with trying to debug this.

But yeah, in the meantime separate processes could be an interim solution for you. Even `gulp lint-watcher & gulp browserify` may be a simple way to do it.

**Comment by noahgrant** [comment]
ah okay, thanks!  i've put the `lint-watcher` task in a separate process and, minus the nice color scheme, it works fine.  i'll try to put together a reproducible repo for you soon.

**Comment by noahgrant** [comment]
@es128 [here's a test repo](https://github.com/noahgrant/share-watchfile). you should be able to run `npm i` and then `gulp` to launch the watchify task as well as `gulp.watch` for the linters on the javscript files. try saving `myJsFile.js`—there are enough jshint/jscs errors that plenty will be output on the first save. but subsequent saves will be swallowed by chokidar in the watchify task.

if you just run `gulp watch`, launching the watcher only, then subsequent saves on `myJsFile.js` will spew the linting errors each time, as expected.

**Comment by noahgrant** [comment]
any thoughts about this @es128 ? have you had a chance to check out the test repo?

**Comment by es128** [comment]
I've reproduced the issue - thanks for that repo - but haven't yet worked on debugging it. Will keep you posted.

**Comment by jacobnijgh** [comment]
Having the same issue, any updates on this?

**Comment by mbrevda** [comment]
+1! At least I know it's not me!

**Comment by mbrevda** [comment]
Interestingly, while change events are not emitted, a raw event for change is.

**Comment by ngryman** [comment]
Hi,

I think I have the same issue with my plugin: https://github.com/ngryman/gulp-bro.
I use `watchify` under the hood (not in polling mode). When `watchify` is running, no `change` event is fired from `chokidar`.

I noticed that if I [touch](https://github.com/isaacs/node-touch) the output file just after it has been written, `chokibar` is detecting the change. This is my current quick fix.

`watchify` also uses `chokibar`, couldn't be some kind of conflict?

Here is a pseudo-code highlighting the issue with the latest version of every dependency:
```javascript
const bundler = watchify(browserify('app.js'))
bundler.on('update', bundle)

function bundle() {
  bundler.bundle()
    .pipe(source('app.js')
    .pipe(vfs.dest('dist'))
    .on('finish', () => {
      // without this, chokibar does not trigger any `change` event
      touch.sync('dist/app.js')
  })
}
bundle()

chokidar.watch('dist/app.js').on('change', () => {
  // never called, `add` is called the first time
  console.log('change')
})
```

**Comment by ngryman** [comment]
EDIT: The above solution does not always work :disappointed:. It seems that there is some kind of concurrency problem somewhere.

**Comment by ngryman** [comment]
EDIT 2: FYI, this ugly piece of code resolved the issue:
```javascript
setTimeout(() => touch.sync(file.path), 100)
```

*Sorry for the flood*
