### ISSUE TITLE
No events fired when watching non-existent directory

### ISSUE THREAD

**Issue by rfossella** [paulmillr/chokidar#346]
chokidar is not firing any events when watching folders that don't exist yet.
My scenario on Windows:

I begin my node server and watcher and request to watch folder **C:\reports\2015-09-04** , a folder that doesn't exist yet.
In my nodejs console I correctly see a message that reads:

> Error: ENOENT, no such file or directory 'C:\reports\2015-09-04'

I then manually create the folder **2015-09-04** (i.e. C:\reports\2015-09-04) and no events are fired. I also add file to newly created folder and again, no events.  

It's my understanding that parent folder (_C:\reports_) is being watched and that I should receive an event when folder 2015-09-04 gets created, but nothing.   

I don't have to use polling do I?

_Note: my other folder in this example is properly monitored._

I am using entire event handling - i.e.

```
var watcher = chokidar.watch(['C:\reports\2015-09-03', 'C:\reports\2015-09-04'], 
                    {ignored: /[\/\\]\./, persistent: true});

    watcher
    .on('add', function(path, stats) 
        { 
            dirChange({type: 'File',  action: 'create', path: path , stats:stats });
        })
    .on('addDir', function(path, stats) 
        { 
            dirChange({type: 'Directory',  action: 'create', path: path , stats:stats });
        })
    .on('change', function(path, stats) 
        { 
            dirChange({type: 'File',  action: 'change', path: path , stats:stats });
        })
    .on('unlink', function(path, stats) 
        { 
            dirChange({type: 'File',  action: 'delete', path: path , stats:stats });
        })
    .on('unlinkDir', function(path, stats) 
        { 
            dirChange({type: 'Directory',  action: 'delete', path: path , stats:stats });
        })
    .on('error', function(error) 
        { 
         console.log('chokidar watch error occurred ' + error);
        })
    .on('ready', function() 
        { 
            console.log('Initial scan complete. Ready for changes.');
        })
```

Any ideas?

Thank you!

Rob

**Comment by es128** [comment]
Just a couple quick ideas that may uncover temporary workarounds and help with debugging - try adding a trailing slash to the paths (`C:\reports\2015-09-03\`), and try making them into glob patterns (`C:\reports\2015-09-03\**\*` or `C:\reports\2015-09-03*`)

I doubt polling would help, but you could give it a shot just to see if it has any impact.

**Comment by rfossella** [comment]
Hmm. I must be missing something related to glob patterns?
Using ````C:\reports\2015-09-15\**\* ````  I now get

````Error: ENOENT, no such file or directory 'C:\reports\2015-09-15\**'```` 

Also, there was no effect with *adding trailing backslash* nor with *using polling*.

**Comment by rfossella** [comment]
So using the following causes *file or directory not found errors*
```` chokidar.watch(['C:\reports\2015-09-15\**\*'] ````

I'm concerned that I will either have to watch the parent folder manually (which can potentially have 100's of folders and 1000's of files) or use some sort of timer to periodically check for the non-exisitent folder.

Anyone have any other ideas they can share?

Thanks.
Rob

**Comment by es128** [comment]
Until the underlying bug gets figured out, you probably need to watch the parent directory to get what you want. But you can still limit how much of the tree under the parent gets watched by using the `depth` and/or `ignore` options.

Perhaps one watcher on the parent with `depth: 1` and a listener on the `addDir` event which triggers the addition of the new directory onto your main watcher instance.

I'm sorry, I know this is far less than ideal :scream:

**Comment by rfossella** [comment]
Thank you for the feedback.  I will attempt this and report back my experience and performance.

**Comment by rfossella** [comment]
Hi.  I was wondering if anything was ever done with watching a non-existent folder?

I tried the offered solution above but this does not work in a desirable manner.  To explain:
1. I'm watching files within **logs/mm-dd-yy** folders - e.g. _a.log, b.log, c.log_
2. Files are created daily within this **logs** folders but may span from one night into the next day - e.g. I initially watch 01-09-16 (this may include _a.log, b.log_).  I also want to watch the (non-existent, yet) 01-10-16 folder which will eventually include _c.log_.  So all three files need to be tracked
3. As I described in an earlier post, 01-10-16 genuinely generates an error **[Error: ENOENT, no such file or directory '\logs\2016-01-10']**
4. However, when the 01-10-16 folder gets created no event is generated.

Here's the main issue.  If I use the technique offered above - i.e. watch the **parent** folder - i.e. **logs** with depth:1 it is looking inside **ALL** the previously created folders (on init) within the parent and incorrectly reporting found files - e.g. if there was a folder 01-05-16 with c.log it reports THIS as found.

I only need the NEWLY created older watched - not everything within the parent hierarchy.  Man, I hope my use case makes sense!  Hope someone can assist.  Thanks

**Comment by es128** [comment]
You definitely will want a filtered watcher on the parent dir which will get you what you want without deeply watching the entire hierarchy. You could use a `ignored` function to rule out everything you are not interested in, or a glob pattern that only matches what you care about and uses glob magic on the non-existent directory name as well such as `\logs\[0]1-05-16\*`

**Comment by rfossella** [comment]
To be sure I understand - I would need TWO separate watchers?  So, right now I watch the existing folder (and several other **folders**) like this:
```
var watcher = chokidar.watch(folders, 
	                {
	                	ignored: /[\/\\]\./, 
	                	persistent: true,
	                	usePolling: true,
	                	interval: 2000,
	                	binaryInterval: 2500
	                });
```

Can I add a (the) parent folder to this watcher or should I create another one?  Thanks so much for your prompt reply!

**Comment by es128** [comment]
You should be able to add the glob pattern I suggested to your `folders` array.

**Comment by rfossella** [comment]
Hi.  I have a follow-up question regarding watching a parent folder.
I have a folder named **myStuff**.  Within it I have two folders called **newStuff** and **archived**
/myStuff/newStuff
/myStuff/archived 

I need to know if the **newStuff** folder gets removed (or renamed, same thing) so I watch parent folder **myStuff**.  I DO NOT want to watch **archived**.  I tried to use the following glob pattern with no success:
``\myStuff\[0]newStuff\*``  It doesn't watch **archived** (which is fine) but it is not picking up the deletion of folder **newStuff**

I also tried adding ignore option:
``ignored: [/[\/\\]\./, 'C:\\myStuff\\archived\\'] ``

I appears it ignores files/folder inside **archived** but still tracks a __deletion__ of **archived**.

I am still trying to find the "correct" approach for watching parent but only interested in one (or select group of) folders.

Thanks.

**Comment by es128** [comment]
The glob pattern you tried does not even match the `newStuff` directory itself, just its contents. Try `myStuff/[n]ewStuff` or `['myStuff/[n]ewStuff', 'myStuff/newStuff/*']`

**Comment by rfossella** [comment]
Adding only `` myStuff/newStuff/* `` **does now** watch that folder for a delete but ignores a rename of the folder (on Windows). I would have thought a rename would trigger *delete* event. It appears i **still** need to watch the parent folder ``myStuff`` to track anything that occurs to that folder but brings me back to the situation where watching the parent is still watching other folders that I don't care about.  Keep in mind that I there may be many folders that I don't care about in that parent folder.

**Comment by rfossella** [comment]
It seems the issue with the rename not firing the delete event was because of polling.  As soon as I set ``usePolling: true`` the delete event event fired.  FYI: I originally only used polling for watching files over a network; no polling while watching local files. It seems I always need polling to handle rename.  Not sure if this is desired behavior.

Thanks for your previous assistance!

**Comment by hedefalk** [comment]
+1

**Comment by alex-page** [comment]
I am experiencing this issue on Windows 10. 

I am using [onchange](https://github.com/Qard/onchange) which uses chokidar to watch folders.

When one of the folders in the `matches` array is non existent chokidar refuses to watch all folders, even if they exist.

```
var watcher = chokidar.watch(matches, {
  cwd: cwd,
  ignored: opts.exclude || [],
  usePolling: opts.poll === true || typeof opts.poll === 'number',
  interval: typeof opts.poll === 'number' ? opts.poll : undefined
})
```

**Comment by Tamilselvanmaplebots** [comment]
yea, this code is ok for watching, while running this code its printing the existing files also from the folder. i want to print what i am newly adding.
