### ISSUE TITLE
File is ignored after removing and quick adding back

### ISSUE THREAD

**Issue by vojtajina** [paulmillr/chokidar#35]
Ubuntu 12.04.1 LTS
Chokidar 0.5.1
Node 0.8.14

``` javascript
var w = chokidar.watch('watched');
['add', 'change', 'unlink'].forEach(function(event) {
  w.on(event, function(p) {
    console.log('chokidar:', event, p);
  });
});
```

In command line (this basically simulates VIM's backup behavior):

``` shell
cd watched
mv some.js some.js.swp && sleep .1 && mv some.js.swp some.js
```

Output:

```
chokidar: change watched/some.js
chokidar: unlink watched/some.js
chokidar: add watched/some.js.swp
chokidar: change watched/some.js.swp
```

**Chokidar does not catch when `some.js` is moved back. And any subsequent changes on `some.js` are ignored as well.**

If I increase the sleep between `mv` commands, it works fine. Node's `fs.watchFile` does not watch a file, once it's removed (eg. adding the file back after removing is ignored). Chokidar catches new files by watching the directory. So I guess there is some sort of race condition between the "directory watcher" and "file" watcher - the "directory" watcher needs to be fired after the "file remove" watcher, so that it registers a new watcher for the file - I guess this doesn't happen.

Based on https://github.com/vojtajina/testacular/issues/199

**Comment by jugheadjones10** [comment]
Hi @es128 , I was using Tailwindcss, which uses Chokidar, and I came across this same problem. Is there a possibility that this issue isn’t resolved yet? Thanks.

**Comment by paulmillr** [comment]
@jugheadjones10 there is no point in asking this question a person from 2015.

**Comment by jugheadjones10** [comment]
> @jugheadjones10 there is no point in asking this question a person from 2015.

Then can I direct it to you instead? Thanks! If needed I might be interested in creating a PR for this.

**Comment by cesutherland** [comment]
2015 was pretty dope tho

**Comment by paulmillr** [comment]
@cesutherland in some way, yes
