### ISSUE TITLE
Node 4 Segmentation Fault

### ISSUE THREAD

**Issue by fusepilot** [paulmillr/chokidar#350]
I know 4.0 just came out today. But,

0.12 works
````
> nvm use 0.12
> npm install -g chokidar
> chokidar -version

chokidar-cli: 1.0.0
chokidar: 1.0.5
````

4.0 seg faults
````
> nvm use 4
> npm install -g chokidar
> chokidar -version

[1]    13322 segmentation fault  chokidar -version
````

This is on OSX 10.10.4.

**Comment by es128** [comment]
I guess you were actually globally installing `chokidar-cli`? Anyway, getting a segfault from just running `chokidar -version` seems odd, and I haven't reproduced it (running the same OSX version).

Any chance you can provide a better description of what you were actually doing/running when the segfault was encountered?

**Comment by fusepilot** [comment]
Yes, sorry, chokidar-cli. This was in an attempt to isolate where a seg fault was coming from when I tried to use node 4.0 with my application. I narrowed it down to requiring chokidar. It's a fairly big app, so I was trying to condense the problem down and noticed that it seg faulted all the way down to the cli. So I just posted that.

But trying to use either chokidar or chokidar-cli with node 4.0 results with a seg fault for me.

````
> nvm --version
0.26.1
````
````
> nvm list
    iojs-v3.3.0
        v0.12.7
->       v4.0.0
         system
````
````
> which node
~/.nvm/versions/node/v4.0.0/bin/node
````
````
> node
>> process.version
'v4.0.0'
>> require('chokidar')
[2]    16272 segmentation fault  node

````

Also, I forgot to mention that this also happens with iojs-v3.3.0 as well.

**Comment by clintonwoo** [comment]
I was having a problem too but fixed it by updating fsevents to this branch https://github.com/gdi2290/fsevents/commit/88287b3ae33600ee2d8234ddb6aea722ed7cfbac and building this version (it's 1 commit ahead of fsevents master) .

**Comment by es128** [comment]
@fusepilot it sounds like you somehow are not actually running a fresh version of chokidar/fsevents after switching node versions. Try using `npm rebuild` or fully deleting the relevant `node_modules` and reinstalling. 

@clintonwoo that particular commit is just a change to Travis CI config, so it couldn't have had any impact. You were probably benefitting from just ensuring that the dependency was rebuilt.

**Comment by fusepilot** [comment]
Thanks @es128. ````npm rebuild```` fixed it. fsevents was the only thing that needed rebuilding.
