### ISSUE TITLE
using function for `ignored` exits immediately with no output

### ISSUE THREAD

**Issue by mbroadst** [paulmillr/chokidar#354]
When running the following code snippet:
```
var chokidar = require('chokidar');

var watcher = chokidar.watch('/some/local/path', {
  ignored: function(path) { return path.indexOf('.pid') === -1; },
  persistent: true
});

watcher
  .on('add', function(path) { console.log("added: " + path); })
  .on('unlink', function(path) { console.log("removed: " + path); })
```

the script immediately ends with no warning, no errors, and an exit code of 0. It works perfectly fine if I switch ignored to the opposite case (`return path.indexOf('.pid') !== -1;`)

**Comment by mbroadst** [comment]
It occurred to me that it was ignoring the base path, so I modified the ignored function as follows:

```
var watcher = chokidar.watch('/some/local/path', {
  ignored: function(path, stats) {
    if (stats && stats.isDirectory()) return false;
    return path.indexOf('.pid') === -1;
  },
  persistent: true
});
```

which now shows a proper initial `added` message, however it exits immediately afterward without warning. Is there something I'm missing here?

**Comment by es128** [comment]
What's in the path you're watching? Whatever is going on is not obvious to me, but kind of sounds like there's no watcher being set, even in the case where you're getting `add` events somehow.

**Comment by mbroadst** [comment]
@es128 it's just a local path, that exists and has files in it. If I change the logic as follows, this works fine:

```
var chokidar = require('chokidar');

function isPidFile(path) { return path.indexOf('.pid') !== -1; }
var watcher = chokidar.watch('/some/local/path', {
  persistent: true
});

watcher
  .on('add', function(path) { if (isPidFile(path)) console.log("added: " + path); })
  .on('unlink', function(path) { if (isPidFile(path)) console.log("removed: " + path); })
```

**Comment by es128** [comment]
Just to recap the discussion from gitter, @mbroadst can solve his problem by switching to a glob pattern that filters for .pid files, but the concern with function-based `ignored` definitions is not resolved and still needs to be investigated.

**Comment by mbroadst** [comment]
@es128 additionally that solution does not work on linux with node 0.10.25. The only thing that seems to work consistently across all systems involved is the last `isPidFile` approach

**Comment by es128** [comment]
There's potential that `/var/run` is a special case
