### ISSUE TITLE
Publish chokidar for fsevents to be compatible with Node 4?

### ISSUE THREAD

**Issue by Unitech** [paulmillr/chokidar#356]
https://github.com/Unitech/PM2/issues/1596
https://github.com/paulmillr/chokidar/commit/a58160678302e4f0d1263177229e18789296a599

Thanks!

**Comment by es128** [comment]
I will be publishing today, but it's not necessary for Node 4 compatibility. Users just need to `npm update` if they do not yet have fsevents@0.3.8

**Comment by Unitech** [comment]
awesome, thanks sir
