### ISSUE TITLE
Chokidar watcher fails if watched path contains $ character.

### ISSUE THREAD

**Issue by KostiantynKopytov** [paulmillr/chokidar#357]
I've used to keep my projects under $ folder. Just started to use chokidar, and when I pass a full path it fails to find any changes. To reproduce create /$/test/test.js:

```javascript
var chokidar = require('chokidar');

chokidar.watch('/$/test/*').on('all', function(event, path) {
  console.log('absolute', event, path);
});

chokidar.watch('*').on('all', function(event, path) {
  console.log('relative', event, path);
});
```

Does the following output:
```text
relative add test.js
```

**Comment by paulmillr** [comment]
Brunch thinks you're passing a glob pattern here. Not sure what is the best way of handling this.

**Comment by KostiantynKopytov** [comment]
I guess glob pattern does not have any specific meaning for $. Regular expressions does. If regular expressions for glob are enabled, probably path should be pre-processed in some way to encode $, or other chars if needed.

**Comment by es128** [comment]
If you were to watch `/$/test` instead of `/$/test/*` it would likely work (at least based on what I've observed in a quick local test. When combined with globs, I'm suspecting a bug in micromatch allowing the `$` to pass in unescaped to the underlying regular expression, which of course would destroy it.

cc/ @jonschlinkert

**Comment by jonschlinkert** [comment]
This should now be fixed. Try reinstalling and let us know if you still have any issues.

**Comment by es128** [comment]
Thanks so much @jonschlinkert! Closing the issue.

**Comment by jonschlinkert** [comment]
no problem! just I wish I had seen the issue sooner
