### ISSUE TITLE
'Add' event immediately executed while file is transferring

### ISSUE THREAD

**Issue by fbm-static** [paulmillr/chokidar#358]
It seems the "add" event immediately fires while a file is being transferred to the directory being watched. Is there a way to figure out if it's finished transferring?

**Comment by paulmillr** [comment]
I don't think there's OS-level event for that. You can try using polling (`setInterval`) to check whether it's done or not.

**Comment by es128** [comment]
That's what the #352 PR is about. I'm finishing up some housekeeping to get chokidar 1.1.0 released, then we can evaluate that feature for inclusion. 

If you could try out the code from the PR and let us know how it works out for you, that'd be great.

**Comment by fbm-static** [comment]
The way I went for this is to use `setInterval` and stat the added file checking it's filesize since I know what the added file's filesize is.

**Comment by alexpusch** [comment]
May I ask how come you know the added file's size?
