### ISSUE TITLE
Why is fsevents mentioned twice in package.json?

### ISSUE THREAD

**Issue by binarykitchen** [paulmillr/chokidar#363]
This as a dependency and as an optional dependency both?

Furthermore I am unable to use `npm shrinkwrap` on my Ubuntu machine anymore because fsevents is targeted for OS machines only. It is breaking our build in our organization :(

Looking at your issues, I think fsevents has caused lots of trouble. Maybe time to drop it?

If not, how else can I solve the shrinkwrap issue then?

**Comment by paulmillr** [comment]
`fsevents` is an optional dependency: https://github.com/paulmillr/chokidar/blob/master/package.json#L41

If you can't do `shrinkwrap`, that seems like a npm issue, not brunches. NPM should always respect optionalDependencies. Please report it here: https://github.com/npm/npm/issues

**Comment by es128** [comment]
https://github.com/npm/npm/issues/9865
