### ISSUE TITLE
Chokidar seems to fire a 'change' event before the file is changed

### ISSUE THREAD

**Issue by fresheneesz** [paulmillr/chokidar#365]
I just recently updated a few things, including chokidar from 0.9 to 1.2, and a script I had stopped working properly. I was listening for changes on a file that I was making with the following shell command:

`sudo sh -c 'echo -n someText > theFile'`

On the change event (or its possible its an add event, not actually 100% sure), I do a `fs.readFileSync(theFile)` to get its contents, but the contents return empty. But when I check in the real file system, the correct text is there. Doing this works:

`echo -n someText > theFile`

And since I don't need sudo for that at the moment (and hopefully won't again), i worked around it. But I thought I should mention it here. Is this something that's expected to be possible?

**Comment by fresheneesz** [comment]
Oh and this was on centos 6

**Comment by es128** [comment]
Sounds like a race condition - you caught and acted on the `change` event so quickly that the new contents of the file weren't done being written. It's actually a sign of chokidar working extremely efficiently. The OS reports that the file has been touched as soon as it's touched, not after it's done being written to. There's a new `awaitWriteFinish` option that ought to solve for this, but it *really* slows things down and probably wouldn't be satisfactory.

Probably the only reasonable solution is a bit of error correction code that retries the file read if it comes back empty. Or your own small artificial delay just to make it much less likely for this to happen.

**Comment by fresheneesz** [comment]
In my case, that's exactly what I need and would be very satisfactory. In fact, in most of my use cases, I want to ensure that write has finished (i use chokidar to copy files).

Thanks!

**Comment by es128** [comment]
If you're not working with large files, you can probably change the settings to make it much more responsive than the defaults... But it'll take a bit of trial and error to determine how fast is too fast.

**Comment by fresheneesz** [comment]
In this particular case, its just a file that is overwritten with one character. So I'm surprised chokidar can even fire the change event before the OS finishes writing it.

**Comment by es128** [comment]
> So I'm surprised chokidar can even fire the change event before the OS finishes writing it

me too
