### ISSUE TITLE
wrong nested dir glob watching

### ISSUE THREAD

**Issue by mikehaas763** [paulmillr/chokidar#367]
I'm reporting this as being found through the use of gulp-watch and karma. I often provide glob paths such as `!node_modules/**/*`. This will match the file at `node_modules/a/a` but will not match the file at `node_modules/b`

Is `**/*` the correct glob to use when I want to match all files and all files in all subdirectories?

If I'm using the correct glob then this may be a bug with chokidar or one of its deps. I noticed that for at least gulp-watch using `!node_modules/**` works for all files and all files in all subdirectories.

**Comment by es128** [comment]
Is my assumption correct that with the `!` that you're deliberately trying to negate the matching of everything under `node_modules`?

Please provide more detail about what your glob patterns look like and what you're trying to match or not match, as this is not quite descriptive enough to understand what problem you're having.

Just FYI, some quick local tests using micromatch, which is chokidar's glob matching lib:

```
> mm.isMatch('node_modules/file', 'node_modules/**/*')
true
> mm.isMatch('node_modules/dir/file', 'node_modules/**/*')
true
> mm.isMatch('node_modules/file', '!node_modules/**/*')
false
> mm.isMatch('node_modules/dir/file', '!node_modules/**/*')
false
```

**Comment by es128** [comment]
Closing due to lack of response.
