### ISSUE TITLE
Examples for .watch function

### ISSUE THREAD

**Issue by FernandoBasso** [paulmillr/chokidar#369]
I am trying to do something like this:

    chokidar.watch('**/*.js, **/*.css' { ...

It works if I only have `'**/*.js'`, for instance, but not with both globs (in which case I keep minifying already minified files, since it seems the ignore doesn't work then). Is that even possible? I could not figure out from reading the README if it would be the way I tried, or

    .watch('**/*.js', '**/.css' { ...

or something else.

This is the relevant piece of code I am trying:

    var watcher = chokidar.watch('**/*.js, **/*.css', {
      ignored: /[\/\\]\.|\.min\./,
      persistent: true
    });

**Comment by TrySound** [comment]
@FernandoBasso Did you read documentation? Only first argument is paths/dirs/globs or array of them.

**Comment by es128** [comment]
You need to put your multiple patterns in an array

```js
chokidar.watch(['**/*.js', '**/*.css'], { options })
```

But this can be done more efficiently with a single glob pattern anyway: `**/*.{js,css}`

**Comment by FernandoBasso** [comment]
@TrySound I was reading this part "chokidar.watch(paths, options) — takes one or more paths (which may be paths to files, dirs to be watched recursively, or glob patterns) and options". Now I see more on that down below the docs. Thanks.

@es128 All right. Thanks.

**Comment by TrySound** [comment]
@FernandoBasso (...paths) and (paths) are not equal expressions.

**Comment by FernandoBasso** [comment]
@TrySound Although I am not being able to completely understand what you are saying, where in the docs it says that `.watch` takes "an array"?

**Comment by TrySound** [comment]
@FernandoBasso Yeah, maybe need to add `array` to docs. I meant [spread operator from es6](http://ariya.ofilabs.com/2013/03/es6-and-spread-operator.html)

**Comment by FernandoBasso** [comment]
@TrySound All right. Thank you and @es128 again for the help and insights.

**Comment by es128** [comment]
https://github.com/paulmillr/chokidar/commit/625fe8e2660257e2f3d352d5cab312d0cdac95ea

Hopefully this helps to clarify. If you have any suggestions about better ways to present it let me know.

**Comment by FernandoBasso** [comment]
@es128 That is just perfect. :) Way to go. Thank you all.
