### ISSUE TITLE
Tracking file change similar to tail

### ISSUE THREAD

**Issue by rfossella** [paulmillr/chokidar#371]
When chokidar picks up a change event for a file, is the actual change recorded and accessible ?

Use case: I want to watch file and , in essence, tail the file and track each new line to the file

I know there are other tools that do log tailing , just wondering if chokidar posts the event with the line change

Thank you 
Robert

**Comment by paulmillr** [comment]
yeah we do

**Comment by es128** [comment]
If what you mean is a diff between the contents of the file before and after the change, then no, chokidar does not do that for you. In fact, `change` events are emitted if you just `touch` a file without changing contents. Understanding what changed and what to do about it is up to you.

**Comment by rfossella** [comment]
Thanks for your response. Yes, that's what I meant.  I am tracking 100's of files using chokidar but there are 4 files that I need to track (tail) the actual file change. As you fairly suggested, I will add separate log tailing processes for those files.  Just thought it prudent to ask the question so nothing duplicated. Thanks, again!
