### ISSUE TITLE
Merge config from .chokidar file

### ISSUE THREAD

**Issue by capaj** [paulmillr/chokidar#375]
Seems to me a lot of projects are using chokidar under the hood. Setting up chokidar properly can be problematic and some tweaking is needed on many systems out there. That's why I thought- why not let chokidar have it's own config file, which it would merge with options supplied from cli or api method call.
I think that options from chokidar file should have higher priority than those supplied with the cli/api call.
What do you think? If you leave this config merging work for the packages which use chokidar under the hood it will be much more work for all the projects and each of them will implement it differently. Don't we have enough fragmentation already?

My usecase would be for my library users with mounted drives in VM https://github.com/capaj/chokidar-socket-emitter/pull/3#issuecomment-150226727

BTW shouldn't VM mounted drive work properly with fs.watch?

**Comment by paulmillr** [comment]
Sorry, not going to add this feature. Chokidar needs to stay super basic, bloating the library won't be a good long-term decision.

**Comment by paulmillr** [comment]
It's a good idea probably to implement a separate npm package wrapper that would do this functionality though.

**Comment by capaj** [comment]
@paulmillr not a bad idea. Then I can try convince anyone using chokidar to switch to chokidar-configurable. I may do that.

**Comment by es128** [comment]
> BTW shouldn't VM mounted drive work properly with fs.watch?

It doesn't. Maybe we'll be able to resolve #242 eventually though

As for the wrappered package to provide config file functionality, I don't really like the idea and I doubt it would see wide adoption. It's no more work for library authors to expose the config than to switch. For this idea to have significant impact, I think we'd have to do it here. I'm not fully decided on whether I think it's something we ought to provide though.

For sure, my preference would be to go further in solving for more scenarios using the default settings such as #242, but at the same time there will always likely be some need for some end-users to make direct changes to the config.
