### ISSUE TITLE
Feature Request: provide regex as matcher 

### ISSUE THREAD

**Issue by shakyShane** [paulmillr/chokidar#377]
Hi guys!

Browsersync maintainer here saying a huge thanks for Chokidar, I'm extremely grateful for the work you all put into it.

I'm working on a rewrite at the moment and was surprised to learn that you cannot provide a regex as a pattern?

*desired* (from anymatch docs)
```js
var matchers = [
    'path/to/file.js',
    'path/anyjs/**/*.js',
    /foo.js$/ // this would be great
];
```

Is this something that cannot be done? or is there a specific reason you require every string to be a pattern?

Thanks again.

**Comment by es128** [comment]
The problem with it is that we'd need to be able to derive a common parent from which to apply the regex against, or else we're potentially walking through way too much of the file system looking for matches. 

I suppose the base could be assumed as `cwd` (either the inherent one or the option), but it would be easy for users to misunderstand the behavior and start trying to match against parent or absolute paths. I'd be nervous about unleashing a bunch of confusion and new edge cases.

Beyond just "more flexibility for users", can you elaborate on the use case you're envisioning a bit more? What is the situation that cannot be addressed within the confines of a glob pattern?

**Comment by es128** [comment]
By the way - I appreciate the expression of gratitude. I've lately been thinking a lot about how I could reallocate my time and energy to become more active again and tackle the outstanding issues (while keeping the rest of my life in balance too). Every bit of motivation helps.

**Comment by shakyShane** [comment]
@es128 - I honestly don't have a better reason than `more flexibility for users`. So this is a fine answer.

Re: motivation, I hear ya - I always find just stepping away for a month is enough :)
