### ISSUE TITLE
Issue with watching a deleted, then recreated directory

### ISSUE THREAD

**Issue by es128** [paulmillr/chokidar#379]
Opening an issue to describe the scenario presented in #378 

> If we add a watch on directory A, mkdir A/B, rm -r A/B, mkdir A/B,
mkdir A/B/C, no event comes from fs.watch on creation of A/B/C

> Encountered on Ubuntu 14.04.3 LTS, Linux 3.16.0-50-generic x86_64

**Comment by es128** [comment]
Fixed by #380

**Comment by rottmann** [comment]
Problem exists again in chokidar 3.2.2.
Linux Mint 19.2, Kernel 4.15.0-65-generic
