### ISSUE TITLE
Only outputs about ~1/3 of events on rapid file change

### ISSUE THREAD

**Issue by natew** [paulmillr/chokidar#383]
I have a test saving a file with changes about every 5-10ms.

I `tail -f` the file, and also chokidar watch, and the chokidar process outputs *maybe* 1/3 of the events tail -f is getting.

The strange thing is I can do a process.spawn tail, and pipe stdout in node, and its also slow!

What's happening here? If I just do a setInterval and read the file, it's incredibly fast. Why are the streams going so slow?

**Comment by es128** [comment]
`tail -f` is not based on file change events, it keeps a file descriptor open

chokidar is not meant for this sort of use case, in fact it deliberately suppresses events it considers to be duplicates

The `process.spawn` thing you mentioned is out of scope here, but I'd guess you bumped into one of the gotchas with managing child processes in node and the various ways inter-process message passing can be blocking operations.

There are several `tail`-type modules on npm in case you haven't tried that route.

**Comment by natew** [comment]
This seems like exactly the type of thing chokidar should handle, it's a file watcher.

The file is changing rapidly, chokidar should notify of changes as fast as they happen. That seems to be it's only purpose.

I tried a number of different watchers and all of them seem to be slow. Even `fs.readFileStream` was slow.

**Comment by es128** [comment]
Thank you for correcting my perception of chokidar's purpose and how it operates. Looks like you're going to have to find someone with more expertise to help you with your problem.
