### ISSUE TITLE
npm dependencies version conflict (fstream)? 

### ISSUE THREAD

**Issue by sixinli** [paulmillr/chokidar#386]
not sure if this is a good place to report the issue... 

when running `npm install` in this project there's this warning:
npm WARN unmet dependency /Downloads/chokidar-master/node_modules/fsevents/node_modules/fstream-ignore requires fstream@'~0.1.17' but will load
npm WARN unmet dependency /Downloads/chokidar-master/node_modules/fsevents/node_modules/fstream,
npm WARN unmet dependency which is version 1.0.8

and when running `npm shrinkwrap --dev` there's this error:
npm WARN unmet dependency /Downloads/chokidar-master/node_modules/fsevents/node_modules/fstream-ignore requires fstream@'~0.1.17' but will load
npm WARN unmet dependency /Downloads/chokidar-master/node_modules/fsevents/node_modules/fstream,
npm WARN unmet dependency which is version 1.0.8
npm ERR! Darwin 13.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "shrinkwrap" "--dev"
npm ERR! node v0.12.7
npm ERR! npm  v2.14.8

npm ERR! Problems were encountered
npm ERR! Please correct and try again.
npm ERR! invalid: fstream@1.0.8 /Downloads/chokidar-master/node_modules/fsevents/node_modules/fstream
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Downloads/chokidar-master/npm-debug.log

FYI i need to run shrinkwrap on a parent project and it all fails downstream....

**Comment by freaz** [comment]
I am having same issue.

**Comment by es128** [comment]
Track the issue at https://github.com/strongloop/fsevents/issues/100

In the meantime you can `npm i fsevents@1.0.2` prior to running shrinkwrap.

**Comment by adidahiya** [comment]
@es128 that solution only works for Mac... any ideas for Linux?

**Comment by es128** [comment]
You shouldn't have the `fsevents` dependency to begin with if you're on linux

**Comment by adidahiya** [comment]
I'm shrinkwrapping on Mac (local machine) and running CI builds on linux

**Comment by es128** [comment]
So why doesn't it work?

**Comment by adidahiya** [comment]
Well, I can't install `fsevents` without adding it to `package.json` (shrinkwrap complains about extraneous dependencies). And I don't want to add it to `package.json` because of the Linux builds.

I was able to work around this by going into node_modules/chokidar/node_modules/fsevents/node_modules/fstream-ignore and running `npm install fstream`. Shrinkwrap worked correctly after that.

**Comment by es128** [comment]
Resolved with fsevents 1.0.4

**Comment by sixinli** [comment]
thanks for the update!
