### ISSUE TITLE
ready vs initial add events with awf

### ISSUE THREAD

**Issue by nono** [paulmillr/chokidar#397]
Hi,

when the `awaitWriteFinish` option, the `ready` event is fired before the `add` events for files that already exist on the watched space. Do you think it's normal? I'd have expected `ready` to be fired only after all the `add` events.

**Comment by es128** [comment]
`awaitWriteFinish` suppresses any `add` events based on its parameters of polling for file size changes. Perhaps this should be changed to not take effect until after the `ready` event though.
