### ISSUE TITLE
Adding a previously deleted directory does not produce an event

### ISSUE THREAD

**Issue by CxRes** [paulmillr/chokidar#404]
Like it says

I am on Windows 10 x64, Node 4.2, Chokidar 1.3.0 (does not work even in Chokidar 1.1.0)

**Comment by es128** [comment]
Try master branch. Some recent changes may have an impact. 

For your reference, there is a test for this exact scenario at https://github.com/paulmillr/chokidar/blob/4c5747c24a1a2e291b99a247e32d9c3da2c33b44/test.js#L357-L383

When re-adding the directory, is it empty? I've been seeing some sporadic test failures that seem related to not picking up empty directories. Try writing a file in it.

**Comment by CxRes** [comment]
It works when a file is written in the directory. I'll check if master helps.

**Comment by CxRes** [comment]
It does NOT work in master when empty directory is written again. Please Reopen.

**Comment by es128** [comment]
There's a chance that `fs.watch` simply does not always report the creation of empty directories, in which case there would be no reasonable solution here. But I'll investigate some more. 

If you can show what is output by the `raw` event while you observe this it might help.

**Comment by CxRes** [comment]
I'll do that in a day or two.

**Comment by CxRes** [comment]
My output looks like this:

On deleteing the directory `qux`:
```
Raw: rename, null, Object {watchedPath: "C:\foo\bar"}
Raw: rename, null, Object {watchedPath: "C:\foo\bar"}
Raw: change, bar, Object {watchedPath: "C:/foo"}
Raw: change, bar, Object {watchedPath: "C:/foo"}
UnlinkDir: bar\qux
```
On recreating the directory `qux`:
```
Raw: rename, qux, Object {watchedPath: "C:\foo\bar"}
Raw: rename, qux, Object {watchedPath: "C:\foo\bar"}
Raw: change, bar, Object {watchedPath: "C:/foo"}
Raw: change, bar, Object {watchedPath: "C:/foo"}
Raw: change, qux, Object {watchedPath: "C:\foo\bar"}
Raw: change, qux, Object {watchedPath: "C:\foo\bar"}
```

**Comment by CxRes** [comment]
I also found a couple of other things, I am wondering if these are known or should I open tickets:
1) The use of slashes in the output above is not consistent?
2) `raw` events are not issued before the `ready` event?

**Comment by es128** [comment]
Looks fixable, I just need to find a way to reproduce it. Does the test I pointed out pass when you run it?

As for your other questions, the forward slash version `C:/foo` is how you're providing it to chokidar, while the others are the way the OS reports the paths. Use backslashes yourself if you want it to be consistent, but it shouldn't matter. 

`raw` events are not emitted with the initial add events, this is expected.

**Comment by CxRes** [comment]
I get these errors (the one you mention does not lead to a problem):
```
1) chokidar fs.watch (non-polling) unwatch should unwatch paths that are relative to options.cwd:
     Uncaught AssertionError: expected spy to not have been called with arguments add
      at null._onTimeout (<path>\chokidar\test.js:1606:38)

2) chokidar fs.watchFile (polling) unwatch should ignore unwatched paths that are a subset of watched paths:
     Uncaught expected spy to have been called exactly once, but it was called twice
    spy(change, <path>\chokidar\test-fixtures\143\change.txt, {
  atime: Sun Nov 29 2015 22:36:17 GMT+0530 (India Standard Time),
  birthtime: Sun Nov 29 2015 22:36:17 GMT+0530 (India Standard Time),
  blksize: undefined,
  blocks: undefined,
  ctime: Sun Nov 29 2015 22:36:52 GMT+0530 (India Standard Time),
  dev: 716632857,
  gid: 0,
  ino: 844424930329930,
  mode: 33206,
  mtime: Sun Nov 29 2015 22:36:52 GMT+0530 (India Standard Time),
  nlink: 1,
  rdev: 0,
  size: 0,
  uid: 0
}) at emitThree (events.js:97:13)

    spy(change, <path>\chokidar\test-fixtures\143\change.txt, {
  atime: Sun Nov 29 2015 22:36:17 GMT+0530 (India Standard Time),
  birthtime: Sun Nov 29 2015 22:36:17 GMT+0530 (India Standard Time),
  blksize: undefined,
  blocks: undefined,
  ctime: Sun Nov 29 2015 22:36:52 GMT+0530 (India Standard Time),
  dev: 716632857,
  gid: 0,
  ino: 844424930329930,
  mode: 33206,
  mtime: Sun Nov 29 2015 22:36:52 GMT+0530 (India Standard Time),
  nlink: 1,
  rdev: 0,
  size: 13,
  uid: 0
}) at emitThree (events.js:97:13)
  AssertionError: expected spy to have been called exactly once, but it was called twice
      spy(change, <path>\chokidar\test-fixtures\143\change.txt, {
    atime: Sun Nov 29 2015 22:36:17 GMT+0530 (India Standard Time),
    birthtime: Sun Nov 29 2015 22:36:17 GMT+0530 (India Standard Time),
    blksize: undefined,
    blocks: undefined,
    ctime: Sun Nov 29 2015 22:36:52 GMT+0530 (India Standard Time),
    dev: 716632857,
    gid: 0,
    ino: 844424930329930,
    mode: 33206,
    mtime: Sun Nov 29 2015 22:36:52 GMT+0530 (India Standard Time),
    nlink: 1,
    rdev: 0,
    size: 0,
    uid: 0

      spy(change, <path>\chokidar\test-fixtures\143\change.txt, {
    atime: Sun Nov 29 2015 22:36:17 GMT+0530 (India Standard Time),
    birthtime: Sun Nov 29 2015 22:36:17 GMT+0530 (India Standard Time),
    blksize: undefined,
    blocks: undefined,
    ctime: Sun Nov 29 2015 22:36:52 GMT+0530 (India Standard Time),
    dev: 716632857,
    gid: 0,
    ino: 844424930329930,
    mode: 33206,
    mtime: Sun Nov 29 2015 22:36:52 GMT+0530 (India Standard Time),
    nlink: 1,
    rdev: 0,
    size: 13,
    uid: 0
      at null._onTimeout (<path>\chokidar\test.js:1548:50)

  3) chokidar fs.watchFile (polling) unwatch should unwatch paths that are relative to options.cwd:
     Uncaught AssertionError: expected spy to not have been called with arguments add
      at null._onTimeout (<path>\chokidar\test.js:1606:38)
```

**Comment by CxRes** [comment]
On second thoughts: I am watching two levels of directories `depth:1`. When I work with one, it seems to work fine. Output looks like this:
```
Raw event info: rename null { watchedPath: 'C:/foo' }
delDir qux
Raw event info: rename qux { watchedPath: 'C:/foo' }
Raw event info: change qux { watchedPath: 'C:/foo' }
addDir qux
```

**Comment by egasimus** [comment]
Same thing happens for me, more or less, with Chokidar `1.4.2` in Node `5.5.0` on Arch Linux `4.1.13-rt15-bfq`. My program launches an empty Chokidar instance with `depth: 0`, and then manually adds watch targets to it as it recursively traverses a directory. Curiously enough, tracing `raw` event only prints out `rename` events when creating or deleting the directory (1 rename event when creating, and 3 rename events when deleting -- wtf...?!).

**Comment by primozs** [comment]
Hello,
I am having similar issue. I am playing with this example:
https://github.com/ourcodeworld/electron-examples/tree/master/examples/electron-folderandfilewatcher
chokidar version 1.5.1

I want to watch a stick volume or a certain file on a memory stick. When I unmount it, events are fired but when I mount it no events fire. This works the same if I watch directory or a file:
/Volumes/aaa
/Volumes/aaa/Settings/Default.xml

**Comment by primozs** [comment]
If i start to watch the file or the folder before it is mounted then it works mount and unmount.
Otherwise if the stick is mounted and I start to watch the folder or file then unmount events are fired but when I mount again then everything is quiet.

**Comment by badalyan** [comment]
I'm still experiencing this issue. Anybody know of a workaround?

**Problem:**
When watching a folder, and then deleting that folder, and then creating a new folder with the same name, events are no longer fired when new files are added. 

**Versions:**
Chokidar version: 3.4
Node version 12.18.2
OS version: Windows 10

**To Reproduce:**

1. Attempt watching a folder named "Test"
1. Add file into "Test" folder
1. `Add` event is fired
1. Delete "Test" folder
1. Create new folder named "Test"
1. Add file into "Test" folder
1. **BUG:** `Add` event is NOT fired

**Comment by aral** [comment]
@badalyan I’m seeing the same thing on Linux (Pop!_OS 20.04, based on Ubuntu 20.04) on Node 12.16.2.

In case it helps: If you attach a `raw` handler, you see that `rename` events _are_ being fired on the removed/re-added folder.
