### ISSUE TITLE
my project needs a solution for using it on mac os and linux

### ISSUE THREAD

**Issue by thinkrapido** [paulmillr/chokidar#408]
I am migrating a mac os node project which uses chokidar to linux.

A chokidar's dependency is fsevents.
When I perform npm install it tells me that it is not compatible with my operation system.

What shall I do?

**Comment by es128** [comment]
Chokidar is cross-compatible on Mac, Linux, and Windows. `fsevents` is an optional dependency, used only on Mac. If you're just doing a regular `npm install` you should have no problem aside from perhaps a warning message that `npm` is skipping the optional dependency.

Are you checking in your `node_modules` and/or using a shrinkwrap file? What version of `npm`?

Take a look at https://github.com/npm/npm/issues/5095 and the related issues to see if you can figure out the right way to handle what you want to do on your systems.
