### ISSUE TITLE
Events suddenly stopped

### ISSUE THREAD

**Issue by rfossella** [paulmillr/chokidar#417]
Hi. Running Windows 7 Pro.
I installed (upgraded) to *v1.4.1* today (from *1.2*) and noticed that suddenly many events are no longer being fired off.  There is now sporadic behavior for add, change, delete.  I am (have been) tracking folders on a network.  I initialize my watcher and use POSTMAN to view its contents.  I am also running debug mode of Node within Chrome.  

I'll explicitly add a new file and will get proper add event; if I then delete file I do not get delete event.  Subsequently, when I check for stats my watcher is holding onto a file that no longer exists.  If I add the file back in I again DO NOT receive event, then when I examine the watcher instance the update time is that of the **first time** it was added.  Sometimes file changes occur (e.g. edit file in notepad) -- sometimes the change does not get fired.  It's driving me kind of batty.

My original thought was that I started using the getWatched() method instead of my previous implementation using private _watched (btw, this caused some grief since I was reading _items which was no longer needed).  I have since backed out the use of getWatched() to see if that was issue.  It was no help as the sporadic behavior.  

So, my question is, has anyone been witnessing dropped events?  Any thoughts for further debugging other than putting breakpoints inside the watcher .on() statements?

I may back out 1.4.1 and revert to 1.2 to see if problem persists and will report back.  But if anyone can assist please advise.

Thanks.

**Comment by rfossella** [comment]
A follow-up to my previous post.  While reading some other posts about network access I changed my watcher init to **usePolling:true**.  This has so far helped.  The only issue is that now CPU spikes to 10% for node.exe.  Is this a recommended approach for network files? Has anybody solved without polling?  Thank you!

**Comment by es128** [comment]
`usePolling` is the only mode in chokidar that works for watching across a network. I have to assume that the upgrade was a coincidence that had nothing to do with the issue you experienced. Yes, it comes with a CPU penalty, which you can influence by changing the `pollInterval` and ensuring you don't watch any more than really necessary (by using targeted glob patterns and/or `ignore`).
