### ISSUE TITLE
Mac: watcher seems to be case sensitive when watching a folder?

### ISSUE THREAD

**Issue by bpasero** [paulmillr/chokidar#418]
I have a folder called `/Users/bpasero/Development/express` and install a chokidar watcher on it. Everything works fine. If I do the same with lowercase in the beginning (`/users/bpasero/Development/express`), I am not getting any events. Is that intentional?

**Comment by es128** [comment]
"Intentional" may not quite be the right word - it's how the file system works. Chokidar doesn't do anything special to try to allow for case-insensitive path lookups.

**Comment by bpasero** [comment]
@es128 do you know at which layer this actually "breaks"? If I use node fs APIs, the case does not matter for a file system that is case-preserving but case-insensitive. I would probably expect the same from a file watching library :+1: .

**Comment by es128** [comment]
I don't know, this isn't something I've explored before. If there are simple changes we can make within chokidar to fix this, I'd be supportive of that.

**Comment by bpasero** [comment]
Ok, lets just hope it is not deep down in native fsevents.

**Comment by bpasero** [comment]
@es128 I traced it down to this check: https://github.com/paulmillr/chokidar/blob/master/lib/fsevents-handler.js#L43

Basically you only emit the file event if the path is identical in case. This check is not making sense in environments where the file system is case-insensitive imho. Any reason this check is there in the first place?

**Comment by es128** [comment]
> Any reason this check is there in the first place?

Yes, it has to do with efficient utilization of underlying fsevents instances to avoid hitting system limits in cases where many watcher instances are spawned for similar paths.

This also explains why I wasn't able to reproduce the problem in a simple test - it can only occur with multiple instances watching overlapping parts of the file tree.

We're going to need some test coverage here. Removing the condition would lead to problems, but all the tests currently pass regardless.

Then coercing to lowercase in that comparison to solve the case sensitivity should be easy enough.

**Comment by nono** [comment]
> Then coercing to lowercase in that comparison to solve the case sensitivity should be easy enough.

Well, it can be more complex than that (and upper case should be prefered to lower case). https://nodejs.org/en/docs/guides/working-with-different-filesystems/#be-prepared-for-slight-differences-in-comparison-functions is a good read on the subject.

**Comment by bpasero** [comment]
> This also explains why I wasn't able to reproduce the problem in a simple test - it can only occur with > multiple instances watching overlapping parts of the file tree.

In my test case I was just opening chokidar on one folder, are you saying that there are multiple instances of fsevents created in that case?

**Comment by es128** [comment]
@nono Thanks for that reference. It might be tricky to slide a `fs.realPath(resolvedPath, ...` call in there, but I'll consider it. At worst, I'll defer to `.toUpperCase()`.

**Comment by es128** [comment]
@bpasero I noticed that you cross-linked from an issue with VS Code. I was assuming that it has opened watcher instances somewhere else in the process looking at https://github.com/paulmillr/chokidar/blob/master/lib/fsevents-handler.js#L60-L62, but now that I look again I see that I was mistaken. `filteredListener` is used upon the initial creation of an fsevents instance as well.

But nonetheless, I was not able to reproduce the issue in a simple test using `example.js`

```
λ node example.js
addDir /users/eshanker/Code/chokidar/coverage
addDir /users/eshanker/Code/chokidar/lib
addDir /users/eshanker/Code/chokidar/test-fixtures
add /users/eshanker/Code/chokidar/CHANGELOG.md
add /users/eshanker/Code/chokidar/README.md
add /users/eshanker/Code/chokidar/appveyor.yml
add /users/eshanker/Code/chokidar/example.js
add /users/eshanker/Code/chokidar/index.js
add /users/eshanker/Code/chokidar/package.json
add /users/eshanker/Code/chokidar/test.js
Ready
change /users/eshanker/Code/chokidar/example.js
change /users/eshanker/Code/chokidar/example.js
```

In your case, something has to have caused a disparity between the path reported with the event and the user-entered absolute path.

**Comment by es128** [comment]
Looking at the `raw` events, fsevents is actually reflecting back the incorrect casing supplied by the user in its events. Watching a symlink also didn't break it.

`RawEvent: change /USERS/ESHANKER/CODE/CHOKIDAR-LINK/lib/fsevents-handler.js`

@bpasero can you help figure out what's happening differently in your case?

**Comment by bpasero** [comment]
@es128 actually when I was looking into this issue I was just using a simple stand alone node application:

```javascript
var watcher = chokidar.watch('/users/bpasero/Development/express', {
    ignored: /[\/\\]\./,
    persistent: true
});
```

On disk the path is actually with an uppercase: `/users/bpasero/Development/express`

This alone is enough for me to reproduce that the event is emitted from fsevents, but not emitted to the chokidar user because of the filter:

![screen shot 2015-12-18 at 16 22 16](https://cloud.githubusercontent.com/assets/900690/11900041/8bf7e0a2-a5a3-11e5-96bf-cc0ee3139faf.png)

I am in a breakpoint after duplicating a file in the directory and you can see in the variables to the left that fullPath is `/Users/bpasero/Development/express/History copy.md` and resolvedPath is `/users/bpasero/Development/express`. So the filter condition will make this event not be emitted.

**Comment by es128** [comment]
For some reason I get a different result when doing effectively the same thing, but it doesn't matter - it's clear what needs to be done to fix it.

```
RawEvent: change /USERS/ESHANKER/CODE/CHOKIDAR-LINK { curr:
   { dev: 16777220,
     mode: 16877,
     nlink: 18,
     uid: 510,
     gid: 600,
     rdev: 0,
     blksize: 4096,
     ino: 1150998,
     size: 612,
     blocks: 0,
     atime: Fri Dec 18 2015 10:27:52 GMT-0500 (EST),
     mtime: Fri Dec 18 2015 10:27:52 GMT-0500 (EST),
     ctime: Fri Dec 18 2015 10:27:52 GMT-0500 (EST),
     birthtime: Sat Mar 21 2015 21:55:02 GMT-0400 (EDT) },
  prev:
   { dev: 16777220,
     mode: 16877,
     nlink: 17,
     uid: 510,
     gid: 600,
     rdev: 0,
     blksize: 4096,
     ino: 1150998,
     size: 578,
     blocks: 0,
     atime: Fri Dec 18 2015 10:27:45 GMT-0500 (EST),
     mtime: Fri Dec 18 2015 10:11:03 GMT-0500 (EST),
     ctime: Fri Dec 18 2015 10:11:03 GMT-0500 (EST),
     birthtime: Sat Mar 21 2015 21:55:02 GMT-0400 (EDT) } }
add /USERS/ESHANKER/CODE/CHOKIDAR-LINK/index Copy.js
```

**Comment by bpasero** [comment]
> it's clear what needs to be done to fix it.

So would you change the filter to to a comparison in uppercase? I think the hard part is that in theory someone could run with HFS+case-sensitive on Mac so maybe this even needs to be configurable option in Chokidar to control? And certainly on Linux case-sensitive file systems are common.

**Comment by es128** [comment]
> So would you change the filter to to a comparison in uppercase?

Hopefully not, I'd first want to try to solve it with a better option. Some thoughts:

1. Run a string transform that ensures the user's original casing on the reported path is preserved, even if it came out differently from the raw event, before doing the comparison.
2. Utilize `fs.realpath` - although I may have just ruled this out as a possibility since it also seems to be preserving whatever case the user supplies when I tried it locally just now.

**Comment by bpasero** [comment]
@es128 from what I know there is no function to get the real path with the casing as it is defined in the file system. The only way I think you can do this is by repeated `fs.readDir()` calls for each segment of the path because that is returning the proper case.

**Comment by es128** [comment]
Yes, I'm coming to that realization... So hopefully there's a workable solution somewhere in that first idea. 

If not, I am ok with going to the `.toUpperCase()` solution. Even in the cases of strict-case file systems you pointed out, it's hard to imagine where that solution would cause a problem for chokidar users.

I don't think doing `readdir`s up through the parents will be something we'd want to pursue.

**Comment by bpasero** [comment]
Right, I also think this solution is good for the 99% case. The only gotcha is that node started to return a different Unicode normalization form on Mac. I think this topic is described in that document as well. To compare paths you would need to normalize its Unicode form if they differ.

**Comment by bpasero** [comment]
@paulmillr @es128 can this be looked at again? The reality for Mac users on VS Code (and pretty much any chokidar user on Mac) today is that all file events are broken when you open a folder (from the command line) with wrong casing. The workaround for me is to detect the bad casing and rewrite the paths in the events flowing out of chokidar (odd).

One issue I noticed is that when I do the `toUpperCase` trick in https://github.com/paulmillr/chokidar/blob/1.4.0/lib/fsevents-handler.js#L44 I am getting the event, however it will incorrectly be detected as `added` even though I just changed a file.

The repro is to open chokidar on a path with wrong case and modify a file within.

**Comment by es128** [comment]
@bpasero unfortunately in my past attempts I was not able to repro locally. It does not appear to impact Mac users universally, there seems to be some other system setting having an impact, but I don't know where to find it.

**Comment by bpasero** [comment]
@es128 wow that is weird. I have a simple reproducible case here. Just checkout latest of chokidar, add a new *.js file with this script and run it with node (5.10.0):

```javascript
var chokidar = require('./');
var fs = require('fs');
var path = require('path');

var base = __dirname.toUpperCase();
chokidar.watch(base, {ignored: /[\/\\]\./, ignoreInitial: true}).on('all', (event, path) => {
  console.log(event, path);
});

setTimeout(function() {
  fs.writeFileSync(path.join(__dirname, 'test'));
}, 1000);
```

On my Mac (10.11.4) I am not getting anything printed to the console. Are you?

**Comment by es128** [comment]
Yup. 10.10.5

```
λ node bpasero.js
change /USERS/ESHANKER/CODE/CHOKIDAR/test
change /USERS/ESHANKER/CODE/CHOKIDAR/bpasero.js
```

**Comment by bpasero** [comment]
@es128 very weird, could it be the OS X update?

My disk info:

```
~/Development/Microsoft/monaco> diskutil info /
   Device Identifier:        disk1
   Device Node:              /dev/disk1
   Whole:                    Yes
   Part of Whole:            disk1
   Device / Media Name:      APPLE SSD SM0512F

   Volume Name:              HD

   Mounted:                  Yes
   Mount Point:              /

   File System Personality:  Journaled HFS+
   Type (Bundle):            hfs
   Name (User Visible):      Mac OS Extended (Journaled)
   Journal:                  Journal size 40960 KB at offset 0xe8f000
   Owners:                   Enabled

   Content (IOContent):      Apple_HFS
   OS Can Be Installed:      Yes
   Recovery Disk:            disk0s3
   Media Type:               Generic
   Protocol:                 PCI
   SMART Status:             Not Supported

   Total Size:               499.0 GB (499046809600 Bytes) (exactly 974700800 512-Byte-Units)
   Volume Free Space:        116.1 GB (116098367488 Bytes) (exactly 226754624 512-Byte-Units)
   Device Block Size:        512 Bytes
   Allocation Block Size:    4096 Bytes

   Read-Only Media:          No
   Read-Only Volume:         No

   Device Location:          Internal
   Removable Media:          No

   Solid State:              Yes
   Virtual:                  Yes
   OS 9 Drivers:             No
   Low Level Format:         Not supported

   This disk is a Core Storage Logical Volume (LV).  Core Storage Information:
   Fusion Drive:             No
   Encrypted:                No
```

**Comment by es128** [comment]
This has been reported since before El Capitan, hasn't it? I don't see any impactful differences in my disk config. One notable thing is that I have disk encryption on, but it seems like a stretch that this issue hinges there.

**Comment by bpasero** [comment]
@es128 not sure to be honest, might be. Would be interesting to get someone else on this to reproduce :). I know that a colleague has the same issue, but he sits on the same OS.

And you are also on node.js 5 right?

**Comment by es128** [comment]
Yes, I was using node v5.6.0 just now to test.

**Comment by bpasero** [comment]
Well actually it was for sure happening with 4.x already, given how old this report is.

**Comment by es128** [comment]
Right, I highly doubt this has anything to do with node version or any part of the stack we have influence over. It's something at a lower level in the system, and the only thing we can possibly do is pursue a workaround using toUpperCase normalization or something like that. But without being able to reproduce, I'd have a tough time searching for a reliable workaround on my own.

**Comment by bpasero** [comment]
I wonder if this happens at the layer of native fsevents where you get the path reported back. In your case I would expect fsevents to give the uppercase path and in my case the real path as it is on disk.

**Comment by es128** [comment]
That does appear to be what is happening at least at the level of the fsevents node bindings we are using here.

**Comment by bpasero** [comment]
@es128 I suggest we try to come up with a test and let it run on travis with different configurations to see if the OS X update broke this.

Can you try to run the following test on your machine to see if it succeeds or not? I added the following test within the `describe('watch individual files', function ()` test suite:

```javascript
it('should detect changes (UPPERCASE)', function (done) {
  var spy = sinon.spy();
  var testPath = getFixturePath('change.txt');
  var testPathUppercase = testPath.toUpperCase(); // UPPERCASE !
  watcher = chokidar.watch(sysPath.dirname(testPathUppercase), options)
    .on('change', spy)
    .on('ready', function () {
      fs.writeFile(testPath, Date.now(), simpleCb);
      waitFor([spy], function () {
        spy.should.have.always.been.calledWith(testPath);
        done();
      });
    });
});
```

In order to run travis with multiple OS X releases, you can use their matrix option:

```yml
matrix:
  include:
    - os: osx
      osx_image: xcode7.3
      node_js: "5"
    - os: osx
      osx_image: xcode7.2
      node_js: "5"
    - os: osx
      osx_image: xcode7.1
      node_js: "5"
    - os: osx
      osx_image: xcode7
      node_js: "5"
    - os: osx
      osx_image: xcode6.4
      node_js: "5"
    - os: osx
      osx_image: beta-xcode6.3
      node_js: "5"
    - os: osx
      osx_image: beta-xcode6.2
      node_js: "5"
    - os: osx
      osx_image: beta-xcode6.1
      node_js: "5"
```

**Comment by ryanelian** [comment]
I was bitten by something similar (probably not the same) to this on Windows, just documenting my experience:

```
watch('.../folder/*.txt')
```

Works for files with extensions `.txt` but not `.TXT` (the glob don't seem to be case insensitive in regards to file extension)
