### ISSUE TITLE
Changing a file causes a "remove" event sometimes

### ISSUE THREAD

**Issue by arubtsov** [paulmillr/chokidar#421]
I'm on Windows 8.1 x64, node v4.2.2, Chokidar 1.4.1. I change the file using Webstorm and "remove" fires once per ~10 changes ("change" event is also fired). After next changing of the file fires "create".

**Comment by es128** [comment]
This sounds related to the `atomic` option (should be `true` by default in your environment) and the following code: https://github.com/paulmillr/chokidar/blob/master/index.js#L153-L168.

Please log the output from the `raw` event when this happens so we can see how the editor is actually behaving with saving the file.

You can also try seeing if there is an "atomic save" sort of setting in webstorm you can change.

**Comment by arubtsov** [comment]
It is interesting that i can't reproduce this behavior while I'm subscribed to `raw` event. Also everything is fine in case if the file is changed using node (so yes, it is likely connected with Webstorm).

**Comment by es128** [comment]
Closing this for now. Please post more details if you'd like this to be investigated further.
