### ISSUE TITLE
Files added via FTP on OS X don't trigger events

### ISSUE THREAD

**Issue by SphtKr** [paulmillr/chokidar#423]
This is very strange to me, but I can't find another variable. I have this code:

    var watcher = chokidar.watch(this.path, {alwaysStat: true});
    watcher.on('all', function(event, path){debug("Got event: " + event + " " + path);});

I'm watching a directory that is uploaded to by user `ftpuser`, using the OS X Server (10.11) FTP service. I am watching the directory using a process owned by another user, but that doesn't seem to be the issue.

If I upload a file via FTP as `ftpuser`, nothing happens. I figured it had to be permissions making the difference somehow. But, if I do this:

    sudo -u ftpuser touch testfile

Which creates a file with the same permissions as the FTP upload does--then I get an event!

Any idea what the difference could be when uploading via FTP that would cause the events not to fire?

**Comment by SphtKr** [comment]
Minor addition, I tried ftp'ing something as the same user as the watching process is running as, again no event. Somehow the FTP server seems to be slipping things in without FsEvents firing (or at least I presume the failure is here).

I was also trying to make it fall back to `fs.watch`...is that not possible on OS X? According to the docs--and my understanding--if you set `useFsEvents: false` (disables FsEvents) and also `usePolling: false` (disables `fs.watchFile`), that leaves only `fs.watch`. But when I try that I get hit with the `EMFILE` error because of the 256-file-per-process (default) limit on OS X, which I thought only happens with `fs.watchFile` not `fs.watch`, so I think my options didn't do what I think they would. And/or I have a flawed assumption in there somewhere.

**Comment by SphtKr** [comment]
One more thing, sorry...puzzlingly, a Folder Action on the same path *does* pick up FTP'd files. So now I'm confused, as I thought that would be using FsEvents also?

**Comment by es128** [comment]
> which I thought only happens with fs.watchFile not fs.watch

No, you have this backwards. You did correctly enable `fs.watch`. Did you try polling mode (which uses `fs.watchFile`)? I would guess polling mode would work if you can accept the CPU penalty.

If you want to diagnose what's happening in the original case with fsevents, add and listener that logs the output of the `raw` event so we can see whether your presumption that FsEvents is missing these new files is correct.

Seems unrelated to your issue, but you may also want to look into the `awaitWriteFinish` option, which was added to support users with a similar use case of slowly written files via ftp.

**Comment by SphtKr** [comment]
> Did you try polling mode (which uses fs.watchFile)? I would guess polling mode would work if you can accept the CPU penalty.

Ugh...I did try it, but it used up most of two cores on my i5...that won't do. I should have tested if I actually get events with that configuration though--I'll go back and try it later.

> If you want to diagnose what's happening in the original case with fsevents, add and listener that logs the output of the raw event so we can see whether your presumption that FsEvents is missing these new files is correct.

Unsure exactly what you were saying to do, but I have this now:

    var watcher = chokidar.watch(this.path, {ignoreInitial: true, alwaysStat: true, useFsEvents: true, usePolling:false});
    watcher.on('add', changeHandler);
    watcher.on('change', changeHandler);
    watcher.on('raw', function(event, path){debug("Got event: " + event + " " + path);});

And with the `raw` listener, I only get events if I touch a file locally, if I FTP a file I get no output. Does that help?

**Comment by es128** [comment]
> And with the `raw` listener, I only get events if I touch a file locally, if I FTP a file I get no output. Does that help?

Yes. It confirms your original suspicion that the FTP service somehow bypasses detection by FSEvents. So each of the 3 watch modes has severe drawbacks for you. You could try `ulimit -n 10000` and go back to `fs.watch` mode if that was otherwise working for events. Or perhaps try a different FTP server.

But I don't think there's anything that can be done in chokidar to help. Seems to be something lower level between the FSEvents API and the built-in API server. Closing for now.
