### ISSUE TITLE
File change does not trigger sometimes.

### ISSUE THREAD

**Issue by anshulguleria** [paulmillr/chokidar#424]
I am using `v1.4.1` for chokidar in `linux 15.04`.
Editor: `vim`

I am using `on('change')` event on some files I am observing.

I can't replicate the scenario but it happens too frequently that some files changes are not triggering the `change` event. Like I have `.js`, `.html` and `.py` file opened in my editor and i saved `.js` file but the change is triggered but if I change `.html` or `.py` file the change is triggered. 

I don't think there is anything wrong in my code but initially everything works file, it starts happening after some time. But still if you need code sample please tell.

**Comment by anshulguleria** [comment]
I think it happens every time when i change the same file again. Like if I had changed `.js` file last then frequent changes in the same is not triggering but after changing another file change is triggered and then again if I change first file again then it gets triggered again.

**Comment by paulmillr** [comment]
Could you try switching `usePolling: true / false`? Also, `atomic: true/false`

**Comment by es128** [comment]
Please log the output of the `raw` event in addition to the `all` event when this happens to observe more closely what the actual underlying event behavior looks like.

There's a chance, if the machine is slow enough, that your changes actually get emitted as and `unlink` and `add` instead of a `change` and you wouldn't notice if you've only added the one listener.

**Comment by anshulguleria** [comment]
@es128 I will try it but I don't think my laptop would be slow. Its `lenovo thinkpad i5`.
@paulmillr I tried setting `usePolling` and `atomic` to `true`. Today I didn't felt that same issue but today sometimes I had to save my files twice for the `change` event to trigger.

**Comment by anshulguleria** [comment]
I think setting those `usePolling` and `atomic` true solved the issue. Today I didn't experienced it. May be its because I upgraded my node to `v5.3.0` from `v5.1.0`

**Comment by anshulguleria** [comment]
Hi,
Sorry to raise this issue again but recently I observed that it is working fine with my sublime editor but in case of `vim` sometimes I have to save my file twice or thrice to trigger the file change events.

**Comment by bagau** [comment]
Adding only `usePolling` and `atomic` to `true` doesn't help me. I added also `persistent` to `true` and it helps me.

**Comment by beorn** [comment]
Might be caused by throttling eating subsequent events? See #1084
