### ISSUE TITLE
Not compatible with your operating system or architecture: fsevents@1.0.6

### ISSUE THREAD

**Issue by 4Digits** [paulmillr/chokidar#425]
I am trying to use a Grunt plugin that compiles nunjucks templates into html.
This plugin requires fsevents. I am running an Linux Mint 17+.

During the npm installation I am getting the following errors:

```
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.6
```
Is there a workaround? I already tried other nunjucks-plugins for Grunt, but they all require the same dependency.

**Comment by nono** [comment]
It's just a warning, not an error. You can safely ignore it. Fsevents is an optional dependency and is used on only on OSX.

**Comment by 4Digits** [comment]
The problem is that that these nunjucks plugins (does not matter which one I use) break my complete grunt build. When I remove them it works...

**Comment by paulmillr** [comment]
Please report the issue to the nunjucks plugin repo. We definitely have tons of cross-platform projects using Chokidar without breakage.

**Comment by aniruddha-chakraborty** [comment]
@nono How ?
