### ISSUE TITLE
`ignored` works only if `cwd` is set

### ISSUE THREAD

**Issue by paulovieira** [paulmillr/chokidar#426]
I had to dig in the source code to understand why the `ignored` option was not taking effect. The reason was that I didn't have the `cwd` option set.

Should I open a pr to add note about this in the readme? Or is it a bug that should be corrected?

From my perspective (end user of this lib), I would expect these options options to be independent.

**Comment by es128** [comment]
They are independent, but if you mix up the relative-ness of your paths you might not get the behavior you were hoping for. 

You can take a look at the `describe('ignored')` section of the tests to see how they work without specifying `cwd`.

If you're seeking help or still think you've found a problem, please provide more evidence of the issue you actually encountered. Closing for now.
