### ISSUE TITLE
Losslessly restarting Chokidar

### ISSUE THREAD

**Issue by Voyz** [paulmillr/chokidar#428]
I'm running a local intranet file watching server that fills in my database using Chokidar's events. Is there's a way of restarting the Chokidar without a need of rescanning whole data? I seem to have two options:

 1. Redo initial scan and compare all items against my database to check for any changes / new items.
 2. Ignore the initial scan events to have the Chokidar up and running quicker

The first case seems pretty slow. In second case I'd be losing data between restart and the end of the initial scan.

.

I can think of a couple of ways out of this:

 1. Keep the watchers backed up on a separate process and load them in on Chokidar's start. (Although no idea if there's functionality to do this)
 2. Run a clone of the server that takes over its responsibilities once the primary server restarts (Although that doesn't save me from a power-cut since both of them would go down)

This brings a few questions:

 **- Is there a way of keeping FSWatchers (and the fs_event_wrap) alive during the node.js process restart?**
 **- Is there a way to save / load state of Chokidar?**
 **- What is your recommended way of restarting without experiencing downtime?**

Thanks!

.

(
I also made a stackoverflow thread about the file watcher restarts in general if you'd like to share the thoughts more broadly
http://stackoverflow.com/questions/34677142/how-to-restart-a-file-watcher-robustly
)

**Comment by es128** [comment]
You might want to elaborate on the reasons why you need to restart - perhaps you can find ways to avoid doing it to begin with. You hinted at this already when you described some ideas about managing the watching part as a separate continuous (perhaps daemonized) process.

As for avoiding the initial scan, I don't think it would be possible to provide accurate events without it. A locally cached state would not be useful as it could not be trusted.

Something I am intending to work on in the near term is making that initial scan much more fast and efficient, which should help a lot, but isn't quite what you asked.

Another suggestion for you to consider given your use case is to look into [watchman](https://facebook.github.io/watchman/), which can't be deployed as simply as chokidar via npm, but likely provides a more robust solution for the kind of operations you are trying to perform.
