### ISSUE TITLE
'Not compatible with your operating system or architecture'

### ISSUE THREAD

**Issue by magick93** [paulmillr/chokidar#432]
Hello

I am getting:
```
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.6
```

When running ```npm install chokidar --save```

I am running:
* Ubuntu 15.10
* Node 5.5.0

Thanks

**Comment by es128** [comment]
`fsevents` is an optional dependency, targeted for Mac only. That's why `npm` writes these as `WARN`, not `ERROR`. Everything is fine.

If you don't like the presence of these messages, take it up with npm's issue tracker - we don't control them here.
