### ISSUE TITLE
Request for help tracking down missing "add" event

### ISSUE THREAD

**Issue by d6y** [paulmillr/chokidar#435]
I'm not seeing an "add" event for changes to the filesystem.  I think this is _unlikely_ to be a problem with chokidar, but I'm hoping someone may spot what I'm missing here, so I can understand what's going on.

## Problem

Inside an Atom package, I'm waiting for two files to appear.  The files are created, by an external process. 

The code I have is:

```
// test.js
var chokidar = require('chokidar');

files = [
  "/Users/richard/Developer/wip/slash/.ensime_cache/port",
  "/Users/richard/Developer/wip/slash/.ensime_cache/http"
];

chokidar.watch(files, {
  persistent: true
}).on('add', function(path) {
  return console.log('WATCH', path);
});
```

Inside Atom, that code only sees the "port" file appear.  That is, I expect to see in the console...

```
WATCH /Users/richard/Developer/wip/slash/.ensime_cache/port
WATCH /Users/richard/Developer/wip/slash/.ensime_cache/http
```

...but I actually only see:

```
WATCH /Users/richard/Developer/wip/slash/.ensime_cache/port
```

The files are created on disk.

However, if I run that code outside of Atom (`$ node test.js`, on a Mac, using node 4.2.1) I see the two files appear as expected.

## Work around

If I watch for one file, and when it is "add"-ed go watch for the second one, I see both add events.  Example code: https://github.com/ensime/ensime-atom/pull/150/files

## Request for help

I've become stuck in trying to understand why I see only one of the files appear when running inside Atom. Any suggestions for investigating this would be much appreciated.

**Comment by es128** [comment]
Instead of watching the two file paths directly, using a glob pattern like `/Users/richard/Developer/wip/slash/.ensime_cache/(http|port)` may help since it will cause a watcher to be attached at the `.ensime_cache` directory level. Picking up `add` events can be spotty when setting watchers on specific file paths.

**Comment by d6y** [comment]
Thank you @es128 - I couldn't get that glob to match, but it did suggest another direction: watching the directory for add `add` events, and picking out the ones I want. Thank you.
