### ISSUE TITLE
change a.html, a.html.js is triggered?

### ISSUE THREAD

**Issue by senwzz** [paulmillr/chokidar#436]
**Testing on win 10:
1, a.html
2, a.html.js
3, test.js:**

var chokidar = require('chokidar');
var watcher = chokidar.watch('.', {ignored: /[\/\\]\./, ignorePermissionErrors:true});
watcher
  .on('add', function(path) {console.log('File', path, 'has been added');})
  .on('change', function(path) {console.log('File', path, 'has been changed');})
  .on('unlink', function(path) {console.log('File', path, 'has been removed');})
  .on('error', function(error) {console.error(error);})
  .on('raw',function(){console.log(arguments);});

when change a.html, a.html.js tirggered ...
a.html has been changed
a.html.js has been changed

**Comment by paulmillr** [comment]
Could you add a test case? I don't think this is reproducible on every system

**Comment by senwzz** [comment]
https://github.com/senwzz/test-case

**Comment by es128** [comment]
This is a Windows behavior that has been reported several times, but there is no clear way so far for chokidar to know when there are misreported events to filter out. You could try changing watch modes (`usePolling: true`) if that is preferable to dealing with this bug.
