### ISSUE TITLE
Retrieving files from current directory and subdirectories when the module is first loaded.

### ISSUE THREAD

**Issue by SeedyROM** [paulmillr/chokidar#438]
Is it possible to retrieve all the files in the watched directory and subdirectories when Chokidar is loaded? Since the ready event has no context or access to directory information, I'm just wondering if it's possible to retrieve a list or object of files within the watched directory on startup. This could be a stupid question, but I'm a noobie so delete this if I missed something crucial.

**Comment by bunterWolf** [comment]
I think there are two ways:

### 1. use the ready event and .getWatched

`
watcherChokidar.on('ready', logWatched)
function logWatched() {
  console.log(  watcherChokidar.getWatched()   )
}
`
(In this case, you have the base dir and the parent of that in the list too)

### Way 2 - collect with add Events
Collect all files and folders with add events
You have much more control and the fs.stats too.

`
watcher.on('add', add)
watcher.on('addDir', add)
watcher.on('ready', look)
`

**Comment by SeedyROM** [comment]
I was super tired last night when I asked the question but the first answer seems to answer my needs. Thanks for the friendly response! :)

**Comment by es128** [comment]
Thanks @bunterWolf
