### ISSUE TITLE
Slow work with many files (over 300)

### ISSUE THREAD

**Issue by movie4** [paulmillr/chokidar#440]
Hello!

With a large number of files to watch - events run very slowly
Files list example https://gist.github.com/movie4/f7cf8871fc59195aea5a

Issue on gulp-watch project – https://github.com/floatdrop/gulp-watch/issues/218

**Comment by paulmillr** [comment]
I don't think that's the case. We have many large Brunch projects and they work pretty well.

You can set `usePolling` to `false` if you want better performance on OS X.

We'll need more info on your system, node version, npm version, chokidar version et cetera.

**Comment by es128** [comment]
Nothing to investigate. Closing for now.
