### ISSUE TITLE
File changes detected on windows when atctivate window (SublimeText)

### ISSUE THREAD

**Issue by gintsgints** [paulmillr/chokidar#441]
I just show hide window of SublimeText with open file and change detection is goin on file.
Modification time of the file is not changed.
(OS Windows)
Code:
```
var chokidar = require('chokidar');

chokidar.watch('./dev/app.component.ts', {atomic: true}).on('all', (event, path) => {
  console.log(event, path);
});
```

**Comment by gintsgints** [comment]
Problem is repeatable with fs.watch

**Comment by es128** [comment]
So, that means Sublime is touching the file. Look at the `raw` event if you want to examine more closely exactly what is happening.

If you want to suppress this, you could try `usePolling: true` as it won't be triggered if the file's stats aren't changed.

**Comment by gintsgints** [comment]
Yeah.... usePolling helps.
