### ISSUE TITLE
Close() / Unwatch() issue

### ISSUE THREAD

**Issue by fyodorvi** [paulmillr/chokidar#448]
Here's test code:

```javascript
var chokidar = require('chokidar');
var fs = require('fs');

var setupWatcher = function () {

    var watcher = chokidar.watch('index.js', { ignoreInitial: true }).on('change', function() {

        console.log('changed');
        watcher.close();
        var file = fs.readFileSync('index.js').toString();
        var result = file.replace(/123/g, '234');
        fs.writeFileSync('index.js', result);
        setupWatcher();

    });

};

setupWatcher();
```

This leads to infinite loop. Same happens if you change it to unwatch('index.js') and then add('index.js').

Tried this as well: 

```javascript
process.nextTick(function () {
   setupWatcher();
});
```
No luck.

Adding a decent timeout helps, like 1 second:
```javascript
setTimeout(function() {
   setupWatcher();
}, 1000);
```

And usePolling: true helps as well.

Is it supposed to be like that?

System is Mac OS 10.11.3

**Comment by es128** [comment]
Some of the things that you're doing that seem synchronous don't necessarily really behave that way all the way down the stack. Starting a watcher immediately after the `writeFileSync` is liable to pick up on that change. This happens at the `fs.watch()` level and lower, not something chokidar could do anything about afaict.

I don't see any good reason for you to be closing and recreating the watcher on every change as in that sample code, so my suggestion is work on refactoring that out. But if it really is necessary for some reason, then the `setTimeout` is probably necessary.
