### ISSUE TITLE
Missed 'unlink' events with cwd + awf

### ISSUE THREAD

**Issue by nono** [paulmillr/chokidar#450]
Hello,

I've been tracking a bug in chokidar where some 'unlink' events are not fired. I'm pretty sure it's in chokidar code, as some events are fired in for a path and later the same path is no longer in `getWatched()` and no `unlink` event have been fired for it.

I've added some console.log in chokidar code to try to understand what happened. I think its cwd + awf + a file updated and then moved.

https://github.com/paulmillr/chokidar/blob/master/index.js#L516-L520
Here, `path` is absolute but `this._pendingWrites` has relative paths as keys. So, `cancelWait` is not called and `this._pendingWrites` still has an entry for the relative path associated to path when `_emit` is called.

https://github.com/paulmillr/chokidar/blob/master/index.js#L144 +
https://github.com/paulmillr/chokidar/blob/master/index.js#L151
Here, the path is set relative to cwd. Thus, it is found in `this._pendingWrites` and the emit is cancelled.

If I am right, to fix it, we have to transform `path` in a relative path before checking it in `cancelWait`. But it's not enough.

In theory, awf makes an `add` and an `unlink` events to cancel. But, here, it's a `change` and an `unlink`, so only the update should be canceled. Should we track if the first event of awf is an `add` or a `change` to and return it to `cancelWait`, in order to `return` or not here: https://github.com/paulmillr/chokidar/blob/master/index.js#L519?

**Comment by es128** [comment]
Sounds really complex. Is there a set of steps you can describe or example code that will consistently demonstrate the problem?

cc/ @alexpusch

**Comment by nono** [comment]
@es128 I've made a PR (#451) with 2 commits. The first one add a failing test case and the other fix it.
