### ISSUE TITLE
HELP! for npm start error :Skipping failed optional dependency /chokidar/fsevents

### ISSUE THREAD

**Issue by a757375927** [paulmillr/chokidar#454]
Window 7 ![qq 20160324130538](https://cloud.githubusercontent.com/assets/5990860/14008876/2e4a7540-f1c1-11e5-9709-b38a076613c8.png)

**Comment by es128** [comment]
It's not a problem - this is expected `npm` behavior. And it's not an error at all, which is why it says `WARN`.
