### ISSUE TITLE
Track path-parent remove events too

### ISSUE THREAD

**Issue by bunterWolf** [paulmillr/chokidar#457]
I'm afraid this is not easy to solve, but is there a possibility to track path-parent changes too.

**Example (OS X 10.11):**
chokidar.watch('  /Users/.../parent-folder/watching-folder ')
When I move the parent-folder to trash or do a rename there is no event.

I could add all the parent-folders to the watcher, but then i will watch all there childs too.

Is there a better way?:)
Thanks!

**Comment by edouardmercier** [comment]
It seems that the use case depicted in this issue is not covered easily by chokidar: is there a way to detect that one of the directory ancestors is deleted, because, at the current time, with v3.4.2, no event seems to be triggered in that case? It would be very handy.
