### ISSUE TITLE
Incompatibility error on Linux 64-bit

### ISSUE THREAD

**Issue by queirozfcom** [paulmillr/chokidar#460]
After trying to install a package that depends upon chokidar, I got the following error:

```sh
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.11
```

I'm running Linux 64-bit.

**Comment by rhoggSugarcrm** [comment]
I think that's probably deliberate. `fsevents` is a Mac-only module, but because it's optional it won't fail the build when you install `chokidar` on a different platform.

**Comment by es128** [comment]
@rhoggSugarcrm is correct, everything is fine.

**Comment by nicholaschiang** [comment]
Is there any way that we could somehow get rid of that warning when it is expected (e.g. `chokidar` should be able to dynamically build `fsevents` *only* when the user is on MacOS)?

I just got bit by this too (and am trying to clean up my Yarn v2 `yarn install` output):
```
➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed in 0.52s
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed in 0.99s
➤ YN0000: ┌ Link step
➤ YN0062: │ fsevents@patch:fsevents@npm%3A2.1.3#builtin<compat/fsevents>::version=2.1.3&hash=495457 The platform linux is incompatible with this module, building skipped.
➤ YN0062: │ fsevents@patch:fsevents@npm%3A1.2.13#builtin<compat/fsevents>::version=1.2.13&hash=495457 The platform linux is incompatible with this module, building skipped.
➤ YN0000: └ Completed in 1.97s
➤ YN0000: Done with warnings in 3.71s
```
