### ISSUE TITLE
cannot emit any event with using fs.watch

### ISSUE THREAD

**Issue by acrazing** [paulmillr/chokidar#463]
I run test code as follow:

```js
// watcher.js
/**
 * @description
 * @author acrazing
 * @since 2016-04-07 20:13:27
 * @version 1.0.0.0
 */
'use strict';

function chokidar() {
  const chokidar = require('chokidar');
  const watcher = chokidar.watch('./');
  console.log('chokidar watch');
  'add, addDir, change, unlink, unlinkDir, ready, raw, error'.split(', ').forEach((e) => watcher.on(e, function () {
    console.log(e, JSON.stringify(arguments));
    console.log('--------------------------');
  }));
}

function fs() {
  const fs = require('fs');
  console.log('fs watch');
  fs.watch(__dirname, function () {
    console.log(JSON.stringify(arguments));
    console.log('-----------------------');
  })
}


process.argv[2] === 'fs' ? fs() : chokidar();
```

run both command

```bash
node watcher.js
```

and 

```bash
node watcher.js fs
```

will work correctly.

but if change the code `__dirname` to `./`, the `fs.watch` will not work.

AND, `chokidar` doesn't work on centos, which platform doesn't support `fsevents`, and run with `fs.watch`.

the problem is `fs.watch` need absolute path!

**Comment by acrazing** [comment]
with node `v 4.2.6`, or `v 5.6.0`, or `v 5.10.0`

**Comment by es128** [comment]
Chokidar works fine on centos. `fsevents` is only for OS X, it doesn't need to be installed on other platforms.

`fs.watch()` is a node core module, chokidar uses it, it doesn't control it or have any impact on how it treats relative paths.
