### ISSUE TITLE
Not working in guest os of parallels desktop

### ISSUE THREAD

**Issue by YunSun-CN** [paulmillr/chokidar#465]
I use parallels desktop and share my work folder from my osx to fedora(guest). The path seems like to be 
`/media/psf/share`
And I create a symbolic link to work directory in fedora.
`/home/www/mywork -> /media/psf/share`
When I use browsersync which uses chokidar watching files, it seems not working.
However, nodejs and gulp.watch do work.

**Comment by es128** [comment]
You typically need to specify the `usePolling: true` option to watch over network shares.
