### ISSUE TITLE
How to unwatch recursive?

### ISSUE THREAD

**Issue by cakebake** [paulmillr/chokidar#466]
**I am very excited by the module! Thanks for the work!**

I have not yet understood how to remove paths recursive from the watcher. I have tried a lot. For example:

```js
...

const dir = '/absolute/path/to/directory'
const glob = path.join(dir, '**', '*')
watcher.unwatch(dir)
watcher.unwatch(glob)
const watchedPaths = watcher.getWatched()
```

This removes only `dir` and not `glob`, when I observe with `watchedPaths`. Looking forward to your feedback :)

**Comment by es128** [comment]
Do you still get events on those paths that you unwatched? Or you just see them still reflected under `.getWatched()`?

Depending on the situation `.unwatch()` sometimes acts to add ignore filters as opposed to actually turning off watchers, so you wouldn't necessarily see the paths dropped from `.getWatched()`. I understand this might be confusing, it's possible an enhancement could be made to address this.

Either of your `.unwatch()` statements should have worked to suppress any further events under that directory. If that's not the case, it may be a bug, but please provide a better demonstration of how to reproduce it.

**Comment by cakebake** [comment]
Thanks for the fast respond!

Currently I am still testing how do I monitor the files (adding/removing files to/from global watcher, performance with vue.js inside electron renderer process, ......). The events I have not tested until now. I'll do that tonight :) I admit definitely feedback! If the events fire properly, everything is great!

Perhaps it is worth mentioning:

- I´m on linux
- I "foreached" the `watchedPaths` object and called `.unwatch(key)`. All paths +1 sublevel were removed - not recursive, too

**Comment by cakebake** [comment]
So, it fits far everything with the events. The events are not triggered for files inside the parent folder, if the parent folder has been unwatched.

However, if you then add the same parent folder again, no `add` event for its files would be triggered. Because I need this behaviour, currently I remove parent folder AND its files in a big forEach with minimatch´s glob features.

Close this, because it´s not a bug - but a little confusing ;)
