### ISSUE TITLE
NO `ready` event if directory contains a symlink on Windows

### ISSUE THREAD

**Issue by CxRes** [paulmillr/chokidar#469]
Like the title says:

On Windows 10, Chokidar 1.4.3, nodejs 5.7.1 - 5.11.0

**Comment by CxRes** [comment]
A little evolution on this: I do not get `ready` only when the symlink directory does not exist. I am wondering if there is a change in code or is this a node issue?

**Comment by CxRes** [comment]
Has this been fixed? 

Or do you want a new issue filed? 

Because the code specifically ignores the `ENOENT` error even for the non-existant symlink.

**Comment by CxRes** [comment]
@paulmillr Can we please discuss this a bit further. I think the fix is not that hard!

As I understand, Chokidar simply waits for a file/directory to be created before issuing the `ready` event. When the item is a symlink, this becomes a two layered process in a way. Chokidar waits for the symlink; on finding a symlink it waits for the directory. 
IMHO, it makes more sense to wait for the symlink item but if the linked directory does not exist it should send an `error` event as it is most likely that the symlink is dangling for good and needs to be fixed separately. With the current behaviour the user has no idea that the wait for `ready` event is because symlink does not exist or whether the symlink is dangling. 

The other option is for user to check for dangling before adding the item, which seems redundant as Chokidar has this information already.

If this seems like a breaking change perhaps this could be introduced under a flag.

**Comment by paulmillr** [comment]
@CxRes nothing to discuss here. We just need the code to get it fixed. And the test cases.
