### ISSUE TITLE
How to ignore entire subdirectories

### ISSUE THREAD

**Issue by samvv** [paulmillr/chokidar#478]
I know this sounds really stupid but I can't seem to get it working. I want to ignore several subdirectories, using the `ignored`-flag, but everything I tried does not seem to work.

This is my code:

```js
chokidar.watch('some/folder', {
  ignored: ['node_modules/**/*', '.git/**/*']
}).on(...);
```

The above code does not work. It fires `add` and `addDir` events even for the ignored subdirectories. Any way to fix this? I tried variations like `node_modules/` and `.git/`, but to no avail. Yet I feel like I'm missing something really obvious.

**Comment by samvv** [comment]
Never mind, fixed my own issue. Using absolute paths, it works. Though I'm wondering ... is this a bug? The README states that relative paths should work fine, too.

**Comment by es128** [comment]
Yes, relative paths work, but it seems like you're assuming they'll be relative to your match pattern rather than `cwd` or whatever you set `cwd` to be with the option. You also don't need to use globs in a case like this. Something like `ignored: 'some/folder/node_modules'` should work.

**Comment by VladimirAmiorkov** [comment]
I am having the same issue, I want to watch "some/folder" but ignore the "build" subfolder of that directory ("some/folder/build")

```
chokidar.watch('some/folder/', {
  ignored: ['some/folder/build']
}).on(...);
```

Is this possible using chokidar, I have started using this package recently and I am currently learning its possibilities.
