### ISSUE TITLE
watch null ECONNRESET on ftp watcher

### ISSUE THREAD

**Issue by chenko47** [paulmillr/chokidar#479]
I set my folder to watch on ftp folder , and sometime I get this error : 

var watcher = chokidar.watch(ftp_path,{"persistent":true});

> watcher.on('change',function(){
> ...
> })
> watcher.on('error',function(err){
> console.log(err);
> })

I see this error message on console , and the watcher stops : 
> watch null ECONNRESET

I read around that the problem may occur on the remote server, but the listener stop when this errors appears. How can I reset the connection by code ?

**Comment by es128** [comment]
> How can I reset the connection by code ?

Depends on how you established the connection to begin with, but managing your ftp transactions is outside of chokidar's scope.
