### ISSUE TITLE
Watch glob with placeholder in the middle

### ISSUE THREAD

**Issue by apfelbox** [paulmillr/chokidar#484]
Hi,

I want to watch the following glob:
`src/**/Resources/` and I want to be notified if a new directory is added that matches the glob.

I don't care about files / subdirectories contained in the globs, I just want the base directories.

I tried

``` js
chokidar.watch("src/**/Resources/", {ignoreInitial: false})
                .on("addDir",    path => console.log(path))
                .on("unlinkDir", path => console.log(path))
                .on("add",       path => console.log(path));
```

but got nothing (no output).

``` js
glob.sync("src/**/Resources/", (err, dirs) => console.log(dirs))
```

correctly returns the directories.
Is watching for directories not supported or do I have to configure something differently?

**Comment by es128** [comment]
You're looking for subdirectories under `Resources`? Or instances of directories named `Resources`?

Perhaps adding a `*` at the end of your pattern gets you what you want?

**Comment by apfelbox** [comment]
I look for instances of directories named `Resources`, for example:

```
src/A/B/Resources/
src/C/Resources/
src/D/Resources/
```

**Comment by UltCombo** [comment]
Maybe try setting the `{ depth: 0 }` option.

> - `depth` (default: `undefined`). If set, limits how many levels of subdirectories will be traversed.

**Comment by apfelbox** [comment]
Hi @UltCombo, thanks for the suggestion and sorry for the late reply. I just tested it with `depth: 0` but it still doesn't find the directories.

**Comment by apfelbox** [comment]
So, I just tested it with raw events and found some really strange behavior:

Here is my code example:

```js
chokidar.watch("test/**/a", {
    ignoreInitial: false,
})
    .on("addDir", (path) => console.log("add", path))
    .on("unlinkDir", (path) => console.log("del", path))
    .on("raw", (event, path, details) => console.log("raw", event, path, details));
```

### watch without trailing slash: `test/**/a`

Everything works without a problem. `ignoreInitial: false` works, adding and removing works.


### watch with a trailing slash: `test/**/a/`

Initial `addDir` are events not thrown, the following events are all from `raw` events:

* Adding a directory throws correct events with type `directory` and event `'unknown'`
* Removing a directory throws correct events with type `directory` and event `'deleted'`, but no `unlinkDir` event

I got a strange case earlier, where the initial event was a `deleted` event, but I can't reproduce it now.


Tested on OSX 10.11.6 with node 6.2.2 and chokidar 1.6.0

I have my fix now, but maybe this is something that needs to be added to the docs or need to be fixed?
