### ISSUE TITLE
simple support Q => adding file that is already being watched

### ISSUE THREAD

**Issue by ORESoftware** [paulmillr/chokidar#485]
I am wondering if watcher.addFile is called and the file is already being watched by that watcher, if this library takes care of this, and doesn't add duplicate data.

For example, we do this first:

```js
var watcher = chokidar.watch('a/b*.js', {});

watcher.add('a/bx.js');
```

if the first call covers this new file (bx.js), because it already existed, how does this library handle it? Do I need to handle it, or does the library prevent duplication like this? Thanks!

**Comment by paulmillr** [comment]
The library currently handles it. No need to do a check on your side.
