### ISSUE TITLE
Add Watchman option to chokidar

### ISSUE THREAD

**Issue by jonricaurte** [paulmillr/chokidar#486]
Hi,

After looking around different repos, there doesn't seem to be any movement on adding a watchman option to chokidar as was discussed here:

https://github.com/facebook/react-native/issues/628

and here:

https://github.com/ember-cli/ember-cli/issues/4503

Since chokidar supports symlinking, and sane does not (https://github.com/amasad/sane/issues/42), it would be nice to have an option to use watchman and if not fall back to chokidar. Also chokidar seems to perform better than sane.

Thanks.

**Comment by es128** [comment]
It's a big job to add a new underlying watch mode. As much as I'd love to see it happen, it's not where my time and attention is at this point.

PR welcome.

**Comment by jonricaurte** [comment]
Thanks for the quick response.
