### ISSUE TITLE
ignored option as an array instead of single regex or string

### ISSUE THREAD

**Issue by ORESoftware** [paulmillr/chokidar#488]
Hi Paul

Why not have the ignored option of the options object be an array property instead of a single regex or string. I would like to ignore changes to .txt and .log, so AFAICT the easiest way for me to do that as an end user would be:

`ignored: ['.txt', '.log']`

but my guess is that, given the docs, I need to do:

`ignored: /(\.txt|\.log)$/`

this is kind of tough to work with, it would be a lot easier for end user to be able to use array with strings.

am I off base?

**Comment by es128** [comment]
What you're asking for is already supported, and is described in the readme a little further down. To make your particular example work, it should look more like `ignored: ['*.txt', '*.log']` to match files with those extensions as opposed to a file whose entire filename is `.txt`.

See https://github.com/paulmillr/chokidar#path-filtering and https://github.com/es128/anymatch

**Comment by ORESoftware** [comment]
@es128 thanks, trying it out right now
