### ISSUE TITLE
watcher.getWatched() - watched paths format

### ISSUE THREAD

**Issue by ORESoftware** [paulmillr/chokidar#491]
Watched paths format is currently a nested object, but I am looking for a straight list of paths as this is much more easy to consume. Is there a way to get just get a straight list of all the paths that are currently being watched? The nested object is hard to work with. Thanks!

**Comment by ORESoftware** [comment]
alternatively,  if you could verify the right way to walk the object that would be helpful also.

I have this:

```js
	watcher.on('ready', () => {
					
					const watched = watcher.getWatched();
				
					(function A(watched) {
						Object.keys(watched).forEach(function (key) {
							const array = watched[key];
							array.forEach(function (p) {
								const temp = path.resolve(key + '/' + p);
								pathHash[temp] = {
									transpile: transpile
								}
							});

						});
					})(watched);

				});
```

but this is not complete yet, I believe I need a to complete the recursive call, by calling A again, but I am not sure under which condition to recurse.

**Comment by es128** [comment]
The object does not do several levels of object nesting, so you don't have to worry about any further recursion. It's just directory paths as object keys and arrays of entry names for their contents. Not that complex.

Your example code seems fine, although if I'm nitpicking I'd say a more "proper" way to do `path.resolve(key + '/' + p)` would be `path.join(key, p)`, and also I don't see that the IIFE wrapper is necessary there, just adds some cruft. Also, if you want to include only files and filter out directories, you could add something like `if (watched[temp]) return;` before adding the entry to `pathHash`.

**Comment by ORESoftware** [comment]
thanks that will help!

**Comment by eoinmurray** [comment]
We have made a small library to format the output of `getWatched` into nested form 

https://github.com/rinocloud/chokidar-nest/

It might be of use...

**Comment by audunolsen** [comment]
Old thread, but I ran into same situation wanting a flat array. Did the following:

```
function watchedFlatArr(watched) {
    
    return Object.entries(watched).map(([path, basenames]) =>
        basenames.map(name => `${path}/${name}`);    
    ).flat();
    
}
```

**Comment by sersanchus** [comment]
Thanks @audunolsen, I'm using your version right now. Super.

> Old thread, but I ran into same situation wanting a flat array. Did the following:
> 
> ```
> function watchedFlatArr(watched) {
>     
>     return Object.entries(watched).map(([path, basenames]) =>
>         basenames.map(name => `${path}/${name}`);    
>     ).flat();
>     
> }
> ```
