### ISSUE TITLE
Ignoring directories/files

### ISSUE THREAD

**Issue by somebody1234** [paulmillr/chokidar#492]
How would I specify directories/files to ignore? (i.e. how do the regexes need to be modified for only directories/only files?)

**Comment by zanona** [comment]
Have a look at #488
I am using something like

```js
   { ignored: ['node_modules', 'bower_components', 'build'] }
```

**Comment by es128** [comment]
@somebody1234 make sure whatever you're putting in matches the paths you want matched, and doesn't match others. You have lots of options for how you do that (matching is accomplished with [anymatch](https://github.com/es128/anymatch), take a look there for examples of the different types of patterns you can use). 

Note that in many circumstances, ignoring a directory inherently means ignoring its children as well. You may need to be more specific about what you're trying to accomplish if you're looking for more specific feedback.
