### ISSUE TITLE
weird stuff appended to changed file path

### ISSUE THREAD

**Issue by ORESoftware** [paulmillr/chokidar#493]
I get this stuff

```
Raw event info: unknown /Users/amills/WebstormProjects/oresoftware/suman/test/simple-tests/one-1.js___jb_tmp___ { path: '/Users/amills/WebstormProjects/oresoftware/suman/test/simple-tests/one-1.js___jb_tmp___',
  event: 'unknown',
  type: 'file',
  changes: { inode: false, finder: false, access: false, xattrs: false },
  flags: 65792 } 


File /Users/amills/WebstormProjects/oresoftware/suman/test/simple-tests/one-1.js___jb_tmp___ has been added
```

this unfortunately be messin' up my algorithm - I using the file path value as a key in a hash, but for some reason that extra stuff ```___jb_tmp___``` is being appended to it - what's the deal with that? Is there a way to get the actual straight filepath? Is this an issue with my system perhaps?

**Comment by ORESoftware** [comment]
jb might be jetbrains (My guess) so maybe my IDE is doing this crap :/

**Comment by ORESoftware** [comment]
looks like it:

http://stackoverflow.com/questions/23271895/temporary-jb-old-file-in-phpstorm-and-webstorm-causing-errors

**Comment by es128** [comment]
Yes, editors often don't play nicely with file watchers, it's something we've dealt with before.

Good news is that it looks like we should be able to add that temp file pattern to be ignored by default when `atomic: true` at https://github.com/paulmillr/chokidar/blob/master/index.js#L328

If you can observe this issue consistently, try locally adding `|___jb_tmp___$` to the end of that regex and let us know whether it resolved the problem.

**Comment by ORESoftware** [comment]
I seem to have solved it by always replacing '___jb_tmp___' with an empty string.

my understanding is that the temp files created by JetBrains (in my case Webstorm) are the old versions of the file, so the actual filepath always references the newest version which is what we want anyway.
