### ISSUE TITLE
v1.5.1 npm package missing README.md

### ISSUE THREAD

**Issue by silverwind** [paulmillr/chokidar#494]
Probably something gone wrong during publish:
````
npm WARN package.json chokidar@1.5.1 No README data
````
Interestingly, https://registry.npmjs.org/chokidar/-/chokidar-1.5.1.tgz contains CHANGELOG.md which is in `.npmignore` (which you can remove, by the way, as CHANGELOG.md is not in package.json's `files`).

**Comment by es128** [comment]
Hmm, I just published 1.5.2 expecting it to resolve this, but the same thing appears to have happened again. Bug in npm maybe?

**Comment by es128** [comment]
Although I have not been able to reproduce the `No README data` warning. What version of npm were you using when you saw that?

**Comment by es128** [comment]
The inclusion of changelog is actually expected behavior. See https://docs.npmjs.com/files/package.json#files

```
Certain files are always included, regardless of settings:

package.json
README (and its variants)
CHANGELOG (and its variants)
LICENSE / LICENCE


Conversely, some files are always ignored:

.git
CVS
.svn
.hg
.lock-wscript
.wafpickle-N
*.swp
.DS_Store
._*
npm-debug.log
```

The readme data is showing on npm's site... don't think there's a problem there.

Closing this for now, but if you still think there's a problem please let me know.

**Comment by silverwind** [comment]
3.8.9. The missing README should be quite obvious in above tgz, though :)

**Comment by silverwind** [comment]
> Bug in npm maybe?

I heard there's a unresolved quirk where random files are missing from published packages. Never occured to myself though.

**Comment by es128** [comment]
In 1.5.2 the readme file is still missing from the tarball, but after you `npm i chokidar` all the readme data is there embedded in the package.json. Seems to be normal, although I'm not deeply familiar with all the internals of how npm treats this stuff.

Are you still encountering a problem when installing 1.5.2?

**Comment by silverwind** [comment]
Can't reproduce the warning right now, but the situation is kind of complicated with npm triggered from an git hook, I can't exactly say right now that the npm in was really the version mentioned. A local `npm i chokidar` still produces a module folder with no README, and looking through the tgz files, the issue seems to have started with 1.5.0 (1.4.3 has a README in the tgz).

Anyways, I think this might be related: https://github.com/npm/npm/issues/5082.
