### ISSUE TITLE
watching file over network...

### ISSUE THREAD

**Issue by tamaker** [paulmillr/chokidar#495]
Im working on a project where I have node running on a linux machine, and files I want to watch running on another linux machine, both on same network... 

When I have used chokidar in the past with local files (files on same machine) it works flawlessly... and I've used a line like this:

fs.watch("/myfolder/mypath/myfile.json", function(event, fileName){....

when the file is across a network, if I can access it from my browser using simply file://server/foldername/path/file.ext, what would my fs.watch line look like exactly?   I've tried reversing the slashes, and still get ENOENT error that seems to mean the file path is bad / not valid.

**Comment by es128** [comment]
Add the `usePolling: true` option
