### ISSUE TITLE
ENV variable override for polling

### ISSUE THREAD

**Issue by yaycmyk** [paulmillr/chokidar#496]
In many cases, chokidar is used several layers down in a project... so it's difficult (if possible at all) to make the necessary adjustment and switch to polling. It would be great if an env variable override was added to help with this issue. Perhaps something like `CHOKIDAR_USEPOLLING=true`?

**Comment by es128** [comment]
Sounds like a good idea, although I worry a bit that people will end up wanting to control a bunch of other settings this way as well.

PR welcome.
