### ISSUE TITLE
[Recommendation] Drop support for old Node versions, add "engines" package.json field

### ISSUE THREAD

**Issue by yaycmyk** [paulmillr/chokidar#498]
0.10 in particular is quite an old version at this point and now that 4.x is the official LTS branch, I think support of it (and potentially 0.12) can be dropped without too much friction.

**Comment by paulmillr** [comment]
What advantages would we have in dropping 0.10? I'm all for using newest nodes, but we should not limit people unless there are some cool new features that are only available in 4.x+

**Comment by yaycmyk** [comment]
That's fair. The benefit would mostly be for using ES6 syntax in this library to help avoid bugs thanks to some of the newer language constructs like let/const. There's a lot of new functionality of course, but I'm not sure if any of it is strictly relevant to what's being done in chokidar.

**Comment by paulmillr** [comment]
Think we can accomplish this with eslint either.

**Comment by es128** [comment]
> can be dropped without too much friction.

:-1: I strongly disagree. Plenty of people locked in to older versions for a variety of reasons, and not nearly enough to be gained to consider this at this point imo.
