### ISSUE TITLE
toggling between watch mode and non-watch mode

### ISSUE THREAD

**Issue by ORESoftware** [paulmillr/chokidar#500]
When I call `watcher.close()` or `watcher.unwatch('**/*.js')`, I can't seem to start watching files again.

Is there some special step I need to take if I unwatch all files and then decide to watch some files again?

Any idea why I wouldn't be able to start watching files again after unwatching them?

thanks!

**Comment by ORESoftware** [comment]
I also have this output:

                                   ```js
   if (watcher) {
				// Stop watching.
				console.log('\n\n => Watched paths before "unwatch":', watcher.getWatched());
				watcher.unwatch('**/*.js');
				console.log('\n\n => Watched paths after "unwatch":', watcher.getWatched());
			}

```
```

 => Watched paths before "unwatch": { '/Users/Olegzandr/WebstormProjects/poolio': [ 'test' ],
  '/Users/Olegzandr/WebstormProjects/poolio/test': 
   [ '_suman',
     'fixtures',
     'test-canonical.js',
     'test-hook-params.js',
     'test-poolio-w-suman.js',
     'test-repeated-inits.js',
     'test.js' ],
  '/Users/Olegzandr/WebstormProjects/poolio/test/_suman': 
   [ '.readme',
     'examples',
     'logs',
     'suman.globals.js',
     'suman.hooks.js',
     'suman.ioc.js',
     'suman.once.js',
     'suman.order.js',
     'suman.reporters.js' ],
  '/Users/Olegzandr/WebstormProjects/poolio/test/fixtures': [ 'sample-file.js', 'sample-file1.js', 'worker1.js' ],
  '/Users/Olegzandr/WebstormProjects/poolio/test/_suman/examples': [ 'one.js', 'three.js', 'two.js' ],
  '/Users/Olegzandr/WebstormProjects/poolio/test/_suman/logs': [] }


 => Watched paths after "unwatch": { '/Users/Olegzandr/WebstormProjects/poolio': [ 'test' ],
  '/Users/Olegzandr/WebstormProjects/poolio/test': 
   [ '_suman',
     'fixtures',
     'test-canonical.js',
     'test-hook-params.js',
     'test-poolio-w-suman.js',
     'test-repeated-inits.js',
     'test.js' ],
  '/Users/Olegzandr/WebstormProjects/poolio/test/_suman': 
   [ '.readme',
     'examples',
     'logs',
     'suman.globals.js',
     'suman.hooks.js',
     'suman.ioc.js',
     'suman.once.js',
     'suman.order.js',
     'suman.reporters.js' ],
  '/Users/Olegzandr/WebstormProjects/poolio/test/fixtures': [ 'sample-file.js', 'sample-file1.js', 'worker1.js' ],
  '/Users/Olegzandr/WebstormProjects/poolio/test/_suman/examples': [ 'one.js', 'three.js', 'two.js' ],
  '/Users/Olegzandr/WebstormProjects/poolio/test/_suman/logs': [] }

```

**Comment by es128** [comment]
When you `unwatch` a glob pattern as in the example you provided, the actual impact is like adding a post-facto entry to the `ignored` option. I'm not sure I can think of a good way to un-unwatch in that scenario (i.e. surgically remove the part of the ignore that conflicts with the new request to watch). I'm willing to consider it a bug nonetheless.

This also explains why the `.getWatched()` output hasn't changed. It's still watching all that stuff, just filtering the events based on what you've decided to start ignoring.

On the other hand, if you were to `watcher.unwatch('/Users/Olegzandr/WebstormProjects/poolio')` it would actually tear down the underlying watch and clean up after itself, and I'd think re-watching would work.

But if you use `watcher.close()` and create a new instance each time then I don't see why you'd still be having this problem.

That said, my primary recommendation would be to reconsider whether you actually need to pause/resume watching in the way you're attempting. Can't you just make decisions in your own code about when to take action in response to events or not?

**Comment by ORESoftware** [comment]
Thanks for the info - I am using chokidar as part of a library, not an end-application. Basically I am working on Suman, a test runner, and on a file-save I want to execute and/or transpile the test file that changed. I want to give the users of my lib the ability to watch and un-watch files/folders, and using globs would be convenient, but I can manually unwatch each file path, if that is the only way to get this to work. 
I could manually ignore events for filepaths that should be unwatched, but really I think it would be ideal if chokidar managed this internally. I'd also rather not create and destroy instances of a watcher to get that behavior, it would be best to use the same watcher instance I think.

**Comment by es128** [comment]
You might still have similar problems if you try to unwatch file paths that are a subset of what chokidar has set watcher instances on.

I should mention that chokidar does try to take measures to address your use case. If you unwatch, then set to re-watch the exact same glob pattern, it should work (https://github.com/paulmillr/chokidar/blob/master/index.js#L596-L60). It's when dealing with subsets and intersections of globs that it gets messy. 

> I think it would be ideal if chokidar managed this internally

The problem with doing it in the way I think you've described is that you're often not freeing any resources, you're actually adding processing overhead. So I think you have to be pretty careful about your approach to really accomplish your aims here.

Based on what you've described, I don't think `unwatch` is the best approach. I think you should keep a toggle on your side of whether certain paths should be executed at any given time and leave the watch implementation simpler.

**Comment by ORESoftware** [comment]
Ok no prob, I will see if unwatching / re-watching specific file path(s) works, if not I will do that bookkeeping that you mention, the performance effect in my lib won't matter, just feels like a bit of extra work :)

**Comment by ORESoftware** [comment]
:( Bummer TBH it seems you guys don't have it quite right

I am calling unwatch on specific filepaths in a loop:

```
 => The following file path is being unwatched => /Users/amills/WebstormProjects/oresoftware/poolio/test
 => The following file path is being unwatched => /Users/amills/WebstormProjects/oresoftware/poolio/test/_suman
 => The following file path is being unwatched => /Users/amills/WebstormProjects/oresoftware/poolio/test/fixtures
 => The following file path is being unwatched => /Users/amills/WebstormProjects/oresoftware/poolio/test/test-canonical.js
 => The following file path is being unwatched => /Users/amills/WebstormProjects/oresoftware/poolio/test/test-hook-params.js
 => The following file path is being unwatched => /Users/amills/WebstormProjects/oresoftware/poolio/test/test-poolio-w-suman.js
 => The following file path is being unwatched => /Users/amills/WebstormProjects/oresoftware/poolio/test/test-repeated-inits.js
 => The following file path is being unwatched => /Users/amills/WebstormProjects/oresoftware/poolio/test/test.js
 => The following file path is being unwatched => /Users/amills/WebstormProjects/oresoftware/poolio/test/_suman/.readme
 => The following file path is being unwatched => /Users/amills/WebstormProjects/oresoftware/poolio/test/_suman/examples
 => The following file path is being unwatched => /Users/amills/WebstormProjects/oresoftware/poolio/test/_suman/logs
 => The following file path is being unwatched => /Users/amills/WebstormProjects/oresoftware/poolio/test/_suman/suman.globals.js
 => The following file path is being unwatched => /Users/amills/WebstormProjects/oresoftware/poolio/test/_suman/suman.hooks.js
 => The following file path is being unwatched => /Users/amills/WebstormProjects/oresoftware/poolio/test/_suman/suman.ioc.js
 => The following file path is being unwatched => /Users/amills/WebstormProjects/oresoftware/poolio/test/_suman/suman.once.js
 => The following file path is being unwatched => /Users/amills/WebstormProjects/oresoftware/poolio/test/_suman/suman.order.js
 => The following file path is being unwatched => /Users/amills/WebstormProjects/oresoftware/poolio/test/_suman/suman.reporters.js
 => The following file path is being unwatched => /Users/amills/WebstormProjects/oresoftware/poolio/test/fixtures/sample-file.js
 => The following file path is being unwatched => /Users/amills/WebstormProjects/oresoftware/poolio/test/fixtures/sample-file1.js
 => The following file path is being unwatched => /Users/amills/WebstormProjects/oresoftware/poolio/test/fixtures/worker1.js
 => The following file path is being unwatched => /Users/amills/WebstormProjects/oresoftware/poolio/test/_suman/examples/one.js
 => The following file path is being unwatched => /Users/amills/WebstormProjects/oresoftware/poolio/test/_suman/examples/three.js
 => The following file path is being unwatched => /Users/amills/WebstormProjects/oresoftware/poolio/test/_suman/examples/two.js
 => The following file path is being unwatched => /Users/amills/WebstormProjects/oresoftware/poolio/test/_suman/logs/.readme

```

but after calling unwatch on these, they are still listed:

```
 => Watched paths after "unwatch": { '/Users/amills/WebstormProjects/oresoftware/poolio': [],
  '/Users/amills/WebstormProjects/oresoftware/poolio/test': 
   [ '_suman',
     'fixtures',
     'test-canonical.js',
     'test-hook-params.js',
     'test-poolio-w-suman.js',
     'test-repeated-inits.js',
     'test.js' ],
  '/Users/amills/WebstormProjects/oresoftware/poolio/test/_suman': 
   [ '.readme',
     'examples',
     'logs',
     'suman.globals.js',
     'suman.hooks.js',
     'suman.ioc.js',
     'suman.once.js',
     'suman.order.js',
     'suman.reporters.js' ],
  '/Users/amills/WebstormProjects/oresoftware/poolio/test/fixtures': [ 'sample-file.js', 'sample-file1.js', 'worker1.js' ],
  '/Users/amills/WebstormProjects/oresoftware/poolio/test/_suman/examples': [ 'one.js', 'three.js', 'two.js' ],
  '/Users/amills/WebstormProjects/oresoftware/poolio/test/_suman/logs': [ '.readme' ] }

```
but even though they are still listed, and even after calling watch on each of them again, they are not re-watched. Major bummer, will do a workaround for now.

**Comment by ORESoftware** [comment]
Ok, so this does work however - if I want to "unwatch" files, I run

```
watcher.close();
watcher = null;

```
unfortunately, this doesn't give me or the user the option to unwatch specific files, just all the current files. Then when I want to start watching again, I create a new watcher instance and start over. I don't find this ideal, but this is what is working for me for now.

**Comment by alolis** [comment]
Hello,

I am noticing weird behavior when unwatching a specific file as well but a little but different than the one @ORESoftware reported. In my case, with latest chokidar from npm, after I unwatch a specific file, I immediately perform a file system move but the `change` event is being triggered, although I expect the event not to.

The weird part is that if I call `getWatched` before I make the move, sometimes the file is included there (after i call unwatch) and some times it does not, but the behavior stays the same. Another thing i notice is that, in both cases the file which i ignored is listed under the `_ignoredPaths`.

Is there a latest update regarding unwatch/watch or this still work in progress?
