### ISSUE TITLE
high memory usage when file number grow 

### ISSUE THREAD

**Issue by amtrek** [paulmillr/chokidar#501]
Chokidar appears to be hauling CPU usage and memory when the total file number in the watching directory grows. It's repeatable, and when watching files in the directory were deleted, the memory usage dropped.

**Comment by es128** [comment]
This depends on the watch mode being used. `usePolling: true` is a heavy consumer of system resources, which `fsevents` on OS X is much more efficient. Either way, when you ask your computer to do more work, including watching files, it causes the computer to do more work.

If you have any specific performance improvements to suggest, feel free to elaborate on the details and/or PR welcome.
