### ISSUE TITLE
Not supported: fsevents module

### ISSUE THREAD

**Issue by janbiasi** [paulmillr/chokidar#506]
Just for your information ...

`npm WARN optional Skipping failed optional dependency /chokidar/fsevents:`
`npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.12`

I am using: 
* OS: **Windows 10**
* Node.js: **v4.2.2**
* NPM: **v3.8.9**

**Comment by paulmillr** [comment]
fsevents is an macos-only module

**Comment by janbiasi** [comment]
First off thanks for your answer. But isn't there another way to include fsevents which won't output the incompatibility with Windows everytime you install a new module via NPM? Thanks in advice!

**Comment by paulmillr** [comment]
Not that i'm aware of.

**Comment by es128** [comment]
@janbiasi you could try `npm install --no-optional`. Another potential workaround is using a shrinkwrap file which was generated on a non-OS X system.

But in any case this is controlled by the npm project. Feel free to take it up with them at https://github.com/npm/npm/issues

**Comment by janbiasi** [comment]
Thanks @es128, the flag `--no-optional` works perfect. I also took this issue over to the NPM issue tracker, available under  https://github.com/npm/npm/issues/13267.
