### ISSUE TITLE
Windows: Chokidar not executing command after changes detected

### ISSUE THREAD

**Issue by tw3080** [paulmillr/chokidar#508]
Hey, I'm trying to use Chokidar in an NPM build system. I don't have any issues getting it to watch files on my mac,  but can't seem to get it to work on Windows, even with the exact same repository. Here's an example of a repo I've tried (which does work on my mac, like I said): 

https://github.com/tw3080/Taylor

Here's part of the scripts section of the package.json file in that repo:
`"build": "npm run build:css",`
 `"watch": "npm run watch:css",`
 `"build:css": "npm run clean:css && lessc --source-map less/style.less css/style.css",`
 `"watch:css": "npm run build:css && chokidar less/style.less -c 'npm run build:css'",`
 `"clean:css": "rm -f css/style.css css/style.css.map"`

On mac, when I run 'watch' everything works fine, and changes are detected and 'npm run build:css' is executed afterwards, and changes are made to my files. On Windows, however, here's what I see after I run 'watch':

![image](https://cloud.githubusercontent.com/assets/18711238/16700162/4d3fe742-450d-11e6-8387-fdbf852dde20.png)

So, for some reason, on Windows, Chokidar is also trying to watch "run" and "build:css" (which are just part of the next command), in addition to "less/style.less" (the only file I want it to watch). Changes are detected when I edit the .less file, but then I get an error when it tries to move forward and run build:css. It seems to me, then, that it's getting confused by my command or something? On my mac, it only watches "less/style.less" and executes "npm run build:css" afterwards accordingly.

`"watch:css": "npm run build:css && chokidar less/style.less -c 'npm run build:css'"`
Is there something wrong with my syntax here? I can't figure it out :( I don't understand why the same files work fine on mac, but not on Windows. I'm running the same version of node and npm on both computers. I also tried just straight up re-installing node/npm and making sure they're up-to-date, which did nothing. Can anyone help?

Also, I'm super new to using node/npm/chokidar, so I'm sorry if my question is poorly worded or I seem clueless. Thanks!

Edit: I realize this could probably be an issue with node/npm and windows itself, but I just wanted to ask here first to see if anyone has any ideas.

**Comment by es128** [comment]
At a glance it looks like the problem may be the `&&` syntax you're using to set up 2 commands at once. Afaik that's a *nix/bash thing, not something that's available in the windows cmd prompt. Perhaps it would work if you used something like cygwin.

**Comment by tw3080** [comment]
I guess I forgot to mention that I'm actually using bash, not cmd prompt. Thanks for your response, though. I closed this because it seemed more appropriate to post it on NPM's issues page, but I haven't gotten a response there. I guess it could also be something to do with bash, I dunno. Still haven't figured anything out.

**Comment by es128** [comment]
Does it work with each command separately? Does it work to run them together like that if you just enter it directly into the prompt the same way?
