### ISSUE TITLE
Not compatible with your operating system or architecture

### ISSUE THREAD

**Issue by Soolan** [paulmillr/chokidar#510]
I got the following error when I try to install any package:
npm WARN optional Skipping failed optional dependency /karma/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.13

I'm using Ubuntu on a VM. Is there any way to get rid of them? 
Thanks for your time.

**Comment by paulmillr** [comment]
that's alright. it's **optional dependency**.

**Comment by es128** [comment]
> Is there any way to get rid of them? 

Use `npm install --no-optional`

**Comment by Soolan** [comment]
Cheers
