### ISSUE TITLE
On add event fire two times

### ISSUE THREAD

**Issue by AlessandroMinoccheri** [paulmillr/chokidar#511]
Good morning,
I would like to know if there is a way to fire eventi ony one times, I have a script that import file into a directory, I watch that directory when a file is added, if so I call a script. 
Sometimes seems that when is added a file the event add fire two times, I would like that on add file the script is called only one time. It's a bug or not? Is there a way to fix it?
My script:

```
var chokidar = require('chokidar');
var sys = require('sys')
var exec = require('child_process').exec;

var folder = process.argv[2];
var watcher = chokidar.watch('tmp/xml/' + folder + '/', {ignored: /^\./, persistent: true});
watcher
  .on('add', function(path) {
    var filenameArr = path.split('/');
    filename = folder + '/' + filenameArr[filenameArr.length - 1];

    function puts(error, stdout, stderr) { sys.puts(stdout) }
    exec('bin/cake manager readXmlAndSave ' + filename, puts);
})
```

**Comment by es128** [comment]
It happens sometimes for various reasons including editors using atomic save methods and other stuff happening at the lower-level file watching methods. Chokidar tries to suppress duplicate events, but there are some circumstances where it can't, and some where the two events you're observing are legit.

If you suspect chokidar is doing something wrong, please add a listener to the `raw` event to log what gets sent there at the time you observe the issue and report back your findings along with details like chokidar version, node version, and OS.

In the meantime, you could implement some form of debounce or throttling to prevent your `exec` from firing off too often.

Closing this issue for now, but will reopen if you provide more evidence that merits further investigation.
