### ISSUE TITLE
Inconsistencies between "ignored" and anymatch

### ISSUE THREAD

**Issue by kafoso** [paulmillr/chokidar#512]
**Problem:**

Some glob patterns are not matched by [`anymatch`](https://www.npmjs.com/package/anymatch), but will be matched in `chokidar`.

```javascript
var anymatch = require('anymatch'); // Version: ^1.3.0, same as chokidar

anymatch(['node_modules'], "node_modules/foo/bar"); // => false
anymatch(['node_modules/**'], "node_modules/foo/bar"); // => true
```

According to the documentation and [zanona](https://github.com/zanona)'s example in #492, the following should work in `chokidar`:

```javascript
{ ignored: ['node_modules', 'bower_components', 'build'] }
```

How come these matches "magically work" in `chokidar`?

I have made a repository illustrating the problem in detail: https://github.com/kafoso/chokidar-anymatch-inconsistencies

**Context:**

I'm writing an SSH2 SFTP synchronization tool, in which I'm using `chokidar` because it blows other similar tools (e.g. [watch](https://github.com/mikeal/watch), [grunt-este-watch](https://www.npmjs.com/package/grunt-este-watch) and [grunt-contrib-watch](https://www.npmjs.com/package/grunt-contrib-watch)) straight out of the water.

I need means of synchronizing files without the involvement of `chokidar`. I'm using the very same arrays (and thus glob patterns) as being provided to `chokidar` in the `ignored` option. I'm also using the same version of `anymatch` ([`^1.3.0`](https://github.com/es128/anymatch/releases/tag/1.3.0)). However, they have different behaviors.

**Comment by es128** [comment]
Because chokidar presumes that if you provide it a directory name (not a glob pattern) you intend to ignore that entire tree under it. It effectively adds the `/**` for you.

Anymatch is doing a straight string comparison on non-globs.

If you want matching behavior, you can do the same before providing your user input to anymatch. Chokidar's code for doing it is at https://github.com/paulmillr/chokidar/blob/57cf3a7/index.js#L356-L364

**Comment by kafoso** [comment]
Thanks for the feedback and suggested answer.

I'll look into using the `FSWatcher.prototype._isIgnored` function.

**Comment by ivan-kleshnin** [comment]
Anymatch ignore pattern is `"!xxx"` (exclamation mark prefix). Chokidar uses `ignore` option. 
It would be great if this was somehow unified. If Chokidar sticks to Anymatch API it'll be logical to drop `ignore` option and require to include ignore patterns in the same array:

Migration guide then:

```js
Chokidar.watch(includeMasks, {ignored: excludeMasks})
// ->
Chokidar.watch(includeMasks.concat(excludeMasks.map(x => "!" + x))
// --- and basic API is --
Chokidar.watch(allMasks)
```
