### ISSUE TITLE
awaitWriteFinish not working

### ISSUE THREAD

**Issue by super-ienien** [paulmillr/chokidar#513]
Hi,

I'm experiencing troubles with awaitWriteFinish option.

I'm using chokidar to watch all events in a directory containing some subdirectories : 

When i replace a file in a subdirectory via ftp. The 'change' or 'add' event is fired immediatly and multiple times until the file is completly written. Even with awaitWriteFinish set to true : 

`watcher = Chokidar.watch('path to my directory', {depth: 2, awaitWriteFinish: true})
            .on('all', watcherEventHandler)
            .on('error', watcherErrorHandler);`

It's very anoying.

Any idea of what could be wrong ?

in the meanwhile i added this to the 'change' and 'add' handlers : 

`function _awaitWriteFinish (path, cb)
{
    if (_awf.hasOwnProperty(path))
    {
        clearTimeout(_awf[path]);
    }
    _awf[path] = setTimeout(function ()
    {
        delete _awf[path];
        cb();
    }
    , 2000);
}
const _awf = {};`

it does the job but chokidar should do this directly

Thanks

**Comment by es128** [comment]
Add a listener for the `ready` event, and possibly wait until after it's emitted before you bind the listener for the `all` event. 

May be related to #458

**Comment by super-ienien** [comment]
Ok it works. Should i close this issue? I think this should be added to the doc.
