### ISSUE TITLE
Limit number of file watched

### ISSUE THREAD

**Issue by AlessandroMinoccheri** [paulmillr/chokidar#515]
Good morning, I would like to know if there is a way to limit number of watched file or something else because if my script wait for "added file" and in a second the system add 300 files, the server can crash.
Is there a way to limit the number of files watched?

My script:

```  
var chokidar = require('chokidar');
var sys = require('sys')
var exec = require('child_process').exec;

var folder = process.argv[2];
var watcher = chokidar.watch('tmp/xml/' + folder + '/', {ignored: /^\./, persistent: true});
watcher
  .on('add', function(path) {
    var filenameArr = path.split('/');
    filename = folder + '/' + filenameArr[filenameArr.length - 1];

    function puts(error, stdout, stderr) { sys.puts(stdout) }
    exec('bin/cake manager readXmlAndSave ' + filename, puts);
})


```

**Comment by es128** [comment]
You could write a function for the `ignored` option that causes chokidar to ignore anything past a certain number of watched files (which you can inspect with the `getWatched` method).

**Comment by AlessandroMinoccheri** [comment]
Can you please make a little example because I don't understand how to do It if is possible. 
Thanks

**Comment by AlessandroMinoccheri** [comment]
I think that the problem is different I need not to ignore but to wait, for example I would like that the max number of file read at the same time is 10. The others file wait until another file is closed.
Is possible?

**Comment by es128** [comment]
Sounds like what you want is to throttle or debounce your `exec` call so you don't have too many running at once.

See https://lodash.com/docs#throttle and https://lodash.com/docs#debounce
