### ISSUE TITLE
How to disable warning message?

### ISSUE THREAD

**Issue by andyl** [paulmillr/chokidar#517]
During the npm installation I am getting the following errors:

    npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
    npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14

This appears *every time* I run npm install.  How do I disable this useless warning message?

chokidar 1.6.0 | ubuntu 16.04 | npm 3.10.3

**Comment by es128** [comment]
`npm install --no-optional`
