### ISSUE TITLE
Add environment support for configuring the poll interval

### ISSUE THREAD

**Issue by langri-sha** [paulmillr/chokidar#518]
Currently, `CHOKIDAR_USEPOLLING` can be set to either 0, 1 or an arbitrary value. Would it make sense to use values greater than 1 to configure the desired polling interval (or introduce another flag)? 

This would be immensely useful for environments where resources may be scarce, say a Docker container.

**Comment by es128** [comment]
Probably its own flag for cleanliness. `CHOKIDAR_POLLINTERVAL` maybe.

PR welcome.
