### ISSUE TITLE
How about the `rename` event?

### ISSUE THREAD

**Issue by lichenhao** [paulmillr/chokidar#520]
Now the rename fired unlink and add task queue, but how about call that rename? It's more difficult but very friendly

**Comment by paulmillr** [comment]
I'm not open to the idea — hard to track this consistently on different platforms. You can emulate this  on your own. simply make a queue that listens to add / unlink events.

**Comment by ryanblock** [comment]
Hello! @paulmillr: I'm wondering if your feelings on this have changed at all?

Related, I'm a bit confused by the feedback above. If it's hard to track consistently, wouldn't it be inadvisable to emulate it on your own?

Alternately, if it is indeed advisable to emulate `rename` events on one's own, what are the various platform considerations one would need to take into account to do so effectively?

**Comment by ryanblock** [comment]
Sorry, I see #303 is probably the canonical thread for this!
