### ISSUE TITLE
add triggers on listener creation

### ISSUE THREAD

**Issue by pthieu** [paulmillr/chokidar#523]
Wrote some pretty simple code to check functionality, looks like the moment `add listener` is instantiated, it triggers the `add` event if file is already there (file was copied to path before code was run). Is this a feature?

```
var chokidar = require('chokidar');

var testJson = '/path/to/file.json';

  // Initialize watcher.
  var watcher = chokidar.watch(testJson, {
    ignored: /[\/\\]\./,
    persistent: true,
  });

  watcher
    .on('add', console.log);

  var watchedPaths = watcher.getWatched();
```

**Comment by es128** [comment]
Yes. If you don't want those events then use the `ignoreInitial: true` option.

**Comment by pthieu** [comment]
Thanks for quick reply.
