### ISSUE TITLE
Need to trigger deletion many times to clean  up a directory

### ISSUE THREAD

**Issue by xsq007** [paulmillr/chokidar#524]
Say a directory D  is watched by chokidar, D has many subdirectories which have many sub ones, too. (e.g. node_modules directory)
When I try to remove the directory D , I have to trigger deletion many times. 
Each time the deletion only cleans parts of the directory, which annoys me. 

Is there any way to clean up the directory with one deletion? 

I am on win10 x64,  node 4.4.0, chokidar 1.6.0
Thanks for any suggestions or clues.

**Comment by paulmillr** [comment]
Not sure what you mean by "trigger deletion".

**Comment by xsq007** [comment]
Let me clarify it.
I have to delete the directory D several times (with Shift ＋ Delete keys on Win10) to clean up the directory and all subdirectories. Each deletion only removed some subdirectories.
Hope to clean up the directory with only one deletion.

Is it clearer?
thanks.

**Comment by paulmillr** [comment]
Still don't understand. On a Mac, pressing ⌘⌫ would remove the folder and all subdirectories if the folder is selected right now.

Do you mean that on Windows pressing a combination would only remove *some subdirectories*?

**Comment by xsq007** [comment]
yes, I mean that. 
Pressing Shift + Delete keys on Windows only remove some subdirectories. 
Need to press the keys multiple times to remove all subdirectories.

**Comment by xsq007** [comment]
By the way, if the directories were not watched by chokidar, one pressing Shift+Delete keys would remove all subdirectories.  However, once watched by chokidar, multiple pressings are needed.

**Comment by paulmillr** [comment]
Interesting.

**Comment by es128** [comment]
This is because of strange fs locking on Windows. I really don't think there's anything we can do about it.

Possibly could be reported to libuv in case there is something they can do with the lower-level system APIs, but I wouldn't hold my breath. 

Obviously you could just tolerate it as it is, stop watching before attempting a recursive delete, or switch off of Windows for this sort of dev work (a Linux VM running on Windows won't have this problem). 

You could also try different approaches at deleting, such as [trash-cli](https://github.com/sindresorhus/trash-cli)

**Comment by xsq007** [comment]
@es128  thanks for response. 
I am developing a tool in which chokidar is used to watch file changes and then those changes including deletion are synchronized with the server side's.  
Windows OS is not only for dev work, but also a production environment,  I'm afraid I still need to support Windows any way.

Do you know any option to stop such fs locking on Windows?
thanks.

**Comment by es128** [comment]
I'm unaware of an easy fix - I would have mentioned it if I were. 

You could try toggling the `usePolling` option, although setting it to `true` comes with some performance tradeoffs and is not suitable for too large a file tree.

I suggest you also do some googling and look through articles like [this](http://www.howtogeek.com/128680/how-to-delete-move-or-rename-locked-files-in-windows/) to see if you can find any other helpful suggestions that might be tenable for your app/users.

**Comment by xsq007** [comment]
@es128 appreciate  your suggestions. I'll give it a try.

**Comment by xsq007** [comment]
After adding usePolling, the problem was gone.  Close this. Thanks.
