### ISSUE TITLE
Event 'add' not fired on polling over network > file was created via remote ssh

### ISSUE THREAD

**Issue by airbenich** [paulmillr/chokidar#525]
Two linux machines servers:
One runs the node.js script (script-server) and the other one holds the data (data-server).
The script-server mounts successfully the data-server to '/mnt/data-server' and chokidar monitors this mounted folder. Chokidar is in polling mode (usePolling: true).

**Case 1 (not working):**
When copying a file via commandline (script-server) into the mounted folder, chokidar fires no events (even not when displaying raw events).

**Case 2 (working):**
When mounting the data-server additionally on a windows client (samba) and creating the file from the windows client, chokidar (on the script-server) works as excpected and fires the add-event for the file.

Whats the problem here?

**Comment by es128** [comment]
You said it yourself - the raw events from the polling aren't picking up the change, but I don't know why. This happens *every* time you create a new file in the mounted drive from the script-server? What if it isn't a copy command, something like `touch foo.bar` instead?

**Comment by airbenich** [comment]
Sadly it happens every time. Even with`touch foo.bar`.

**Comment by es128** [comment]
Try `touch /mnt/data-server`

Also take a look at the output of `stat` on the dir and any relevant files before and after your attempts to make something happen.

**Comment by airbenich** [comment]
Okay - `Touch ` on the file > no change.
`Touch `on the folder > Chokidar recognized the file after the touch.

**Comment by airbenich** [comment]
Okay my workaround is now to touch the folder every second continuosly. Thank you very much Elan for helping me on this! Looks like there is a caching problem with cifs-mounts. Maybe the touch shoud be also part of the polling-feature?

**Comment by es128** [comment]
> Maybe the touch shoud be also part of the polling-feature?

I don't think so, especially considering this doesn't appear to be a common problem.
