### ISSUE TITLE
Ignoring dynamic directories

### ISSUE THREAD

**Issue by oksreenath** [paulmillr/chokidar#526]
Hello,
I have a problem with excluding sub directories in the folder that I am watching.
I am saving html files in the main directory and there are folders created along with the html files that I want to ignore.
The problem is these folders are randomly named, but has a common word "files" in it. So can anyone help me to figure out a way to ignore these folders?
(Pseudo Code)
watch C:\input
The contents of input folder are:
input\sample.html
input\sample1.html
input\sample_files
input\sample1_files
I would like to ignore the folders with "files" keyword in them.
Any help would be really appreciated.

**Comment by es128** [comment]
`ignored: 'input/*_files'`

**Comment by oksreenath** [comment]
Thank you.. It worked..
