### ISSUE TITLE
watcher isn't closed on SIGINT

### ISSUE THREAD

**Issue by wagerfield** [paulmillr/chokidar#528]
Watchers are not closed on `SIGINT` —is this intentional?

```js
var chokidar = require('chokidar');
var watcher = chokidar.watch('some/glob/*.ext');
watcher.on('all', function(event, path) {
  console.log(event, path); // Continues to log after CTRL + C is pressed (on Mac) 
});
process.on('SIGINT', function() {
  watcher.close(); // This fixes the problem...
});
```

**Comment by paulmillr** [comment]
Never thought about it, but I think that's intentional. 

The reason is: chokidar is usually as a library for doing something else — for example, for building javascript apps. So the app builder would handle sigint on its own and execute the proper `watcher.close()` logic in there.

**Comment by ycjcl868** [comment]
+1
