### ISSUE TITLE
Some "add" events were missing for a big directory

### ISSUE THREAD

**Issue by xsq007** [paulmillr/chokidar#531]
When I copied a large directory with many files into the directory that is being watched, I just found not all files issued "add" events,  instead some were missing. 
For example, the directory has totally 15,000 files, but I can only get 14800 "add" events.

More weird, when I copied the directory (deleted and added it again) several times , I got different number of "add" events,  and all of them were less than 15,000.

BTW, if the directory already existed and I  initialized chokidar.watch with ignoreInitial=false,  
then I got the correct 15,000  "add" events.

Here is my setting:
`var watcher = chokidar.watch(watchDir, { 
      ignored: /^\./,
      persistent: true,
      ignoreInitial: true,
      usePolling: true,
      ignorePermissionErrors: true
    });`

I am on Windows 10, NodeJS 4.4.0 (x64), choikdar 1.6.0.

Any clues and suggestions are appreciated. Thanks.

**Comment by paulmillr** [comment]
Is there a pattern that shows how all of missing files are similar? Maybe it's related to your `ignored` setting?

**Comment by xsq007** [comment]
Thanks for response.  I'll give  a try to remove the `ignored `setting.
I still have a question. As showed above, if the directory already existed and chokidar.watch was initialized with `ignoreInitial=false` setting, then  correct number of "add" events (15000) were issued. 
At initialization time, `ignored` setting was not considered. Correct?

**Comment by paulmillr** [comment]
`ignored` is always taken into account, I think.

**Comment by es128** [comment]
`ignored` is utilized during initialization, yes. 

This is a massive amount of files and events to be trying to watch with polling. Try a much higher `pollInterval` setting or see what happens with `usePolling: false`.

**Comment by es128** [comment]
Also see if the missing ones get found if you add one more file a bit after the fallout of the huge copy operation settles down.

**Comment by xsq007** [comment]
Sorry for late response and  I was on vacation in the past several days.
Using `interval: 800` mitigates the issue. 
At least I could get correct number of "add" events for several times. 
Meanwhile I can not use `"usePolling: false"` option because it prevents deleting large directories  on Windows.
Will try the advice to add one more file.

Thanks for your help. Have a good day.
