### ISSUE TITLE
Windows subsystem for Linux: Unstable behavior

### ISSUE THREAD

**Issue by paulmillr** [paulmillr/chokidar#532]
https://github.com/webpack/webpack/issues/2949 

Test output: https://gist.github.com/paulmillr/c9e4a4fd85b3652319fd78787fb8526b

I think this is mostly a broken backend (WSL is new and unstable), but may be worth looking into.

**Comment by es128** [comment]
Seems a lot of the failures are in the before/after hooks. Try upping the delay settings to make it all run slower... could be that the file system can't keep up with how fast we are running the tests.

**Comment by djensen47** [comment]
Here's a related issue: https://github.com/Microsoft/BashOnWindows/issues/216

Any chance for fix or workaround for this? Who knows how long Microsoft will take to fix it, could be tomorrow, could be next year. 😕

**Comment by paulmillr** [comment]
> workaround for this

Yeah. Just switch to a native Windows system. Or, native linux. No emulation.

**Comment by uhoh-itsmaciek** [comment]
The linked bug is closed, so maybe this is no longer an issue? https://blogs.msdn.microsoft.com/commandline/2016/10/07/wsl-adds-inotify-filesystem-change-notification-support/
