### ISSUE TITLE
Chokidar detect japanese file not correct ?

### ISSUE THREAD

**Issue by shinbutchi** [paulmillr/chokidar#534]
Hello everybody,
I used chokidar library for my project about synchronize file between client and server. Everything work fine until I add a file with Japanese language file name **BINDの基本コンセプト＿ベトナム語版(-p22).docx**.  With this file, chokidar always detects with name **BINDの基本コンセプ ト＿ベ トナム語版(-p22).docx**. As we see, a second name has 2 space characters.  This problem only happens on Mac OS.
Can anyone explain what happens ?

**Comment by huynhvanhoang** [comment]
oh my god, I have a same problem. Please to help me :'(

**Comment by es128** [comment]
I copied and pasted the first filename from your issue description to test this and could not reproduce

```
change BINDの基本コンセプト＿ベトナム語版(-p22).docx
```

No extra spaces.

What does the output look like from the `raw` event?

Could you possibly set up a simple repo that reliably reproduces the problem?

**Comment by shinbutchi** [comment]
Oh, it's my mistake. It's related with filename encoding UTF-8 on macOS. Chokidar detects these characters ( **プ,ベ**) with 2 bytes, not 1 byte. 
Thanks for your time es128.
