### ISSUE TITLE
Unignore path?

### ISSUE THREAD

**Issue by peteruithoven** [paulmillr/chokidar#540]
Is is possible to ignore a folder (`npm_modules` for example), but then unignore (watch) a certain subfolder inside that ignored folder (`npm_modules/chokidar/lib` for example)?

**Comment by es128** [comment]
Not in the same way you're describing.

If you `.add()` the exact same path you previously ignored, then it should unignore it.

https://github.com/paulmillr/chokidar/blob/master/index.js#L595-L597

To accomplish what you want, you probably just need to get more granular in describing what you want watched without relying as much on large wildcards and exclusions (and un-exclusions).

Such as
```
project/*
project/dir1/**
project/dir2/**
project/node_modules/chokidar/lib
```

**Comment by peteruithoven** [comment]
Thanks. I'm afraid then, that it's doesn't seem feasible to watch a specific folder in node_modules while still ignoring all other folders (packages) in node_modules.
