### ISSUE TITLE
watcher.add does not seem to actually add paths or fire on('add') or on('addDir') events

### ISSUE THREAD

**Issue by ORESoftware** [paulmillr/chokidar#542]
I tried both this:

```
              watcher.add(paths);  //an array of paths
```

and this:

```js
            paths.forEach(function (p) {
                    console.log(' => watcher is adding path =>', p);
                    watcher.add(p);
            });
```

...neither seems to add paths to the exiting watcher and neither call seems to fire the 'add' or 'addDir' events. These are definitely valid paths.

I have

```
               watcher.on('error', error => {
                    console.log(`chokidar watcher error: ${error}`)
                });
```

and nothing is getting logged there. So not sure what's going on, any ideas?

**Comment by es128** [comment]
Chokidar deliberately does not fire `add` events for existing file system entries under new paths provided to `.add()` after the `ready` event was fired. But it does set up the watchers, and if you make changes under those newly watched paths you'll get the corresponding events.

**Comment by ORESoftware** [comment]
huh, that's weird...but even when I call `watcher.getWatched()` it does not reflect the new paths being watched. Feel like that would be an imperative to have?

How we debug so that we can be sure the watcher has captured everything?

**Comment by es128** [comment]
It should be in `.getWatched()` after the new watch paths have been scanned, but it definitely won't be there yet if you're calling it on the same tick of the event loop as `.add()`. Unfortunately there is no good solution right now for getting the equivalent of a new `ready` event after calling `.add()` (therefore you won't know how long you need to wait), so if your use case requires this combination it probably means you need to open separate instances of `chokidar.watch()` and manage them accordingly. 

If what I'm saying is not consistent with your observations, please set up a reproducible case I can review.

**Comment by ORESoftware** [comment]
what you're saying makes sense, I will try logging watcher.getWatched() in the next tick

```
process.nextTick(function(){
    log(watcher.getWatched())
});
```

and see if I can get more up to date info

**Comment by es128** [comment]
You need a bigger delay than `nextTick`, the file system scanning is asynchronous. The current problem is that you're not going to be able to predict how long that delay needs to be, nor is there a callback or event interface to let you know when it's ready

**Comment by ORESoftware** [comment]
right, I can understand that...there is no way to tap into that, to register some event listener?

**Comment by ORESoftware** [comment]
I might just use setInterval to log it for now

**Comment by ORESoftware** [comment]
ok, so seems to work as you described, thanks for the details
