### ISSUE TITLE
Fire change event without making an actual change to file

### ISSUE THREAD

**Issue by ORESoftware** [paulmillr/chokidar#543]
I am using this lib to run individual tests when they themselves change or to run the whole test suite if certain files in the project change.

What I am doing sometimes is adding comments to files ('//') and then saving the file, just to get the watcher 'change' events to fire, so my tests run on demand, but that adds unnecessary comments to files and eventually they will end up in source control which is bad.

Is there some keystrokes to use to fire a change event somehow if a file on the filesystem hasn't experience a change in its contents?

**Comment by paulmillr** [comment]
```
const watcher = chokidar.watch('dir')
watcher.emit('change', 'filepath')
```

that should do the trick

**Comment by ORESoftware** [comment]
thanks but I meant not programmatically so much - I meant via some
keystrokes - which somehow change file without changing its contents - is
there some recommend way to do that? otherwise maybe could use some sort of
stdin thing and then use the simple methodology you described.

**Comment by es128** [comment]
Like [`touch`](http://www.unix.com/man-page/POSIX/1posix/touch/)?

**Comment by ORESoftware** [comment]
maybe, yeah, would that fire a change event in this library? Or maybe a 'touch' event?

**Comment by es128** [comment]
There is no `touch` event in chokidar. It will fire a `change` event when you `touch` a file on POSIX platforms

**Comment by ORESoftware** [comment]
ok good to know!

**Comment by ORESoftware** [comment]
works for me, I guess it would be interesting for the docs to document would kind of low level events the library hooks into. I frankly don't know which lower level events "change" events originate from.
