### ISSUE TITLE
Missing unlink and unlinkDir events when using wildcard selector

### ISSUE THREAD

**Issue by birjolaxew** [paulmillr/chokidar#547]
As originally reported in [gulp#1844](https://github.com/gulpjs/gulp/issues/1844):

When a watched directory is deleted, no events are fired for directories or their files.

With the following initial folder structure:

```
test
├── dir
│   └── foo
└── test
```

These actions are executed manually:
1. Create folder `test/dir2` (should emit `addDir - test/dir2`)
2. Create file `test/dir2/foo` (should emit `add - test/dir2/foo`)
3. Create file `test/dir2/bar` (should emit `add - test/dir2/bar`)
4. Delete file `test/dir2/bar` (should emit `unlink - test/dir2/bar`)
5. Delete folder `test/dir2` (should emit `unlinkDir - test/dir2` and/or `unlink test/dir2/foo`)
6. Delete folder `test/dir` (should emit `unlinkDir - test/dir` and/or `unlink test/dir/foo`)
7. Delete file `test/test` (should emit `unlink - test/test`)

As can be seen below, the watch listener is never informed of the deletion of `test/dir2` or `test/dir`, nor that of the `foo` file in either of them.

---

**Code:**

``` javascript
var chokidar = require("chokidar");
chokidar.watch("test/**/*", { ignoreInitial: true })
  .on("all", (event, path)=>console.log(event, "-", path));
```

**Expected output:**

```
addDir - test/dir2
add - test/dir2/foo
add - test/dir2/bar
unlink - test/dir2/bar
unlinkDir - test/dir2    (and/or unlink test/dir2/foo)
unlinkDir - test/dir     (and/or unlink test/dir/foo)
unlink - test/test
```

**Observed output:**

```
addDir - test/dir2
add - test/dir2/foo
add - test/dir2/bar
unlink - test/dir2/bar
unlink - test/test
```

**OS:**
Ubuntu 14.04
Node v4.6.1
Chokidar v1.6.1 (installed using `npm install chokidar`)

**Comment by birjolaxew** [comment]
Various things I've tested:

- Running the chokidar test (cloning repo, `npm test`) passes everything
- Running `example.js` *does* output the relevant `unlinkDir` and `unlink` when watching `.`, `./test` or `test`. Events in this situation (when deleting `test/dir`):

    ```
RawEvent: rename dir { watchedPath: 'test' }
RawEvent: rename dir { watchedPath: 'test/dir' }
unlinkDir test/dir
unlink test/dir/foo
```
- Running `example.js` *does not* output the relevant `unlinkDir` and `unlink` when watching `test/**/*`, `./test/**/*` or `test/*`. Events in this situation (when deleting `test/dir`):

   ```
RawEvent: rename dir { watchedPath: 'test' }
RawEvent: rename dir { watchedPath: 'test/dir' }
```

Seems like the problem lies in using a wildcard selector, although the same raw events are still fired.

**Comment by es128** [comment]
Thank you for the thorough issue report. I will investigate.

**Comment by DecaHub** [comment]
@es128 Have you found any way to be able to watch for deleted files/directories successfully? Thanks.

**Comment by es128** [comment]
@DecaHub yes, as @birjolaxew has pointed out, unlink events are reported correctly when specifying a directory to watch without using wildcards. 

If you mean specifically with the conditions described above, then no, it hasn't been solved, and that's why the issue remains open.

**Comment by VentyCZ** [comment]
As this is still an open issue, I also have something related to this (also using Gulp 4.0).
Note: I'm using Samba (which might be cause of the problem) and PHPStorm for an editor.

I'm also using wildcards (see [this](http://take.ms/Dj17I)).

The problem ([screenshot](https://monosnap.com/file/22fmibj2hNKKS74VJHag4xvQtrTwD7)):
 - The first change is reported properly (the line after "Watching for changes ...")
 - The task is done, and changes are made to bundle.js in the same folder as all the others (*.njs files)
 - On a second change > it just unlinks everything (as seen after the first task completes)
 - No changes are recognized afterwards

Also interesting that the "unlinkDir" event does not use a relative path, as the "change" event (might be caused by gulp itself though).
