### ISSUE TITLE
Should not prepend cwd to ignored absolute paths

### ISSUE THREAD

**Issue by sebastien-p** [paulmillr/chokidar#548]
Hi,

Coming from [gulp-watch](https://github.com/floatdrop/gulp-watch), I need to implement a watch task like configured like this:

```JavaScript
{
  cwd: FOLDERS.SRC,
  src: [
    PATTERNS.IMAGES,
    PATTERNS.FONTS,
    PATTERNS.JSON,
    '!modules/*/{config,i18n}/' + PATTERNS.JSON
  ],
  run: ['copy']
}
```

Note the negation pattern which is causing the issue.

Now when I add some `console.log` calls to both the *gulp-watch* code and yours this is what I get:

```JavaScript
// gulp-watch sets paths to be absolute
[ '/Dev/project/src/**/*.{png,jpg,gif,svg,ico}',
  '/Dev/project/src/**/*.{ttf,eot,woff,svg}',
  '/Dev/project/src/**/*.json',
  '!/Dev/project/src/modules/*/{config,i18n}/**/*.json' ]

// chokidar paths
[ '/Dev/project/src/**/*.{png,jpg,gif,svg,ico}',
  '/Dev/project/src/**/*.{ttf,eot,woff,svg}',
  '/Dev/project/src/**/*.json' ]

// chokidar generated ignore list
{ 'src/Dev/project/src/modules/*/{config,i18n}/**/*.json': true }
```

Then I get errors because the generated ignore list is incorrect, the path here should not be `'src/Dev/project/src/modules/*/{config,i18n}/**/*.json'` but `'/Dev/project/src/modules/*/{config,i18n}/**/*.json'`.

I think this simply happens because negation patterns are [always treated like relative paths](https://github.com/paulmillr/chokidar/blob/master/index.js#L584-L585) so the `cwd` is prepended to them but it should not, you should also check if the path after `!` is not an absolute one before doing that I guess.

What do you think?

Thanks

**Comment by es128** [comment]
What you're saying about that bit of code makes sense - checking for absoluteness again without the `!`, but I'm confused about the example you've provided. 

Your negation pattern `'!modules/*/{config,i18n}/' + PATTERNS.JSON` is not absolute. Seems like the value given as the `cwd` option may be wrong, and I don't see why you're specifying it anyway if you're intending to provide only absolute paths.

**Comment by sebastien-p** [comment]
You're totally right, my example shows relative paths, this is *gulp-watch* that actually turns them into absolute ones.
