### ISSUE TITLE
Globs not working correctly?

### ISSUE THREAD

**Issue by alan-agius4** [paulmillr/chokidar#549]
Hi I am having some issues with the paths more specificy using globs,

When I try to use a glob like the below it fails to pick up changes;

```cmd
./node_modules/@obg/**/dist/es2015/*.js
```
However like the below works
```cmd
./node_modules/@obg/ion2.ui.global/dist/es2015/*.js
```
Thanks

**Comment by paulmillr** [comment]
Update to Chokidar v3, it should resolve this.
