### ISSUE TITLE
NodeJS 7.x issues and other issues

### ISSUE THREAD

**Issue by ghost** [paulmillr/chokidar#550]
@paulmillr @isaacs @es128 

Thanks for a great library!

What is the status of this repo? I noticed there are a lot of issue ticket marked with `bug`, and not yet solved? And also a few open issue tickets.

Any idea when this is going to be solved?

However. NodeJS 7.x gave me headache. Not sure if the issue is in Chokidar or a a dependency, and I can't reproduce. The case is that sometimes I rename a file on Windows, but it got deleted instead!
And it also deleted two other files for me in a folder with symlinks. I tested this with a dummy folder and same thing happened!!

Other issues I noticed - not only on NodeJS 7.x is

- using Globs doesn't work as expected. The path separator mixes things up, and files are not filtered correctly. E.g. `.*jsx` are seen as `*.js`. file. And `bmp` and `jpeg` are seen as `bm` and `jpe` in rare cases I ran into. And also brackets doesn't seem to work as it should. 
And why not support Globs out of the box? Now it seems Chokidar is checking if its a glob file, and if it deals with it, it checks for it . Couldnt this isGlob check be skipped? Look at this library: https://github.com/jonschlinkert/matched

- very high CPU usage on large folders. Tested both on Windows and Mac. On Windows it's worse. The difference is around 23%.

- doing a simple folder scan with say 50 files take a lot of time! Seems to be issues with the startup? Is there any scanning here, or whats going on? In this case I'm using a  CPU i7  with 32 GB RAM (*windows*) and my memory usage for it jumped to 127 MB

- if try to use negated glob patterns, it takes **3501ms** to finish that task!

- I experienced that dot files including numbers sometimes doesn't seem to be filtered out? I still find them. E.g. `.f12oo3`. The order of the numbers has nothing to say.

**Comment by paulmillr** [comment]
Hey. The status is described in #503. Node v7 seems to be unstable so far.
