### ISSUE TITLE
doesn't trigger change / add event when renaming folders, and delete files

### ISSUE THREAD

**Issue by ghost** [paulmillr/chokidar#551]
@paulmillr @es128 

Let say we have a folder named `foo` and we have 2 files in it. Add some more files, and it works just fine.
Then rename `foo` to `bar`, and the change is not noticed at all.

```js
// adding new files to foo folder
File foo\b.js has been added
File foo\foo.js has been added

// renaming the folder
File foo\b.js has been removed
File foo\foo.js has been removed
```
If you try this, you will see that no events are triggered. The new folder isn't found, and new files not re-added to that folder for watching.

And also on `NodeJS 7.0` some of the files gets deleted!!!! I experienced this a random times when I was trying to reproduce this.
 
I did this on a windows computer.

**Comment by birjolaxew** [comment]
[Might be related.](https://github.com/paulmillr/chokidar/issues/547

**Comment by crazyhuggins** [comment]
@birjolaxew I experience the same thing as you described now, yes. But also try to create a folder name `A` with two files inside it. Run `chokidar`, and rename folder `A `to folder `B` and add a few more files.

Any events invoked for you if you do that? If you change the name on the folder, and not the files?

And also delete folder `B` after you renamed it from `A`. What happen in your `console.log`?

**Comment by birjolaxew** [comment]
@crazyhuggins Yes, I do see events (when watching `test/`, not a wildcard selector, as described above):

```
unlinkDir test/A
addDir test/B
add test/B/b.js
add test/B/foo.js
unlink test/A/b.js
unlink test/A/foo.js
add test/B/a.js
unlinkDir test/B
unlink test/B/b.js
unlink test/B/foo.js
unlink test/B/a.js
```

**Comment by crazyhuggins** [comment]
@birjolaxew Same as I do. I see the events, but in the moment I rename the folder, the last event I see is what you are seeing - unlink.

There is no folder re-added with a new name, and if I try to change the content of the files inside the folder I renamed, no events at all. And if I try to delete or add files in the folder I renamed too, same thing. No events get invoked.

I'm on a Windows computer using Windows 10.

**Comment by birjolaxew** [comment]
@crazyhuggins That's not what I'm seeing. The events I posted above are exactly as expected (unlinks on old dir and files, adds on new dir and files, including those added/removed after the rename).

What code are you using to run chokidar?

**Comment by crazyhuggins** [comment]
@birjolaxew Funny enough. I'm using the examples given in the readme. 

```js
var watcher = chokidar.watch('foo');
// Something to use when events are received.
var log = console.log.bind(console);
// Add event listeners.
watcher
  .on('add', path => log(`File ${path} has been added`))
  .on('change', path => log(`File ${path} has been changed`))
  .on('unlink', path => log(`File ${path} has been removed`));
```

**Comment by birjolaxew** [comment]
@crazyhuggins I would expect that deleting (which you're doing when you rename) the folder you're watching would stop chokidar from watching it, seeing as it's no longer there. Since you're asking chokidar to watch for changes to `foo`, it won't fire events for `bar`. It would be nice if it informed you of the deletion of the files you're watching when you rename, though.

**Comment by crazyhuggins** [comment]
@birjolaxew Agree what you are writing, but with this tree structure where I'm watching the test folder, I'm getting the same results if I rename foo. No events invoked.

```js
test
| -- foo 
      |-- a.js
      | - b.js
```

**Comment by birjolaxew** [comment]
@crazyhuggins What code are you using?

**Comment by crazyhuggins** [comment]
Same code as earlier - examples from the readme. Except this time I was atching the test folder.

**Comment by crazyhuggins** [comment]
@birjolaxew It could be the new Windows 10 filesystem that scew things up. I tried now with and without bash in Windows 10. Same thing. But when I restarted suddenly I got over 200 extra files in my folder. I think NodeJS 7 are doing some crazy stuff too. I also got my files deleted with latest NodejS, so I'm back again on v. 6.9.1

**Comment by birjolaxew** [comment]
@crazyhuggins Seems possible. Just to confirm that our outputs aren't matching, try running the following:

Tree:
```
test
└── foo
    ├── a.js
    └── b.js
```

Code:
```
var watcher = chokidar.watch('test');
// Something to use when events are received.
var log = console.log.bind(console);
// Add event listeners.
watcher
  .on('add', path => log(`File ${path} has been added`))
  .on('change', path => log(`File ${path} has been changed`))
  .on('unlink', path => log(`File ${path} has been removed`));
```

Manual events:
1. Rename `test/foo` to `test/bar`
2. Add `test/bar/c.js`

Observed (Ubuntu 14.04):
```
File test/foo/a.js has been added
File test/foo/b.js has been added
File test/bar/a.js has been added
File test/bar/b.js has been added
File test/foo/a.js has been removed
File test/foo/b.js has been removed
File test/bar/c.js has been added
```

**Comment by crazyhuggins** [comment]
I did, and I got some extra files this time around. And if you notice it, the new folder name is not there. Here is my output:

```js
File test\foo\a.js has been added
File test\foo\b.js has been added
File test\foo\a.js has been added
File test\foo\b.js has been added
File test\foo\a.js has been removed
File test\foo\b.js has been removed
File test\foo\b - Copy.js has been added
File test\foo\b - Copy - Copy.js has been added
File test\foo\b - Copy - Copy - Copy.js has been added
File test\foo\b - Copy - Copy - Copy - Copy.js has been added
File test\foo\a - Copy.js has been added
File test\foo\a - Copy (2).js has been added
```

**Comment by crazyhuggins** [comment]
Not sure what's going on. But just in case I video recorded this as well. So this is nothing I did manually. But I need to investigate and figure out who to blame here.

**Comment by paulmillr** [comment]
Seems like node v7 is shitty.

**Comment by danbucholtz** [comment]
Sounds similar to what I'm seeing with Node 4.x and Node 6.x. If you have a directory and rename it or delete it, the files in that directory are being watched never receive events when listening for `all`.

See my issue here: https://github.com/paulmillr/chokidar/issues/555

Thanks,
Dan

**Comment by paulmillr** [comment]
Update to Chokidar v3, it should resolve this.
