### ISSUE TITLE
Some add events were missing when copying many files into watched folder

### ISSUE THREAD

**Issue by xsq007** [paulmillr/chokidar#552]
When copying many files, e.g. hundreds of files into the watched  folder, I found number of add events is not equal to the total file number, i.e. some add events were missing.
Following is the configuration of chokidar.
```
  var watcher = chokidar.watch(watchDir, {
      persistent: true,
      ignoreInitial: false,
      followSymlinks: false,
      ignorePermissionErrors: true,
      awaitWriteFinish: true
    });
watcher.on('add',  path => {
  console.log('add' , path)
})
```
BTW, if I exit the program and re-run it,  then  all add events are emitted.  Guess ignoreInitial=false option does the trick.

Wondering if there is a way to prevent lost "add" events  when files are copied into the folder at first.

My environment is Windows 10 x-64 and Node.js v6.6.0

**Comment by birjolaxew** [comment]
Cannot reproduce on Ubuntu 14.04, Node v4.6.2.

---

Steps:
1. In another folder, create 1000 files using `for i in $(seq 1 1000); do echo $i > "file-$i.txt"; done`. Copy those.
2. Run the code below, starting chokidar
3. Paste files into watched folder

Code:
```javascript
require('./').watch('test/', {
  ignoreInitial: true,
  ignored: /node_modules|\.git/
}).on('all', function(event, path) {
  console.log(event, path,"("+addCount+")");
  ++addCount;
}).on('ready', function() {
  console.log('Ready');
}).on('raw', console.log.bind(console, 'RawEvent:'));

var addCount = 0;
```

Observed:
```
...
add test/file-995.txt (995)
add test/file-996.txt (996)
add test/file-997.txt (997)
add test/file-998.txt (998)
add test/file-999.txt (999)
```

**Comment by xsq007** [comment]
Tried to copy "grunt" folder in a node_modules folder. 
There are totally 504 files in the folder on Windows OS.

I tried several times and got different results of add events, e.g. 501, 499, 496, but no luck to get 504.
Possibly it is related with nested folder structure.

**Comment by birjolaxew** [comment]
**Can replicate** on Ubuntu 14.04, Node v4.6.2.

---

Steps:
1. Do `npm install grunt` in a folder, copy every file inside `node_modules/grunt/node_modules/dateformat` (probably also works with other complex folders)
2. Run the below code in the main folder, with an empty folder called `test` present
3. Paste copied files into `test`

Code: 
```javascript
var watchPath = "test/";
var found = (function(){
  var hist = {},
      done = false,
      timer;

  return function found(path){
    if (done) {
      console.log("Already checked. Please rerun.");
      return;
    }
    if (hist[path]) {
      console.log("Found path multiple times: "+path);
      return;
    }

    hist[path] = true;
    clearTimeout(timer);
    timer = setTimeout(function(){
      done = true;
      check(hist);
    }, 500);
  };
})();

function check(files) {
  var fs = require("fs"),
      path = require("path");

  var badFiles = 0,
      total = 0;
  walk(watchPath, function(file){
    ++total;
    if (!files[file]) {
      console.log("File without add event: ",file);
      ++badFiles;
    }
  });

  console.log("Add events seen:",Object.keys(files).length);
  console.log("Files found:",total);
  console.log("Files without add event:",badFiles);
}

// http://stackoverflow.com/questions/2727167/getting-all-filenames-in-a-directory-with-node-js
function walk(searchPath, cb) {
  var fs = require("fs"),
      path = require("path");

  fs.readdirSync(searchPath).forEach(function(name){
    var filePath = path.join(searchPath, name);
    var stat = fs.statSync(filePath);
    if (stat.isFile()) {
      cb(filePath);
    } else {
      walk(filePath, cb);
    }
  });
}

require('chokidar').watch(watchPath, {
  ignoreInitial: true
}).on('add', function(path) {
  found(path);
});
```

Observed:
```
File without add event:  test/.npmignore
File without add event:  test/.travis.yml
File without add event:  test/LICENSE
File without add event:  test/Readme.md
File without add event:  test/node_modules/meow/node_modules/normalize-package-data/node_modules/.bin/semver
File without add event:  test/node_modules/meow/node_modules/normalize-package-data/test/normalize.js~
File without add event:  test/node_modules/meow/node_modules/redent/node_modules/.bin/strip-indent
File without add event:  test/package.json
File without add event:  test/test/test_dayofweek.js
File without add event:  test/test/test_formats.js
File without add event:  test/test/test_isoutcdatetime.js
File without add event:  test/test/weekofyear/test_weekofyear.js
File without add event:  test/test/weekofyear/test_weekofyear.sh
Add events seen: 258
Files found: 271
Files without add event: 13
```

**Comment by birjolaxew** [comment]
The missing files **have** `raw` events fired for them. [Example log](https://gist.github.com/birjolaxew/2192037365664657941cbac25e6d017b), logging `raw` in format `<event> - <path> - <details>`, `add` events in format `<path>` and `fs.watch` events in format `Native:  <event> <path>`. Notice how (for instance) `.travis.yml` [has raw events](https://gist.github.com/birjolaxew/2192037365664657941cbac25e6d017b#file-chokidar_-552-1-log-L373-L376) but [no add event](https://gist.github.com/birjolaxew/2192037365664657941cbac25e6d017b#file-chokidar_-552-1-log-L407).

**Comment by xsq007** [comment]
@birjolaxew  thanks a lot for your investigation.

Would you guys have a plan to fix the problem in the future?

**Comment by birjolaxew** [comment]
@xsq007 Chokidar isn't really super active any more (#503), so it's unlikely that issues are going to get fixed - especially ones like this that don't have reproduction steps included, and likely requires hours of debugging to find the reason for.

**Comment by dietervanhoof** [comment]
I'm a bit late to the party but for me enabling polling fixed this issue (so far). I tested with 2.1K files (touch 2k files in one command) and all of them came through.

**Comment by xsq007** [comment]
enabling polling caused very high cpu usage at all times. So polling may be not optimal. My workaround is to record all file changes emitted by chokidar and then several seconds later (after no changes), compare existing files in the directory with them to check missing ones.

**Comment by dietervanhoof** [comment]
CPU usage was fine for me but might become an issue in the future. Is your workaround stable and can I find the code somewhere?

Thanks.

**Comment by rcmedeiros** [comment]
I experienced this issue with only 4 files. Not all the times though, but when I'm running tests I often have to deal with it.

**Comment by vladimirmelekh** [comment]
It's very easy to reproduce - just watch over node_modules folder, like xsq07 mentioned. Chokidar goes crazy with folders with complex structure and a lot of subfolders.
I spent some time on testing, overall files count to be watched is 57 in my folder. Usually, chokidar sends 7/53/57 "add" events on the initial scan.  Weird, but just these numbers. 
If it's 7 - then just .txt files are watched, all .html and .docx are skipped
If it's 53 - then just .txt and .html are watched, .docx are skipped
It always read txt files well, maybe the problem is somewhere in extractors area?

I don't use ignoredFiles, well basically I do use it, but tested with/without.

**Comment by birjolaxew** [comment]
@vladimirmelekh The problem is that as long as the output is basically random, there's no way to really debug it (not to mention that chokidar isn't really actively maintained any more).

**Comment by es128** [comment]
It's going to be difficult to reliably detect/fix the issue within chokidar. I don't know exactly how stuff gets missed, but I believe it happens at a lower level. Based on the reports above, it seems to be isolated to `fs.watch()` mode. 

A possible solution may be to detect the sorts of conditions that tend to express the problem, like a very high rate and volume of events, and then after that abates do a new directory scan (i.e. trigger a synthetic watch event) on the affected paths just to catch up on anything that somehow got missed.

I'm not going to work on this, but will review PRs

**Comment by srguiwiz** [comment]
I get all files to `add` in our use case **if** in file `nodefs-handler.js` in function `_handleDir` in line
```
var throttler = this._throttle('readdir', directory, 1000);
```
I replace the 1000 with 0.

**If** files get added quickly, then that throttle prevented the directory from being looked at again if the next file got added before the throttle time.

I have not thought through or tested impact of that.
