### ISSUE TITLE
Watch event not firing when directory is deleted

### ISSUE THREAD

**Issue by danbucholtz** [paulmillr/chokidar#555]
Reproduction steps:

```
1. Create directory test
2. Create file test/my-file.txt with some content
3. Create a chokidar watch on the file and listen for `all` events
4. Make a change to the file and observe that the watch fires
5. Delete the test directory and observe the watch not firing and the user never being notified
```

Here is a very simple [repo](https://github.com/danbucholtz/chokidar-bug-reproduction) showing the issue. It is one file and incredibly simple.

Thanks,
Dan

**Comment by paulmillr** [comment]
we cannot reliably track changes for top-level watched directories at this point. the solution is to watch the parent of the directory.

**Comment by Faline10** [comment]
Possible workaround mentioned in this bug: https://github.com/paulmillr/chokidar/issues/459 Set depth to 1 instead 0, and ignore accordingly.
