### ISSUE TITLE
Change event is only triggered twice when watching one file

### ISSUE THREAD

**Issue by lonelywolf4git** [paulmillr/chokidar#556]
I want to watch file and only handle change event, but it is only triggered twice, when I change the watched file with third time, it can not handle change event, my code is here:

var chokidar = require('chokidar');
var path = require('path')
function registerFileChangeListener()
{
 let testfile= path.join(__dirname, '../test.txt')
    let watcher = chokidar.watch(testfile)
     watcher.on('change',(path,stats)=>
        {
            console.log(path +'  is changed')
        })
}
registerFileChangeListener()

But it can fix this issue by adding  
 {
      usePolling:true
    }
 I　am not sure why this happen.

**Comment by birjolaxew** [comment]
Cannot reproduce on Windows 7.1, Node 6.9.1, Chokidar 1.6.1

**Comment by lonelywolf4git** [comment]
I do not try on windows. but it happens on Ubuntu

**Comment by birjolaxew** [comment]
Also cannot reproduce on Arch, Node 7.1.0, Chokidar 1.6.1

**Comment by steelbrain** [comment]
I have been hitting this error as of lately, I'm on v1.6.1 as well
The exact problem I'm hitting is that some files, with really long paths have their change events emitted twice. While files with shorter closer paths have their change event triggered only once.

**Comment by steelbrain** [comment]
My issue turned out to be an EMFILE one

**Comment by metaa** [comment]
Experiencing that [here](https://github.com/metaa/stardew-git/issues/1).
