### ISSUE TITLE
Subsequently added glob patterns (partially) ignored when overlap with previous ones

### ISSUE THREAD

**Issue by goser** [paulmillr/chokidar#559]
Hi,

I tried to reuse a single watcher for multiple file types inside the same root directory. This way I stumbled upon a bug (I think). 

Steps to reproduce:

1. Create following file structure:
```
subdir
    sub2/
        a.txt
        b.xml
        sub3/
            c.ini
 ```
2. Add a watcher and 'add'-listener:
```
var watcher = chokidar.watch('subdir/**/*.txt', {ignoreInitial:false})
watcher.on('add', function(file) {
    console.log('add', file);
});
```
4. Add additional globs when watcher is ready:
```
watcher.on('ready', function() {
    watcher.add('subdir/**/*.xml');
    watcher.add('subdir/**/*.ini');
})
```

The output is:
```
add subdir/sub2/a.txt
add subdir/sub2/b.xml
```
My expectation was:
```
add subdir/sub2/a.txt
add subdir/sub2/b.xml
add subdir/sub2/sub3/c.ini
```

I added [this test](https://github.com/goser/chokidar/commit/f5978a7471d906e16853308eda8f1447faa3f5d4) and tried to fix it myself. To my disgrace all my attempts result in breaking other tests :(

**Comment by es128** [comment]
At a glance, this might be related to other issues with `.add()`

Does it impact the output if you reverse the `.add()` operations?

```js
watcher.on('ready', function() {
    watcher.add('subdir/**/*.ini');
    watcher.add('subdir/**/*.xml');
})
```

**Comment by goser** [comment]
No. Same output.

All directories below sub2 are filtered by the line: 
`if (item === target || !target && !previous.has(item)) {`
inside:
`NodeFsHandler.prototype._handleDir`

This is only happens when added after the first scan completed.

The previous.has-check is true on this point but does not check if subsequent parts of the given path are new.

**Comment by laggingreflex** [comment]
Same issue as #561
