### ISSUE TITLE
Inconsistent behaviour of exclusion rule across OSes

### ISSUE THREAD

**Issue by rasenplanscher** [paulmillr/chokidar#560]
I recently introduced a new watcher in my team's build-chain where I have a directory watched but exclude a sub-directory, like so:
```
gulp.watch(
  [
    'directory/**/*',
    '!directory/not-me'
  ],
  { events: ['add', 'change', 'unlink'] },
  task
)
```
`task` adds and removes `directory/not-me`

With that, everything is fine on Windows, but on OSX the watcher kept firing `task` in an infinite loop...

I changed the setup to this, which fixed the issue: 
```
gulp.watch(
  [
    'directory/**/*',
    '!directory/not-me/**/*'
  ],
  { events: ['add', 'change', 'unlink'] },
  task
)
```

In retrospect, it was obviously an error on my part to forget the `/**/*` in the first version. However, I think the behaviour should be the same irrespective of OS.

**Comment by es128** [comment]
I'm guessing it's more of a watch mode thing, more so than an OS thing - even though it seems to express itself in that way. Like a bug somewhere in the fsevents-specific code.

You could help me confirm that hunch by trying the same scenario with the `useFsEvents: false` option on OS X.

**Comment by rasenplanscher** [comment]
Sure, I will check that out next week. My Mac-colleagues seem to have vanished for the rest of this week :D

**Comment by rasenplanscher** [comment]
@es128 I could finally verify your hunch: using `useFsEvents: false`, it works on OSX just like on Windows.
