### ISSUE TITLE
Issue with dotfiles exclusion? 

### ISSUE THREAD

**Issue by alancwoo** [paulmillr/chokidar#563]
For some reason, the exclusion of dotfiles doesn't seem to be working for me?

In my config I have the same as the example: `ignored: /[\/\\]\./`

However, any edits with vim which create files such as `.filename.swp` or other dotfile events fire. Other exclusion rules seem to work properly.

Is something wrong with my configuration?

I'm using `chokidar 1.6.1` and `node 6.7.0` on `OS X 10.11`

**Comment by es128** [comment]
Depends on the rest of what you're doing, but that regex from the example probably won't work for dotfiles directly in cwd because they won't be preceded with a path separator.

For that you might try `ignored: /(^|[\/\\])\../`

**Comment by es128** [comment]
I checked this new readme locally, seems to do the right thing. Updated the readme. Closing the issue, but if you're still having problems with this one let me know.

**Comment by alancwoo** [comment]
Perfect, thank you!
