### ISSUE TITLE
issue with mounted folder, not detectng new files

### ISSUE THREAD

**Issue by miha-** [paulmillr/chokidar#564]
Hey

i am having some issue. I have mounted webdav folder and chokidar does not detect new files in it. If I look at this filesystem everything looks ok.

tnx
miha

**Comment by miha-** [comment]
just one thing. I a create blank file, with no data, it detect then all new data. Is this a bug are this can be fixed some other way?

**Comment by birjolaxew** [comment]
You're definitely going to need to provide more information. What steps should be taken to reproduce, what code are you using, what's the folder structure, how are you mounting the folder, what versions of Node and Chokidar are you running, what OS are you on, etc.

**Comment by miha-** [comment]
Hello.

Agree.

Server:
CentOS Linux release 7.2.1511 (Core)

Mounting: 
mount.davfs -o rw,user,noauto https://test.domain.si/softnet/cdr /var/www/nodejs/mobileApp/cdrs

NodeJs:
v6.7.0

Chokidar:
"chokidar": "^1.6.1",


```
var dir = chokidar.watch('./cdrs/', {
        persistent: true,
        ignoreInitial: false,

});


 dir.on('add', function(path){
                        console.log(path);

        if(path.split("/")[1] == "CCI"){
                        fs.createReadStream(path).pipe(parse({delimiter:';'})).on('data', function(csvrows){
                                output.push(csvrows);
                console.log(csvrows);
.
```
Folder strocture inside cdrs:
total 29
drwxr-xr-x. 2 root root 18352 Dec  9 08:34 CCI
drwxr-xr-x. 2 root root  1240 Dec  9 01:04 DBD
drwxr-xr-x. 2 root root    64 Jul  5 12:11 EXTservice
drwx------. 2 root root  1152 Dec  9 09:27 lost+found
drwxr-xr-x. 2 root root   288 Dec  8 16:07 TEST
drwxr-xr-x. 2 root root  5888 Dec  8 10:10 SOAxml
drwxr-xr-x. 2 root root   512 Nov 23 10:26 TAPfiles



If you need anything else please let me know!
MIha

**Comment by es128** [comment]
Usually you need the `usePolling: true` option for mounted drives
