### ISSUE TITLE
fsevents optional dependency

### ISSUE THREAD

**Issue by alexbowen** [paulmillr/chokidar#568]
i have 1.6.1 of this module installed. it lists fsevents as an optional dependency in package.json but fsevents is also listed in dependencies. This causes a problem when I shrinkwrap my project after executing `npm install --no-optional`. fsevents is still in my shrinkwrap file and CI complains `npm ERR! notsup Unsupported platform for fsevents@1.0.14: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})`.

However you have removed fsevents in dependencies in package.json when i look at master in this repo. I can manually remove this from my shrinkwrap in the meantime, but I think you need to publish this change as it will surely be causing other people the same problem?

**Comment by es128** [comment]
It has always been an optional dependency, never been in the main dependencies list.

npm does not play well with the combo of optional dependencies and shrinkwrap (https://github.com/npm/npm/issues/2679), you have to take care to ensure it is excluded from your shrinkwrap files.

**Comment by alexbowen** [comment]
hmmm, yes i am aware of that issue, but before i get to do any shrinkwrapping, package.json for chokidar explicitly says:

```  "dependencies": {
    "anymatch": "^1.3.0",
    "async-each": "^1.0.0",
    "fsevents": "^1.0.0",
    "glob-parent": "^2.0.0",
    "inherits": "^2.0.1",
    "is-binary-path": "^1.0.0",
    "is-glob": "^2.0.0",
    "path-is-absolute": "^1.0.0",
    "readdirp": "^2.0.0"
  },
...
  "devDependencies": {
    "chai": "^3.2.0",
    "coveralls": "^2.11.2",
    "graceful-fs": "4.1.4",
    "istanbul": "^0.3.20",
    "mocha": "^2.0.0",
    "rimraf": "^2.4.3",
    "sinon": "^1.10.3",
    "sinon-chai": "^2.6.0"
  },
...
  "optionalDependencies": {
    "fsevents": "^1.0.0"
  },
```
package.json is published with the module, but this is not representative of whats in master of your project? fsevents should not have an entry in dependencies and optionalDependencies should it?

**Comment by es128** [comment]
Not the case in the tarball: https://registry.npmjs.org/chokidar/-/chokidar-1.6.1.tgz

It does show up that way in `npm info chokidar`, but as far as I can tell it always has. I just checked with npm@3 and npm@2, as well as looking at the info output for older versions of chokidar.

I think this observation just goes in as an aspect of the existing issue on the npm side. Not aware of anything we can do over here to help.

**Comment by alexbowen** [comment]
ok, thanks for your time anyway :)
