### ISSUE TITLE
Running alm.tools on termux (android)

### ISSUE THREAD

**Issue by angelosc** [paulmillr/chokidar#571]
This is a followup from https://github.com/alm-tools/alm/issues/404#issuecomment-274358858

Basarat, thanks for looking into this. I've run the provided code but I do not get an error. I've also written tHe folllowing script which seems to work correctly.

$ cat app.js
console.log('a');
var c = require('chokidar');
console.log('b');
$ node app.js
a
b

**Comment by es128** [comment]
Not sure what you're asking for here. You can try running the example.js script from this repo to get a better idea of whether chokidar works in your environment in isolation.

Will re-open if you come back with evidence of an actual issue to report.
