### ISSUE TITLE
Use graceful-fs instead of fs

### ISSUE THREAD

**Issue by steelbrain** [paulmillr/chokidar#572]
The latest release uses [`fs.watch`](https://github.com/paulmillr/chokidar/blob/a3157e3c5239c5069aaa3864866a28d6fd24ef8e/lib/nodefs-handler.js#L37) from [`fs`](https://github.com/paulmillr/chokidar/blob/a3157e3c5239c5069aaa3864866a28d6fd24ef8e/lib/nodefs-handler.js#L3) instead of the `graceful-fs` module, which in turn results in this in our app

<img src="https://cloud.githubusercontent.com/assets/4278113/22355955/b62ddec6-e44f-11e6-8124-ee6c7fea7fb7.png">

**Comment by steelbrain** [comment]
Blocked on https://github.com/isaacs/node-graceful-fs/issues/106

**Comment by paulmillr** [comment]
we're not going to switch to `graceful`. It's up to user.

**Comment by steelbrain** [comment]
@paulmillr I am not really sure how a user could switch to graceful inside of a module that has hardcoded references to the native fs.watch. Could you please elaborate on that?

**Comment by paulmillr** [comment]
```
var realFs = require('fs')
var gracefulFs = require('graceful-fs')
gracefulFs.gracefulify(realFs)
require('chokidar')
```

**Comment by steelbrain** [comment]
That is not an idea solution but could work. Thanks @paulmillr

**Comment by wmertens** [comment]
@paulmillr monkey-patching `fs` is not that great - would you accept a PR that lets the user provide an optional `fs` module, stored on the FSWatcher class?
