### ISSUE TITLE
Option for `ignored` to test against relative paths only

### ISSUE THREAD

**Issue by scottmas** [paulmillr/chokidar#573]
I can't figure out a way to watch a directory and ignore files via their relative path from the `cwd`.

For instance, imagine I want to watch my node_modules directory, but I don't want to watch the node_modules within packages. E.g. we want to watch `./node_modules/package1/blah.js` but we don't want to watch `./node_modules/package1/node_modules/package2/blah.js`

One would think this would work to accomplish that, but it doesn't:
```
var watcher = chokidar.watch('./node_modules', {
  cwd: './node_modules', 
  ignored: /node_modules/  //Ignore if the relative path from the cwd contains node_modules
})
```

Could this be supported? Or is there something I'm missing?

**Comment by es128** [comment]
```js
var watcher = chokidar.watch('.', {
  cwd: './node_modules', 
  ignored: '**/node_modules'  //Ignore if the relative path from the cwd contains node_modules
})
```
