### ISSUE TITLE
Support question - can chokidar help with listening for changes to head of file

### ISSUE THREAD

**Issue by ORESoftware** [paulmillr/chokidar#574]
I have used this library to observe for any changes to a file.
But for a particular use case, I am looking to see if the head of a file changes, but want to ignore other changes.

Can I accomplish this with chokidar?

Here are more specific details:
http://unix.stackexchange.com/questions/341144/use-head-command-or-similar-to-determine-when-bytes-change-in-a-file

**Comment by es128** [comment]
You can use your own code to determine whether the change to the file is something you want to act upon. There is no option built in to chokidar to filter events in that way.

**Comment by ORESoftware** [comment]
Ok, sure understood, when the change event fires though, we don't know what kind of change it was right? It's just change with no further granularity? Totally understandable if that's the case, just making sure.

**Comment by es128** [comment]
Correct

**Comment by ORESoftware** [comment]
thanks
