### ISSUE TITLE
different `path` in `ignored` callback in $TMPDIR after init and change

### ISSUE THREAD

**Issue by tyv** [paulmillr/chokidar#575]
```js
const {watch} = require('chokidar');
const {dir} = require('tmp');
const {mkdirSync, writeFileSync} = require('fs');

dir({unsafeCleanup:true, prefix: 'myTmpDir_'}, (err, path, cleanupCallback) => {
    watch(path, {
        ignored: path => console.log(path)
    });

    mkdirSync(`${path}/a`);
    writeFileSync(`${path}/a/a.txt`, 'a');
});
```

will give output:

```bash
/var/folders/vg/f6zdfz6x7pg69p35xv47ksjddxrvxn/T/myTmpDir_43701b3zwC2NhKswA
/var/folders/vg/f6zdfz6x7pg69p35xv47ksjddxrvxn/T/myTmpDir_43701b3zwC2NhKswA
/private/var/folders/vg/f6zdfz6x7pg69p35xv47ksjddxrvxn/T/myTmpDir_43701b3zwC2NhKswA/a
/private/var/folders/vg/f6zdfz6x7pg69p35xv47ksjddxrvxn/T/myTmpDir_43701b3zwC2NhKswA/a
/private/var/folders/vg/f6zdfz6x7pg69p35xv47ksjddxrvxn/T/myTmpDir_43701b3zwC2NhKswA/a/a.txt
```

you can see first two lines after init is `/var/folders/..` and next, after change are with `/private/var/folders` — which makes writing ignored callback quite hard.

p.s. macOS 10.12.11

**Comment by es128** [comment]
`/var` is a symlink to `/private/var`. At first the `path` provided by your input is checked against your `ignored` callback, then once the file system is actually being crawled, the `fullPath` (as reported by `readdirp`) is checked. It's not a bug. If you choose to do things this way then you need to cope with it in your callback.

The paths that get emitted with actual watch events (which you're not listening to in the snippet you've provided) match the symlink-ness of your input like

```
addDir /var/folders/vg/f6zdfz6x7pg69p35xv47ksjddxrvxn/T/myTmpDir_43701b3zwC2NhKswA/a
add /var/folders/vg/f6zdfz6x7pg69p35xv47ksjddxrvxn/T/myTmpDir_43701b3zwC2NhKswA/a/a.txt
```

**Comment by tyv** [comment]
the problem as I see: I can't guarantee in ignored callback `path === myIgnoredPath` because it is not the same from what I passed and not the same as I am getting in change callbacks.
