### ISSUE TITLE
Matching png in a directory

### ISSUE THREAD

**Issue by nicolas-zozol** [paulmillr/chokidar#576]
I'm trying:

```
var watcher = chokidar.watch('*.png', {
    ignored: /(^|[\/\\])\../,
    persistent: true
});
watcher.on("add", (path)=>{
        console.log('new file :', path);
});
```

which works great. But as I don't want to watch the png in the source directory, i'm trying

```
var watcher = chokidar.watch(__dirname+'/../captures/*.png', {
    ignored: /(^|[\/\\])\../,
    persistent: true
});
```
But I don't catch anything. Or:

```
var watcher = chokidar.watch(__dirname+'/../**/captures/*.png', {
    ignored: /(^|[\/\\])\../,
    persistent: true
});
```
Wich also catch any change on `node_modules`,  including non Pngs. So I guess I don't do it well.

**Comment by es128** [comment]
This is a question about how to use globs, not a chokidar issue. I'd try to help, but you haven't explained clearly enough about your directory structure or what you're trying to accomplish.

**Comment by es128** [comment]
You might try taking your question to stackoverflow - asking how to write a glob that matches what you want. It's not so significant that you're trying to do it with chokidar (as opposed to any other tool that accepts globs for input).
