### ISSUE TITLE
Chokidar emits 'add' events right after chokidar.watch().on() is called?

### ISSUE THREAD

**Issue by NeekSandhu** [paulmillr/chokidar#578]
EDIT: Check my second comment for TLDR
```
platform: win32
node: 6.9.2
chokidar: 1.6.1
```
I had to use chokidar since using regular fs.watch on win32 locks directories and I fixed that with chokidar using `{usePolling: true, depth: 0}`. But now I get false positives.

## How to replicate
```
~ some-folder > ls
styles     scripts     index.html
~ some-folder > node
> process.platform
'win32'
> var chokidar = require('chokidar')
> var watcher = chokidar.watch('../some-folder', {usePolling: true, depth: 0}).on('all', (e, f) => console.log(e, f))
> addDir some-folder
addDir styles
addDir scripts
add index.html
```

## Expected behavior

watcher should not emit events that didn't happen

## Temporary fix

Legitimacy of events emitted by chokidar can be checked by comparing mtime/ctime of a path, before and after.
```
var watch = (path, listener) => {
    if (process.platform === 'win32') {
        var prevStat
        fs.stat(path, (err, stat) => prevStat = stat)
        return chokidar.watch(path, { usePolling: true, depth: 0 }).on('all', async (event, file) => {
            let nowStat = await fsp.stat(path)
            if (nowStat.mtime.getTime() !== prevStat.mtime.getTime() || nowStat.ctime.getTime() !== prevStat.ctime.getTime()) {
                    listener(event, file)
            }
            prevStat = nowStat
        })
    }
}
```

**Comment by NeekSandhu** [comment]
Linux is also effected
Code on RunKit
https://runkit.com/5864ac58dc0ad5001474052d/589ab84131e2b200154c1043

**Comment by es128** [comment]
Sounds like you want `ignoreInitial: true`

**Comment by NeekSandhu** [comment]
😖 My bad

Just out of curiosity, what is the idea behind having them enabled by default? Like any use case I'm not aware of?

**Comment by jonathan-annett** [comment]
@NeekSandhu i'd have thought the idea behind having ignoreInitial enabled by default is, it would be a convenient way to iterate all the files before you start watching them, if for some reason you want to do that.

... and if you were doing that, you can wait for the 'ready' event to know when actual change events are happening.
