### ISSUE TITLE
Request directory exclusion

### ISSUE THREAD

**Issue by epicblood** [paulmillr/chokidar#58]
Hello,
I would like to be able to wath a directory, but exclude on or a few of it's subdirectories.
Something like:
(Pseudocode)

```
watch C:\home\
don't watch C:\home\priv\
don't watch C:\home\default\
```

(sorry if you can already do this, I spent a few hours looking for it and couldn't find)

**Comment by donaldpipowitch** [comment]
The Readme says Chokidar supports globs. I tried notations like `!(priv|default)`, but it didn't work. Can you specify which sorts of globs are supported?

**Comment by es128** [comment]
Don't use negated globs in `ignored` - it's a double-negative. Try `(priv|default)/**/*`

**Comment by donaldpipowitch** [comment]
Yeah, I don't want to use negated globs in `ignored`. I tried them in `paths`.

**Comment by es128** [comment]
Need more details to help you diagnose the problem. What was the full set of paths/patterns you were trying to watch and what was the result?

**Comment by donaldpipowitch** [comment]
Let's say I want to use `chokidar.watch('src/**/*!(_test).js')`. Watch all JS files except test files. I know I can use the additional second params with `ignored`, but I would also expect that the glob would work.

**Comment by es128** [comment]
I'll open an issue with micromatch, the underlying glob matching library for chokidar, regarding my observations using that glob pattern.

**Comment by donaldpipowitch** [comment]
Thanks, I'll watch it.

**Comment by es128** [comment]
@donaldpipowitch you should be able to achieve the result you want by changing the pattern to `src/**/?!(_test)*.js`

// @jonschlinkert

**Comment by StreetStrider** [comment]
Hello. I wonder, what is the proper approach for ignoring in general? Is it negated globs in `path` or `ignored`? In my opinion, using negative paths is better, since you can formulate your intentions in a single input sequence without messing with options (additional input) at all. Does it have any downsides?

**Comment by paulmillr** [comment]
you can use either one, i'd prefer ignored by myself since it's simpler to read
