### ISSUE TITLE
ignoreInitial: false vs. getWatched

### ISSUE THREAD

**Issue by ORESoftware** [paulmillr/chokidar#581]
if you set `ignoreInitial: false`

essentially it fires the on('add')/on('change') handlers when the watcher has initialized.

what I am looking for is `watcher.on('ready')`.   I don't think this is in the docs.

IMO the initial firing should fire watcher.on('ready'), it should not be firing watcher.on('change') or watcher.on('add').

Sorry if I mistaken about this. Is there something akin to `watcher.on('ready')`?

**Comment by es128** [comment]
Yes, there is exactly that, the `ready` event. It *is* in the readme, and it is reflected in the example.js file in the repo as well.

**Comment by ORESoftware** [comment]
sorry! :(
