### ISSUE TITLE
Array passed to watcher, get error

### ISSUE THREAD

**Issue by ORESoftware** [paulmillr/chokidar#582]
```js
const _ = require('underscore');

const include = _.flatten([]);

// Initialize watcher.
const watcher = chokidar.watch(include, {
  ignored: rgx,
  persistent: true,
  ignoreInitial: true,
});
```

I get:

```
TypeError: Non-string provided as watch path: 
    at FSWatcher.add (/Users/alexamil/WebstormProjects/oresoftware/roodles/node_modules/chokidar/index.js:578:11)
    at Object.exports.watch (/Users/alexamil/WebstormProjects/oresoftware/roodles/node_modules/chokidar/index.js:710:33)

```

not sure what to say, since the docs say:

`chokidar.watch('file, dir, glob, or array')` // I assume array means I can pass an array of strings, etc

what might I be doing wrong? thanks

**Comment by es128** [comment]
What's actually in the array? The example you're showing passes an empty array.

**Comment by ORESoftware** [comment]
Right, the array is populated with string paths - but for simplicity I showed it as empty

the error says:
TypeError: Non-string provided as watch path.

This would suggest it doesn't accept arrays. If problem is the array is empty, then I would hope for an error saying "the array you passed is empty".

**Comment by es128** [comment]
I'm guessing there's something illegal inside the array.

**Comment by ORESoftware** [comment]
ok let met get you the actual contents

**Comment by ORESoftware** [comment]
Will chokidar barf if there is more than one item in the array?

**Comment by es128** [comment]
Only if any of the items is not a string. 

https://github.com/paulmillr/chokidar/blob/master/index.js#L577-L580
