### ISSUE TITLE
node v 7.4.0

### ISSUE THREAD

**Issue by AlexNodex** [paulmillr/chokidar#583]
Very strange bug when using chokidar on node v 7.4.0

I can't even see why it's happening however...

When listening for changes on a file any `fs` operation reports a zero byte file. I know it's not an issue with `fs` because I've tested the functions upon script boot, however when chokidar is watching the file, it's somehow zeroing the bytes in the OS cache or something because they report as zero bytes using fs.statSync()...

If I kill the script and start it again, the boot (test) functions report the correct filesize again which tells me that it's not touching the file directly?

Script is below for a test

```
var chokidar = require("chokidar");
var fs = require("fs");
var config_directory=__dirname+'/clients/';
chokidar.watch(['*.client.json'],{ignoreInitial:true, ignored: /[\/\\]\./, cwd: config_directory}).on('all',
 function(event, file) {
   try {
     var file_path = config_directory + file;
     var o = fs.statSync(file); 
     console.log(o);// zero bytes size
   } catch(err) {
     console.log(err);
   }

});
var a = fs.statSync(config_directory + 'hj.client.json');
console.log(a); // correct sizes` 

The test machine is Ubuntu 14.04 with node 7.4.0
I've tested the same script on MacOS (latest) with node 7.2.0 and it works as expected (no bug present)

**Comment by es128** [comment]
It's possible that the file actually is at 0 bytes at the time your run your stat call, depending on the way the editor or whatever other program is operating on the file. A `change` event might be processed faster than the amount of time it takes for the file to be rewritten. 

You could use the `awaitWriteFinish` option in chokidar to delay events until the stat has stabilized.

Either way, it isn't something chokidar has control over or can do anything to affect.
