### ISSUE TITLE
Windows Unwatch does not work

### ISSUE THREAD

**Issue by atomsoftwarestudios** [paulmillr/chokidar#584]
Hello,

I am using chokidar 1.6.0 through the gulp-watch 4.3.11 module on Windows 10 x64, Node.js 7.6.0 x64 (I tried also 7.3.0 x32).

First of all bit of off-topic, I am experiencing problems with deleting subfolders of watched folder.

fs.rmdirSync reports:

```
Error: ENOTEMPTY: directory not empty, rmdir '<abspath_to_some_watched_subfolder>'
```

I am sure it is empty and nobody is holding any file even directory open, except watcher.

But also try to delete a subfolder in windows file explorer and it fails. I am using the following proceudre:

delete subfolder of watched folder -> folder is not deleted, no error reported by windows nor watcher
delete subfolder of watched folder again ->  folder gets deleted -> wathcher/chokidar/node reports:

```
Error: EPERM: operation not permitted, lstat '<abspath_to_watched subfolder'>
```

This is vaid for polling: false. polling: true, as it would be expectable works well, but I would like to avoid it if possible.

It will be probably hard to reproduce for you, the folder structure I am using is up to 6 levels deep with some files within it.

Also I have noticed there is big difference if I am using ```<abspath>/**/*``` or ```<abspath>/*.*``` Both cases behave bit differently but none of them is stable while deleting folders.
I didn't try relative paths.

As I have really old and bad experience with file/folders changes monitoring in windows since W98 when I was using WinAPI from C to monitor folders I know it will be hard to fix these problems, especially when node is targeting all platforms. So I decided to try to find a workaround.

---

I was thinking about unwatching the folder first then deleting subfolders then rewatch the root folder again.

Unfortunately, unwatch seems not to be working at all and I am still getting events on watched folder / subfolders / files. My gulp script is too large and complicated to publish it here but in short, I have tired also following test:

```
   var gulp = require("gulp");
   var watcher = require("gulp-watch");

   var watcherInstance;
   var watchedDir ="<absolute_path_to_dir>/**/*";

   gulp.task("default", function() {

      setTimeout(function() {
         console.log("Unwatching folder: " + watchedDir);
         watcherInstance.unwatch(watchedDir);
      }, 5000);

      watcherInstance = watch(watchedDir, { read: false }, function(file) {
         console.log(file);
      }

      return watcherInstance;
   }
```

please note the read is parameter of gulp-watch and I am not passing any chokidar options so it is using defaults. Watcher instance is a gulp stream wrapping three chokidar functions: add, unwatch and close. When I started this code and modified a file within one of subfolders of a watched folder till 5 seconds I got change event. That's correct. But I was getting the same event even after unwatching the folder.

I have checked if the problem can't be in the gulp-watch itself but I have found the unwatch is directly bound to chokidar unwatch so I don't think the problem can be there.

---

As the final workaround I have prepared complete stopping of the gulp-watch / chokidar or using of polling: true but it would be much better if problems with deleting subfolders of watched folder or unwatch can get fixed :)

**Comment by atomsoftwarestudios** [comment]
So after few other tests, even if I stop watcher by calling close() the behavior is still the same, unable to delete folders. It seems that node holds something internally.

**Comment by atomsoftwarestudios** [comment]
So the workaround with complete stopping is working. No hurries with fixing mentioned issues ;)

**Comment by es128** [comment]
The `.unwatch()` method might not actually stop watchers if given a subset of the path(s) originally watched. In that case it acts more like the `ignored` option, just introduced after the fact. This probably explains most of the behavior you've described, although I had a hard time following the narrative you presented.

The errors you experienced come from the windows file system - even if it's the watcher that's locking up those entries, there's nothing we can do about it.

**Comment by atomsoftwarestudios** [comment]
Thanks for your answer! I really appreciate it.

I understand the .unwatch actually does not stop watchers. However, I should not receive any events for unwatched folder as they should be filtered out somehow :) Ofcourse, it can't solve problems described above. Hopefully I'll find time to debug it and contribute to this project.

Errors related to filesystem monitoring are probably more related to node fs.watch windows implementation than to chokidar itself. But it should be working. Explorer works too when it monitors the folders :). It is using the same WinAPI methods & notification - ReadDirectoryChangesW Unfortunately I have no time to debug it now. I am suspicious the problem will be in creating multiple RDCWs for the whole dir subtree and monitoring changes for them, but it would require a little bit of debugging what I have no time now.

For this time, I am good with workaround I have described. Closing the watcher works well.

**Comment by atomsoftwarestudios** [comment]
Hello  again, unfortunately, my workaround does not work too. Sometimes it fails even if I close the chokidar as it seems that monitoring handles are not closes properly.

Just a qq, when I close chokidar, don't you know if it properly closes any underlying subsystems in fs.watch and it consequently releases all open handles to dirs it watches?

Unfortunately, I am not node specialist so before I'll spend so many time with debugging it, I rather ask you and node guys. 

From a quick sources review I can see the watcher.close() is called in the chokidar itself.  Also, it seems win the library (fs-event.c) for node seems to be closing dir handles properly as well but I don't know if this really happen and it is not blocked somewhere in between.

Thanks.

**Comment by atomsoftwarestudios** [comment]
So. No. After bit of experimenting I am experiencing same issues as before. It seems the chokidar watcher does not properly release all opened watchers on close(). When I call

      process.nextTick(function() {
           watcher.close();
           console.log(process._getActiveHandles());
           console.log(process._getActiveRequests());
          // proces should exit now as there is nothing else in the event queue by me, but it actually does not, because something is keeping it running 
     }

which is actually called on a file change event. I can see tons of fs.watcher event handlers there even if they should be closed.

Unfortunately I have to move further so I switched directly to fs.watch what is painfull but seems to be working now and I can't spend another 3 to 5 days with debugging of 5 layers of code (my code, chokidar, watch, node, windows).
