### ISSUE TITLE
chokidar as dependency: warning when doing npm install

### ISSUE THREAD

**Issue by papakai** [paulmillr/chokidar#589]
See here, for

grunt-nodemon: https://github.com/ChrisWren/grunt-nodemon/issues/73
pm2: https://github.com/Unitech/pm2/issues/2774

Thanks for having an eye on it.

ok: https://github.com/paulmillr/chokidar/issues?utf8=%E2%9C%93&q=is%3Aissue%20warning

**Comment by es128** [comment]
npm chooses to to output that warning, more discussion at https://github.com/npm/npm/issues/11632

**Comment by papakai** [comment]
ty!
