### ISSUE TITLE
rename raw event breaks further events

### ISSUE THREAD

**Issue by fdiogo** [paulmillr/chokidar#591]
.watch seems to break when there's a 'rename' event on Linux and no more events are fired from there on.
Vim fires this on wq and Git on checkout, for example.

The current workaround I'm using seems to fix this:
```javascript
this.watcher.on('raw', (event, path, {watchedPath}) => {
            if (event === 'rename') {
                this.watcher.unwatch(watchedPath);
                this.watcher.add(watchedPath);
            }
        });
```
It seems this might be easily patched out by verifying that the renamed file has the same name and re-attach the listener automatically.

**Comment by es128** [comment]
Please provide a script or repo for demonstrating the problem. I suspect the cause is something different than just receiving a `rename` event from `fs.watch()`.

**Comment by AndyOGo** [comment]
I observe a similar behaviour on my CI tests at Linux if an empty dir is deleted:
https://travis-ci.org/AndyOGo/node-sync-glob/jobs/220915572#L976

```sh
console.log src/index.js:242
    RAW: rename -> empty 	
    { watchedPath: 'tmp/mock/bar/empty' }

console.log src/index.js:242
    RAW: rename -> empty 	
    { watchedPath: 'tmp/mock/bar/empty' }

console.log src/index.js:242
    RAW: rename -> empty 	
    { watchedPath: 'tmp/mock/bar' }

 FAIL  test/sync.spec.js (13.696s)
  ● node-sync-glob watch › should sync empty sub directory deletion
    Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
      
      at ontimeout (timers.js:386:14)
      at tryOnTimeout (timers.js:250:5)
      at Timer.listOnTimeout (timers.js:214:5)

  node-sync-glob watch
    ✓ should sync a file (2135ms)
    ✓ should sync an array of files (2125ms)
    ✓ should sync a directory (2153ms)
    ✓ should sync globstar (2149ms)
    ✕ should sync empty sub directory deletion (5008ms)
```

**Comment by fxha** [comment]
I also have this problem when editing a file which is watched. For example if you watch just `a.txt` and edit the file with `gedit`, only the first edit is triggered. I think the problem is the `rename` event and chokidar still listen on the old file. Gedit result:

```
raw: "change" "a.txt"
raw: "rename" "a.txt"
raw: "rename" "a.txt"
change: "%path%/a.txt"
```

Where as `atom/watcher` triggers the `creation` event. With other editors like vim or vscode everything works fine and further events are triggered:

```
raw: "change" "a.txt"
raw: "change" "a.txt"
change: "%path%/a.txt"
```

Listening the whole directory shows that gedit creates a temporary backup file and then just move the backup file:

```
created file: %path%/.goutputstream-VP92YZ
modified file: %path%/.goutputstream-VP92YZ
modified file: %path%/.goutputstream-VP92YZ
renamed file: "%path%/.goutputstream-VP92YZ" to "%path%/a.txt"
```

**Comment by pkit** [comment]
Cool, 2 years, no fix. Splendid!

**Comment by paulmillr** [comment]
@pkit Go ahead and fix it. No one pays me to do this.

**Comment by pkit** [comment]
@paulmillr it would have more contributors if the tests were not failing left and right on unrelated things.

**Comment by paulmillr** [comment]
@pkit see #923, fixing failing tests is not a simple task.
