### ISSUE TITLE
Windows 10: creating a new folder and immediatly renameing does not trigger

### ISSUE THREAD

**Issue by AndyOGo** [paulmillr/chokidar#592]
If I create a `New folder` within explorer's context menu chokidar triggers `addDir` event during watch mode with default folder name `New folder`, but if I immediately change it's name to `foo` or anything else nothing happens, neither a `change` event nor an `unlinkDir` followed by `addDir` event.

**Comment by es128** [comment]
Please add a listener for the `raw` event and show what it emits while you follow this sequence of actions.

**Comment by AndyOGo** [comment]
hmh, is closing the right choice?
IMHO it's Windows 10 problem, though may not many people have this use case 🤔

**Comment by paulmillr** [comment]
I've been diving through issues, some of them have "ups", which means other folks experience those. Some have mentions from other projects, fairly recent. And some of them seem critical, like process crashing.

Here we don't seem to have any of those...

**Comment by AndyOGo** [comment]
Thanks for your quick reply. I mostly agree with you.
Though events not being catched or fired by the OS fall into critical IMHO.
