### ISSUE TITLE
awaitWriteFinish ignored on initial files

### ISSUE THREAD

**Issue by coolheinze** [paulmillr/chokidar#594]
With awaitWriteFinish set and ignoreInitial false, initial files fire immediately, despite the fact that they could be in the process of writing. awaitWriteFinish should honour this and not fire the add event until stabilityThreshold is exceeded.

**Comment by es128** [comment]
https://github.com/paulmillr/chokidar/blob/master/index.js#L195

The ` && this._readyEmitted` part of that line is what prevents what you're asking for, but I'm not sure what else would be impacted by removing it. Try it out with your use case to see what happens and let me know.

**Comment by nickverlinden** [comment]
I can vouch for your answer, es128. Am experiencing the same problem and removing that part solves it.

**Comment by es128** [comment]
@nickverlinden feel free to submit a PR, and we can see how it fares against the test suite.
