### ISSUE TITLE
High CPU usage on OSX with no polling

### ISSUE THREAD

**Issue by yebrahim** [paulmillr/chokidar#597]
Is there anything to do to slow down the file tree walk process on OSX? If the directory is deep, chokidar pegs my CPU to max until it finishes scanning the directory, this happens only on OSX.

For my use case, I don't really care about how fast the scan/index is finished, I tried setting polling to false but I'm not seeing any difference.

**Comment by es128** [comment]
See #412

**Comment by yebrahim** [comment]
Thanks for the pointer. Are you guys exploring merging that PR or finding a better way to do this? It seems that exposing an option to slow down the walk is low-hanging fruit in my understanding?

**Comment by es128** [comment]
> low-hanging fruit

Possibly, but changing the underlying lib is risky. We'd either have to vet it to try to minimize the likelihood it will substantially impact existing users or make it part of a major release.

That thread veered in a few directions at the time, and there hasn't been much motivation to move forward. I suppose @kmalakoff wound up proceeding with a fork that used his solution?

I can't recall there being many other people coming with the same sort of concern.

Are you in a position to be able to try it out with your use case and give feedback?

**Comment by yebrahim** [comment]
I understand, making this change should keep the current behavior unless a new option is specified, so that current users aren't broken.

It looks like @kmalakoff's fork isn't maintained, so I might fork off and try that on my own. I'll try to do that soon and report any feedback here.

**Comment by kmalakoff** [comment]
@yebrahim I've been using the fork without any problems. I just don't want to publish it on npm and there was lack of activity by chokidar maintainers...feel free to fork again and get this merged.

**Comment by paulmillr** [comment]
Continuing in #447
