### ISSUE TITLE
Show error message about why `fsevents` could not be required

### ISSUE THREAD

**Issue by vjpr** [paulmillr/chokidar#599]
At present the error is silenced:

```
try { fsevents = require('fsevents'); } catch (error) {}
```

https://github.com/paulmillr/chokidar/blob/85df8a78af3fd654784286cd79c9307391c18357/lib/fsevents-handler.js#L7

Sometimes `fsevents` cannot be required because it has been compiled against the wrong node abi. 

```
try { fsevents = require('fsevents'); } catch (error) { console.log(error) }
```

```
Error: Module did not self-register.
    at Error (native)
    at Object.Module._extensions..node (module.js:583:18)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/Vaughan/dev-live/webpackerator/node_modules/.registry.npmjs.org/fsevents/1.1.1/node_modules/fsevents/fsevents.js:14:14)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/Vaughan/dev-live/webpackerator/node_modules/.registry.npmjs.org/chokidar/1.6.1/node_modules/chokidar/lib/fsevents-handler.js:7:18)
```

Or the user has not installed it correctly.

We could check for the different kinds of errors that occur when requiring a module and show an informative error message.

A very common issue is high CPU usage (100%+) when `fsevents` fails to be required when using `webpack` (`watchpack` requires `chokidar`). I would say that a lot of the time the user doesn't notice what went wrong, but their computer is being slowed down immensely. For this reason, I )would argue for the error message to be shown...or have an event hook...or have an environment variable that would allow printing the error message. E.g. `process.env.CHOKIDAR_PRINT_FSEVENTS_STATUS`.

**Comment by es128** [comment]
Not going to have chokidar start printing messages. That's the domain of the app/tool, not the utility module.

However, I would consider the event hook and env var ideas. But it would have to overcome the counterargument that if the tool using chokidar wants to go out of their way to utilize the feature and print a message, why can't they just directly detect the condition regarding fsevents themselves? Perhaps a separate `fsevents-compat-warning` module, if there's an appetite for such a thing.

**Comment by vjpr** [comment]
> why can't they just directly detect the condition regarding fsevents themselves?

Unless you add a `console.log` to that line of code, you cannot be 100% sure that it is being used. 

If you tried adding `require('fsevents')` to your code, it would be resolving it from your __dirname which would not be the same as how it is required in chokidar. You would have to use something like the `require-from` package, but then you would have to locate the specific chokidar package as there could be multiple instances. Other package managers have different node_modules structures, etc.

For these reasons, I would argue for the env var approach. Which would report the `__dirname` and whether it failed, and for what reason. And also report when it is enabled.

**Comment by es128** [comment]
The thing I don't like about the ENV approach is that it still leaves chokidar to do the actual messaging, and I think the dependent tools should take direct control over that.

Chokidar could perhaps gather the data in the `catch`, then later emit it as a specialized `error` event when a watcher instance is instantiated, and tool authors could take it from there. Can you think of any other lightweight approach?

You've made your case about the need for some sort of solution. PR welcome.

**Comment by vjpr** [comment]
> it still leaves chokidar to do the actual messaging, and I think the dependent tools should take direct control over that

The issue is that a developer using chokidar may never encounter the error themselves to realise that they should handle it. They will only realise the error after they are responding to someone else's github issue, and go through a long debug session like I did to discover that the error is being swallowed silently. Its putting the user through some real pain.

##### We could handle the individual errors for require failing. 

If we regex match the error to be: `Module did not self-register.` then we should throw because that is an exceptional circumstance. But I guess then this would tie us to a specific Node version range if they change the error message.

##### We could only not throw for error `module not found`

If the module is not found, the chokidar consumer should definitely be able to receive a notification of this. But as I said earlier, most developers won't see the need to until they are debugging someone else's code.

##### Option for showing fsevents warning

How about an option passed to chokidar that tells it whether to silence the fsevents not found error.

By default this could be false, meaning the error would be printed to the console.

It could also take a callback function with the actual error to allow the user to alert the user themselves.

The advantage of this approach is that the chokidar consumer is forced to think about this occurring, and if it does occur for someone, the complaint will be "I always see this warning message about fsevents", instead of "webpack-dev-server is incredibly slow".

**Comment by es128** [comment]
I'll maintain that it is not chokidar's place to start printing console messages for any reason. Based on past experience, I predict many more users would be upset by it than the number who are helped. Chokidar does its job when `fsevents` is absent or fails to run. Comparatively poorer performance is not quite the same as an error.

I understand you just went through some pain trying to support a user that got into an odd state. I think this merits some explanation in the troubleshooting section of the readme, but not necessarily much else. If you want to take it further and submit a patch that emits information about the failed `require` as an `error` event so that tools can choose to notify their users in an appropriate way, I'd consider that as well.
