### ISSUE TITLE
All events stop being emitted on Linux when file is replaced

### ISSUE THREAD

**Issue by deemson** [paulmillr/chokidar#601]
As of chokidar v.1.6.1

Steps to repro:

```javascript
const chokidar = require('chokidar')

let watcher = chokidar.watch('file.txt')
watcher.on('raw', (event, path, details) => {
  console.log('Raw event info:', event, path, details)
})
```

Now, if I modify the file `file.txt`

```bash
touch file.txt
# or
echo some > file.txt
```

events are reported.
If I do something like:

```bash
echo something > z.txt
mv z.txt file.txt
```

i.e. replace the original `file.txt` with new one, chokidar stops emitting events.

This issue may be seen when using Emacs with chokidar on Linux: Emacs seems to be doing exactly what is described above when it creates backups. Maybe this could be relevant to somebody in frustration about what is going on.

**EDIT** tried that on my MacOS (same script, same chokidar version) -- it won't repro.

**Comment by es128** [comment]
Why are you only watching the individual file and only listening to the `raw` event? That's only showing you what `fs.watch()` is doing, not what chokidar is doing.

`usePolling: true` is one solution, but I suspect this is a contrived example.

Listening to chokidar's regular events, and watching the directory, or even a glob that would only match this file (like `[f]ile.txt`), would likely solve the problem. You could also play with the `atomic` option.

**Comment by deemson** [comment]
Sorry, my bad.
I've actually listened to both `raw` and `all`. Watching the directory instead of a single file indeed solves the problem.
