### ISSUE TITLE
Tracking single folder with ignored complex subdirectory tree is slow.

### ISSUE THREAD

**Issue by AdaRoseEdwards** [paulmillr/chokidar#603]
The goal is to look into a single folder to see if files are added/deleted/changed and ignore all the sub directories.

If I use the example from the readme in my home directory it is very slow to start even though I am ignoring all the sub directories.

```
var watcher = chokidar.watch(process.env.HOME, {
  ignored: /(^|[\/\\])\../,
  ignorePermissionErrors: true,
  alwaysStat: true,
  ignoreInitial: true
});
```

If I append the path with /*.* to make it a glob for the files it is very fast. But misses files with no extensions.

It seems that it is watching the whole sub directory tree.

I looked through the documentation and I couldn't find a way to make a glob which matched just the contents of a single dir but no sub dir.

Am I missing something?

**Comment by es128** [comment]
`depth: 0`

**Comment by AdaRoseEdwards** [comment]
Can't believe I missed that, thank you!

**Comment by es128** [comment]
No problem 😺
