### ISSUE TITLE
ignore regular expression with negative lookahead not working

### ISSUE THREAD

**Issue by shawninder** [paulmillr/chokidar#604]
Consider this example, heavily inspired from **example.js** in this repo:

**brokenExample.js**
```javascript
var chokidar = require('./').watch('.', {
  ignored: [
    /\.git|node_modules(?!\/cliui)/,
    /[\/\\]\./
  ],
  persistent: true,
  usePolling: false
})
  .on('change', log('change'))
  .on('add', log('add'))
  .on('ready', log('ready'))
  .on('error', function (err) {
    console.log('err', err);
  });

function log (tag) {
  return function () {
    console.log(tag)
  }
}
```
As you can see, I am trying to tell chokidar to watch the current directory but ignore dot files and node_modules, with the exception of **node_modules/cliui**. To achieve this exception, I am using a negative lookahead in my regular expression: `node_modules(?!\/cliui)` so it should match all occurences of `node_modules` which are not immediately followed by `/cliui`.

This example is useful in the case where you are developing a module and one of its dependencies concurrently. The dependency could be `npm link`ed, for example. In cases like this, you want the files of the module and the dependency to be watched, but none of either's node_modules.

Let's run this file:
```sh
node brokenExample.js
```

Expected:
- saving the above file (brokenExample.js) should trigger the `change` event, and it does (success)
- saving **node_modules/chalk/index.js** should *not* trigger the change event since it is in node_modules, and indeed it doesn't (success)
- saving **node_modules/cliui/index.js** should trigger the `change` event since it is the exception, but it doesn't (FAILURE)
- saving **node_modules/cliui/node-modules/index.js** should *not* trigger the `change` event since it contains a `node_modules` not followed by `/cliui`, and indeed it doesn't (success)

Any clue what is going wrong here?

**Comment by shawninder** [comment]
Btw I am trying this on Ubuntu running node v6.9.1

**Comment by es128** [comment]
You need the regex to NOT match `node_modules` or else it gets ignored and chokidar does not traverse down into its contents. 

I think this will work `/\.git|node_modules\/(?!cliui)/`
