### ISSUE TITLE
can not resolve tmp directory in ubuntu 

### ISSUE THREAD

**Issue by gy134340** [paulmillr/chokidar#608]
The system is Ubuntu 12.04, the node version is 7.10.0

but the following code cannot work, and the command ` node index.js`  just flash and exit

```
...
var watcher = chokidar.watch('./aquair/uploads', {
	ignored: /(^|[\/\\])\../,
	persistent: true
});
...
```
then I  remove the `./` and it works, is it something wrong with the detecting  mechanism for the directory.

```
...
var watcher = chokidar.watch('aquair/uploads', {
	ignored: /(^|[\/\\])\../,
	persistent: true
});
...
```

**Comment by ultimate-tester** [comment]
Can you please provide the absolute path to the index.js file and the absolute path to the uploads folder?

**Comment by gy134340** [comment]
@ultimate-tester   it's like following:

the `index.js`

```
/var/www/app/index.js     // node  index.js  command  here
```
the directory  to detect 

```
/var/www/app/aquair/uploads       
```

**Comment by es128** [comment]
I think the `ignored` regex you're using is matching the version that starts with `./`

**Comment by gy134340** [comment]
@es128 thanks for that, it's my carelessness
