### ISSUE TITLE
Add an option to specify custom FileSystem (FS) implementation

### ISSUE THREAD

**Issue by ultimate-tester** [paulmillr/chokidar#609]
I would like to be able to override the FS implementation that is used. There are a lot of custom FileSystem implementations, for instance webdav-fs which exposes the same methods as the "normal" filesystem. Therefore if I'd be able to override the full FS object that chokidar uses, I can use those custom FileSystem implementations to monitor files (in my particular case I want to monitor files on webdav, even though it might be slow I have an interval of 1 minute).

**Comment by es128** [comment]
Feel free to submit a PR. If it's a simple implementation that doesn't get in the way of any of the existing functionality then it has a good chance of being accepted. But it'll have to be a "use at your own risk" type of thing. I have no interest in supporting issues stemming from the use of custom or wrapped fs implementations.

**Comment by ultimate-tester** [comment]
Okay I decided to give it a shot. A little bit of work needs to be done to be able to specify a custom filesystem, and the final result definitely needs to use polling (or the custom filesystem needs to implement the "watch" methods as well which my test case doesn't). 

The first problem I encounter is at the polling part where the module readdirp get's called. In my opinion this dependency needs to go in favour of a custom written recursive readdir using the filesystem's "readdir" method. There is no way around this, because otherwise chokidar will never use the custom filesystem's readdir method to provide its files thus never firing events. 

I just wanted to know if you're okay with me removing the readdirp dependency and writing my own custom replacement. It won't break anything and the tests should still be able to succeed. Please let me know.

**Comment by es128** [comment]
No, that's a very significant change that I don't think we'd accept for the sake of your original feature request.

If polling with `fs.watchFile()` works with webdav-fs have you tried just using it directly? What's your motivation for trying to push chokidar into the equation?
