### ISSUE TITLE
chokidar firing twice

### ISSUE THREAD

**Issue by vasyl-shumskyi** [paulmillr/chokidar#610]
I moved from `fs.watch()` to chokidar because of `fs.watch()` multi-calls
But chokidar also firing twice even in simplest scenario:

```
chokidar.watch(file).on('change', (event, path) => {
      console.log(event, path);
 }
```

How can I  make sure chokidar fires only once? 

Versions:
```
chokidar:  1.7.0
Node v7.10.0
MacOS Sierra 10.12.3
```

Thanks!

**Comment by dhruv004** [comment]
+1

Versions:
```json
Chokidar: 1.7.0
Node: v6.10.3
OS: Windows 8
```

**Comment by es128** [comment]
There probably actually are separate changes happening to your file. Chokidar makes some attempts at suppressing duplicate events, or events arising as artifacts of atomic save techniques employed by some text editors. 

But if it's not working well enough in your case you could consider using the `awaitWriteFinish` option in chokidar or employing a separate debounce utility that you can tune to whatever parameters work best for you.

**Comment by corvuscornix** [comment]
I have the same issue. I think it's IntelliJ making multiple changes then.

**Comment by liesislukas** [comment]
```
      awaitWriteFinish: {
        stabilityThreshold: 2000,
        pollInterval: 100,
      },
```

just delays double event by some time for me. tracking changes by IntelliJ WebStorm. WebStorm is doing some magic on it's own for sure when it comes to file writes so probably that's related.
