### ISSUE TITLE
Windows 10: Watching a dir prevents moving/renaming its content in explorer

### ISSUE THREAD

**Issue by sebn** [paulmillr/chokidar#611]
Hello there, first thank you very much for such a nice lib!

My config:
- node 6.10.2
- npm 3.10.10
- chokidar 1.7.0

When I run the following script...

```javascript
var chokidar = require('chokidar');
var fs = require('fs')
var path = require('path')

var dir = path.resolve('./tmp')
if (!fs.existsSync(dir)) fs.mkdirSync(dir)
var watcher = chokidar.watch('.', {
  cwd: dir
})
watcher.on('raw', (event, path, details) => {
  console.log('Raw event info:', event, path, details);
});
```

... and I start adding content in the Windows file explorer, it seems that as soon as a directory has a subdir, I cannot move/rename it anymore: Windows shows a popup saying the directory may be busy.

When I stop the watching script, I can move/rename everything again.
The issue doesn't occur when passing `usePolling: true` to chokidar.

Any idea of the best way to debug this?
Thanks

**Comment by sebn** [comment]
Example output before failing at renaming `foo` to `foo2`:

```
PS C:\Users\Seb\src\windows-busy> node .\index.js
Raw event info: rename Nouveau dossier { watchedPath: 'C:\\Users\\Seb\\src\\windows-busy\\tmp' }
Raw event info: rename Nouveau dossier { watchedPath: 'C:\\Users\\Seb\\src\\windows-busy\\tmp' }
Raw event info: rename foo { watchedPath: 'C:\\Users\\Seb\\src\\windows-busy\\tmp' }
Raw event info: rename Nouveau dossier { watchedPath: 'C:\\Users\\Seb\\src\\windows-busy\\tmp\\foo' }
Raw event info: change foo { watchedPath: 'C:\\Users\\Seb\\src\\windows-busy\\tmp' }
Raw event info: rename Nouveau dossier { watchedPath: 'C:\\Users\\Seb\\src\\windows-busy\\tmp\\foo' }
Raw event info: rename bar { watchedPath: 'C:\\Users\\Seb\\src\\windows-busy\\tmp\\foo' }
Raw event info: change foo { watchedPath: 'C:\\Users\\Seb\\src\\windows-busy\\tmp' }
```

**Comment by es128** [comment]
Nothing we can do here afaik, seems to just be a side effect of the `ReadDirectoryChangesW` system API provided by Windows that `fs.watch()` utilizes. To avoid it, use polling, or turn off the watcher when making the sorts of changes that are in conflict.

**Comment by sebn** [comment]
Ok, thanks for the explanation!

**Comment by sebn** [comment]
I can do the same creation/renaming/move actions from a node script and it seems to work... Also it doesn't occur for a directory containing only files... Isn't it strange? (sorry for bothering you again with this)

**Comment by es128** [comment]
Yes, it's strange. You're not the first one to report it. But it's something the Windows OS is responsible for.

**Comment by LokiMidgard** [comment]
I know it's old and propably already solved. But I stumbled over the same issue. I found out that I created the directory handle only with `FILE_SHARE_READ` since the HANDLE did not allow write I couldn't move files in.

I changed the handle creation to:
```c++
CreateFile(path,
        FILE_LIST_DIRECTORY,
        FILE_SHARE_READ| FILE_SHARE_WRITE| FILE_SHARE_DELETE,
        nullptr,
        OPEN_EXISTING,
        FILE_FLAG_BACKUP_SEMANTICS | FILE_FLAG_OVERLAPPED,
        nullptr)
```

So it is less an OS problem then a porblem of the library that calls the OS API.

**Comment by paulmillr** [comment]
Update your chokidar to v3
