### ISSUE TITLE
Assertion failed: (0), function uv_close, file ../deps/uv/src/unix/core.c, line 173.

### ISSUE THREAD

**Issue by doughsay** [paulmillr/chokidar#612]
I have a test suite that runs a bunch of tests that read and write files to disk pretty rapidly.  I get this error when running the test suite in Node 8.0.0 and 8.1.0.  It runs fine in 6.10.3.

`Assertion failed: (0), function uv_close, file ../deps/uv/src/unix/core.c, line 173.`

This error does NOT occur if I disable the chokidar file watcher.  If I still enable the watcher, but just ignore all events, the error still occurs.

I'm on OSX, and if I disable FsEvents (`useFsEvents: false`), then it works.

I get nothing else with this, no stack trace, no details.  The process just dies with this message...

**Comment by shnhrrsn** [comment]
Seeing this in 8.2.1 as well

**Comment by mattdesl** [comment]
FWIW I think I may have fixed this in my own project by waiting for a `'ready'` event before calling `watcher.close()`. See here:
https://github.com/mattdesl/budo/blob/38b7fe25d0c758aea7179f6cb8a6562723012581/lib/file-watch.js#L28

**Comment by OmgImAlexis** [comment]
Just randomly got this from the Vue cli while hitting CTRL+C.

```

> my_servers-webui@0.0.8 start /Users/xo/code/unraid/my_servers-webui
> vue-cli-service serve

 INFO  Starting development server...
98% after emitting CopyPlugin

 DONE  Compiled successfully in 7099ms                                                                                                                                                 3:35:35 pm


  App running at:
  - Local:   https://localhost:4000/ 
  - Network: https://localhost:4000/

  Note that the development build is not optimized.
  To create a production build, run npm run build.

^CAssertion failed: (0), function uv_close, file ../deps/uv/src/unix/core.c, line 174.
```

**Comment by Vesper-0407** [comment]
> Just randomly got this from the Vue cli while hitting CTRL+C.
> 
> ```
> 
> > my_servers-webui@0.0.8 start /Users/xo/code/unraid/my_servers-webui
> > vue-cli-service serve
> 
>  INFO  Starting development server...
> 98% after emitting CopyPlugin
> 
>  DONE  Compiled successfully in 7099ms                                                                                                                                                 3:35:35 pm
> 
> 
>   App running at:
>   - Local:   https://localhost:4000/ 
>   - Network: https://localhost:4000/
> 
>   Note that the development build is not optimized.
>   To create a production build, run npm run build.
> 
> ^CAssertion failed: (0), function uv_close, file ../deps/uv/src/unix/core.c, line 174.
> ```
I have noticed the same problem as yours and this hasn't happened before. How did you fix it and would it have any bad effects? Because everything seems okay while running but the problem only occurs after I stop the server.
