### ISSUE TITLE
Glob not working for multi-level paths within braces

### ISSUE THREAD

**Issue by bustbr** [paulmillr/chokidar#614]
Using the latest version (1.7.0) there's a bug in the [`filterDir`](https://github.com/paulmillr/chokidar/blob/1.7.0/index.js#L434) function of [`FSWatcher._getWatchHelpers`](https://github.com/paulmillr/chokidar/blob/1.7.0/index.js#L383).

Using the watcher like this:
```js
chokidar.watch('./{foo/bar,qoo}/**/*.js', opts)
```
will call [`dirParts = getDirParts(path)`](https://github.com/paulmillr/chokidar/blob/1.7.0/index.js#L430) with `path = '{foo/bar,qoo}/**/*.js'` which leads to `dirParts` being set to `['{foo', 'bar,qoo}', '**']`, which will never match any of the targeted files (e.g. `./foo/bar/test.js` or `./qoo/test.js`).

**Comment by jonschlinkert** [comment]
To avoid splitting inside brackets or quoted strings, maybe we should consider using [split-string](https://github.com/jonschlinkert/split-string), with `options.brackets` set to `true`.
