### ISSUE TITLE
not update server after change

### ISSUE THREAD

**Issue by heinhoang** [paulmillr/chokidar#621]
I want to watch files changing in express app and reload server but it's not working.
```
server.listen(port, () => {
            console.log('server start');
        });
    const watcher = chokidar.watch(['./app', './front/views'], { persistent: true });

    // Browser Sync
    const filesToWatch = [
        './public/**/*',
    ];
    browserSync.init(null, {
        proxy: 'http://localhost:3000',
        files: filesToWatch,
        port: 4000,
        // browser: ['google-chrome'],
    });

    watcher.on('ready', () => {
        watcher.on('all', () => {
            browserSync.reload();
            console.log('watching for app change...');
        });
    });
```
after changing some codes in express app. Such as:
from
```
app.get('/contact', contactController.contactGet);
```
to
```
app.get('/contact-change', contactController.contactGet);
```
server not update???

**Comment by es128** [comment]
This isn't a chokidar issue, but I don't see any indication that you're restarting the backend app upon code changes. BrowserSync only reloads the frontend for you.

There are several tools out there for watching for backend code changes (with chokidar) and automatically restarting your node process for you, such as PM2 and nodemon.

**Comment by heinhoang** [comment]
I know that. I just try to find a new way to reload server using chokidar
only but I'm fail.
Anyway, thanks,
