### ISSUE TITLE
interval failed

### ISSUE THREAD

**Issue by feifeipan** [paulmillr/chokidar#623]
```
 this.state.watcher = chokidar.watch(buildPath, {
                usePolling: true,
                interval: 2000,
                binaryInterval: 2000,
                CHOKIDAR_INTERVAL:2000,
                ignored: mm.makeRe("node_modules|\.DS_Store|pom.xml",{dot:true}),
                ignoreInitial: true

            });

 this.state.watcher.on("all", (event, path)=>{
                console.log("all"+event, path);
                this.getFileList();
            });
```

The directory changed frequently , and I need to check it 2 seconds a time. 
But it seems anything changed will trigger. 

so the "getFileList" function execute so many times.

Do I miss something?Thanks.

**Comment by es128** [comment]
`interval` is not an event throttle, it just describes how often each of the fs entries you are watching will have their stats checked. You shouldn't be getting events on the same file or dir more frequently than once every 2 secs, but you still can if multiple files are being touched at once. 

Seems like what you want is to wrap your event handler with a throttle or debounce utility.
