### ISSUE TITLE
  code: 'ENOSPC',   errno: 'ENOSPC',

### ISSUE THREAD

**Issue by cool-firer** [paulmillr/chokidar#624]
I met across the error:

Error happened { [Error: watch /var/test/testproject2/cases.Display.xml ENOSPC]
  code: 'ENOSPC',
  errno: 'ENOSPC',
  syscall: 'watch /var/test/testproject2/cases.Display.xml',

on Ubuntu, is there a solution?

**Comment by es128** [comment]
You can be more targeted about how much you're watching, or increase your system's user watches limit as described at https://stackoverflow.com/questions/16748737/grunt-watch-error-waiting-fatal-error-watch-enospc
