### ISSUE TITLE
Chokidar ignoring persistent flag on Windows

### ISSUE THREAD

**Issue by cjrutherford** [paulmillr/chokidar#625]
Versions of Node Tested with: 8.1.4, 6.0.0, 6.11.1
Chokidar Verseions Tested: 1.5.0,1.6.0,1.7.0

Code Tested with:

```
const ck = require('chokidar');
const fs = require('fs');
const path = require('path');

var watchList = ['./test-watch'];
var watcher = ck.watch(watchList, {ignored: /(^|[\/\\])\../, persistent: true});

watcher.on('raw', (e, p, d) => {
  console.log(`Event: ${e}\nPath: ${p}\nDetails: ${d}`);
});
```

Expected Output is to have app running while file operations happen, and log the events.
Actual Output is the app exits with no output, and ceases to watch.

Edit: updated code to be full file.

**Comment by es128** [comment]
Change `./test-watch` to just `test-watch`. Your `ignored` regex is matching it and causing nothing to be watched, and the `persistent` setting only has an effect while something is being watched.

**Comment by es128** [comment]
Also you should probably be listening for the `all` event, not `raw`.
