### ISSUE TITLE
How to  make chokidar fire only once when files added or removed to / from certain dir?

### ISSUE THREAD

**Issue by vasyl-shumskyi** [paulmillr/chokidar#626]
Hello,

How to  make chokidar fire only once when some files added or removed to / from certain dir?

So basically I'm only interested if watched dir content was changed

**Comment by es128** [comment]
There is no option to do that. You'll need to implement your own logic to capture related events and accomplish what you want.

**Comment by vasyl-shumskyi** [comment]
Sorry for replying to closed thread. 

With resurrecting watcher after closing it, we will have 1 shot recurrent behavior as asked in the question. For `fs.watch` I've used following logic, but had troubles to move that logic to `chokidar`:

```
const fs = require('fs')
let dir = './watch1'

function watchOnce()
{
  const watcher = fs.watch(dir, (evt, file) => {
    watcher.close()

    // logic goes here
    console.log(Date(), evt, file)

   // resurrecting watcher after 1 sec
    setTimeout(watchOnce, 1000)
  })
}

watchOnce()
```

> Testing

Creating and deleting 10,000 files 5 times in a raw with 1 second delay in between:

```
$ for i in {1..5}; do touch {1..10000}; sleep 1; rm {1..10000}; sleep 1; done
```

Verifying that watcher fired exactly 10 times (5 for creating 10,000 files and 5 for deleting 10,000 files):

```
$ node watchers.js
Wed Jun 07 2017 12:01:44 GMT+0300 (EEST) rename 1
Wed Jun 07 2017 12:01:46 GMT+0300 (EEST) rename 1
Wed Jun 07 2017 12:01:47 GMT+0300 (EEST) rename 1
Wed Jun 07 2017 12:01:49 GMT+0300 (EEST) rename 1
Wed Jun 07 2017 12:01:50 GMT+0300 (EEST) rename 1
Wed Jun 07 2017 12:01:52 GMT+0300 (EEST) rename 1
Wed Jun 07 2017 12:01:53 GMT+0300 (EEST) rename 1
Wed Jun 07 2017 12:01:55 GMT+0300 (EEST) rename 1
Wed Jun 07 2017 12:01:56 GMT+0300 (EEST) rename 1
Wed Jun 07 2017 12:01:58 GMT+0300 (EEST) rename 1
```

**Comment by es128** [comment]
You don't need to close the watcher. If you're already watching only the one directory where you want events to trigger the same actions, then you just want a [debounce](https://lodash.com/docs/#debounce) around your event handler.
