### ISSUE TITLE
Bump glob-parent?

### ISSUE THREAD

**Issue by phated** [paulmillr/chokidar#627]
Just wondering if you were willing to bump glob-parent.  I believe version 3.1.0 is currently available.

/cc @es128

**Comment by es128** [comment]
Willing, yes. There's more to it than a simple version bump - iirc it causes windows backslash problems without further adjustments within chokidar and I haven't taken the time to sort it out.

**Comment by phated** [comment]
@es128 oh yeah, I totally forgot about that.  I'll ping @jonschlinkert and @doowb to see if they can look at this when they have time.

**Comment by doowb** [comment]
I'll take a look this weekend.

**Comment by phated** [comment]
@doowb sorry, I need to ping this again because this (and some other glob related dependencies) are a big duplication problem in my dependency tree.

@es128 any chance we could major bump all the outdated glob dependencies (anymatch, glob-parent, is-glob) and major bump here?  Even if it's a breaking change for my glob-watcher, I can just force the major in my tree.

**Comment by phated** [comment]
This was done in 2.0.0
