### ISSUE TITLE
If folder name contains Exclamation Sign (!), Chokidar is not detecting changes.

### ISSUE THREAD

**Issue by ritwickdey** [paulmillr/chokidar#630]
Suppose our working dir is `C:\users\user\test!web\httpdocs\index.html`.

if I open CMD and type `chokidar C:\users\user\test!web\httpdocs\` , chokidar  is not detecting changes.

if I open go to `cd C:\users\user\test!web\httpdocs\` and type `chokidar .`, it works perfectly fine.

**Comment by es128** [comment]
Using the `disableGlobbing: true` option will likely fix this.

**Comment by ritwickdey** [comment]
Actually chokidar & chokidar-cli both have a this issue.

For an example : 
```js

//Full Dir : C:\users\user\test!web\httpdocs\index.html

let path = 'C:\\users\\user\\'; //This is working perfactly.
let path = 'C:\\users\\user\\test!web\\'; //This is not detecting index.html.
let path = 'C:\\users\\user\\test!web\\httpdocs\\'; //This is also not detecting index.html.

let watcher = chokidar.watch(path, {
    disableGlobbing: true
});

watcher
    .on("change", (path) => {
        console.log("Chnaged: " + path);
    })
    .on("ready", () => {
        console.log("scan completed.");
    });

```
Hope you got my point.
