### ISSUE TITLE
"add" events on startup

### ISSUE THREAD

**Issue by scripting** [paulmillr/chokidar#633]
When I start chokidar.watch, I get an _add_ event for every file in the directory I'm watching. 

let watcher = chokidar.watch ("/path/to/folder/");

The files haven't been modified, or newly added. They were there the last time chockidar.watch was watching. 

Why are these add events being sent? Is there any way to tell chokidar to only send an add when a file is actually added to the directory.

Also, thanks for a great utility, it's made it possible to make some very useful tools. ;-)

**Comment by es128** [comment]
Those events allow apps to know what's being watched at the outset. You can suppress them with the `ignoreInitial: true` option.

**Comment by scripting** [comment]
Thank you. I see the docs are [here](https://github.com/paulmillr/chokidar#path-filtering), in case anyone comes through here looking for the answer. ;-)

**Comment by jonnytest1** [comment]
is there an event for when initialisation has finihsed ?
