### ISSUE TITLE
chokidar.watch(paths)  

### ISSUE THREAD

**Issue by wave2588** [paulmillr/chokidar#634]
我在这里设置完要检测的路径后,这个方法的回调立马就会走,有什么办法在设置检测路径的时候取消回调,而我在操作文件的时候再打开回调呢?? 

Forgive me for not being able to describe the problem in English, please. --!

![image](https://user-images.githubusercontent.com/13011595/29859132-3b4ecbfa-8d93-11e7-8877-10e69ec90022.png)

**Comment by es128** [comment]
Google translate says:

```
I set up here to complete the detection of the path, the callback of this method will immediately go, there is no way to set the detection path when the cancellation of the callback, and I am in the operation of the document and then open the callback
```

Responding to the "immediately go" part, try the `ignoreInitial: true` option.

**Comment by wave2588** [comment]
solved my problem.   Thanks.

**Comment by wave2588** [comment]
I have one more question...

**Comment by wave2588** [comment]
``const fs = require('fs')
When I hope use 'fs'  operation file.
'chokidar' not monitor.
How can I fix it ?
Looking forward your comply.

**Comment by wave2588** [comment]
`const fs = require('fs')`
When I hope use 'fs' operation file.
'chokidar' not monitor.
How can I fix it ?
Looking forward your comply.
