### ISSUE TITLE
change path issue~~

### ISSUE THREAD

**Issue by wave2588** [paulmillr/chokidar#636]
I have a path like this.

I want ignore some files under a folder, For example:
in `/User/wave/Desktop/TestOne/TestTwo/test.py`

Can I change part of the path like "TestOne" to "somepath" but some files under this path like "test.py" ignore this change?
I've tried set 'depth' attribute, but it seems didn't work.

Looking forward your reply.

**Comment by wave2588** [comment]
![image](https://user-images.githubusercontent.com/13011595/30022131-961c06d0-919c-11e7-8042-abe74e868d05.png)

**Comment by es128** [comment]
Could you please clarify your question? I don't understand what you're trying to do.

**Comment by wave2588** [comment]
Forgiving my English is not very good,please.    --!

**Comment by wave2588** [comment]
i.e.   I just don’t want to receive the change notification of the changed folder's subfoler
