### ISSUE TITLE
unwatch issue

### ISSUE THREAD

**Issue by wave2588** [paulmillr/chokidar#638]
![image](https://user-images.githubusercontent.com/13011595/30369139-071f8ff4-98a6-11e7-8860-c2456cd779ea.png)

When I cancel watch wathcer_path.
Then I rename wathcer_path's subpath.
I find 'chokidar' can also watch rename action.
Why?????
Looking forward your reply.

**Comment by wave2588** [comment]
I solved the problem.
ha-ha

**Comment by lastboy** [comment]
> I solved the problem.
> ha-ha

It would be nice if you put some details instead of the words "ha-ha"
Thank you.
