### ISSUE TITLE
child directory deletion with files in does not fire an event when using 'all' on windows

### ISSUE THREAD

**Issue by lilpug** [paulmillr/chokidar#640]
Hi,

I have seen this issue raised a couple of times now through the year,

**issue**

When using the ".on('all'" event on a parent directory and all its files, if you delete a sub directory which has files no event is triggered but if you use ".on('raw'" and you do the same process you can see its triggering the event as "rename".

**temporary fix**

Is there any way to chain event orders so as a fix we could say if the 'all' event has not been triggered then use raw and check the event parameter is "rename", this way it will fix the issue short term while its looked into why 'raw' finds the event trigger but 'all' does not

**Comment by wave2588** [comment]
I'm waiting, too
