### ISSUE TITLE
setTimeout().unref() for chokidar?

### ISSUE THREAD

**Issue by huan** [paulmillr/chokidar#641]
Currently, if we use chokidar to watch directories/files, then the Node.js will not exit until we called `watcher.close()`.

I believe it's because we have some `setTimeout` / `setInterval` which will block Node.js to quit until the event loop is clean.

I'd like to suggest that use `setTimeout().unref()` to make the chokidar to `set-forget` mode.

**Comment by awwright** [comment]
Yeah, for any listener that holds open the Node.js process I would expect to be able to call `watcher.unref()` to change that behavior.

In my case, I've got an application that should refresh data that's been read from underlying files, but the point isn't to act on file changes; the process should close by itself once the main server has closed.

**Comment by paulmillr** [comment]
Fixed this in chokidar v3

**Comment by awwright** [comment]
@paulmillr  I had to dig a little bit to figure out what you're talking about; this is the `persistent` option, right?

I would add something like

> This provides behavior similar to `unref()` on Node.js listeners.

To make it more searchable. And I'd still consider adding an unref method for consistency with Node.js core behavior.
