### ISSUE TITLE
Can chokidar handle diffing of files?

### ISSUE THREAD

**Issue by pthieu** [paulmillr/chokidar#642]
Looked around docs and searched issues to see if there was any inquiries for getting the `diff` changes of a watched file but couldn't find anything

I want to write a logging agent to send diff'd updates of a log file to a logging server so that the two copies can sync, logging server gets updates in real-time, and we don't bottleneck on filesize when things get large. With `fs.watchFile`, I can grab the previous and current file descriptor and compare bytes.

Is this possible in `chokidar`?

**Comment by es128** [comment]
> With `fs.watchFile`, I can grab the previous and current file descriptor and compare bytes.

You're comparing the `stat`? Or the actual contents of the file?

Chokidar doesn't read the contents of files in order to watch them - that's what would be needed in order to do before/after diffs. It is possible, but should be handled outside of chokidar.

**Comment by pthieu** [comment]
@es128: ah, I've only done some research, but it's the `fs.Stats` class I will be working with so will not be comparing contents.

**Comment by es128** [comment]
Chokidar can provide you with the `fs.Stats` with each event. It already does it when the data is already available via normal processing, or you can force it to happen with every event with the `alwaysState: true` option. 

Combined with the default `ignoreInitial: false`, which will send you `add` events for all paths being watched upon instantiation along with file stats, you can hold those stat objects and diff them against new ones received with subsequent events.

**Comment by pthieu** [comment]
Yep, I had to track the stats myself in a normalized dictionary. Was hoping for some convenience like what we get with `watch`, but it's working now.

**Comment by cvalenzuela** [comment]
@pthieu can you elaborate more on how you managed to get the diff?

**Comment by pthieu** [comment]
Not near my code so can't share it.
But a library like `watch` implicitly holds the previous `fs.stat` data of the file. You compare the previous data with the new data to find the delta and parse the delta content into a buffer.

`chokidar` does not not keep the results of the previous `fs.stat` state so you have to do it yourself using whatever software pattern you like best.

**Comment by pthieu** [comment]
@cvalenzuela: Not near my code so can't share it.
But a library like `watch` implicitly holds the previous `fs.stat` data of the file. You compare the previous data with the new data to find the delta and parse the delta content into a buffer.

`chokidar` does not not keep the results of the previous `fs.stat` state so you have to do it yourself using whatever software pattern you like best.

**Comment by cvalenzuela** [comment]
@pthieu, thanks!
