### ISSUE TITLE
globs are not working (again)

### ISSUE THREAD

**Issue by ORESoftware** [paulmillr/chokidar#645]
TBH this library has caused me nothing but pain when it comes to file path matching. If I do this:

```js  
let watcher = chokidar.watch(['**/*.js']);
```

I also tried this, and this does not seem to work either:

```js  
let watcher = chokidar.watch('**/*.js');
```

Using the array, it will watch all sorts of files that don't end in '.js'...how can I tell chokidar to only watch files with a certain extension. I really don't want to use the ignore option to ignore the 15+ file extensions I don't want to watch, instead I'd rather just declare the one that I positively want to watch.

Please advise.

**Comment by ORESoftware** [comment]
What would make it so much better for users, is if you could accept an array of regular expressions for the includes argument.

**Comment by ORESoftware** [comment]
nevermind fml seems to work with array

**Comment by FeaRCODE** [comment]
I can confirm. Everything broke after `1.7.0` and I still cannot get an array of globs to work. Did you find a fix or workaround other than reverting back to the older version @ORESoftware ?

**Comment by klemenoslaj** [comment]
No updates? This issue seems to be a major one, and for sure it's blocking me from updating or using it in new project.

**Comment by paulmillr** [comment]
What about disableGlobbing option?

**Comment by paulmillr** [comment]
**Fixed** in master. 89f5239

**Comment by paulmillr** [comment]
Update to Chokidar v3, it should resolve this.
