### ISSUE TITLE
Watch for add/remove of a dir, but ignore watching anything inside of it

### ISSUE THREAD

**Issue by vjpr** [paulmillr/chokidar#648]
Say you have a mono-repo with lots of modules and you want to ignore the `node_modules` folders because they could involve 100Ks files or more.

```
- packages
    - foo
      - node_modules
    - bar
      - node_modules
```

If I use globs with unlimited depth, will `ignores` try to match against every nested file path?

Maybe an option similar to `ignore` called `stopAt`?

At the moment I am using a breadth-first traversal with an early exit if I match a path. I then pass these into the watcher. Only tricky thing is that when a new dir is added I have to add it to the watcher. Does this sound like the best approach?

**Comment by es128** [comment]
It will stop traversing if you ignore or don't match a dir - except when matching with a glob that has the potential to match the contents of a dir without matching on the dir path itself.

TIMTOWTDI, but you should be able to solve for your use case with the `ignored` option and a regex.

**Comment by vjpr** [comment]
Thanks, the `ignore` callback is really good to debug which files are being scanned.

**Comment by vjpr** [comment]
@es128 It seems that it is not possible.

I want to:
- ignore watching inside `node_modules` dirs
- not visit any files inside a `node_modules` dir (in the ignored callback for example)
- be notified when `node_modules` dirs are created and removed

At present, this is not possible. There should probably be another `ignored` field that says "ignore looking inside this dir".

Related issue: https://github.com/isaacs/node-glob/issues/335

**Comment by vjpr** [comment]
Also, when I receive add or remove events deep inside an ignored dir, they are triggering the `ignored` callback.

Are watchers set per directory? Do they adhere to their `ignored` callback. I'm a little confused.

**Comment by vjpr** [comment]
So I just realized that when you watch a dir, you get raw events if anything changes in the entire tree.

So I should just use the raw events instead. And `ignored` does not affect the number of listeners or anything, but...it does have the potential to cause iterate over every file in the tree. There should be a warning about this.

> Be advised that chokidar will initiate watchers recursively for everything within scope of the paths that have been specified, so be judicious about not wasting system resources by watching much more than needed.

Still confused by what this means...as the module could just listen to the raw events and run matchers on them and respond accordingly...what is the need for recursively setting watchers.

**Comment by es128** [comment]
Sorry, but you've now asked too many different questions for me to process.

You are correct that there is no way to watch a directory and not traverse into its contents at all. Adding options to describe what you want at that level of granularity seems like it would add more complexity than it's worth.

You can ignore `**/node_modules/*` and then yes, you will get one `fs.readdir()` operation on `node_modules` itself, but it won't drill down any further.

> The best solution I can think of now is to set depth = 0 and pass it exactly the dirs I want to watch and manage this myself.

Yes, you can do this.

Going to leave this closed until I see something that merits making changes in chokidar's code, but feel free to keep discussing.

**Comment by vjpr** [comment]
@es128 Maybe I will confine it to two small questions then to help my overall understanding:

What does it mean by "chokidar will initiate watchers recursively for everything within scope of the paths that have been specified,"?

If I use '**' as the glob on a huge and deep directory, is this inefficient (is there any code that runs per tree level, per file?)), or why can't you simply run regexes/globs on the paths involved in the `raw` events?

---

Also, FYI:

> You can ignore **/node_modules/* and then yes, you will get one fs.readdir() operation on node_modules itself, but it won't drill down any further.

In a mono-repo there could be hundreds of top-level `node_modules` dirs with 1000s of folders in each. Just an FYI.
