### ISSUE TITLE
No events fired on a raspberry pi

### ISSUE THREAD

**Issue by Saturnyn** [paulmillr/chokidar#651]
Hello,
I am using chokidar to detect when images are added in a folder, fairly simple use case, no nesting.

It works perfectly on my dev machine (windows 7), but I can't get it to work when deploying my app on a raspberry pi (_Raspbian GNU/Linux 8.0 (jessie)_).
The 'ready' event is fired, but none of the others ('add', 'error', 'raw')
I tried with and without usePolling.

Is there anything else I could try ?

Not sure if relevant, but I get this when doing npm install:
```
pm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})
```

**Comment by ranganath135** [comment]
@Saturnyn Can you post a code snippet? Or more info? 

This may seem very basic but make sure you have the watch paths set correctly using `path.resolve`. Windows uses `\` for paths and linux uses `/`.

**Comment by Saturnyn** [comment]
@ranganath135 Thanks for your reply.

I went back to check on the code, it was already using `path.resolve()`, but I realized the folder I was watching was created after the `chokidar.watch()` call. If I ensure the folder exists before creating it, it works fine.

It was a stupid mistake on my part, the fact that it worked on windows made me miss the obvious reason.
