### ISSUE TITLE
Working of Polling ?

### ISSUE THREAD

**Issue by EagleHawk** [paulmillr/chokidar#653]
Hello,

I am trying to put a delay in the chokidar by using the polling but it's not working.
Scenario :
Like I am watching a folder and want to copy files from the watched folder to other location. I copied 100 files want each file to be copied in interval of 2 sec. 
Do not want to use fs.copyFileSync

Can anyone help me

**Comment by es128** [comment]
The issue description is unclear, and it doesn't seem like the problem has much do with chokidar itself - it's something you need to solve in your handler code.
