### ISSUE TITLE
Run Listener Once for Multiple File Changes

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [paulmillr/chokidar#654]
It would be helpful if there could be an option to only run the handler once if the files being watched were all changed in the same polling period.

**Comment by BebeSparkelSparkel** [comment]
Something similar to this:

```javascript
function rate_limit_drop(time_limit, func) {
  let last_run_time = 0

  return function() {
    const to_return = (last_run_time + time_limit < Date.now()) ?
       func(...arguments) :
       undefined

    last_run_time = Date.now()

    return to_return
  }
}
```

**Comment by es128** [comment]
You can accomplish this by wrapping your handler in a standard debounce utility such as https://lodash.com/docs/4.17.4#debounce

**Comment by BebeSparkelSparkel** [comment]
Thanks
