### ISSUE TITLE
Add trueCasePath option to resolve file when the platform is case sensitive filesystem

### ISSUE THREAD

**Issue by rubeniskov** [paulmillr/chokidar#655]
I suggest add a flag in options "trueCasePath" to take in mind the case sensitive and set by default as true. This is really usefull in many cases when the file to find is for example a NodeJS module, because depending of the platform you can make the mistake to use a case sensitive file and require it without the proper name. 

I know someone could be think this... 

_Just fix that, using the right name when you notice getting an error when you check the module on 
the platform that doesn't support this feature_

But this chokidar could be used in a precompiled process as webpack or watchify (the most of cases) in a development environment where you can't notice of this behaviour.  

Actually watchify is having this issue, when put a wrong name the require resolver get the module without any problem, but when the watchify try to watch the modified file it does't work because chokidar is watching a missing file. 

The idea is if the flag is assigned as true use the module [true-case-path](https://github.com/barsh/true-case-path) and check the current file entry and the return value raising a warning to the stderr if doesn't match.

This could be really usefull to find that kind of errors and keep the module working properly.
  
I gonna put the PR as soon as posible, I hope your feedback!!

**Comment by es128** [comment]
I think I understand the problem you're trying to solve and your suggestion, but I do not think a new option inside of chokidar is the right layer at which to address it. When there is a case-sensitivity concern on user input that is going to be fed into chokidar, you should first use true-case-path to resolve the user input into an exact path, and then pass that result into chokidar. No need for it to be a baked-in option.

Possibly makes sense to do it within watchify.
