### ISSUE TITLE
Can't install chokidar on windows 7

### ISSUE THREAD

**Issue by bellalDjam** [paulmillr/chokidar#657]
Hi Paul,
Merry christmas.

I tried to install angular/cli, running : npm install -g @angular/cli
and the installation progress still in [..................] | fetchMetadata: sill resolveWithNewModule chokidar@1.7.0 without progress.

I followed many proposed solutions in https://www.npmjs.com/package/npm-windows-upgrade, github and stackoverflow, and no way to get a complet installation.

So I tried to install chokidar as administrator with any progress:

Your environment has been set up for using Node.js 8.9.3 (x64) and npm.

C:\Windows\System32>npm install chokidar --save
[..................] | fetchMetadata: sill resolveWithNewModule chokidar@1.7.0 .

Is there some suggestion for me.

happy new year 2018

**Comment by whiplashomega** [comment]
for more details, there appears to be an error installing the OS X library fsevents on windows systems. Because it is listed as a required dependency for chokidar, chokidar in turn fails on windows systems. Because chokidar is a required dependency of angular compiler-cli, that fails to install on windows systems.

**Comment by whiplashomega** [comment]
This appears to be fixed when using chokidar 2.0.0, but angular-cli is still looking for an older version. Not your issue, but an fyi.

**Comment by es128** [comment]
@whiplashomega 
> there appears to be an error installing the OS X library fsevents on windows systems

`fsevents` is an optional dependency. If it is blocking your ability to install it is likely because of a shrinkwrap file that was created on a different system.

**Comment by es128** [comment]
@bellalDjam seems like you might be having trouble reaching the npm registry, but you haven't provided enough information for us to help you understand what's going wrong. Closing the issue for now.

**Comment by bellalDjam** [comment]
Hi Elan,
Sorry Im in my learning step for Angular,  I tried to access https://registry.npmjs.org/ in my browser, and I get : 

{"db_name":"registry","doc_count":760712,"doc_del_count":343,"update_seq":8860975,"purge_seq":0,"compact_running":false,"disk_size":5663588486,"data_size":3876069613,"instance_start_time":"1515517876925775","disk_format_version":6,"committed_update_seq":8860975}

and in runing :
npm config get registry
print : https://registry.npmjs.org/ 

PS C:\Windows\system32> npm config ls -l 
print:
; cli configs
long = true
metrics-registry = "https://registry.npmjs.org/"
scope = ""
user-agent = "npm/5.5.1 node/v8.9.3 win32 x64"

; builtin config undefined
prefix = "C:\\Users\\moi\\AppData\\Roaming\\npm"

; default values
access = null
allow-same-version = false
also = null
always-auth = false
auth-type = "legacy"
bin-links = true
browser = null
ca = null
cache = "C:\\Users\\moi\\AppData\\Roaming\\npm-cache"
cache-lock-retries = 10
cache-lock-stale = 60000
cache-lock-wait = 10000
cache-max = null
cache-min = 10
cafile = undefined
cert = null
cidr = null
color = true
commit-hooks = true
depth = null
description = true
dev = false
dry-run = false
editor = "notepad.exe"
engine-strict = false
fetch-retries = 2
fetch-retry-factor = 10
fetch-retry-maxtimeout = 60000
fetch-retry-mintimeout = 10000
force = false
git = "git"
git-tag-version = true
global = false
global-style = false
globalconfig = "C:\\Users\\moi\\AppData\\Roaming\\npm\\etc\\npmrc"
globalignorefile = "C:\\Users\\moi\\AppData\\Roaming\\npm\\etc\\npmignore"
group = 0
ham-it-up = false
heading = "npm"
https-proxy = null
if-present = false
ignore-prepublish = false
ignore-scripts = false
init-author-email = ""
init-author-name = ""
init-author-url = ""
init-license = "ISC"
init-module = "C:\\Users\\moi\\.npm-init.js"
init-version = "1.0.0"
json = false
key = null
legacy-bundling = false
link = false
local-address = undefined
loglevel = "notice"
logs-max = 10
; long = false (overridden)
maxsockets = 50
message = "%s"
; metrics-registry = null (overridden)
node-version = "8.9.3"
offline = false
onload-script = null
only = null
optional = true
otp = 0
package-lock = true
parseable = false
prefer-offline = false
prefer-online = false
; prefix = "C:\\Program Files\\nodejs" (overridden)
production = false
progress = true
proxy = null
read-only = false
rebuild-bundle = true
registry = "https://registry.npmjs.org/"
rollback = true
save = true
save-bundle = false
save-dev = false
save-exact = false
save-optional = false
save-prefix = "^"
save-prod = false
scope = ""
script-shell = null
scripts-prepend-node-path = "warn-only"
searchexclude = null
searchlimit = 20
searchopts = ""
searchstaleness = 900
send-metrics = false
shell = "C:\\Windows\\system32\\cmd.exe"
shrinkwrap = true
sign-git-tag = false
sso-poll-frequency = 500
sso-type = "oauth"
strict-ssl = true
tag = "latest"
tag-version-prefix = "v"
timing = false
tmp = "C:\\Users\\moi\\AppData\\Local\\Temp;C:\\Program Files (x86)"
umask = 0
unicode = false
unsafe-perm = true
usage = false
user = 0
; user-agent = "npm/{npm-version} node/{node-version} {platform} {arch}" (overridden)
userconfig = "C:\\Users\\moi\\.npmrc"
version = false
versions = false
viewer = "browser"


PS C:\Windows\system32> npm list -g --depth=0
print:

C:\Users\moi\AppData\Roaming\npm
+-- ember-cli@2.17.2
+-- generator-angular2@0.6.4
+-- jshint@2.9.5
+-- moi@1.0.0 -> C:\Users\moi
`-- npm-windows-upgrade@4.1.0

npm ERR! peer dep missing: rxjs@^5.5.0, required by @angular/core@5.1.3
npm ERR! peer dep missing: zone.js@^0.8.4, required by @angular/core@5.1.3


so, what can I verify to check the needed file or package?
thanks for all.

Best Regards.

**Comment by es128** [comment]
What is the output of `npm install chokidar —verbose`?

**Comment by bellalDjam** [comment]
PS C:\Windows\system32> npm install chokidar --verbose

npm info it worked if it ends with ok
npm verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
npm verb cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
npm verb cli   'install',
npm verb cli   'chokidar',
npm verb cli   '--verbose' ]
npm info using npm@5.5.1
npm info using node@v8.9.3
npm verb npm-session 2b0de071fc52202c
npm http fetch GET 304 https://registry.npmjs.org/chokidar 310ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/async-each 110ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/fsevents 71ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/braces 273ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/is-glob 275ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/glob-parent 281ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/inherits 284ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/is-binary-path 288ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/normalize-path 291ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/anymatch 304ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/path-is-absolute 307ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/readdirp 313ms (from cache)
[..................] - fetchMetadata: http fetch GET 304 https://registry.npmjs.org/readdirp 313ms (from cache)

**Comment by es128** [comment]
Looks normal aside from being truncated. Not sure what's going on, but seems like something local to your system. You could try `npm cache clean` and starting over in a new directory.
