### ISSUE TITLE
Error when watching Drive with a slash in windows

### ISSUE THREAD

**Issue by CxRes** [paulmillr/chokidar#661]
If I try to watch something like `D:` chokidar does not read anything but issues a `ready` event. However this is not a problem if I watch `D:/`. I am watching at `{depth : 1}` to prevent a lot of files from being read.

Also if I read `D:/` with `{ cwd: 'D:' }` files are output as `..\..\..\..\..\somefilename`. 

Node 8.9.3
Windows 10 x64 build 1703

**Comment by es128** [comment]
I don't understand what you're asking for. You want chokidar to automatically correct `D:` to `D:/` for you? Can't you just handle this on your side?

**Comment by CxRes** [comment]
I did ... but the behaviour is inconsistent! For `C:/Foo` and `C:/Foo/` produce the same correct result but not the above...

**Comment by es128** [comment]
I suppose the trailing slash does not mean the same thing at the root of the drive versus for a directory. From your descriptions it seems like `D:` is being interpreted as a relative path to the current cwd, and the slash is a necessary signal to the file system methods that you intended to watch the drive's root.

This isn't a decision chokidar is making deliberately, these strings are simply being passed to node's `fs` methods and to windows system APIs from there. Afaict, microsoft has decided you need the slash.

**Comment by CxRes** [comment]
@es128 You were right. Windows is a bitch (excuse my language)!

From the relevant [MSDN](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247.aspx#fully_qualified_vs._relative_paths) page: 

> If a file name begins with only a disk designator but not the backslash after the colon, it is interpreted as a relative path to the current directory on the drive with the specified letter. Note that the current directory may or may not be the root directory depending on what it was set to during the most recent "change directory" operation on that disk.
