### ISSUE TITLE
awaitWriteFinish and wrong "change" event

### ISSUE THREAD

**Issue by LeMisterV** [paulmillr/chokidar#662]
Hi,

Using chokidar 1.7.0
I start watching a folder using this config:
```javascript
{
    persistent: true,
    ignoreInitial: false,
    followSymlinks: false,
    disableGlobbing: true, // we will give real file path, no need for globbing
    awaitWriteFinish: true,
  }
```

**Normal behaviour :**
I create a file
-> I get a "add" event 2s after

I remove the file
-> I get a "unlink" event

All good this far

**Now my problem :**
If I create a file and remove it within the 2s delay
-> I get no event at all... all right

Then I create this file again
-> I get a "change" event instead of the expected "add" event

**Quick command line to reproduce the behavior:**
```bash
echo "content" > filename.txt && sleep .1 && rm filename.txt && sleep 2 && echo "content" > filename.txt
```
Executing this command, I should get 1 "add" event.
What I get is 1 "change" event

**Comment by es128** [comment]
Looks like you may be playing your delay periods too closely. Have you tried increasing the time period before recreating the file to ensure you're out of the original poll cycle?
