### ISSUE TITLE
Issue with Renaming Nested Files

### ISSUE THREAD

**Issue by MichaelEPope** [paulmillr/chokidar#664]
Hey, I just noticed a small issue with renaming files.  I think it might be my error, but just in case it isn't, I thought I'd post it.  Perhaps someone can test it on their system and see if they are getting the same results.

I'm running on 64-bit Windows 10.  I have not tested it on other operating systems (sorry =/).

The steps I take to cause the error are the following.
1)  Watch the current directory with chokidar (the error appears even if you don't watch the current directory, but for the simplicity of testing, let's say it's the current one).
2)  Create a folder in that directory.  We'll call that __Created_Folder_1__.
3)  Create another folder inside of that folder.  We'll call that  __Created_Folder_2__.
4)  Attempt to rename  __Created_Folder_1__.
5)  You should see a Windows prompt saying that a program is currently using the folder and so it can't be renamed (if you are using an IDE like VSCode, it may not show that error, but in both cases, the file can't be renamed, and no add or unlink event is thrown by chokidar).

Here's the file I use in order to test this:

```javascript
const chokidar = require('chokidar');

var ready = false;

const watcher = chokidar.watch('.', {ignored: /node_modules.*/});
watcher.once('ready', function()
{
    ready = true;
});
watcher.on('add', function(path)
{
    if(ready)
    {
        console.log('add', path);
    }
    else
    {
        console.log('add-pre-init', path);
    }
});
watcher.on('change', function(path, stats)
{
    if(ready)
    {
        console.log('change', path, stats);
    }
    else
    {
        console.log('change-pre-init', path, stats);
    }
});
watcher.on('unlink', function(path)
{
    if(ready)
    {
        console.log('unlink', path);
    }
    else
    {
        console.log('unlink-pre-init', path);
    }
});
watcher.on('addDir', function(path)
{
    if(ready)
    {
        console.log('addDir', path);
    }
    else
    {
        console.log('addDir-pre-init', path);
    }
});
watcher.on('unlinkDir', function(path)
{
    if(ready)
    {
        console.log('unlinkDir', path);
    }
    else
    {
        console.log('unlinkDir-pre-init', path);
    }
});
watcher.on('error', function(err)
{
    console.log('error', err);
});


module.exports = {}
```

Here's the error that I see if I do it from the regular File Explorer UI:

![image](https://user-images.githubusercontent.com/19957372/34634289-6c211e1e-f237-11e7-80e9-dce22736c5ce.png)

If you do it in VSCode there is no immediate error, but the rename is not accepted.

![image](https://user-images.githubusercontent.com/19957372/34634327-d84f5916-f237-11e7-9b40-c29f32479583.png)

Eventually though an error appears: 

![image](https://user-images.githubusercontent.com/19957372/34634339-f30fb87c-f237-11e7-870a-9db8e53873f2.png)

This does not effect non-nested files at all.  So I could renamed Created_Folder_2 with no problems.

![image](https://user-images.githubusercontent.com/19957372/34634354-1ed7ae2e-f238-11e7-8c8e-1949ce998fac.png)

Thanks for your help on this.  And I hope this post provided enough info... it's my first time doing this. :)

**Comment by es128** [comment]
It's a known quirk of the Windows API for file watching, as exposed by the node.js core method `fs.watch()`. You could try setting the `usePolling: true` option in chokidar to switch to watching based on stat polling as provided by `fs.watchFile()`, although there is a performance penalty. Your watch target seems relatively small, so you may not notice the difference.
