### ISSUE TITLE
Ignore files in a directory but not in its subdirectories

### ISSUE THREAD

**Issue by jogold** [paulmillr/chokidar#666]
Hi,

I have the following structure:
```
/home
/home/abc
/home/abc/def
/home/pqr
/home/stu
```

I'm watching `/home` and I want to ignore files in `/home/abc` but not files in `/home/abc/def`. I'm trying with something like `ignored: /(^|[\/\\])\..|abc\/(?!.*def\/)/` but can't get it to work... any ideas?

**Comment by es128** [comment]
Untested, but you could try something like this:
```js
chokidar.watch(['/home/!(abc)**','/home/abc/*/**'])
```

Alternately, stop trying to ignore events on these special cases and just use conditional logic in your event handler to bail out early if it's one of that paths you don't want to act on.
