### ISSUE TITLE
fsevents listed as dependency of chokidar

### ISSUE THREAD

**Issue by turnerhayes** [paulmillr/chokidar#667]
I have a project which has `nodemon` as a dependency, which has `chokidar` as a dependency.

For some reason, when I try to `npm install` my module, the package.json that it pulls in for `chokidar` lists `fsevents` in the `dependencies` list, not just in `optionalDependencies`. This causes the install to fail on Ubunutu (since `fsevents` requires Darwin OS). I don't know how fsevents got into `dependencies`, since the code in this repo doesn't seem to have it there. Any ideas? Is my system borked?

[the generated package.json (as a txt file because Github doesn't allow .json files)](https://github.com/paulmillr/chokidar/files/1613448/chokidar.package.txt)

**Comment by es128** [comment]
You probably have a shrinkwrap.json file that was generated on OS X

**Comment by turnerhayes** [comment]
No shrinkwrap.json, and I've never developed on OS X.

**Comment by es128** [comment]
@turnerhayes I'm not sure then, but it isn't an issue with the chokidar code. Have you tried reinstalling all your deps from scratch?

As you've noted, the published chokidar lists it as an optional dependency, although the package.json you've shown is the one generated locally by npm and is a little different. 

Is there an npm-debug.log?

**Comment by turnerhayes** [comment]
I think it may be a problem with nodemon, actually, because when I install `chokidar` directly it's fine. I'll take it up with them.

**Comment by es128** [comment]
I kind of doubt it’s an issue over there either. 

It’s still an issue now if you try to install nodemon?

Have you tried `npm cache clean`?

**Comment by turnerhayes** [comment]
I did try cleaning the cache.

Strangely, after I directly installed `chokidar`, I tried `npm i nodemon` again, and it worked. Maybe there was something funky with my cache after all...
