### ISSUE TITLE
[Proposal] Use native ReadDirectoryChangesW on Windows to prevent locking?

### ISSUE THREAD

**Issue by NeekSandhu** [paulmillr/chokidar#670]
Previously mentioned: https://github.com/paulmillr/chokidar/issues/446#issuecomment-193287727

`ReadDirectoryChangesW` [documentation](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365465(v=vs.85).aspx)

As a bonus, `ReadDirectoryChangesW` also reports rename events, real rename events. Neat IMO.

Already being used in [`nsfw`](https://github.com/Axosoft/nsfw) by Axosoft and works really well.

**Comment by es128** [comment]
Chokidar uses `fs.watch()` on Windows, which does use `ReadDirectoryChangesW`.

I don't expect anyone has an appetite for major architectural changes like this in chokidar at this point. If nsfw serves your use case better or bypasses problems you have with chokidar, then by all means use it.
