### ISSUE TITLE
[Proposal] File watch expiry

### ISSUE THREAD

**Issue by dyst5422** [paulmillr/chokidar#671]
We are looking at using chokidar for long term file watching for a large scale automation and integration system. In order for us to maintain performance, we need to be reaping file watchers over time. I propose having an expiry duration as an option on the `FSWatcher.add()` which would essentially set a timeout to clear the file watch after the expiry. It should work something as follows.
```js
FSWatcher.add(GLOB1, { expiry: 86400 })
```
Chokidar goes through the glob tree applying watchers as usual, except that is also creates a setTimeout to remove the watcher after the expiry
```js
if (options.expiry) {
  let expiryTime = new Date();
  expiryTime.setSeconds(expiryTime.getSeconds + options.expiry)
  const timoutRef = setTimout(() => removeWatcher(), options.expiry)
}
```
Note that if there are overlapping globs we would need to reset the expiry to the latest expiry when adding a callback to that glob.
```js
if (options.expiry) {
  const newExpiryTime = new Date();
  newExpiryTime.setSeconds(newExpiryTime.getSeconds + options.expiry)
  if (expiryTime < newExpiryTime) {
    expiryTime = newExpiryTime;
    clearTimeout(timoutRef);
    timeoutRef = setTimout(() => removeWatcher(), options.expiry);
  }
}
```

**Comment by es128** [comment]
Why don't you just implement this yourself using the `unwatch()` method?

**Comment by dyst5422** [comment]
Correct me if I'm wrong, but if I have two overlapping glob patterns, and I unwatch one, it removes the watches that are shared. 

I think it needs to be on the per-file resolution in order to properly handle the overlapping case.

**Comment by es128** [comment]
Have you tried it? No, I don't think it'll remove the watchers that are shared, and `.unwatch()` accepts any file path as input, not just the ones that were sent to `.watch()` - although if you are not careful with this you won't see any performance benefit as it will just have the effect of adding the newly unwatched paths to the ignore filter.

**Comment by es128** [comment]
Actually I just realized that you're probably thinking about the intersection of watch and unwatch in the reverse of how I am. The unwatch would take precedence, but leave the rest of the other glob's scope alone. So in that sense, it does stop watching the shared parts, but you could correct that with `.add()`ing the other glob you want to keep alive.

**Comment by dyst5422** [comment]
The complexity involved in resolving any nontrivial number of globbing patterns in that way is definitely prohibitive.

I might look into putting together an initial PR this weekend and see how much would need to be changed as a point for a further discussion.

**Comment by es128** [comment]
As a new option that can't impact any existing users' workflows, I'm receptive to it. Looking forward to seeing your PR.
