### ISSUE TITLE
Avoid emitting 'change' when file is saved without any change

### ISSUE THREAD

**Issue by harunurhan** [paulmillr/chokidar#673]
I am looking for the best way to avoid emitting `change` events when a file is saved without any change from a text editor, in other words when a file is written with the same content.

**Comment by es128** [comment]
Can’t suppress the event. That’s not how these signals work.

You could hold onto before and after `stat`s to see if the size changed (which will be imperfect, but maybe good enough), or you could read and hold onto entire file contents to compare whether any actual changes happened.
