### ISSUE TITLE
Watching large files fires add while the copy hasn't finished even with high awaitWriteFinish settings

### ISSUE THREAD

**Issue by watery** [paulmillr/chokidar#675]
I don't know if this is a bug or just a misconfiguration by my side, btw: I can't get chokidar to fire _add_ events only after large files are completely written to the watched folder, I always get _add_+_change_.
I've tried with higher _awaitWriteFinish_ settings and even with polling, but I get the same result: after the set _stabilityThreshold_ an _add_ event is fired, although the file is still being written.

The file is more than 2GB in size and is being copied from another folder of the same disk.

I want to only monitor files within a "news" labeled folder (i.e. no subfolders); file content is important for the subsequent processing so it is imperative that notifications are only triggered after files are completely written to the folder.

This is my chokidar last config attempt:

```
watcher = _watch.watch(_path.resolve(__dirname, 'news'), {
            ignored: [/(^|[\/\\])\../, /([\/\\])$/],
            followSymlinks: false,
            depth: 0,
            awaitWriteFinish: {
                stabilityThreshold: 30000, /* also tried 15000, 20000 */
                pollInterval: 250 /* also tried 500 and 1500 */
            }
        });
```

and with polling:

```
watcher = _watch.watch(_path.resolve(__dirname, 'news'), {
            ignored: [/(^|[\/\\])\../, /([\/\\])$/],
            usePolling: true,
            interval: 100,
            binaryInterval: 100,
            followSymlinks: false,
            depth: 0,
            awaitWriteFinish: {
                stabilityThreshold: 30000,
                pollInterval: 250
            }
        });
```

I'm on Windows 7 Pro, Node 8.9.4 and chokidar 2.0.0

**Comment by es128** [comment]
What kind of process is doing the copying of the file? Is it like a drag and drop in windows explorer or something else?

**Comment by watery** [comment]
Yes, actually a cut-paste within windows explorer itself, much like a drag&drop I guess.

**Comment by sebastienfi** [comment]
Same problem here but with files much smaller of 9mb
Using chokidar 1.7.0

**Comment by devmondo** [comment]
sorry if it is related but i got a  problem when copying/cutting file or folder chokidar reports the change correctly to the target files or folders have been copied, but how do I get the event to tell me that it is was removed from the previous location
