### ISSUE TITLE
unlinkDir event on windows returning absolute path when it should be relative

### ISSUE THREAD

**Issue by rzl** [paulmillr/chokidar#676]
var chokidar = require('chokidar');
var dir='.\\M';
chokidar.watch(dir,{depth:5})
.on('change', (path) => {
  	console.log(`Directory ${path} has been change`)	
})
.on('addDir', (path) => {
	console.log(`Directory ${path} has been added`)
})
.on('unlinkDir', (path) => {
	console.log(`Directory ${path} has been removed`)
})
.on('add', (path) => {
	console.log(`File ${path} has been added`);
})
.on('unlink', (path) => {
	console.log(`File ${path} has been removed`)
});

D:\nodejs\test\filesync>node slave.js
Directory M has been added
Directory M\新建文件夹 has been added
File M\新建文件夹\新建文本文档.txt has been added
Directory D:\nodejs\test\filesync\M\新建文件夹 has been removed
File M\新建文件夹\新建文本文档.txt has been removed
Directory M\123123 has been added
Directory M\123123\新建文件夹 has been added
Directory M\123123\新建文件夹 has been removed
Directory M\123123\123 has been added
File M\123123\123\新建文本文档.txt has been added
File M\123123\123\443.txt has been added
File M\123123\123\新建文本文档.txt has been removed
Directory D:\nodejs\test\filesync\M\123123\123 has been removed
File M\123123\123\443.txt has been removed

**Comment by es128** [comment]
PR with a failing test for this scenario would be welcome.
