### ISSUE TITLE
Files from node_modules being leaked into watcher events

### ISSUE THREAD

**Issue by mighty-pirate** [paulmillr/chokidar#677]
I've setup a project for this issue at: https://github.com/mighty-pirate/chokidar-leak

Perhaps I am configuring the watcher wrongly, so please show me the error of my ways if I am.

run `yarn` to install chokidar into the project and then `node index.js`

Once running, try to install something with yarn or npm, for example `npm install sass-lint` and the console will show files that aren't supposed to be being watched, being leaked into the watcher events. This also creates a lag, which is the main problem.  

Is this something that has been encountered before? Is there a workaround?

**Comment by es128** [comment]
I followed your instructions, but did not reproduce the problem. Only touching the `.watchme` files triggered an event. That said, if your main concern is lag then you need to use a more targeted glob or use the `ignored` option. Using a globstar pattern the way you did means that all of `node_modules` needs to be watched recursively in case a `.watchme` file appears anywhere in there.

**Comment by mighty-pirate** [comment]
Just out of interest, what OS are you running? I probably should have mentioned that I am running Manjaro which is based on Arch. I've tried it again on a fresh Install with the same outcome.

**Comment by es128** [comment]
I'm using OS X. Does it still happen if the filename you're watching is not a dotfile (e.g. `**/watchme`)?

Either way, you mentioned your main concern is lag, and that's not going to go away if you use a globstar like that, even if you get it down to only the events you're expecting.

**Comment by mighty-pirate** [comment]
It still happens with `**/watchme` and `**/watchme.watchme`. OK, thanks for the advice, I'll figure out a more optimal way of handling this 👍
