### ISSUE TITLE
ignored isn't accepting strings?

### ISSUE THREAD

**Issue by Jakobud** [paulmillr/chokidar#680]
I have a very simply test setup for this:

```
chokidar.watch(somePath, {
        ignored: '*.txt'
}).on('all', (event, path) => {
        console.log(event, path);
});
```

The `somePath` is a directory that contains text files, `node_modules` folder, some .js files, etc...

This did not ignore all `.txt` files. They showed up as watched files when running my script. 

Next I tried `ignored: 'node_modules'`. Nope. That did not ignore the `node_modules` directory in my project.

Next I tried `ignored: /node_modules/` and this did work. Also tried an array and that worked.

So what is going on here? The examples clearly shows it supports strings but it just doesn't seem to work but using regex does work. Am I completely missing something obvious here?

**Comment by Jakobud** [comment]
So I got the strings to work as a glob pattern like this:

`ignored: '**/*.txt'` or `ignored: '**/node_modules'`

But I guess now my question is why wouldn't those work without using `**/`? If I have the `node_modules` or `.txt` files in the root of my `somePath` shouldn't those strings work?

For example if I have a watch path of `/Users/me/repos/myproject` and I specify `*.txt` to be ignored, shouldn't this file: `/Users/me/repos/myproject/about.txt` be ignored?

**Comment by es128** [comment]
You've mixed relative and absolute paths in your watch string and ignore pattern, which is what is causing them to not behave the way you expect. There are several ways you could resolve this, one way you might want to try would be setting `cwd: somePath`

**Comment by Jakobud** [comment]
Okay thanks. So does chokidar assume that the ignore patterns are absolute by default?

**Comment by es128** [comment]
No, not at all. If the watch path is an absolute path, then the file paths output with events are also absolute. And you won’t get a glob match against a simple filename wildcard glob against a nested path, it’s just the nature of how globs work. 

You could watch `.` with `cwd` set to whatever base path you want to use, then the events on top-level files will just use the bare filename and your `ignore` setting would work on those.

**Comment by Jakobud** [comment]
Ah interesting. Okay thanks for that explanation.
