### ISSUE TITLE
nsp advisory

### ISSUE THREAD

**Issue by TheLarkInn** [paulmillr/chokidar#686]
Hey @paulmillr!!! 

We saw this get submitted upstream: 

> nsp check

(+) 1 vulnerability found
┌────────────┬────────────────────────────────────────────────────────────────────┐
│            │ Prototype pollution attack                                         │
├────────────┼────────────────────────────────────────────────────────────────────┤
│ Name       │ hoek                                                               │
├────────────┼────────────────────────────────────────────────────────────────────┤
│ CVSS       │ 4 (Medium)                                                         │
├────────────┼────────────────────────────────────────────────────────────────────┤
│ Installed  │ 4.2.0                                                              │
├────────────┼────────────────────────────────────────────────────────────────────┤
│ Vulnerable │ <= 4.2.0 || >= 5.0.0 < 5.0.3                                       │
├────────────┼────────────────────────────────────────────────────────────────────┤
│ Patched    │ > 4.2.0 < 5.0.0 || >= 5.0.3                                        │
├────────────┼────────────────────────────────────────────────────────────────────┤
│ Path       │ app@1.0.0 > webpack@3.11.0 > watchpack@1.4.0 >              │
│            │ chokidar@1.7.0 > fsevents@1.1.3 > node-pre-gyp@0.6.39 > hawk@6.0.2 │
│            │ > hoek@4.2.0                                                       │
├────────────┼────────────────────────────────────────────────────────────────────┤
│ More Info  │ https://nodesecurity.io/advisories/566                             │
└────────────┴─────────────────────────────────────────────────────────────

Is this already patched in chokidar/fsevents? If not, I figured I'd report this so we could get the dependency chain solidified.

**Comment by es128** [comment]
see strongloop/fsevents#198

**Comment by TheLarkInn** [comment]
I finally caught up to that! Thanks! :)
