### ISSUE TITLE
chokidar doesn't allow node to exit?

### ISSUE THREAD

**Issue by greggman** [paulmillr/chokidar#688]
Here's a simple test. On macOS 10.13.3, chokidar@2.0.2

```
const chokidar = require('chokidar');

const watcher = chokidar.watch(process.argv[2]);
watcher.on('add', (fn, stats) => { console.log(fn, "file", stats.size); });
watcher.on('addDir', (fn, status) => { console.log(fn, "dir"); });
watcher.on('ready', () => {
  console.log("---done---");
  watcher.close();
});
```

note: I understand that I can pass `persistent: false` but according to the docs that's not what I'm looking for since. I want my app to watch things until my app is ready to quit. I thought at that point I could just call `watcher.close` but apparently no?

Adding in 

```
 watcher.unwatch(process.argv[2]);
```

just before `close` doesn't exit either.

Am I doing something wrong?

**Comment by greggman** [comment]
Ok, so apparently it's some specific folder chokidar is not happy with. If I try some other folders it exits.

**Comment by greggman** [comment]
I guess it's recursive link that's the issue

```
mkdir foo
ln -s foo/config /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/config
```

then if I scan that folder chokidar never exits. Looking inside

```
$ ls -l /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/config
total 88
-rw-r--r--  1 root  wheel  51182 Jul 16  2017 Makefile
-rw-r--r--  1 root  wheel  18479 Jul 16  2017 Setup
-rw-r--r--  1 root  wheel    368 Jul 16  2017 Setup.config
-rw-r--r--  1 root  wheel     41 Jul 16  2017 Setup.local
-rw-r--r--  1 root  wheel   2187 Jul 16  2017 config.c
-rw-r--r--  1 root  wheel   1507 Jul 16  2017 config.c.in
-rwxr-xr-x  1 root  wheel   7122 Jul 16  2017 install-sh
lrwxr-xr-x  1 root  wheel     15 Dec 29 10:37 libpython2.7.a -> ../../../Python
lrwxr-xr-x  1 root  wheel     15 Dec 29 10:37 libpython2.7.dylib -> ../../../Python
-rwxr-xr-x  1 root  wheel   7431 Jul 16  2017 makesetup
-rw-r--r--  1 root  wheel  33740 Jul 16  2017 python.o
```

I see those links that link above which suggests a circular link issue.


That seems like it would be easy to solve if chokidar provided a function based filter as the user implemented filter would track what's being tracked and not follow something that has already been followed?

**Comment by es128** [comment]
So the main issue is that the process keeps running even after you call `watcher.close()` when watching a symlinked dir?

**Comment by greggman** [comment]
That appears to be the issue.

**Comment by akayami** [comment]
This is affecting me as well. Specifically my `mocha` tests are not quitting because `chokidar` refuses to stop watching files.

**Comment by laggingreflex** [comment]
Here's a repro: https://github.com/laggingreflex/repro-chokidar-never-close

Simple file structure:
```
├───index.js
└───test
    └───index.js
```

Watching this glob: `['test', 'tests', 'test*.*', '**/*.test.*']`

I patched `fs.watch` to see what's going on, and it shows that the path `test` never gets unwatched.

Also the `ready` event never fires in this case, I suspect this might be related to #449, #561

**Comment by chriscasola** [comment]
Any movement on this? Seems like there are PRs that fix this?

**Comment by paulmillr** [comment]
**Fixed** in master. 89f5239
