### ISSUE TITLE
persistent:false doesn't seem to be working

### ISSUE THREAD

**Issue by TimKingtonFC** [paulmillr/chokidar#689]
I'm creating chokidar like this on Ubuntu:

watcher = chokidar.watch "#{baseDir}",
        cwd: baseDir
        followSymlinks: false
        ignored: checkIgnore
        persistent: false

I get the ready event, and then I continue to get change events after that whenever I save a changed file.

**Comment by es128** [comment]
`persistent: false` doesn't mean the watching stops after the `ready` event, it means that the watcher is not supposed to keep the node program going if it is the only thing on the event loop. If there are other sorts of processes or listeners running then node keeps going and the watchers keep receiving signals.

I'm not sure what you're trying to do, but if you don't want any more events after `ready` you could close the watcher explicitly at that point.

**Comment by TimKingtonFC** [comment]
Gotcha.  Thanks!
