### ISSUE TITLE
Add symlink resolved path (as opposed to realpath) to `raw` event

### ISSUE THREAD

**Issue by vjpr** [paulmillr/chokidar#691]
I'm relying on raw events to do all my processing. However, when you make a change to a file inside a symlink, it returns the real path and theres no way to find out the resolved path.

**Comment by es128** [comment]
The 3rd argument on `raw` events is a `details` object that takes a different form depending on whether fsevents or the node core fs apis are being used. Do you see a simple way to do this resolution to add this into the `details` object? I don't.

Additionally, the `raw` event is not intended to be used this way, and I don't think it makes sense to add the type of processing you're asking for in front of it.

But if you can show a reasonable way to make this happen in a PR I'd be willing to consider it.
