### ISSUE TITLE
Path matching broken?

### ISSUE THREAD

**Issue by DaleMckeown** [paulmillr/chokidar#692]
Is there any reason that path matching is broken?

i.e. `Modules\\**\\Resources\\**\\*.js` used to work in 1.7.0, but now doesn't work in 2.0.2.

I have to use: `Modules/**/Resources/**/*.js` to get any changes come through.

It seems to now only accept forward slashes for paths?

Is this by design, or a bug?

**Comment by es128** [comment]
From the changelog

> # Chokidar 2.0.0 (Dec 29, 2017)
> Breaking: Upgrade globbing dependencies which require globs to be more strict and always use POSIX-style slashes because Windows-style slashes are used as escape sequences

**Comment by DaleMckeown** [comment]
Doh. I read that at 1am after 12 hours solid programming and it obviously didn't go in properly! Thanks :)
