### ISSUE TITLE
Change event triggered when a file with the same name is replaced

### ISSUE THREAD

**Issue by uramonz** [paulmillr/chokidar#694]
Hi,

I'm using this library to develop a file management app, something like Dropbox. There's this scenario were "user1" downloads files from the server when the app initialize same for "user2". The download process creates or replaces if there's already a file with the same name, chokidar detects this and triggers the `change` event which then causes to upload any file change and following with an intermitted loop between user1 and user2 file download/upload (part of my download process logic).

Is there a way to let chokidar know the difference between a file being replaced and a change made to a file either manually or caused by a another software? btw when this happens the `add` event triggers as well with the `change`.

Any idea to overcome my issue is appreciated!

**Comment by es128** [comment]
Chokidar can't tell you about the nature of what exactly changed within the file or what changed it
