### ISSUE TITLE
chokidar not firing on mysql triggered ibd table file changes

### ISSUE THREAD

**Issue by ianr3** [paulmillr/chokidar#697]
I am using the arrival of anytime inbound MQTT messages into a mysql table called received_messages on an Amazon Linux EC2 instance. This table has a corresponding file "received_messages.ibd" in folder /var/lib/mysql/appname/ along with all other tables' ibd files. Chokidar will NOT fire an event on this file after message arrival! This file changes its timestamp on every message received event, but not its file size, fixed by mysql. When I create and manually edit test files in the same folder, all edits and file touches are correctly detected by chokidar. So I don't believe its a "file mount" issue. However, none of the ibd files, all driven my mysql, cause a chokidar firing. ONLY if I set "usePolling; true" are the file changes causing chokidar to fire. I prefer NOT to use polling due to excessive CPU overhead with a "firehose" of inbound messages event. I have tried every possible config - permissions, owners and group settings - on the mysql ibd files without success. Can anyone suggest my code/config error please?

```
var watch_path = '/var/lib/mysql/appname/*.ibd'
var watcher = chokidar.watch(watch_path,{
	 ignored: /(^|[\/\\])\../,  
	 ignorePermissionErrors: true,
	 //usePolling: true,  ...works if not commented out
         // interval: 100,      ..., setting for polling
	 persistent: true
})
// Add event listeners.
var log = console.log.bind(console);
watcher.on('change', path => log(`${path} changed`, server_timestamp_now()))

**Comment by es128** [comment]
Clearly mysql's treatment of the file does not trigger the operating system's recognition of a change, and polling is your only viable option. The CPU overhead of polling is not that bad on a limited number of files.
