### ISSUE TITLE
strange pattern globing match

### ISSUE THREAD

**Issue by eMerzh** [paulmillr/chokidar#703]
hi, 

here is a reduced code that is launched by node-sass-chokidar:

```js
var chokidar = require('chokidar');

chokidar.watch('src/**/*.{sass,scss}').on('all', (event, path) => {
  console.log(event, path);
});
```

and this gave me 
```
add src/common.scss
add src/setup.scss
add src/.eslintrc
``` 
i was wondering why eslintrc was in there ?
it's not a sass or scss file ?

**Comment by michaelwayman** [comment]
I make a project to _try_ and duplicate this issue, I but I am unable to duplicate it...

 [project](https://github.com/michaelwayman/test-chokidar)

The output of the script you provided.
```
> node index.js                                                           
add src/setup.scss
add src/common.scss
^C
```

**Comment by eMerzh** [comment]
I'm on osx don't know if it helps

**Comment by eMerzh** [comment]
ouch... as is i can't reporuced it iether, but i think i'm a bit closer...
in fact i've just noticed that my eslintrc is a symbolic link.... 

i'll attach a PR with my issue
