### ISSUE TITLE
Failing unit tests

### ISSUE THREAD

**Issue by DanielRuf** [paulmillr/chokidar#712]
It seems the unit tests are failing. We should investigate them and fix this.

**Comment by paulmillr** [comment]
Fixed.

**Comment by DanielRuf** [comment]
I do not see any change.

<img width="362" alt="bildschirmfoto 2018-09-06 um 17 16 14" src="https://user-images.githubusercontent.com/827205/45167045-a13dfc80-b1f8-11e8-8387-c2ab1499b5d8.png">
<img width="707" alt="bildschirmfoto 2018-09-06 um 17 16 05" src="https://user-images.githubusercontent.com/827205/45167047-a13dfc80-b1f8-11e8-95b0-5d6ba436d682.png">

**Comment by paulmillr** [comment]
It was fixed for one commit on travis only. Better than before...

**Comment by DanielRuf** [comment]
Let me know how / if we can help here.

**Comment by paulmillr** [comment]
we need to understand why this happens and if any configuration can be changed to prevent this.

because sometimes, like in ⅓ of cases, tests do pass. that's very weird.

**Comment by DanielRuf** [comment]
Bump.

At least one job on macOS fails due to the spy which is called twice because it seems macOS triggers create and update when creating a dir..
