### ISSUE TITLE
On windows, cannot watch files with some glob patterns

### ISSUE THREAD

**Issue by meteorlxy** [paulmillr/chokidar#714]
```
const chokidar = require('chokidar')
const path = require('path')

const pagesWatcher = chokidar.watch([
  path.join(__dirname, 'watchdir/**/*.md')
], {
  ignoreInitial: true
})

const log = () => {
  console.log('triggered')
}

pagesWatcher.on('add', log)
pagesWatcher.on('unlink', log)
pagesWatcher.on('change', log)
  
```

Works well on Ubuntu, but logs nothing on Windows

**Comment by es128** [comment]
`path.join(__dirname, 'watchdir/**/*.md')`

Can't do that on Windows as it will introduce backslash path separators to your glob pattern, which is invalid. It's unnecessary anyway. You can just watch `'watchdir/**/*.md'`, or use the `cwd` option if you need to.

**Comment by meteorlxy** [comment]
@es128 
Sorry but I want to watch a absolute path that should be passed in, not the `__dirname` indeed.

E.g:
```js
const sourceDir = '[An absolute path that passed by other script]'
const pagesWatcher = chokidar.watch([
  path.join(sourceDir , 'watchdir/**/*.md')
], {
  ignoreInitial: true
})
```

**Comment by es128** [comment]
Then make sure `sourceDir` uses forward-slash path separators. You cannot combine backslash paths with globs. Backlashes are reserved in globs for escaping special characters.

**Comment by es128** [comment]
Also `cwd: sourceDir` in the options may be an easy solution.

**Comment by meteorlxy** [comment]
@es128 
The `sourceDir` is processed by `path.resolve`.
And the `path.join` will resolve the slash correctly, too.

**Comment by es128** [comment]
notice the backslashes in the result? invalid glob. 

Don't use `path.join` with globs.
