### ISSUE TITLE
New npm's audit feature complains a lot

### ISSUE THREAD

**Issue by cronvel** [paulmillr/chokidar#715]
Hi and thanks for this great lib!
Please, can you publish a new version of *chokidar* with upgraded dependencies?
Npm is reporting various vulnerabilities due to some packages like *hoek, tough-cookie, sshpk,* etc, used by this project.

**Comment by klick-barakgall** [comment]
Possible duplicate of #713

**Comment by ehmicky** [comment]
#713 is unfortunately closed. I posted a comment on it though. The problem is indeed with chokidar dependencies on Mocha, Coveralls and Istanbul. Upgrading those fixes the problem.

**Comment by paulmillr** [comment]
PR please.
