### ISSUE TITLE
watch not works if watched glob contains Japanese characters folder name

### ISSUE THREAD

**Issue by aruku7230** [paulmillr/chokidar#716]
- chokidar: 2.0.3
- gulp: 4.0.0

```javascript
const watchGlob = 'フォルダ/**/*';

gulp.task('test', () => {
    const chokidar = require('chokidar');
    chokidar.watch(watchGlob, (done) => { done() })
            .on('change', (path) => {
                console.log(`File ${path} changed.`);
            });
});
```
Run `gulp test` and change フォルダ/foo file. log message "File フォルダ/foo changed" will not show.

Also reported [a issue](https://github.com/gulpjs/gulp/issues/2153) in gulp.

**Comment by es128** [comment]
Can't do anything here. Needs to be resolved in micromatch/micromatch#127

**Comment by pe8ter** [comment]
See https://github.com/micromatch/nanomatch/issues/18.

**Comment by jonschlinkert** [comment]
Got it, working on it https://github.com/gulpjs/gulp/issues/2153#issuecomment-439673022 (unless someone wants the bounty, please notify me ASAP).

**Comment by paulmillr** [comment]
Update to Chokidar v3.
