### ISSUE TITLE
On linux, when watching './' application closes unexpectedly

### ISSUE THREAD

**Issue by tim-digitized** [paulmillr/chokidar#720]
I originally wrote a small app on my Macbook, then merged and pulled onto my home Ubuntu 16.04 machine, but when I ran the node app, it closes as soon as it identifies that it's watching the current root dir. 

**On MacOS, the below works fine but fails in Ubuntu**
```
var watcher = chokidar.watch('./', {
    ignored: ['node_modules', 'package.json', 'index.yaml', '.git', /(^|[\/\\])\../],
    persistent: true
});
```

**On Ubuntu/MacOS, the following works, but adds all the files and folders as 'new' files and kicks off a mass-update of the file I'm updating when changes are made:**
```
var watcher = chokidar.watch('.', {
    ignored: ['node_modules', 'package.json', 'index.yaml', '.git', /(^|[\/\\])\../],
    persistent: true
});
```
But with the above, in MacOS it detects changes, but in Ubuntu it does not detect any changes.

**Comment by tim-digitized** [comment]
So in relation to chokidar not watching files at all... did some more digging and found out that if I edit files through MS Code, which is from a mapped drive on my NAS, it does not detect changes... but if I open a file a terminal, chokidar does detect the changes.

Are there known issues with GUI editors and mapped drives?

**Comment by es128** [comment]
Seems like you want the `ignoreInitial: true` option for the issue in the first comment, and `usePolling: true` to fix the issue with watching files on the mapped drive.
