### ISSUE TITLE
JavaScript heap out of memory.

### ISSUE THREAD

**Issue by sachin7254** [paulmillr/chokidar#727]
I am getting an error i.e FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory.

**Comment by paulmillr** [comment]
Sad!

**Comment by rostik404** [comment]
Hi!
I've got the same error too. In a snapshot of memory, I see, that chokidar stores links to files in the memory.
![2018-07-04_17-47-22](https://user-images.githubusercontent.com/8089139/42283512-5f2b19cc-7fb2-11e8-93fc-952cd5ce8f86.png)
@paulmillr, do you have any ideas, what can I do with this issue?

@sachin7254, did you fix this problem in your case?

**Comment by srguiwiz** [comment]
I don't see evidence those strings are from chokidar.  Not saying it isn't so, even though I doubt it, but so far this issue is lacking a good chain of evidence.

**Comment by eynol** [comment]
I've got the same error too. I fixed it by ignoring "node_modules" folder.

Don't watch the black hole. :joy:
