### ISSUE TITLE
Changes to files matching glob with negated directory aren't seen on Windows 7/10

### ISSUE THREAD

**Issue by viveleroi** [paulmillr/chokidar#728]
I'm giving chokidar an array of paths to watch - a glob for our core app scss is first, and then a pattern for all stand-alone css (with a negation for the scss directory). This works fine on macOS, but changes  to any file the second pattern matches aren't seen on Windows 7/10.

I can't seem to find any reason the glob won't work on windows only. It works fine on macOS, it reads the correct files when passed to node-sass directly, it's only breaking with chokidar in the stack. 

```
'WebContent/app/shared/scss/**/*.scss',
'WebContent/app/*/!(scss)/**/*.scss'
```

**Comment by paulmillr** [comment]
Update to Chokidar v3, it should resolve this.
