### ISSUE TITLE
Certain path are matched when followSymlinks is true when they should not ?

### ISSUE THREAD

**Issue by user-mk** [paulmillr/chokidar#729]
i want to watch any wp folder that i have in this fashion:

If a folder is named wp and then any number follows it should be returned as a path but only if it also has some other folders within it.

my folder structure is as follows: 

    /wp40
        / public_html
            / wp-content
                / themes
                    / cms
                    / other

    /wp41
        / public_html
            / wp-content
                / themes
                    / cms
                    / other

This is my glob pattern for chokidar to watch:
`/wp[0-9]{2}/public_html/wp-content/themes/cms1`

When i start chokidar it matches these path:
`/wp41/public_html/wp-content/themes/cms/functions.php`
`/wp41/public_html/wp-content/themes/other/other/partials/vc_parts/projects_cards/style_1`

Note that the `other` folder is a symlink and should not be matched according to the glob pattern.

What is wrong ? is it my glob pattern or something else ?

**Comment by paulmillr** [comment]
Update to Chokidar v3, it should resolve this.
