### ISSUE TITLE
Non-existant Symlink does not produce ready or error events

### ISSUE THREAD

**Issue by CxRes** [paulmillr/chokidar#739]
This error occurs in when `followSymlink` is `true`.  When a symlink points to a non existing location, chokidar noes not produce either an `'error'` or `'ready'` events!

This bug occurs  in `NodeFsHandler.prototype._addToNodeFs` in *lib/nodfs-handler.js*  when `fs.stat` in line 454 is invoked with a symlink that points to a non-existing location -- this invokes the error argument in the returned callback. This is handled by  `FSWatcher.prototype._handleError` at line 253 in *index.js*. However, since this is a `ENOENT` error, the conditional causes `'error'` event to be skipped. Hence, we have a situation where the non-exitant symlink essentially remains unhandled leading to the bug. 

I am not sure what would be the best way to handle this, otherwise I would have made a PR.

**Comment by paulmillr** [comment]
Update to Chokidar v3, it should resolve this.
