### ISSUE TITLE
Watch does not work for glob pattern which  intersects with non-glob part of another glob pattern

### ISSUE THREAD

**Issue by eGavr** [paulmillr/chokidar#747]
**Describe the bug**

Files are not being watched for glob `<dir>/**` if `<dir>` does not exist.

**Versions (please complete the following information):**
 - Chokidar version [2.0.4]
 - Node version [8.6.0]
 - OS version: [Ubuntu 16.04]

**To Reproduce**

```js
// index.js
const chokidar = require('chokidar');
const watcher = chokidar.watch([
    'some-*/*/*.js',
    'some-dir/*/*.css'
]);

watcher.on('add', path => console.log(path));
```

Create files `some-dir/dir/file.css`, `some-dir/dir/file.js` and run the script.

You will see nothing in console:

```
some-dir/dir/file.css
```

No any information about `some-dir/dir/file.js`.

If then you add, for example, `some-dir/dir/another-file.js` nothing logs to console too.

**Comment by goser** [comment]
I have some kind of same behavior on a Windows 10 machine.

When adding multiple files (100+) by multiple globs on intersecting directories I get different results for watched files on nearly every run. 

#748 worked for me as a fix

**Comment by paulmillr** [comment]
Update to Chokidar v3, it should resolve this.
