### ISSUE TITLE
Chokidar will trigger for unmodified files on Windows when LastAccessTime is changed

### ISSUE THREAD

**Issue by mikemaccana** [paulmillr/chokidar#750]
Given the following in Windows:

    var watcher = chokidar.watch(dir, {
        ignored: ignored,
        persistent: true,
        usePolling: config.options.legacyWatch || false,
        interval: config.options.pollingInterval,
    });

When a file is opened but not modified, Chokidar will trigger a change as `LastAccessTime` is modified. All other attributes remain unchanged. See https://github.com/remy/nodemon/issues/1208

**Versions (please complete the following information):**
 - Chokidar version: 170
 - Node version: v8.11.2
 - OS version: Microsoft Windows NT 10.0.17713.0

**To Reproduce**
Just open a file (changing `LastAccessTime` on a watched file. LMK if you want a demo app.

**Expected behavior**
No changes. Access Time is not considered a change. It is reading, not writing.

**Comment by dariocravero** [comment]
I can confirm that this is happening on Mac too

**Comment by goser** [comment]
Adding 
```javascript
if (event === 'change' && val1.atime && val1.mtime && val1.atime > val1.mtime) {
    return this;
}
```
to FSWatcher.prototype._emit worked for me as a hotfix but I am not sure if it would break other projects.

**Comment by mikemaccana** [comment]
@goser Send it as a PR and mark it as 'fixes #750'. It'll get more attention and someone will review it.

**Comment by johannreboulleau** [comment]
Hello,
We had the same problem, and we fix it with the [comment](https://github.com/remy/nodemon/issues/1208#issuecomment-405021044) of @svogal

**Comment by 7iomka** [comment]
> Hello,
> We had the same problem, and we fix it thanks to the [solution](https://github.com/remy/nodemon/issues/1208#issuecomment-405021044) of @svogal

Thank you!

**Comment by mikemaccana** [comment]
Looks like this is in 2.1.0, see https://www.npmjs.com/package/chokidar/v/2.1.0
