### ISSUE TITLE
Mac firing folder event twice at times

### ISSUE THREAD

**Issue by sekwah41** [paulmillr/chokidar#753]
**Describe the bug**
Mac firing folder event twice at times when it should fire once

**Versions (please complete the following information):**
 - Chokidar version 204
 - Node version  10.5.0
 - OS version: MacOS Sierra 10.13.6

**To Reproduce**
Copy and paste a large amount of folders in the same directory in the file explorer. If you tally the number of times addDir is fired if comes up as more than the number of folders where on linux and windows it is perfectly fine

Ideally prove a problem by isolating and making it reproducible with a very short sample program, which you could paste here:

```
// This is a stripped down version of my code which should be able to show the issue
var chokidar = require('chokidar');
let total = 0;
// Just point to some folder that is made
chokidar.watch("watchedFolder", {ignorePermissionErrors: true,
                awaitWriteFinish: true,
                ignoreInitial: true,
                depth: 1}).on('addDir', (path) => {
                console.log(++total);
            });/* Adding this next part in fixes the total number of files and the flag 132352 is only fired when it seems to have this double fire problem. (Well only once its come out with the wrong total out of all the times ive tested it)
            .on('raw', (event, path, details) => {
                if(details.flags === 132352) {
                    bar.info.folders--;
                }
            });*/
```

**Expected behavior**
One addDir file event fired per folder like on windows and linux

**Additional context**
I was just testing the limits to make sure it was not losing track of any folders or firing anything wrong. Usually fires with about 20 being copied and pasted but 100 should cause this issue without a doubt.

**Comment by damianobarbati** [comment]
I see the same, probably slightly different because it happens just when watcher is started.

```
watch(['./index.js', './api'], { ignored: ['./output.log'], persistent: true }).on('all', (event, filename) => {
    logger.info(`${filename} ${event}`);
});
```

Nothing should be fired at beginning but I get:
```
 index.js add
 ./api addDir
 api/index.js add
 api/jobs.js add
```

**Comment by sekwah41** [comment]
I think there may be something that isnt accounted for as much with the system that is being used on darwin @damianobarbati, if you look at the raw it states unknown for the event type but then has more info with codes in the details. It seems to mostly be certain flags that pop up that are not in the norm for add and remove events that are causing this but are still being classed as add events. Try logging the raw data and see what is given for file names showing up multiple times.

**Comment by danielo515** [comment]
The same is happening to me. In my case I'm only watching to add events

**Comment by danielo515** [comment]
Ok, I spoke too fast. In my case I was copying the file to a sub-folder in the same watched folder. After changing the watch dept to 0 everything started to work as expected.
