### ISSUE TITLE
Request for documentation of path glob

### ISSUE THREAD

**Issue by kylecordes** [paulmillr/chokidar#756]
**Describe the bug**

This bit of documentation missing is sufficiently problematic that I think it counts as a bug:

The "ignored" setting is documented as being "anymatch" compatible, but the "path", which is documented as accepting globs, doesn't have any pointer to what manner of globs are acceptable.

Further, there are no examples in the documentation of using globs in the path setting.

Addressing both of these might help not only with this request for doc, but might also help with some of the other open issues in this issue tracker right now, which have to do with path and lobs.

**Versions (please complete the following information):**
 - Chokidar version: 2.0.4
 - Node version: n/a
 - OS version: n/a

**To Reproduce**

(Read the docs  :-)  )

**Expected behavior**

Docs with path glob examples.

**Additional context**

**Comment by kimster1** [comment]
kkkkk
