### ISSUE TITLE
Sync file collection metadata to nosql

### ISSUE THREAD

**Issue by ridhwaans** [paulmillr/chokidar#757]
I want to know if someone has done this, and if it is a good design. I have a use case to gather metadata on a file collection in a directory. New files can be added, renamed, or moved to subdirectories at any time. Will need to call some apis to get metadata on each file as json then save/update to nosql db. Preferably without nodemon restarts or hot reloads. Need some guidance please.

**Comment by thelebster** [comment]
@ridhwaans look at this [example code](https://github.com/thelebster/code-examples/blob/master/nodejs/nodejs-file-watcher.js) as initial point, if this is still actual.
