### ISSUE TITLE
Request: Add configuration option to not use braces cache

### ISSUE THREAD

**Issue by BTMorton** [paulmillr/chokidar#759]
Currently, I am using chokidar to watch a folder with >55k files and am finding the this uses a significant amount of memory (450mb+) and is occasionally hitting the node memory limit. Obviously, this is not all due to chokidar and there are ways to extend the node memory limit, but during debugging and looking through a memory snapshot, I noticed that the single largest object in memory (300mb+) was the braces cache. Adding a call to `braces.clearCache()` after the initial file processing resulted in the memory usage being reduced to <200mb.

Would it be possible to add a configuration option to pass `{ cache: false }` to the braces call in chokidar?

**Versions (please complete the following information):**
 - Chokidar version 2.0.3
 - Node version 8.11.2
 - OS version: Windows 10/Debian Jessie

Example program to try to demonstrate the issue:
```javascript
var chokidar = require('chokidar');
var braces = require('braces');

console.log("Test starting");
chokidar.watch('some/folder/with/many/files/*', {}).on('ready', (event, path) => {
  console.log("chokidar ready");

  if (global.gc) { global.gc(); }
  let memoryUsage = process.memoryUsage();
  console.log(`Before clear: ${memoryUsage.heapUsed}/${memoryUsage.heapTotal}`);

  braces.clearCache();

  if (global.gc) { global.gc(); }
  memoryUsage = process.memoryUsage();
  console.log(`After clear: ${memoryUsage.heapUsed}/${memoryUsage.heapTotal}`);

  process.exit();
});
```

Running the above using `node --expose-gc bracesTest.js` on my testing file system gives the following output:
```
Test starting
chokidar ready
Before clear: 446778640/585011200
After clear: 133833408/241065984
```

Obviously, this is part of a solution, but it only works on initial file loading and my concern is that additional calls during add/change/delete events will continue to take up memory as it continues to run. Not using the cache at all will result in slightly slower performance, but for my use case I think it's worth the trade off for saved memory.

I am currently using chokidar to watch media files for changes. My testing system is created using symlinked media files into a single folder with the following script:
```bash
#!/bin/bash

for i in {0..50000} 
do
	ln -s ../MediaFile.mp4 clip_$i.mp4
done
```

Screenshot of the memory snapshot that led me to the braces cache:
![image](https://user-images.githubusercontent.com/9026309/44101143-ad1b72c0-9fde-11e8-8523-f65de3a872e0.png)

**Comment by paulmillr** [comment]
done...probably
