### ISSUE TITLE
Error: Cannot find module fsevents

### ISSUE THREAD

**Issue by j-fliegenschmidt** [paulmillr/chokidar#77]
I just gave chokidar a shot (found you on [SO](http://stackoverflow.com/questions/13695046/watch-a-folder-for-changes-using-node-js-and-print-file-paths-when-they-are-cha)). I got the latest version via NPM (I'm on Win8 64bit), but require() would fail with error "Cannot find module fsevents", after reverting to 0.7.1, that error is gone.<br>
I did try to get fsevents via NPM, but that failed with

npm WARN package.json FSExpose@0.0.0 No repository field.
npm http GET https://registry.npmjs.org/fsevents
npm http 304 https://registry.npmjs.org/fsevents
gypnpm ERR! weird error 1
npm

**Comment by jyoung-fs** [comment]
For people coming here while trying to use `nexe` on linux to compile a project with this module, you need to comment out this line: https://github.com/paulmillr/chokidar/blob/master/lib/fsevents-handler.js#L7 . Browserify (I believe it's this) tries to gather all dependencies by scanning `require`'s, and it tries to find this dependency which isn't used on linux.

**Comment by heyimalex** [comment]
It's the same issue if you're using webpack. And probably any other module bundler that needs to statically resolve dependencies. Here's a one liner to fix it.

```bash
sed -i '/try { fsevents = require/d' node_modules/chokidar/lib/fsevents-handler.js
```
