### ISSUE TITLE
ability to disable fs watching?

### ISSUE THREAD

**Issue by pieh** [paulmillr/chokidar#770]
Would PR that adds ability to disable file watchers be supported?

### Motivation behind it
We use `chokidar` extensively in https://github.com/gatsbyjs/gatsby and we have 2 modes:
 - one that does care about about listening to fs changes (running dev server and handling hot reloads)
 - the other one that only care about initial directories traversal (running builds). 

Builds are often ran in CI/CDs where in some cases we hit limit of FS watchers that we can't increase. We got couple of PRs that add separate implementation for builds ( https://github.com/gatsbyjs/gatsby/pull/5807 , https://github.com/gatsbyjs/gatsby/pull/6207 ). This can be flaky as we would use different tools for builds and dev server and could lead to unwanted differences between those modes.

Current workaround for FS watchers limit is to use polling, but it would be great if we could just disable watching for builds

**Comment by paulmillr** [comment]
No. The purpose of the file watcher is to watch files. If you need to traverse directories, maybe use [readdirp](https://github.com/paulmillr/readdirp) — which I also maintain BTW.

**Comment by pieh** [comment]
Thanks for response @paulmillr - can totally understand! We will probably create some (hopefully thin) abstraction for gatsby that will handle our needs. 

Just have question if path globs in `readdirp` and path globs that can be used in `chokidar` have same handling (f.e. both use `minimatch`)? I'll probably dive more in depth into chokidar and readdirp codebases but this this info could potentially save us some time.

**Comment by paulmillr** [comment]
They both use `micromatch`. Yes.

**Comment by odinho** [comment]
For people getting here via search, you can make your CI work by setting these env vars:
```
CHOKIDAR_USEPOLLING=1
CHOKIDAR_INTERVAL=3600000  # ms between polls (1h here)
```

(This is just to work around other project dependencies that don't have a way to disable watching, but luckily using Chokidar, -- looking at you Firebase emulators)
