### ISSUE TITLE
Emit custom events?

### ISSUE THREAD

**Issue by fabiospampinato** [paulmillr/chokidar#771]
I'm writing a wrapper around chokidar that emits a `rename` event when appropriate, instead of emitting the `unlink` and `add` events.

I think there's no way of emitting custom events, so that the users of my wrapper can write `watcher.on ( 'custom', handler )`, is there?

**Comment by paulmillr** [comment]
Chokidar is an instance of EventEmitter so you can emit your events and listen to them freely.
