### ISSUE TITLE
Ignored directories not being ignored

### ISSUE THREAD

**Issue by mlynch** [paulmillr/chokidar#773]
**Describe the bug**
Ignored does not ignore all files in all subdirectories of the ignored paths. For example, `**/node_modules/**/*` does not ignore files in `**/node_modules/.staging/**/*`

This can be checked by watching a typical JS project that uses npm, and then running `npm install` in that directory. You will receive `file added` events for files in `node_modules/.staging` which is incorrect.

I tried a lot of permutations of the ignored paths, such as `**/node_modules` which did not work either.

**Versions (please complete the following information):**
 - Chokidar version [e.g. 2.0.4, or commit hash] 2.0.4
 - Node version [e.g. 10.4.1] 8.11.1
 - OS version: [e.g. Ubuntu 16.04, or Windows 10] OS X 10.13.3

**To Reproduce**
Steps to reproduce the behavior.

```
var chokidar = require('chokidar');
var fs = require('fs');
// One-liner for files and directories starting with 'test'
const watcher = chokidar.watch(path, {
  ignored:  ['**/node_modules/**/*', '**/.git/**/*'],
  ignoreInitial: true,
  ignorePermissionErrors: true,
  followSymlinks: true,
  interval: 1000,
  binaryInterval: 1000,
});
```

**Expected behavior**
All files in any node_modules directory and any subdirectory in any node_modules directory will be ignored.

**Additional context**
I was able to work around the issue by using the function form of `ignored` to simply reject any path that has `node_modules` in it.

**Comment by zewa666** [comment]
This seems to be only affecting OSx, I can reproduce it there but not on Linux nor Windows. Actually none of the glob patterns inside ignored do work.

Node: 8.9.1
OSX: 10.14

**Comment by ansonhorse** [comment]
`useFsEvents: false` doesn't seem work to me

**Comment by VladimirAmiorkov** [comment]
I am facing similar issues.I want to watch the absolute path "some/folder" but ignore a "build" subfolder of that directory ("some/folder/build")

```
chokidar.watch('some/folder/', {
  ignored: ['some/folder/build']
}).on(...);
```

**Comment by cmckulka** [comment]
Seeing a version of this on OSX. At least simple file globs are working but regular expressions are not.

I **do** get events for '.git/index' for the regex `/^\.git\//` and `/^\.git\/.*/` (among other variants).

I don't get events if I include '.git\/*' in the ignore list.

**Comment by RayzRazko** [comment]
I'm experiencing same issue. 
OSX: 10.14.5
node: 12.4.0
Next code:
```javascript
const baseDir = __dirname;
const ignored = ['node_modules/**/*'].map(glob => path.resolve(baseDir, glob));
watcher = chokidar.watch(baseDir, { ignored });
```
Fires events for all files in node_modules.

**Comment by RayzRazko** [comment]
For those who looks for workaround: you can pass function as `ignored` parameter and filter paths manually. Example:
```javascript
chokidar.watch(watchPath, {
   ignored: (path) => path.includes('node_modules')
});
```

**Comment by Stefano1990** [comment]
I can't seem to stop chokidar from watching my .git directory which in turn is choking (hue hue) my electron.

**Comment by sammenza** [comment]
This answer doesn't work for me. I tried the following:
```
var watcher = chokidar.watch('src/*/*', {
	ignored: (path) => {
		return path.includes('.m.css.d.ts');
	}, persistent: true
  })
```
I'm using MacOS Version 10.14.5

**Comment by entozoon** [comment]
To further @RayzRazko's helpful snippet, you could ignore a variety of string includes in this fashion:
```js
chokidar.watch(watchPath, {
   ignored: path => ["node_modules", "another_dir"].some(s => path.includes(s))
});
```
But it might be a regex situation if you want anything more robust

**Comment by paulmillr** [comment]
Works correctly for me with the latest chokidar@3.2.0 (master). Ensure you have node.js 8.16 or higher.

```js
require('chokidar').watch('src/**/*', {
  ignored: (path => path.includes('hello'))
  persistent: true
}).on('all', (event, path) => { console.log(event, path); })
```

**Comment by lk0606** [comment]
have some issue
macOS: 10.15.4 
node: 13.6.0

**Comment by lk0606** [comment]
> For those who looks for workaround: you can pass function as `ignored` parameter and filter paths manually. Example:
> 
> ```js
> chokidar.watch(watchPath, {
>    ignored: (path) => path.includes('node_modules')
> });
> ```

not work as expected
