### ISSUE TITLE
Why is Chokidar called Chokidar?

### ISSUE THREAD

**Issue by jbreckmckye** [paulmillr/chokidar#776]
I'm just curious.

**Comment by jbreckmckye** [comment]
Found the origin! It's a variant of _chowkidar_, itself a transliteration of a Hindi word meaning 'watchman, gatekeeper', _चौकीदार_.

https://en.wiktionary.org/wiki/chowkidar

**Comment by paulmillr** [comment]
It was pretty random. That's mostly it!

**Comment by xeoneux** [comment]
As an Indian, I found the name funny :smile:

**Comment by shivamb312** [comment]
> Found the origin! It's a variant of _chowkidar_, itself a transliteration of a Hindi word meaning 'watchman, gatekeeper', _चौकीदार_. This ultimately comes from Sanskrit _ चतुष्क_ (crossway, quadrangle, consisting-of-four).
> 
> That comes from _चतुर्_, loosely pronounced 'catur', which is cognate to Proto-Indo-European _*kʷetwóres_, root of our word _quarter_ (via Latin _quartus_). Basically the idea is that you might 'guard' (chowkidar) an enclosed space, usually contained within four walls.
> 
> https://en.wiktionary.org/wiki/chowkidar

When I found this library, I thought the name definitely came from its Hindi meaning LOL. It was so funny. Just wanted to let you know that चतुर् is pronounced "chatur".

**Comment by tukusejssirs** [comment]
@paulmillr, I think the reason behind the name should be mentioned in the `README.md`. :)

> [@xeoneux]
> As an Indian, I found the name funny :smile:

@xeoneux, may I know why do you find the name funny?

**Comment by PrabhanshuAttri** [comment]
@tukusejssirs When I hear chokidar, it reminds of an actual watchman. Chokidar is such a common word that finding it in tech was funny for me, especially having a piece of software in my system which I can refer to as my own chokidar/watchman.

**Comment by Kaos-Industries** [comment]
> 
> 
> That's mostly it!

Mostly? What's the rest of it? And what inspired you to call it that?
