### ISSUE TITLE
Windows Path Separator and Globs

### ISSUE THREAD

**Issue by CaitlinWeb** [paulmillr/chokidar#777]
**Describe the bug**
On Windows chokidar fails to watch files if given a glob path with `\` (expressed in a string as `\\`) as the path separator. This is not documented, and problematic when using [Node's `path`](https://nodejs.org/api/path.html#path_windows_vs_posix).

As stated in #668 "If you want to use globs, you must ensure that only forward slashes are used as path separators on your input to chokidar." Could this be added to the documentation, at the very least?

**Versions (please complete the following information):**
 - Chokidar version: 2.0.2
 - Node version: 9.4.0
 - OS version: Windows 10

**To Reproduce**
Requires a Windows machine. Create a directory structure of `foo/bar/test.txt`.

```
var chokidar = require('chokidar');
var path = require('path');

/*
 * This doesn't work on Windows 10
 */

// Watch files in foo/bar
var watcher1 = chokidar.watch(path.join('foo', 'bar/*.txt'));
watcher1.on('ready', () => {
	console.log(path.join('foo', 'bar/*.txt'), '\n', '[1] Watching ', watcher1.getWatched());
});

// Absolute path foo/bar
var watcher2 = chokidar.watch(path.resolve('foo', 'bar/*.txt'));
watcher2.on('ready', () => {
	console.log('\n', path.resolve('foo', 'bar/*.txt'), '\n', '[2] Watching ', watcher2.getWatched());
});

/*
 * This DOES work on Windows 10
 */

// Relative path
var watcher3 = chokidar.watch(path.join('foo', 'bar/*.txt').replace(/\\/g, '/'));
watcher3.on('ready', () => {
	console.log('\n', path.join('foo', 'bar/*.txt').replace(/\\/g, '/'), '\n', '[3] Watching ', watcher3.getWatched());
});

// Absolute path
var watcher4 = chokidar.watch(path.resolve('foo', 'bar/*.txt').replace(/\\/g, '/'));
watcher4.on('ready', () => {
	console.log('\n', path.resolve('foo', 'bar/*.txt').replace(/\\/g, '/'), '\n', '[4] Watching ', watcher4.getWatched());
});

```

Expected results are like: `Watching { '...\\foo': [ 'bar' ] ... }`
Actual results for [1] and [2]: `Watching { }`

**Expected behavior**
Accept file paths with globs regardless of what path separator is used.

**Additional context**
Caught this while testing out patternlab-node-cli.

**Edit:** Also, I tried using `path.posix` and found it works only for relative paths. Strangely this can result in absolute paths like `C:\folder\to\project/foo/bar/*.txt`. It won't fail completely, it'll result in something like 
```
Watching  { 'C:\\path\\to\\project\\foo': [ 'bar' ],
  'C:\\path\\to\\project\\foo\\bar': [],
  'C:\\path\\to\\project\\foo\\bar\\*.txt': [] }
```
which as you can see says the directory is being watched but not the files. So using _all_ forward slashes is the solution.

**Comment by 7iomka** [comment]
I ran into this problem for a long time without understanding what was happening.
I just upgraded to last version plugin browser-sync, wich uses this plugin!
