### ISSUE TITLE
Chokidar change event triggers on watcher.add(path)

### ISSUE THREAD

**Issue by monchoz** [paulmillr/chokidar#780]
Hi, is there a way to prevent this? I have an electron app that downloads files on start and uploads when change triggers. So it's downloading and uploading the files.

I got the idea of unwatch the path before the download so that It doesn't upload again but when I do the add(path) after the download finishes the change triggers and uploads the file.

**Comment by paulmillr** [comment]
Not really — you need to handle this logic on your own.
