### ISSUE TITLE
Chokidar with FTP

### ISSUE THREAD

**Issue by bahadiremre** [paulmillr/chokidar#781]
Hello,
I've tried to use chokidar with ftp. Here is my code:

var chokidar = require("chokidar");
var watcher = chokidar.watch("ftp://admin:adminpass@125.125.125.125:1234/DATA/", { ignoreInitial:false });

watcher.on("ready", () => {
      console.log("chokidar is ready");
      watcher.on("all", (event, path) => {
             console.log(event,path);
       });
});
I'm trying to watch "DATA" directory on ftp. But events are not fired even if files are added to "DATA" directory on ftp. Is there something wrong with my code or isn't chokidar able to watch file on ftp?

**Comment by samvv** [comment]
Chokidar definitely isn't able to watch FTP directories. It uses facilities provided by the underlying OS, which in case of macOS is `FSEvents`. I  doubt FTP even supports a protocol for getting file updates, so the only thing you can do is to manually write some polling using specialised libraries.
