### ISSUE TITLE
On macOS Sierra (10.12.6) setting 'usePolling' to true override awaitWriteFinish setting.

### ISSUE THREAD

**Issue by backslash451** [paulmillr/chokidar#782]
**Describe the bug**
Setting 'usePolling' to true while watching a local directory on macOS Sierra (10.12.6) override the 'awaitWriteFinish' setting resulting in launching 'add' events for large file stil in the writing process.

**Versions (please complete the following information):**
 - Chokidar version 2.0.4
 - Node version 8.11.2
 - OS version: macOS Sierra 10.12.6

**To Reproduce**
This is the configuration I am using.

```
const chokidar = require('chokidar');

const options = {
    ignored: /(^|[/\\])\../,
    persistent: true,
    followSymlinks:false,
    usePolling: true,
    awaitWriteFinish: {
      stabilityThreshold: 2000,
      pollInterval: 100,
    },
    ignoreInitial: true,
    depth: 0,
  };

const watcher = chokidar.watch(w.PATHS, options);

  watcher.on('ready', () => {
    logger.debug('Initial scan complete. Ready for changes');
  });

  watcher.on('add', (path) => {
    logger.debug(`File ${path} has been added`);
  });

  watcher.on('error', (error) => {
    logger.error(error);
  });
```

**Expected behavior**
The library fires 'add' events for large files still in the write process.

**Comment by paulmillr** [comment]
Update to Chokidar v3, it should resolve this.
