### ISSUE TITLE
Chokidar causes VS Code extensions crashes on VS Code Insiders v1.31

### ISSUE THREAD

**Issue by SounD120** [paulmillr/chokidar#787]
**Describe the bug**
All VS Code extensions that are using Chokidar in their dependencies crashes on new VS Code Insiders version, that to be release approximately in February.

**Versions (please complete the following information):**
 - Chokidar version 2.0.4
 - Node version 10.2.0
 - OS version: macOS Mojave 10.14.2

**To Reproduce**
1) Install latest VS Code Insiders(1.31-insiders)
2) Install any of VS Code extensions that are using Chokidar (for example [vscode-cordova](https://github.com/Microsoft/vscode-cordova))
3) Try to use any of extension functionality, that calls the extension code (accordingly to the example described above, try to debug Apache Cordova application)

**Expected behavior**
VS Code extensions that are using Chokidar is not crashes with new VS Code Insiders(1.31-insiders) version.

**Additional context**
This issue was [investigated already](https://github.com/Microsoft/vscode/issues/64981#issuecomment-447880936) and the problems is in `fsevents` package, that have [some issues with Electron 3 (Node.js 10.2.0) that VS Code 1.31 is using under the hood](https://github.com/electron/electron/issues/14841). As described in [this issue](https://github.com/strongloop/fsevents/issues/229) `fsevents@1.2.4` have no such problems.
So it looks like Chokidar is needed to be bumped `fsevents` to 1.2.4 version to be able to work with new Electron and VS Code versions without any errors.

**Comment by KamasamaK** [comment]
The `fsevents` dependency was updated in v.2.1.0.

**Comment by christianvoigt** [comment]
Hi, I am using v2.1.0 with fsevents 1.2.7 in my VSCode extension and this still causes the extension to crash in VSCode 1.32.3 on OSX. 

See https://github.com/christianvoigt/argdown/issues/104

How far away is the release of 3.0.0?

**Comment by christianvoigt** [comment]
I just checked again and there seems to be an issue with the update process in VSCode. Even though VSCode shows me I have installed the new version of my extension, the fsevents error thrown shows it is still trying to run the old version. So this is not an issue of Chokidar 2.1.0. Sorry for bothering you.

**Comment by nonoroazoro** [comment]
Still not work with chokidar@2.1.5

**Comment by paulmillr** [comment]
Try 3.0-master.

**Comment by nonoroazoro** [comment]
@paulmillr chokidar 3.0.0 works fine, thanks a lot!

**Comment by paulmillr** [comment]
Great!
