### ISSUE TITLE
Not working with fs.writeFile

### ISSUE THREAD

**Issue by hyurl** [paulmillr/chokidar#790]
**Describe the bug**
I use chokidar to watch file changes and reload modules, it works fine when I manually edit the file. However, when I use fs.writeFile() to update the file contents, chokidar doesn't trigger the 'change' event.

**Versions (please complete the following information):**
 - Chokidar version [2.0.4] 
 - Node version [11.6.0]
 - OS version: [Manjaro 18.0]

**To Reproduce**
Steps to reproduce the behavior.

Ideally prove a problem by isolating and making it reproducible with a very short sample program, which you could paste here:

```
var chokidar = require('chokidar');
var fs = require('fs');

fs.writeFileSync("test.txt", "something");
chokidar.watch(process.cwd(), {}).on('change', (filename) => {
  console.log(filename);
});
fs.writeFileSync('test.txt', 'testing 1');
```

**Expected behavior**
The expected output should be the filename of test.txt, however, nothing is printed, the change event 
is never triggerred.

**Comment by paulmillr** [comment]
Update to Chokidar v3, it should resolve this.

**Comment by fabiospampinato** [comment]
@paulmillr I've tried all v3.x.x releases and I can always reproduce the reported issue. Maybe we need better tests?

The only way I can get it to work is if I delay the final `writeFileSync` a bit.

**Comment by hyurl** [comment]
As I’ve tested, the watch will not work immediately, it seems it needs some time for initiating asynchronously, maybe scanning files. If wait a while before performing any operations, it should do fine.

**Comment by fabiospampinato** [comment]
Is that the intended behavior though? Waiting some arbitrary amount of time is not very reliable.

**Comment by paulmillr** [comment]
> Waiting some arbitrary amount of time is not very reliable

In my experience chokidar has always been reliable, so not sure why this case is different. 

Any tests that reproduce a buggy behavior would be useful, of course.

Ensure you are using latest chokidar with node 8.16, latest node-10 or latest node-12. Any other node is unsupported and can be buggy. It's not just chokidar — nodejs by itself doesn't support anything but these versions.

**Comment by paulmillr** [comment]
The "original snippet" blocks event loop before asynchronous actions, including setting up fsevents listeners, happen. A time needs to be passed for chokidar to be ready for events. `ready` event exists for this purpose:

```
var chokidar = require('chokidar');
var fs = require('fs');

fs.writeFileSync("test.txt", "something");
chokidar.watch(process.cwd(), {})
.on('ready', () => {
  fs.writeFileSync('test.txt', 'testing 1');
})
.on('change', (filename) => {
  console.log(filename);
});
```

**Comment by fabiospampinato** [comment]
I see, I totally forgot about the "ready" event, that would work for me, thanks.
