### ISSUE TITLE
Change event not emitted when `polling: true`

### ISSUE THREAD

**Issue by Blackbaud-PaulCrowder** [paulmillr/chokidar#792]
**Describe the bug**
File changes are no longer being detected when the `polling` option is set to `true` in 2.1.0.

**Versions (please complete the following information):**
 - Chokidar version 2.1.0
 - Node version 10.15.1
 - OS version: macOS Mojave 10.14.2

**To Reproduce**
- Install chokidar 2.1.0
- Create a Node script named `index.js` with the following source code:

```
const chokidar = require('chokidar');

chokidar.watch(
  'test.txt', 
  {
    usePolling: true
  }
).on(
  'all', 
  (event, path) => {
    console.log(event, path);
  }
);
```

- Create a `test.txt` file in the same directory as the Node script
- Run `node .` in the Node script's directory
- Open `test.txt` in a text editor (I tested with both TextEdit and Visual Studio Code)
- Make a change to the file and save it

**Expected behavior**
The text `change test.txt` should be written to the console.  Instead, it is never written to the console, or only written sporadically.

**Additional context**
I confirmed the expected behavior does occur in version 2.0.4.  The expected behavior also occurs in 2.1.0 when the `polling` option is not specified.  Commit https://github.com/paulmillr/chokidar/commit/fb8ef5e0ee41054589ace651f38e352004a74079 seems to be the culprit.

I first experienced this issue because chokidar 2.1.0 was installed as a transitive dependency of webpack and webpack-dev-server, so consumers of those libraries will likely experience the same issue.

**Comment by paulmillr** [comment]
@mikemaccana @markablov the change broke this use case. We need to resolve it, or revert.

**Comment by markablov** [comment]
@paulmillr looks like OS sets ModifiedTime and AccessedTime simultaneously. In my test i recevied sutiations when `atime < mtime` and `mtime > atime` for same actions. But it's small difference between them, so i think that 1s threshold is enough. And original issue (which was solved by my PR) also would be coped.

I will prepare PR shortly.

**Comment by markablov** [comment]
@paulmillr https://github.com/paulmillr/chokidar/pull/793

**Comment by paulmillr** [comment]
@Blackbaud-PaulCrowder let us know if the latest `master` commit fixes your issue

**Comment by Blackbaud-PaulCrowder** [comment]
@paulmillr I just installed from `master` and it seems to be fixed.  Thanks for the quick turnaround.

**Comment by paulmillr** [comment]
pushed 2.1.1
