### ISSUE TITLE
Add TypeScript bindings

### ISSUE THREAD

**Issue by paulmillr** [paulmillr/chokidar#794]
Not really familiar with TS — just saw this https://github.com/Microsoft/vscode/blob/master/src/typings/chokidar.d.ts

**Comment by skovy** [comment]
It looks like there are types defined in the DefinitelyTyped repository: 

- https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/chokidar/index.d.ts
- https://www.npmjs.com/package/@types/chokidar

Or are you looking to add those to this package so it's not necessary to install the typings separately?

**Comment by paulmillr** [comment]
Probably. Don’t want to increase size too much; but if it would help TS users.

**Comment by skovy** [comment]
Took a stab at moving the types over in https://github.com/paulmillr/chokidar/pull/801, feedback welcome!
