### ISSUE TITLE
Chokidar 3.x

### ISSUE THREAD

**Issue by paulmillr** [paulmillr/chokidar#797]
- Support only node 8+; since recent fsevents would do the same
- Async / await instead of callbacks
- Less code, less dependencies

**Comment by Globegitter** [comment]
Would it also be possible to get a/the fix in for https://github.com/paulmillr/chokidar/issues/696?

**Comment by paulmillr** [comment]
We'll try; any help on the issue would be appreciated.

**Comment by Globegitter** [comment]
As I said I could only reproduce it on macos but it works fine on linux. I also posted a fix: https://github.com/ecosia/chokidar/tree/symlink-fix-mac we have been using this now for months on the mac's of our developers and it seemingly is working fine. I am also happy to make a PR out of this.

**Comment by paulmillr** [comment]
Out!
