### ISSUE TITLE
Npm Audit Failure

### ISSUE THREAD

**Issue by Adam-Kernig** [paulmillr/chokidar#802]
**Describe the bug**
You have a dependancy on anymatch when anymatch has been updated to include an updated version of micromatch please also update

https://github.com/micromatch/anymatch/issues/26

│ Low           │ Regular Expression Denial of Service                      
│ Package       │ braces                                                    
│ Patched in    │ >=2.3.1                                                     
│ Dependency of │ @angular/compiler-cli [dev]                             
│ Path          │ @angular/compiler-cli > chokidar > anymatch > micromatch > braces                                                       
│ More info     │ https://npmjs.com/advisories/786

**Comment by paulmillr** [comment]
not an issue — just do `npm update`. we follow semver, so does anymatch
