### ISSUE TITLE
Changing one file in a folder triggers 'add' event for all files in watched directory

### ISSUE THREAD

**Issue by vedantroy** [paulmillr/chokidar#805]
**Describe the bug**
Changing one file in a directory unexpectedly triggers add events for every file in that directory.
 
**Versions (please complete the following information):**
 - Chokidar version 2.1.2
 - Node version v10.9.0
 - OS version: Ubuntu 18 LTS

**To Reproduce**
Create a folder with multiple files. Use the program below to watch the folder. Rename one of the files.
```
const chokidar = require('chokidar')
chokidar.watch('path_to_folder', {
    awaitWriteFinish: {
        stabilityThreshold: 2000,
        pollInterval: 100,
    },
})
    .on('add', path => {
        console.log(`${path} ADDED`)

    })
    .on('change', () => {
        console.log(`${path} CHANGED`)
    })
    .on('unlink', () => {
        console.log(`${path} REMOVED`)
    })
```

**Expected behavior**
An add event to be triggered for the new name of the renamed file. An unlink event to be triggered for the old name of the renamed file. 
**Additional context**
Related issue: https://github.com/paulmillr/chokidar/issues/110
Only tested with a single folder with no sub folders.

**Update**: Setting `ignoreInitial` to `true` fixed the issue.

**Comment by paulmillr** [comment]
Update to Chokidar v3, it should resolve this.

**Comment by Aveek-Saha** [comment]
I am still having this issue on Chokidar v3.4.3
