### ISSUE TITLE
Interval with Kubernetes and shared folders

### ISSUE THREAD

**Issue by gigouni** [paulmillr/chokidar#809]
Hi,

I using chokidar in a Kubernetes environment, based on multiple machines, with a shared folder mounted through a volume into my app container. I'm adding files to the watched folder but, even with the following configuration

```javascript
    const watchFolderOptions = {
      ignored: /(^|[\/\\])\../,
      persistent: true,
      usePolling: true
    }
``` 

or 

```javascript
    const watchFolderOptions = {
      ignored: /(^|[\/\\])\../,
      persistent: true,
      usePolling: true,
      interval: 100,
      binaryInterval: 100,
      CHOKIDAR_INTERVAL: 100
    }
``` 

**The interval isn't 100 milliseconds but rather something between 10/60 seconds (it's not always the same timing).**

**Versions**
 - Chokidar version: "chokidar": "2.1.1"
 - Node version

```shell
λ node -v && npm -v
v8.10.0
5.6.0
```

 - OS version: Windows 10 Pro

**To Reproduce**

- Have a Kubernetes cluster
- Mount a volume between an folder within a container
- Start the watchfolder at the start of your app (the existing files will be perfectly watched)
- Move files to the target mounted folder
- Wait (more than the defined interval value)
- The watch folder triggers the rest of the algorithm

**Actual code sample**

```javascript
import watcher from 'chokidar'

[...]

  runWatcher() {
    // See https://github.com/paulmillr/chokidar#getting-started
    const watchFolderOptions = {
      ignored: /(^|[\/\\])\../,
      persistent: true,
      usePolling: true,
      interval: 100,
      binaryInterval: 100,
      CHOKIDAR_INTERVAL: 100
    }

    try {
      watcher
        .watch(INCOMING_PATH, watchFolderOptions)
        .on('all', async (event, absPath) => {
          logger.debug(fnRun, `triggered event "${event}" in the watched folder for "${absPath}"`)
        })
        .on('add', async absPath => {
          logger.info(fnRun, `new file added in the watched folder: "${absPath}"...`)
          await this._readFile(absPath)
        })
    } catch (err) {
      throw new Error(`Cannot watch folder ${INCOMING_PATH}`)
    }
  }
```

**Additional info**

- The app uses a persistent volume which can go to, on the one hand, an host path or in another hand, to NFS. It's working for host path, **but it's taking a while with NFS**.
- I've looked at these issues too but did not solved the problem
  - <https://github.com/paulmillr/chokidar/issues/465>
  - <https://github.com/paulmillr/chokidar/issues/225>
  - <https://github.com/paulmillr/chokidar/issues/783>
  - <https://github.com/paulmillr/chokidar/issues/623>

Where am I  wrong?

Thanks.

**Comment by gigouni** [comment]
FYI,

The Kubernetes network driver was the source of the problem. No problems now.

**Comment by wunderkind2k1** [comment]
I am facing a similar issue - did you change the network driver? Which one works? Thx, Sven
