### ISSUE TITLE
atomic option is broken on Windows since 2.1.3

### ISSUE THREAD

**Issue by jordanbtucker** [paulmillr/chokidar#812]
**Describe the bug**
Version 2.1.3 changed the way the `atomic` option is handled, which has caused chokidar to miss all changes to files on Windows.

**Versions (please complete the following information):**
 - Chokidar version: 2.1.3
 - Node version: 10.15.3
 - OS version: Windows 10

**To Reproduce**
```js
fs.writeFileSync('test.txt', '')
const watcher = chokidar.watch('.')
watcher.on('change', path => {
  console.log(path) // This never happens.
})
watcher.on('ready', () => {
  fs.writeFileSync('test.txt', 'test')
})
```

This works, however.

```js
fs.writeFileSync('test.txt', '')
const watcher = chokidar.watch('.', {atomic: false})
watcher.on('change', path => {
  console.log(path) // This never happens.
})
watcher.on('ready', () => {
  fs.writeFileSync('test.txt', 'test')
})
```

**Additional context**
This has broken nodemon on Windows since `atomic` is `true` by default.

**Comment by kraramel** [comment]
And where can i change this ?

**Comment by paulmillr** [comment]
@mitar we'll revert your stuff unless you fix it

**Comment by paulmillr** [comment]
reverted, check out 2.1.5

**Comment by mitar** [comment]
Hm, there was not really much time given to fix this, no?

Anyway, I do not have access to Windows machine, so somebody else should look into that.
