### ISSUE TITLE
chokidar needs incredible amount of RAM

### ISSUE THREAD

**Issue by Tilogorn** [paulmillr/chokidar#813]
**Describe the bug**
Not sure if its a bug, but adding ~11k files to a watched directory (half of them match the chokidar naming pattern) uses over 5GB of RAM. Nodejs process manually terminated after ~5 minutes.

See this log of psrecord:

![ram_usage](https://user-images.githubusercontent.com/7524854/54923421-7ef89b80-4f0a-11e9-97ab-72e6ec0a6d12.png)

**Versions:**
 - chokidar@2.1.5
 - nodejs@8.12.0
 - Linux Mint 19

**Hardware**
- Lenovo Laptop Intel© Core™ i5-6200U CPU @ 2.30GHz × 2
- 8 GB RAM
- 250 GB SSD

**To Reproduce**
```
var chokidar = require('chokidar');

chokidar.watch('*.json', {
    cwd: './files',
    ignoreInitial: true,
}).on('add', function(fn) {
    console.log('Added: ' + fn);
}).on('unlink', function(fn) {
    console.log('Deleted: ' + fn);
});
```
**Then:** adding about 11000 files to the directory `files/`
The first two files get `console.logged`, then its just the RAM usage that increases.

**Expected behavior**
- A `console.log` for every file
- Not that much RAM usage

**Comment by paulmillr** [comment]
yep, i'm refactoring this now - track #766 for that. improvements should be coming very soon.

BTW try non-polling mode.

**Comment by Tilogorn** [comment]
Happy to hear that! I'm looking forward to your update.

BTW: According to the `README.md` `usePolling` defaults to `false`, so my MWE should already be in non-polling mode.
