### ISSUE TITLE
How unwatch directory non-recursively?

### ISSUE THREAD

**Issue by erikjalevik** [paulmillr/chokidar#817]
I'm implementing a file browser with multiple panes, where each one shows a flat listing of a particular directory. At startup, I'm setting up an `FSWatcher` with depth 0. On navigation, I `unwatch` the previous path, and `add` the new one.

This works, until I unwatch a directory which is an ancestor of a directory shown in a different pane. For example:

Pane 1 shows `/a/b`.
Pane 2 shows `/a/b/c/d`.
If Pane 1 now navigates to `/a/b/c`, I issue an `unwatch` for path `/a/b` and an `add` for path `/a/b/c`.

However, the `unwatch` seems to remove pane 2's watch on `/a/b/c/d` despite my `FSWatcher` being initialised with a depth of 0. I get no more events for anything happening in `/a/b/c/d`.

What is the proper way of doing this?

**Comment by paulmillr** [comment]
Do a check if b is a child of a and don’t unwatch it then

**Comment by erikjalevik** [comment]
You mean if d is a child of b? I could do that, but then unnecessary watches will be hanging around, that the application doesn't need.

So unwatching with a depth of 0 is recursive by design?

**Comment by paulmillr** [comment]
we don't account for depth in unwatching right now
