### ISSUE TITLE
TypeError: fsevents is not a constructor

### ISSUE THREAD

**Issue by DominicTobias** [paulmillr/chokidar#827]
**Describe the bug**
Chokidar fails to run due to calling `new` on fsevents like it's a class or function but it's not.

**Versions (please complete the following information):**
 - Chokidar version: 2.1.5
 - Node version: 12.0.0
 - OS version: MacOS Mojave 10.14.4 (18E226)

**To Reproduce**
Create an app with create-react-app 3.0.0 and run `npm start`

**Error trace**
```
.../node_modules/chokidar/lib/fsevents-handler.js:28
  return (new fsevents(path)).on('fsevent', callback).start();
          ^

TypeError: fsevents is not a constructor
    at createFSEventsInstance (/Users/infensus/Projects/fileflow/app/node_modules/chokidar/lib/fsevents-handler.js:28:11)
    at setFSEventsListener (/Users/infensus/Projects/fileflow/app/node_modules/chokidar/lib/fsevents-handler.js:82:16)
    at FSWatcher.FsEventsHandler._watchWithFsEvents (/Users/infensus/Projects/fileflow/app/node_modules/chokidar/lib/fsevents-handler.js:252:16)
    at FSWatcher.<anonymous> (/Users/infensus/Projects/fileflow/app/node_modules/chokidar/lib/fsevents-handler.js:386:25)
    at LOOP (fs.js:1622:14)
    at processTicksAndRejections (internal/process/task_queues.js:81:9)
```

What I don't get about this is chokidar is doing the following:

```js
// Returns new fsevents instance
function createFSEventsInstance(path, callback) {
  return (new fsevents(path)).on('fsevent', callback).start();
}
```

However `fsevents` is not a class it's a plain object with the following exports :/

```
exports.watch = watch;
exports.getInfo = getInfo;
exports.constants = con;
```

If you look at fsevents docs it matches this: https://www.npmjs.com/package/fsevents#usage

So I'm not sure how this was ever supposed to work, however it was working before I upgraded to create-react-app v3 and NodeJS v12.

Any ideas? Thanks

**Comment by DominicTobias** [comment]
Ah I see that chokidar uses a very old version of fsevents. Seems like the NPM that comes with Node 12 does not install it but installs the latest version at `node_modules/fsevents` instead 🤔

**Comment by paulmillr** [comment]
It's not "very old", it's what everyone uses. fsevents2 is not used in any production yet.

chokidar 2 and fsevents 1 support nodejs up to v12. for nodejs 12, you'll need chokidar 3 (coming soon), or chokidar2 without fsevents

**Comment by DominicTobias** [comment]
Thanks, for now an easier solution to downgrading node/npm was just to use yarn to install

**Comment by yairEO** [comment]
This is a **serious** issue. I do not wish to downgrade my NPM version since I cannot enforce this across the team

**Comment by jedkass** [comment]
This was working for me Friday...logged in today, 3 days later, and am now getting this issue, with with yarn _and_ npm. I'm on nodejs 10 and npm 6.4 (i.e. node LTS). What might have caused this to start happening? I didn't update anything over the weekend

**Comment by unubore88** [comment]
I have the same issue. node_modules/chokidar/lib/fsevents-handler.js:28
  return (new fsevents(path)).on('fsevent', callback).start();

Impossible to run npm start on my react project.

**Comment by chiara-rose-digital** [comment]
Ran into this same issue today.

**Comment by siemiatj** [comment]
Same on node 10.15.3/npm 6.4.1

**Comment by jonathansimmons** [comment]
@paulmillr is there a solution for this. I'm having the same issue on my end. 

Choidar 2.0.4
Node: 12.1.0
OS version: MacOS Mojave 10.14.5 (18F132)

**Comment by ParagKadam101** [comment]
I solved this issue with creating my react app with **npx create-react-app app_name**

**Comment by shenchaoran** [comment]
this works for me
```
rm -rf node_modules
yarn install
```

**Comment by phenric** [comment]
I'm facing the same issue. But nothing works for me.
Does anyone can help me ?

**Comment by cancolpan** [comment]
I had same issue on my MAC. I just installed yarn and solved.

**Comment by kpolgar** [comment]
@ParagKadam101 Wow that worked thanks!

**Comment by Parthan-Sachin** [comment]
> **Describe the bug**
> Chokidar fails to run due to calling `new` on fsevents like it's a class or function but it's not.
> 
> **Versions (please complete the following information):**
> 
> * Chokidar version: 2.1.5
> * Node version: 12.0.0
> * OS version: MacOS Mojave 10.14.4 (18E226)
> 
> **To Reproduce**
> Create an app with create-react-app 3.0.0 and run `npm start`
> 
> **Error trace**
> 
> ```
> .../node_modules/chokidar/lib/fsevents-handler.js:28
>   return (new fsevents(path)).on('fsevent', callback).start();
>           ^
> 
> TypeError: fsevents is not a constructor
>     at createFSEventsInstance (/Users/infensus/Projects/fileflow/app/node_modules/chokidar/lib/fsevents-handler.js:28:11)
>     at setFSEventsListener (/Users/infensus/Projects/fileflow/app/node_modules/chokidar/lib/fsevents-handler.js:82:16)
>     at FSWatcher.FsEventsHandler._watchWithFsEvents (/Users/infensus/Projects/fileflow/app/node_modules/chokidar/lib/fsevents-handler.js:252:16)
>     at FSWatcher.<anonymous> (/Users/infensus/Projects/fileflow/app/node_modules/chokidar/lib/fsevents-handler.js:386:25)
>     at LOOP (fs.js:1622:14)
>     at processTicksAndRejections (internal/process/task_queues.js:81:9)
> ```
> 
> What I don't get about this is chokidar is doing the following:
> 
> ```js
> // Returns new fsevents instance
> function createFSEventsInstance(path, callback) {
>   return (new fsevents(path)).on('fsevent', callback).start();
> }
> ```
> 
> However `fsevents` is not a class it's a plain object with the following exports :/
> 
> ```
> exports.watch = watch;
> exports.getInfo = getInfo;
> exports.constants = con;
> ```
> 
> If you look at fsevents docs it matches this: https://www.npmjs.com/package/fsevents#usage
> 
> So I'm not sure how this was ever supposed to work, however it was working before I upgraded to create-react-app v3 and NodeJS v12.
> 
> Any ideas? Thanks

I also had the same issue though am using MacOS the issue is kind of bug. I solved this issue by repeatedly running the commands,

- sudo npm cache clean --force
- sudo npm uninstall
- sudo npm install

One time it did not worked but when I repeatedly cleaned the cache and after uninstalling npm, reinstalled npm, the error went off. Am using Angular 8 and this issue is common

**Comment by Marco-exports** [comment]
TOTALLY ABSURD...  nothing works, tried everything mentioned here, and since April nothing has been done to fix this.  I can't get my simple React program to work !!!

**Comment by kpolgar** [comment]
@Marco-exports Hi, so sorry that must be so frustrating. Nothing worked for me. I finally uninstalled and reinstalled using: npx create-react-app robofriends. That worked. Hope that is the fix you need.

**Comment by ScriptureCoder** [comment]
Nothing works.

**Comment by SereneMatt** [comment]
`npm install --save --save-exact react-scripts@3.0.1` worked for me

**Comment by roni5** [comment]
create a file called    .env     then add this  ->   SKIP_PREFLIGHT_CHECK=true

**Comment by mnemanja** [comment]
I am using `Material-ui v4.4.0` and my project already uses `react-scripts@3.0.1` and the problem exists.

**Comment by mnemanja** [comment]
> this works for me
> 
> ```
> rm -rf node_modules
> yarn install
> ```

This move is simply reckless at best.

**Comment by logust79** [comment]
For me I had to delete `yarn.lock`, and reinstall node modules

**Comment by nicolasdupouy** [comment]
`npm audit fix --force`

**Comment by stuartmanners** [comment]
If anyone is still experiencing this issue, just read `npm install` again. This worked for me.

**Comment by agathepey** [comment]
If anyone has still the same issue, uninstall yarn and try with npm, worked for me !

**Comment by vineetdigit** [comment]
This may not be an option for everyone, but it has worked for my purpose.

If you ran **npm audit**, it will tell you all the unmet dependencies. Look out out for chokidar v2 and fsevent.

You can fix most of these warnings by running **npm audit fix**.  But whichever are still not fixed, can be fixed manually or by running **npm audit fix --force**

**Comment by heerqa** [comment]
This is totally absurd issue with node. 

/Users/zubair/development/JAMES/reactui/node_modules/webpack-dev-server/node_modules/chokidar/lib/fsevents-handler.js:26
  return (new fsevents(path)).on('fsevent', callback).start();
          ^

TypeError: fsevents is not a constructor
    at createFSEventsInstance (/Users/zubair/development/JAMES/reactui/node_modules/webpack-dev-server/node_modules/chokidar/lib/fsevents-handler.js:26:11)
    at setFSEventsListener (/Users/zubair/development/JAMES/reactui/node_modules/webpack-dev-server/node_modules/chokidar/lib/fsevents-handler.js:80:16)
    at FSWatcher.FsEventsHandler._watchWithFsEvents (/Users/zubair/development/JAMES/reactui/node_modules/webpack-dev-server/node_modules/chokidar/lib/fsevents-handler.js:244:16)
    at FSWatcher.<anonymous> (/Users/zubair/development/JAMES/reactui/node_modules/webpack-dev-server/node_modules/chokidar/lib/fsevents-handler.js:378:25)
    at LOOP (fs.js:1653:14)

**Comment by heerqa** [comment]
> If anyone has still the same issue, uninstall yarn and try with npm, worked for me !

its not working even then

**Comment by heerqa** [comment]
This worked
npm install --save --save-exact react-scripts@3.0.1

**Comment by Excalibur-king** [comment]
I upgraded the dependency fsevents to 1.2.13 and the problem was solved
`yarn add fsevents@1.2.13 `
