### ISSUE TITLE
macOS Crash EXC_BAD_ACCESS when FSEvents Enabled

### ISSUE THREAD

**Issue by semireg** [paulmillr/chokidar#837]
**Describe the bug**
Crashes after multiple calls to watch() and close(). 

```
Crashed Thread:        0  CrRendererMain  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x00000000000003e8
```

```
    __TEXT                 0000000100139000-000000010013a000 [    4K] r-x/rwx SM=COW  /Users/USER/*/Electron.app/Contents/Frameworks/Electron Helper.app/Contents/MacOS/Electron Helper

Thread 0 Crashed:: CrRendererMain  Dispatch queue: com.apple.main-thread
0   com.github.Electron.framework 	0x0000000104ed86b0 0x10013f000 + 81368752
1   fse.node                      	0x000000010af25f57 fse::FSEvents::~FSEvents() + 93 (fsevents.cc:65)
2   fse.node                      	0x000000010af25fea fse::FSEvents::~FSEvents() + 14 (fsevents.cc:62)
3   com.github.Electron.framework 	0x000000010151f481 0x10013f000 + 20841601
4   com.github.Electron.framework 	0x000000010151f83a 0x10013f000 + 20842554
5   com.github.Electron.framework 	0x000000010197fce3 0x10013f000 + 25431267
6   com.github.Electron.framework 	0x000000010197dd81 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) + 1585
7   com.github.Electron.framework 	0x0000000101986ce1 0x10013f000 + 25459937
8   com.github.Electron.framework 	0x0000000101546a7f 0x10013f000 + 21002879
```

**Versions (please complete the following information):**
 - Chokidar version 2.1.5
 - Node version 10.12.18 (Electron 4.1.4
 - OS version: macOS 10.14.4

**To Reproduce**
After multiple calls to watch() and close(), the process will crash. My application is only watching one (1) file at a time.

**Expected behavior**
Should not crash.

**Additional context**
Disabling FSEvents makes everything stable again.

This crash was found in a production app that didn't seem to have any issues with Electron 3.x (node 7.0.68, perhaps).

**Comment by laurent22** [comment]
It seems we have the same problem in Joplin - https://discourse.joplinapp.org/t/returning-from-external-editor-results-in-blank-screen/1982/10?u=laurent

**Comment by semireg** [comment]
Closing this in favor of https://github.com/fsevents/fsevents/issues/273
