### ISSUE TITLE
Watch does not trigger 'add' if folder name starts with an 'İ' character

### ISSUE THREAD

**Issue by oguzhanazari** [paulmillr/chokidar#841]
**Describe the bug**
If watching folder name starts with an 'İ'(Turkish character) character, chokidar add event does not work, but it works another with Turkish characters like Ö,Ş,Ğ,Ü,Ç.

**Versions (please complete the following information):**
 - Chokidar version 3.0.0
 - Node version 10.15.3
 - OS version: Windows 10 x64

**Comment by fabiospampinato** [comment]
I think this is related to #838

**Comment by pipobscure** [comment]
This shoudl be fixed in fsevents@2.0.7

Can you please reinstall and check whether that fixes it. `npm --depth 9999 update`

**Comment by frndmr** [comment]
> The Mac-OSX crash part of this should be fixed in fsevents@2.0.7
> 
> Can you please reinstall and check whether that fixes it. `npm --depth 9999 update`

This is doesn't works for me. I am using windows. There is any solution of windows os?

**Comment by paulmillr** [comment]
That's bug in node.js, not chokidar https://github.com/nodejs/node/issues/27534
