### ISSUE TITLE
Unexpected token ... on v3.0.0

### ISSUE THREAD

**Issue by monchoz** [paulmillr/chokidar#842]
**Describe the bug**
I've just updated to the latest version 3.0.0 as soon as I run `npm start (electron .)` on my Electron app I get this: 

```
...\node_modules\readdirp\index.js:82
    const opts = {...ReaddirpStream.defaultOptions, ...options};
                  ^^^
SyntaxError: Unexpected token ...
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:528:28)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
```

**Versions (please complete the following information):**
 - Chokidar 3.0.0
 - Node 8.11.4
 - OS version: Windows 10
- Electron Builder: 20.28.2
- Electron Rebuild: 1.8.2

**Additional context**
It works fine with the previous version of Chokidar, what would be the ideal Node version to use with chokidar v3?

**Comment by paulmillr** [comment]
Are you sure it's 8.11.4?

**Comment by monchoz** [comment]
Yes

**Comment by paulmillr** [comment]
Try this in your node shell:

`opts = {...{a: 1}, ...{b: 2}}`

**Comment by monchoz** [comment]
returns `{ a: 1, b: 2 }`

**Comment by paulmillr** [comment]
Try `git clone https://github.com/paulmillr/readdirp`, then `cd readdirp`, then `npm install` and do `node index.js` — does it work properly?

**Comment by monchoz** [comment]
It works, well nothing happens after `node index.js`

**Comment by paulmillr** [comment]
As you can see in your main post, there is a syntax error in this code: `const opts = {...ReaddirpStream.defaultOptions, ...options};`

Syntax error happens because node doesn't support object spread (`...{a: 1}`). Node.js versions before 8.5 or so didn't support object spreads. So the very plausible thing here is that the node version is <8.5.

This can happen if electron executes different node.js than the one on your system. 

You're saying it's 8.11.4 and you've shown 8.11.4 works great with the same code.

**Comment by monchoz** [comment]
You are right, It has to be electron then.

**Comment by paulmillr** [comment]
Update your electron-builder and electron-rebuild, that should help

**Comment by monchoz** [comment]
I was able to solve it by upgrading my electron version! Probably my old version was somehow using its own node version, not my system node. Appreciate your time! Thanks!

**Comment by paulmillr** [comment]
Great!
