### ISSUE TITLE
Bigint support

### ISSUE THREAD

**Issue by fabiospampinato** [paulmillr/chokidar#844]
I'm currently using `fs.Stats.ino` numbers to detect renames, but this is especially flawed on Windows (https://github.com/nodejs/node/issues/12115) where multiple files can get assigned the same ino number because they overflow the maximum storable number in JS.

The solution would be to tell `fs.stat` to return `bigint`s instead, which don't have this issue.

I could query `fs.stat` with the `{ bigint: true }` option myself, but I'd rather reuse the stats object provided by chokidar, for performance.

I see no option for enabling `bigint`s in chokidar, can it be added?

**Comment by paulmillr** [comment]
Should be fixed in new chokidar release.

**Comment by fabiospampinato** [comment]
@paulirish has an option been added for this already? And can you say roundabout when the new release will be published?

**Comment by paulmillr** [comment]
It'll use bigints on windows automatically for nodejs 10+. Try it out later this week.

**Comment by fabiospampinato** [comment]
@paulirish I'm not sure this implicit behavior is necessarily what we want, wouldn't it be better to enable bigints on all platforms instead? The fact that currently those regular ino numbers overflow on Windows may change with a macOS update or something, maybe it happens already under macOS as well but it's more rare.

**Comment by paulmillr** [comment]
I think they've added the option because of windows FS. If we'll receive additional bug reports, we'll add it. I think it brings some overhead, but not sure.

BTW readdirp 3.0.3 is out — so do `npm update` and try it; it'll use bigints.
