### ISSUE TITLE
Assertion failed: file ../src/fsevents.c, line 46 for Chokidar 3.0

### ISSUE THREAD

**Issue by unional** [paulmillr/chokidar#848]
**Describe the bug**
When upgrading to Chokidar 3.0. It fails during jest run 

**Versions (please complete the following information):**
 - Chokidar version 3.0.0
 - Node version 10.8.0
 - OS version: OSX Mojave

**To Reproduce**
This PR shows the error
https://github.com/unional/test-progress-tracker/pull/35

All tests are passing before the change, using `chokidar 2.1.5`

The calling code is essentially:
```
const w = chokidar.watch(filepath, { awaitWriteFinish: { pollInterval: 10, stabilityThreshold: 50 })
w.on('add', path => invokeCallback(c, path, callback))
w.on('change', path => invokeCallback(c, path, callback))
return { close: w.close.bind(w) }
```
https://github.com/unional/test-progress-tracker/blob/chokidar/src/monitor.ts#L44-L47

The error is:
```
Assertion failed: (napi_call_function(env, recv, callback, 3, args, &recv) == napi_ok), function fse_dispatch_events, file ../src/fsevents.c, line 46.
```

Thanks. 🌷

**Comment by unional** [comment]
https://github.com/unional/test-progress-tracker/blob/chokidar/src/monitor.spec.ts#L102
https://github.com/unional/test-progress-tracker/blob/chokidar/src/monitor.spec.ts#L122

These are the two tests that failed.

**Comment by paulmillr** [comment]
Update to 3.0.2

**Comment by the-t-in-rtf** [comment]
I see crashes with the same error using 3.0.2 on High Sierra (10.13.5) and node@10.15.2.

**Comment by paulmillr** [comment]
I need a reproducible repo to debug this.

**Comment by the-t-in-rtf** [comment]
@paulmillr, I made the effort to reproduce this outside of our main repo, but wasn't able to.  The problem only occurs on the second of repeated test runs, and only when I clean up each watcher's watched content immediately after closing the watcher.  So now I have two workarounds, disabling FS events, or simply cleaning up and then closing the watcher.

My gut feel is that this is probably a subtle timing issue that may very well be my fault.  If I can narrow it down to the point where I can demonstrate the issue in isolation, I'll file a new detailed ticket.

**Comment by paulmillr** [comment]
@the-t-in-rtf i've spent two days and found the root cause of this. Try 3.2.4 in a few days, or github version right now.

**Comment by the-t-in-rtf** [comment]
Thanks, @paulmillr.  I assume 3.3.0 includes your fix?  I temporarily undid my previous workaround (changing the timing of my calls to `watcher.close()`), and  I don't see errors any more.

**Comment by paulmillr** [comment]
Yes.

**Comment by the-t-in-rtf** [comment]
Perfect, seems like you fixed it then.  Thanks again!
