### ISSUE TITLE
Uncaught error despite error handler and ignorePermissionErrors

### ISSUE THREAD

**Issue by erikjalevik** [paulmillr/chokidar#850]
**Describe the bug**
I am instantiating a watcher with the `ignorePermissionErrors` parameter set to true, and giving it one `on("all")` handler and one `on("error")`. The latter currently just logs the error given to it.

If using this to watch the root directory `/` on MacOS, chokidar seems to choke on the two files `.file` and `.dbfsevents`. The log statement in my error handler prints:

"TypeError: errmap.get is not a function or its return value is not iterable"

But then there's a further uncaught error:

"TypeError: Cannot read property 'close' of undefined"

coming from `setFsWatchListener`.

If specifying `/dev` as the watched directory, things get worse and the app hangs completely but I noticed there's already [a ticket about that](https://github.com/paulmillr/chokidar/issues/455).

**Versions (please complete the following information):**
 - Chokidar version 2.1.5
 - Node version 10.11.0 running in Electron
 - OS version: MacOS 10.14.4

**To Reproduce**
Call `chokidar.watch("/", options)`.

**Expected behavior**
No uncaught errors to be thrown.

I can work around it by adding these two files (and the `/dev` dir) to the ignore list, but wondering if there's not a bug here.

**Comment by paulmillr** [comment]
Update to v3, it should resolve this.
