### ISSUE TITLE
Keep support of branch 2.x or use babel to improve chokidar engine compatibility

### ISSUE THREAD

**Issue by qraynaud** [paulmillr/chokidar#851]
Is it possible to release a 2.1.6 with my fix on branch 2.x? Some of my dependencies still depend on 2.x branch and won't update for the time being (like gulp).

In the same spirit, there is a complex choice to make about chokidar here. Most of the usages of this lib are in big build systems like gulp. But those keep a very serious engine compatibility. Like gulp 4 is still serious about supporting node 0.10 for now. They might drop it for node>=6.x in the next major version but they will keep support for node 6.x at least for a while (see https://github.com/gulpjs/glob-watcher/pull/42).

Thus there is 2 possible paths here that seems right to me, but maybe there are more that I don't see right now:
* backport bugfixes and improvements to the 2.x branch and release it often too
* use babel to compile a version of chokidar that is compatible with old engines and still keep the clean codebase (and use polyfills for new structures like `Map` or `Set` when they are not available in the engine)

What are your thoughts on this matter?

**Comment by paulmillr** [comment]
We should support 2.x and i’ll release 2.1.6. “Using babel” is pretty uncool, it’s not just chokidar — It’s like almost every dependency.

**Comment by qraynaud** [comment]
Yes you are right. The dependency problem is also a big issue there.

**Comment by paulmillr** [comment]
Released, 8f5be3c
