### ISSUE TITLE
unlinkDir does not works for empty folders

### ISSUE THREAD

**Issue by dgknca** [paulmillr/chokidar#852]
If we use unlinkDir and delete a empty folder, returns this error:

> events.js:167
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: EPERM: operation not permitted, watch
>     at FSEvent.FSWatcher._handle.onchange (internal/fs/watchers.js:123:28)
> Emitted 'error' event at:
>     at FSWatcher._handleError (C:\Users\sezginc\Desktop\Odev678\node_modules\chokidar\index.js:260:10)
>     at C:\Users\sezginc\Desktop\Odev678\node_modules\chokidar\lib\nodefs-handler.js:55:5
>     at Array.forEach (<anonymous>)
>     at fsWatchBroadcast (C:\Users\sezginc\Desktop\Odev678\node_modules\chokidar\lib\nodefs-handler.js:54:36)
>     at C:\Users\sezginc\Desktop\Odev678\node_modules\chokidar\lib\nodefs-handler.js:96:23
>     at C:\Users\sezginc\Desktop\Odev678\node_modules\graceful-fs\graceful-fs.js:45:10
>     at FSReqWrap.oncomplete (fs.js:141:20)

If a folder with any file is deleted, does not give an error.

**Comment by paulmillr** [comment]
Try it without `graceful-fs`
