### ISSUE TITLE
npm latest tag went down from 3.0.0 to 2.1.6

### ISSUE THREAD

**Issue by teppeis** [paulmillr/chokidar#854]
**Describe the bug**

Currently, `npm i chokidar` installs chokidar@2.1.6

**Expected behavior**

`npm i chokidar` installs chokidar@3.0.0

**Additional context**

Releasing chokidar@2.1.6, npm latest tag was changed to it.
https://www.npmjs.com/package/chokidar?activeTab=versions

**Comment by paulmillr** [comment]
Fixed.
