### ISSUE TITLE
Linux: Watching large directories is still pegging CPU

### ISSUE THREAD

**Issue by bpasero** [paulmillr/chokidar#860]
**Describe the bug**
I am giving `chokidar@3.0.0` a try to see if watching large directories still keeps the CPU busy or not. My simple test shows no difference to previous versions so I wonder if there is a new option that is needed.

**Versions (please complete the following information):**
 - Chokidar version: `3.0.0`
 - Node version: `10.15.1`
 - OS version: `Linux p520 4.15.0-50-generic #54-Ubuntu SMP Mon May 6 18:46:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
 

**To Reproduce**

```js
const chokidar = require("chokidar");

const watcher = chokidar.watch('/', {
    ignoreInitial: true,
    ignorePermissionErrors: true
});
```

![image](https://user-images.githubusercontent.com/900690/58464683-71dc7080-8136-11e9-8186-144ad1fdb033.png)

**Expected behavior**
By default, I would expect to not see high CPU spikes when watching. I think the default options should optimise for low hits on CPU. 

**Additional context**
High CPU from watching large folders is an issue VSCode users are reporting very often (https://github.com/microsoft/vscode/issues/3998).

**PS**: this is the first time I see how many processes `chokidar` produces when looked at via `htop`, any clues?

**Comment by paulmillr** [comment]
Yeah, the fact it creates many processes is not normal. I haven’t saw this behavior while testing the lib. Can you try watching NOT root directory? There are a few files that may break something. Perhaps watch user directory.

**Comment by bpasero** [comment]
@paulmillr pretty much the same when watching just home:

![image](https://user-images.githubusercontent.com/900690/58481465-b2e77b80-815c-11e9-8dd1-4c1cd2290852.png)

Btw I see those flood of processes even appearing when watching a folder that does not exist...

**Comment by paulmillr** [comment]
that’s not normal at all. I wonder what’s the difference here.

**Comment by bpasero** [comment]
Almost looks like node was using some kind of clustering. I have never seen this before.

**Comment by paulmillr** [comment]
Could you see whether there's any difference after upgrading to node 12.x?

**Comment by paulmillr** [comment]
Also, try chokidar@master — we've changed a few things...

**Comment by bpasero** [comment]
@paulmillr same result with node.js `12.3.1` and `master`: high CPU and multiple node processes.

On macOS I see high CPU but just a single node process.

**Comment by paulmillr** [comment]
Unsure if that's still relevant since you've switched to chok 3.1, perhaps it did get fixed. Try 3.2-master, also.

**Comment by vilic** [comment]
@paulmillr Does this issue affect version `^2`?

**Comment by paulmillr** [comment]
No, you should upgrade
