### ISSUE TITLE
Error Messages on Windows

### ISSUE THREAD

**Issue by manngo** [paulmillr/chokidar#862]
I am using Electron Reload, which, in turn uses Chokadir. Things work well on the Mac, but when I try on Windows, I get a large number of messages of this nature:

	Uncaught Exception:
	Error: EISDIR: illegal operation on a directory, watch

one for every file and folder in my project.

I also get the same error message when I attempt to use Chokadir directly.

Let me mention that I have no idea what I’m talking about here, but I have isolated and patched the code to get it working as follows:

	function createFsWatchInstance(path, options, listener, errHandler, emitRaw) {
		var handleEvent = function(rawEvent, evPath) {
		listener(path);
		emitRaw(rawEvent, evPath, {watchedPath: path});
	/**/	evPath=evPath.toString();
		…
	};

	try {
	/**/	// return fs.watch(path, options, handleEvent);
	/**/	return fs.watchFile(path, options, handleEvent);
	} catch (error) {
		errHandler(error);
	}

The lines marked `/**/` indicate the changes I made to get it working. I got this result through some serious tracing, guess work, and some information from [https://nodejs.org/api/fs.html#fs_fs_watch_filename_options_listener](https://nodejs.org/api/fs.html#fs_fs_watch_filename_options_listener) in the Caveats and Availability section.

As far as I can tell, I am using

- Chokadir 2.1.6
- Node 10.15.3

I am using the latest update to Windows 10 running in a VirtualBox on my MacOS. The project folder is in a folder shared from the Mac, and mapped to a drive letter in Windows

**Comment by paulmillr** [comment]
Upgrade to 3.0.
