### ISSUE TITLE
No file changes shown on arch linux in 3.0.1

### ISSUE THREAD

**Issue by NathanBrooks** [paulmillr/chokidar#865]
**Describe the bug**
After updating to 3.0.1 from 3.0.0, I no longer receive any events on arch linux

**Versions (please complete the following information):**
 - Chokidar version 3.0.1
 - Node version: 8.6.0
 - OS version: Linux NathanVPS 4.13.3-1-ARCH #1 SMP PREEMPT Thu Sep 21 20:33:16 CEST 2017 x86_64 GNU/Linux

**To Reproduce**
Steps to reproduce the behavior.

Ideally prove a problem by isolating and making it reproducible with a very short sample program, which you could paste here:

var watcher = chokidar.watch(['./bot_modules', './api_modules'], {
  ignored: /[\/\\]\./,
  persistent: true,
});

watcher.on('add', (path) => {
  moduleHandles[path] = require('./' + path);
  moduleHandles[path].init(apiHandler, webApp, webServer);
  console.log(path + ' has been added');
});

watcher.on('unlink', (path) => {
  delete require.cache[require.resolve('./' + path)];
  moduleHandles[path].free();
  delete moduleHandles[path];
  console.log(path + ' has been removed');
});

Most valuable could be one or more test cases for [test.js](https://github.com/paulmillr/chokidar/blob/master/test.js) to demonstrate the problem.

**Expected behavior**
On previous version, I would get an add event for all files in the folders that I am watching. This allowed me to dynamically load and unload modules that I was using in my bot.

Now I don't seem to be receiving any events at all. But 3.0.0 does work.

**Additional context**
This is for a chat bot that dynamically loads modules for both the APIs it is working on and the features of the bot.

**Comment by CageFox** [comment]
3.0.2 broken also

**Comment by paulmillr** [comment]
@CageFox OS?

**Comment by JSMonk** [comment]
Can't reproduce this bug.
Maybe, you make/unlink dir, so you need to subscribe on "addDir" and "unlinkDir".

**Comment by stingray21** [comment]
Maybe this is connected
https://stackoverflow.com/questions/57231200/how-to-sync-a-local-folder-with-gulp-with-update-for-deleted-files-and-folders

**Comment by CageFox** [comment]
> 
> 
> @CageFox OS?

3.0.1 not monotoring file changes on windows 8.1 64 bit and on debian9

3.0.2 i checked on windows 8.1

3.0.0 works excellent on both

**Comment by paulmillr** [comment]
Works for me now
