### ISSUE TITLE
Raw event fired for not watched files on macOS

### ISSUE THREAD

**Issue by fredZgred** [paulmillr/chokidar#866]
**Describe the bug**
When using `raw` event the callback gets called also for changes to files that are in the same directory (or nested) as file(s) specified to watch on.

**Versions (please complete the following information):**
 - Chokidar version 3.0.1
 - Node version 12.6.0
 - OS version: macOS 15.14.5

**To Reproduce**
Run the following script and make a change to any file in the directory of watched file, or nested.
```
const chokidar = require('chokidar');
chokidar.watch(__filename).on('raw', (_, name) => console.log(name));
```

**Expected behaviour**
Provided callback gets called only for changes to the file under __filename path.

**Additional context**
I played with above script on two machines with same node and chokidar versions, but different systems: macos and debian 9. Described issue does not exist on the debian machine.
I also run chokidar tests on both machines several times, but results were not deterministic regarding the amount of failing test cases (first run: two different failed on both machines, next few runs: one different for both machines) and even after few runs tests started to pass.

I am not sure whether it has anything in common to the issue, but I also modified above script to use `all` instead of `raw` and surprisingly for macos callback was getting executed correctly, so only on changes to the watched file, however this time for debian there were only 2 calls of the callback and no more despite the many changes to the file.

**Comment by paulmillr** [comment]
That's `raw` though. What about `change`, `add` etc? Why are you listening to `raw`? it's internal

**Comment by fredZgred** [comment]
Looks like for other events it works correctly. I didn't see anywhere the information it's internal. Not necessarily I have to use `raw` specifically, `all` will work for me, but I used it and just noticed that behaviour.

**Comment by paulmillr** [comment]
We should correct docs then

**Comment by fredZgred** [comment]
Assuming that the behaviour is not related to my machine (I didn't have opportunity to check it on different machine) but it is rather related to the os, it is problematic because users don't know that their program will work differently in different environments. IMHO it would be perfectly to make `raw` os agnostic. If not maybe additional information that the way `raw` works may be environment dependent, would be sufficient.

**Comment by paulmillr** [comment]
all is os-agnostic. You should use it. Raw can either push native events from fsevents, or any other backend. I don’t see any point in making it os-agnostic.

**Comment by fredZgred** [comment]
OK, understand your point 👍
