### ISSUE TITLE
Feature Request: expose micromatch's dot-File option

### ISSUE THREAD

**Issue by rasenplanscher** [paulmillr/chokidar#870]
As noted in #577, chokidar does not currently expose an option to watch files/directories starting with dots. Since I need the watch behaviour, simply using `micromatch` directly is not a good option.

Would be nice to have this option exposed.

**Comment by paulmillr** [comment]
Yeah, it's a surprise to me this is the default behavior. We should probably hardcode it. See https://github.com/micromatch/picomatch/issues/25

**Comment by orty** [comment]
Hi,

This is also a feature I would like to see released. I am building a generic backup tool which listens to changes in a text file containing any kind of paths (to files or to dirs/**/*) and back them up in a centralized archive when they change. 

So far, I was not able to successfully watch changes recursively in paths which could contain dotted folders. 

Thx

**Comment by paulmillr** [comment]
We will release 3.1 with the option enabled soon.

**Comment by orty** [comment]
Hi,

Seems to be working way better now ! Thank you :)
