### ISSUE TITLE
Resource starved CPU prevents ready from happening

### ISSUE THREAD

**Issue by catdad** [paulmillr/chokidar#873]
**Describe the bug**
When starting to watch a directory, if there is another task happening concurrently on the OS, the `ready` event does not fire on MacOS. When the `ready` event doesn't fire, even though `add` events have fired for files, those files do not trigger `change` events when they are changed. I have reproduced this on Sierra as well as in testing in Travis CI.

**Versions (please complete the following information):**
 - Chokidar version 3.0.2
 - Node version 10.15.3 (tested in 12, 10, and 8 in Travis CI)
 - OS version: MacOS Sierra

**To Reproduce**
I created a gist with some minimal code: https://gist.github.com/catdad/d7f0bff7b47d0796f994174aa078719c

```bash
git clone https://gist.github.com/d7f0bff7b47d0796f994174aa078719c.git
cd d7f0bff7b47d0796f994174aa078719c
npm install

# run watcher alone
node debug.js
# see that files are added and ready is logged

# run watcher through spawn task with other tasks
node spawn.js
# see that files are added but ready is not logged
```

In the `spawn.js` file, if you comment out the second spawn, you can see that even when it is spawned in a child process without other tasks, `ready` is fired as expected.
Steps to reproduce the behavior.

**Expected behavior**
The `ready` event should always fire consistently.

**Comment by paulmillr** [comment]
Works for me, try node v12.10, chokidar-latest. I've tried this script and in both commented / uncommented mode everything was fine:

```
const { spawn } = require('child_process');

spawn('node', ['debug.js'], { stdio: 'inherit' });
//spawn('node', ['node_modules/.bin/electron', '--version'], { stdio: 'inherit' });

```

**Comment by catdad** [comment]
I just tried the latest chokidar, v3.2.1, using both node 10.15.3 and 12.11.1, and I still get failures on both. Every once in a while, it does fire the `ready` event, but it is pretty rare. I updated the project I mentioned originally to this version as well, and my CI builds are still failing with this issue on MacOS.

Also, I am sure you didn't mean it that way, but it's worth mentioning: chokidar supports node 8+, so there is an expectation that it works in more than just node 12.

**Comment by paulmillr** [comment]
yeah — it still works all the time for me. something is different on your system.

**Comment by catdad** [comment]
What was specifically changed to address this issue between 3.0.2 and 3.2.1? It might help me get a head start on debugging.

**Comment by paulmillr** [comment]
https://github.com/paulmillr/chokidar/compare/3.0.2..3.2.1

It was not specific to the issue. I’ve ensured race conditions don’t happen as often in the async system. This by itself eliminates tons of issues.

Travis build would be useful, yes

**Comment by catdad** [comment]
It looks like the issue might be worse than I originally reported.

I created https://github.com/catdad-experiments/chokidar-macos-ready-bug-repro to add a travis build, which you can see here as well: https://travis-ci.com/catdad-experiments/chokidar-macos-ready-bug-repro

I noticed that in the cases where `ready` never fires, no further code executes either. I added a `setTimeout` for 10 seconds so that the process exits after what is definitely too much time, except the process didn't exit. So I added a `setInterval` to log time every 100ms, and that doesn't get logged either. Removing the use of `chokidar` from that file does in fact log the time correctly for 10 seconds and then exists. This suggests to me that `chokdiar` actually ends up blocking the event loop in addition to just never initializing correctly.

I am investigating further right now, but I have given you access to the repo. Please feel free to do any testing there if you'd like.

**Comment by paulmillr** [comment]
You're calling `npx`. I don't have it installed, neither does travis.

**Comment by catdad** [comment]
That doesn't seem to be the problem, at least not for travis. The electron version is printed correctly in all cases (which is the command that uses `npx`), and the command that launches the child process that uses chokidar does not use it. Also, you can see that in the Linux build, it always works correctly, and in the MacOS builds, it sometimes passes and prints all data as expected. This is why I execute the command 5 times, to get at least one failure each time.

**Comment by paulmillr** [comment]
Found it.

Nonetheless, i've tried to run the command 5 times x3. So, 15 times in total. Every time, chokidar printed `ready`:

```
$ cat a.sh 
node parent.js
node parent.js
node parent.js
node parent.js
node parent.js
```

**Comment by paulmillr** [comment]
Just added GitHub CI to your repo instead of Travis — it can't run Electron, but apparently everything passes, just like on my machine:

https://github.com/catdad-experiments/chokidar-macos-ready-bug-repro/commit/a76e143870e34821ff4a3e43550025ee8a4f82f3/checks?check_suite_id=248902530

Can this be an issue with Electron?

**Comment by catdad** [comment]
Electron shouldn't be causing a problem directory, as it runs in an entirely separate process from chokidar. It should simply be a miscellaneous program that is also putting load on the machine. But just in case, I wrote a small node script that calculates a really large prime (you know, the way we've all learned not to do) and am executing that in a separate process. It seems to not happen as often with this script, but I did get at least one failure still in Travis with this script: https://travis-ci.com/catdad-experiments/chokidar-macos-ready-bug-repro/jobs/241314683

**Comment by catdad** [comment]
Okay, I have a theory. I know from previous projects that Travis has 2 cores on their MacOS agents (and my local machine has 2 cores as well), while GitHub Actions has 4 cores. So for one test, I decided to run 3 processes that calculate a prime along with 1 process running chokidar. In GitHub Actions, that passed most of the time, but one of the builds hung. I cancelled it after 15 minutes because I am impatient, but after cancelling it, I can now see the full logs, and I see that it in fact hung the same way that Travis and my local machine hang: https://github.com/catdad-experiments/chokidar-macos-ready-bug-repro/runs/245670553

It seems that you need to starve the machine enough, and then this issue happens. Things like running a couple of VMs, a webpack build, watching Netflix while working, etc. Peg the CPU enough, and chokidar will lock up the event loop in its process. I checked on my laptop, and when this happens, I can see that there is 0% CPU usage coming from the node process running chokidar, so it's not just doing work. The only other time I've seen this is when a native module pauses the event loop (shared memory reasons, etc.) and fails to release it.

**Comment by paulmillr** [comment]
That’s what I call a great find!

**Comment by nono** [comment]
@catdad maybe you can try with the latest release of fsvents. It includes this PR: https://github.com/fsevents/fsevents/pull/290, and the description makes me think that it can fix your issue.

**Comment by catdad** [comment]
@nono yup, that seems to have fixed it. I updated to `fsevents@2.1.1` in the package-lock file, and I can no longer reproduce it locally or in travis. I reran everything with 2.1.0 as well, just to make sure there weren't any hidden OS/CI updates I didn't know about, that version still fails consistently. I read through the issue and it makes sense why it fixed it.

**Comment by catdad** [comment]
I added a quick MR to make `fsevents@2.1.1` the new minimum version.
