### ISSUE TITLE
Windows 7, Chokidar exits with error when remove a directory

### ISSUE THREAD

**Issue by jeromedecoster** [paulmillr/chokidar#88]
Hi,

On Windows 7, lastest nodejs, latest chokidar

I have this simple test file:

``` javascript
var chokidar = require('chokidar');

var watcher = chokidar.watch('./client', {persistent: true});

watcher
  .on('add', function(path) {console.log('File', path, 'has been added');})
  .on('addDir', function(path) {console.log('Directory', path, 'has been added');})
  .on('change', function(path) {console.log('File', path, 'has been changed');})
  .on('unlink', function(path) {console.log('File', path, 'has been removed');})
  .on('unlinkDir', function(path) {console.log('Directory', path, 'has been removed');})
  .on('error', function(error) {console.error('Error happened', error);})
```

When I run the script I have:

```
Directory ./client has been added
```

If I add a directory `mkdir a`, I have:

```
Directory ./client has been added
Directory client\a has been added
```

But if I remove the dir `rm -rf ./a` I have this error and the script exits

``` javascript
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: watch EPERM
    at errnoException (fs.js:1019:11)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1037:26)
```

**Comment by kafoso** [comment]
Necro, but still relevant.

This error may be caused by deleting a file from within an application being run as a different user on the system. E.g. running a text editor as Administrator (Windows) and deleting the file from within this editor will trigger the error.

**Comment by Myasir92** [comment]
chokidar file remove and unwatch is not working if i add a function to watch but after this i try to remove it or unwatch it but it didnt remove it not unwatch it can you please help
