### ISSUE TITLE
javascript heap out of memory in lagre folder

### ISSUE THREAD

**Issue by phamhoaithuong** [paulmillr/chokidar#880]
**Describe the bug**
Hi, i have problem when watch event "add" in lagre folder (>1TB), it throw out heap memory, how to resoleve that. 
When i watch root folder, how many event listener in app? 1 or more event?
My english not good, i hope every one can understand.
Thanks you very much.

**Versions (please complete the following information):**
 - Chokidar version 3.0.2
 - Node version v10.16.2
 - OS version: 18.04

**To Reproduce**
```
const watcher = chokidar.watch(directory, {
        ignoreInitial: true,
        persistent: true,
        depth: 4,
        awaitWriteFinish: {
            stabilityThreshold: 2000,
            pollInterval: 100,
        },
    });
    watcher.on('add', async (_path, stats) => {
        if (stats) {
            if (path.extname(_path) === sourceFile) {
                const _outPutPath = buildOutPutPath(_path);
                if (!fs.existsSync(_outPutPath)) {
                    // request api
                    const data: JobDataModel = {
                        inputPath: _path,
                        outputPath: _outPutPath,
                    };

                    axios.default.post(requestURL, data).then((res) => {
                        //  console.debug(res);
                        //  console.debug("reuqest done");
                    });
                }
            }
        }
    });

**Comment by paulmillr** [comment]
I don’t think this has anything to do with chokidar. Make sure you have optimized your code, e.g not using Sync fs methods.

**Comment by vilic** [comment]
@paulmillr Could you please explain why using synchronous fs methods might cause this issue? We are hitting the same problem recently in Linux containers (not getting this on Windows or macOS).

**Comment by paulmillr** [comment]
1. Ensure you are using chokidar 3.2.1.
2. Ensure you are using nodejs 8.16, preferably 10.x or 12.x.
3. Synchronous fs events block event loop. Nodejs was blocked with the sole purpose of having simple non-blocking io in place. Blocking a thread, while not directly contributing to mem usage, may create all sorts of unintended behaviors. I suggest to wrap async methods with require(“util”).promisify and doing promisify(fs.readFile), then you’ll be able to do await, or then.

**Comment by vilic** [comment]
@paulmillr Thanks for those tips, just upgraded `^3` to `3.2.1` (but there are still some indirect dependencies of `^2`), will see if it helps. We only use synchronous fs methods in very limited scenarios (simple scripts, initialization etc), just want to ensure there is not direct impact.
