### ISSUE TITLE
Buggy under iCloud Drive

### ISSUE THREAD

**Issue by mohd-akram** [paulmillr/chokidar#881]
**Describe the bug**
Incorrect events being reported when a watched directory is in iCloud Drive.

**Versions:**
 - Chokidar version 3.0.2
 - Node version 12.8.1
 - OS version: macOS 10.14.6

**To Reproduce**
1. Create a directory under iCloud Drive (`mkdir ~/Desktop/folder && cd ~/Desktop/folder`)
2. Create `watcher.js` with the following contents:
```javascript
const chokidar = require('chokidar');
const watcher = chokidar.watch(process.cwd());
watcher.on('ready', function () {
  watcher.on('all', function (event, path) {
    console.error('event', event, 'at', path);
  });
});
```
3. Run `node watcher.js`
4. Modify a file (`touch file`)
5. Observe the output

**Expected behavior**
Output:
```
event add at /Users/user/Desktop/folder/file
```

**Actual behavior**
Output:
```
event add at /Users/user/Desktop/folder/file
event addDir at /Users/user/Desktop/folder
event change at /Users/user/Desktop/folder/file
event addDir at /Users/user/Desktop/folder
event addDir at /Users/user/Desktop/folder
event addDir at /Users/user/Desktop/folder
```

**Comment by paulmillr** [comment]
You should be able to work around that with useFsEvents: false for now.

**Comment by mohd-akram** [comment]
I've been using a modified version of Chokidar which ignores `unknown` events (by removing the `info.event === 'unknown'` check) and it's working well. The tests also pass without this bit. I've traced its addition to commit bb2a77257da129beb105d88a1d9a8632c4ee0fa4 in response to issue #165. The scenario described there seems to work without this check.

**Comment by paulmillr** [comment]
@mohd-akram please try my new branch of fsevents with chokidar's current `unknown` check in place. Cloning would now emit clone event, which is not unknown.

**Comment by mohd-akram** [comment]
The issue remains. I don't believe all those extraneous events have a cloned flag, not sure what's their use.

**Comment by paulmillr** [comment]
Actually it resolves the issue for me. I don't see any additional events. Are you sure you've compiled `fsevents` properly?

**Comment by mohd-akram** [comment]
Yeah, I've placed a bunch of print statements just to make sure. I can see it isn't sending `unknown` events any more, but they're still passing through chokidar as `modified`.

Before:

```
FSEVENT unknown
event addDir at /Users/user/Desktop/folder
FSEVENT deleted
event add at /Users/user/Desktop/folder/file
FSEVENT unknown
event change at /Users/user/Desktop/folder/file
FSEVENT unknown
event addDir at /Users/user/Desktop/folder
```

After:

```
FSEVENT created
event add at /Users/user/Desktop/folder/file
FSEVENT modified
event addDir at /Users/user/Desktop/folder
FSEVENT modified
event change at /Users/user/Desktop/folder/file
FSEVENT modified
event addDir at /Users/user/Desktop/folder
FSEVENT modified
event addDir at /Users/user/Desktop/folder
```

**Comment by BeckettOBrien** [comment]
Hello, I am having issues with this too, and I am wondering if there is a way to detect if a folder is inside iCloud drive, and if so, then set useFsEvents to false.

**Comment by paulmillr** [comment]
Let me know how it feels on 3.3.
