### ISSUE TITLE
Linux: initial startup performance has regressed between 2.x and 3.x

### ISSUE THREAD

**Issue by bpasero** [paulmillr/chokidar#882]
**Describe the bug**
I am testing Chokidar 3.x vs 2.x on a very large folder (all my development [code](https://github.com/microsoft/vscode.git) and NPM dependencies installed) and measure memory and CPU impact on startup until the "ready" event is emitted. It takes almost double the time for me (Ubuntu 18 inside a Parallels VM) compared to 2.x

**Versions (please complete the following information):**
 - Chokidar version latest 3.x and 2.x
 - Node version: `12.9.1`
 - OS version: `Ubuntu 18`

**To Reproduce**
Run below code and have HTOP up to monitor CPU and Memory impact. Also measure how long it takes until you get the ready event.

```js
const chokidar = require("chokidar");
const options = {
    ignoreInitial: true
}

const watcher = chokidar.watch('/home/ticino/development/vscode', options);

watcher.on("ready", () => {
    console.log("ready");
});
```

**Expected behavior**
Given all the changes that went into 3.x I would have expected a perf increase actually (which I do see on macOS). 

**Additional Context**
On Linux, in order to watch so many files and folders, you have to configure `/etc/sysctl.conf` with `fs.inotify.max_user_watches=524288` and restart the OS.

**Comment by bpasero** [comment]
I measure `16s` for `2.x` vs `32s` for `3.x`. And here is htop output

**2.x**
![image](https://user-images.githubusercontent.com/900690/64032143-2200b180-cb4a-11e9-8514-9de620a2cad2.png)

**3.x**
![image](https://user-images.githubusercontent.com/900690/64032261-5b392180-cb4a-11e9-8586-e5c30bf00a9e.png)

**Comment by paulmillr** [comment]
I will investigate this.

**Comment by bpasero** [comment]
**CPU Traces (Linux Ubuntu 18):**
* Chokidar 3.x: [chokidar2-CPU-20190904T164602.zip](https://github.com/paulmillr/chokidar/files/3575060/chokidar2-CPU-20190904T164602.zip)
* Chokidar 2.x: 
[chokidar3-CPU-20190904T164602.zip](https://github.com/paulmillr/chokidar/files/3575061/chokidar3-CPU-20190904T164602.zip)

**Comment by bpasero** [comment]
@paulmillr it looks like the regression is with this call to `fs.realpath` that now runs for each and every file found by `readdir` module:

https://github.com/paulmillr/chokidar/blob/99c2f6099b512b447aa59d3fabc7fbceeb1151cc/lib/nodefs-handler.js#L536

In 2.x you would only call this method if the file is actually a symbolic link:

https://github.com/paulmillr/chokidar/blob/e3e5ed0c78148e5bc9ac680604391accbec17ae1/lib/nodefs-handler.js#L490

`realpath` is probably very expensive and should only be called if the target is a known link. Removing this line brings the time back down to how it was before.

I thought I could simply write this to fix it:

```js
const targetPath = path.includes("*") || path.includes("{") || !stats.isSymbolicLink() ? path : await realpath(path);
```

However it is not as simple as this, a lot of tests around symbolic links seem to fail then.

This line fixes it:

```js
const targetPath = path.includes("*") || path.includes("{") || !(await promisify(fs.lstat)(wh.watchPath)).isSymbolicLink() ? path : await realpath(path);
```

Though obviously comes with a price tag...

**Comment by paulmillr** [comment]
Great catch! Try `master` now.

**Comment by paulmillr** [comment]
I've just tried all three versions (v2, v3, master) with `vscode` repository on the cheapest single-core 5$/mo instance of Ubuntu 18. They all were done in 2.5-3s. Not sure where the `16s` and `32s` come from...

**Comment by bpasero** [comment]
@paulmillr my test setup is:
* macOS 10.14 but testing in Ubuntu 18 of a Linux VM in Parallels
* fully checked out https://github.com/microsoft/vscode.git with `yarn` running to get all node modules

I tested your latest changes and they improve the performance when configuring `followSymlinks: false`, however VSCode is configuring `followSymlinks: true` and with 2.x we are still getting a good number which is much better compared to 3.x.

I still do not understand why we cannot rely on the stat information before doing the `realpath`. There should be no reason to use this expensive method if the stat is not a link itself.

**Comment by paulmillr** [comment]
We totally can — the symlink tests are crashing. Need to investigate why.

**Comment by paulmillr** [comment]
BTW, it would be great if we can simplify `chokidarWatcherService.ts` by a good amount.

**Comment by bpasero** [comment]
> We totally can — the symlink tests are crashing. Need to investigate why.

👍 

> BTW, it would be great if we can simplify chokidarWatcherService.ts by a good amount.

Anything in particular?

**Comment by paulmillr** [comment]
Why are you initializing many chokidar instances instead of using just one?

**Comment by bpasero** [comment]
@paulmillr that code is actually not being used in production and only there for historic reasons. We still use a different file watcher when VSCode is configured to have multiple roots ([NSFW](https://github.com/Axosoft/nsfw)) and we had explored to use Chokidar in that case too. I think that code was from that exploration.

**Comment by paulmillr** [comment]
OK, i've managed to get similar results: **7.10 seconds** on v3 vs **4.06 seconds** on v2; although it's still not close at all to 15-30 seconds from the setup of yours. Unsure why there would be 3x difference, i'm using Parallels 15 w Ubuntu 19 & MBP with NVMe ssd. Will debug this.

**Comment by paulmillr** [comment]
Check `master` now! c660f9d should do the trick.

**Comment by bpasero** [comment]
@paulmillr confirmed, back to good numbers! If you could cut a release from this version, I think we can jump to Chokidar@3 in VSCode.

**Comment by bpasero** [comment]
Maybe there is another set of optimizations possible: checking the memory profile, it seems to me that `setFsWatchListener` is called for each file that is traversed. This means:
* 3 Sets are being created per file
* 1 EventEmitter is being created per file

Is that really needed? Can the watcher not be managed on a per-folder basis?
