### ISSUE TITLE
Editing already existing file only emits `change` once.

### ISSUE THREAD

**Issue by sliem** [paulmillr/chokidar#884]
**Describe the bug**
Chokidar only emit one `change` if the file existed before started watching it when editing it with text editor (tested with vi and nano).

The option `usePolling: true` works.

**Versions (please complete the following information):**
 - Chokidar version: 3.0.2
 - Node version: 10.16.2
 - OS version: Ubuntu 16.04

**To Reproduce**
 1. Run the short program below. 
 2. Create and edit the watched file `test.txt`, and it should spit out appropriate `add` and `change`.
 3. Restart the test program.
 4. Edit the already existing file `text.txt` twice. Only see one `change` event.

```
var chokidar, opts, watch;

chokidar = require("chokidar");

opts = {
//usePolling: true,
  awaitWriteFinish: true
}

watch = chokidar.watch("test.txt", opts);

watch.on("add", function() { return console.log("add"); });
watch.on("change", function() { return console.log("change"); });
watch.on("raw", function() { return console.log("raw");});
```

**Expected behavior**
See a `change` event for each edit of the file. Not only the first.

**Additional context**

Using the polling strategy works, i.e. `usePolling: true`

Curiously it does work as expected when just `echo`ing text to the file. E.g.

```
# echo "test" >> test.txt
# echo "test" >> test.txt
# echo "test" >> test.txt
```

will emit three `change` even if the file already exists.

**Comment by coder456** [comment]
I am also seeing this, only 1 (the first one) change event gets emitted on multiple file changes, polling fixes it, seems like change event is broken

**Comment by paulmillr** [comment]
Works properly for me. I've created test.txt, started watching it with `usePolling: false`, and did three `echo "test" >> test.txt`.

Try using GH version: `npm install github:paulmillr/chokidar`

**Comment by beorn** [comment]
Might be caused by throttling eating subsequent events? See #1084
