### ISSUE TITLE
Linux: file watching consumes a lot of memory for large folders

### ISSUE THREAD

**Issue by bpasero** [paulmillr/chokidar#885]
Extracted from: https://github.com/paulmillr/chokidar/issues/882

Maybe there is another set of optimisations possible: checking the memory profile, it seems to me that `setFsWatchListener` is called for each file that is traversed. This means:
* 3 `Sets` are being created per file
* 1 `EventEmitter` is being created per file

Is that really needed? Can the watcher not be managed on a per-folder basis?

![image](https://user-images.githubusercontent.com/900690/64979816-cb6cd480-d8b8-11e9-98bb-2be7436256e2.png)

Memory profile: 
[Heap-20190916T193304.heapprofile.zip](https://github.com/paulmillr/chokidar/files/3617454/Heap-20190916T193304.heapprofile.zip)

**Comment by paulmillr** [comment]
How does it compare to v2?

**Comment by paulmillr** [comment]
How does it compare to v2?

**Comment by paulmillr** [comment]
Fuck GitHub UX

**Comment by paulmillr** [comment]
I've just tested v2 and v3.1-pre, 12.3% mem vs 14%; so doesn't seem too much. We can investigate for the next release, i'll cut 3.1 meanwhile

**Comment by bpasero** [comment]
Yeah, I was not suggesting that there is any regression from 2.x to 3.x, sorry for not making that clear. I was just checking in general if there is something low hanging to remove memory consumption when scanning large folders.

Btw I think memory actually reduced compared to 2.x, at least when I tested last time 👍

**Comment by paulmillr** [comment]
@bpasero could you check `github:paulmillr/chokidar#ram2` RAM usage? I've made a few optimizations. Curious exactly by how much it optimizes your case.

**Comment by bpasero** [comment]
@paulmillr quite an improvement on my Linux:

**Before**
![image](https://user-images.githubusercontent.com/900690/65485355-ebe0f400-dea1-11e9-9f05-1ab40ca939ab.png)

**After**
![image](https://user-images.githubusercontent.com/900690/65485300-cd7af880-dea1-11e9-8b7f-d3576b7c9936.png)

**Comment by paulmillr** [comment]
👏

**Comment by bpasero** [comment]
@paulmillr currently not at home, I will give you a detailed step by step instruction for how to set this up locally once I am back. I think that makes most sense.

**Comment by bpasero** [comment]
@paulmillr Assuming you have a folder where `chokidar` is checked out within into a folder called `chokidar`. 

**`index.js`**

```js
function chokidar() {
    const chokidar = require("./chokidar");
    const options = {
        ignoreInitial: true,
        followSymlinks: true
    }

    const watcher = chokidar.watch('<LARGE FOLDER>', options);

    const now = Date.now();
    watcher.on("ready", () => {
        console.log(Date.now() - now);
        console.log("ready");
    });
}

debugger;
chokidar();
```

From the command line:
* `node --inspect-brk index.js`
* open browser and type `chrome://inspect`
* select the node executable from the list
![image](https://user-images.githubusercontent.com/900690/65522256-caf0c100-deea-11e9-9509-cac3d6ea6174.png)
* click on "Memory" tab
* pick Allocation Sampling
* wait for ready in console
* stop

Attached my profile:
[Heap-20190924T164639.heapprofile.txt.zip](https://github.com/paulmillr/chokidar/files/3647790/Heap-20190924T164639.heapprofile.txt.zip)

**Comment by bpasero** [comment]
@paulmillr one thing to maybe look into is the new `withFileTypes` option of `fs.readdir` (https://nodejs.org/api/fs.html#fs_fs_readdir_path_options_callback) which would save you one `fs.stat` call per entry in `_addToNodeFs`. I think that is still something that makes the initial scan slower than needed. 

Unfortunately this method was only added in node.js 10.x.

**Comment by paulmillr** [comment]
Yep, I’ve had a dirent chokidar branch for a while. Still need to debug some edge cases. 


Node 8 would become unsupported in 4 months, so that’s not really an issue.

**Comment by bpasero** [comment]
Awesome 👍
