### ISSUE TITLE
Getting `EMFILE` errors on macOS with v3.x.x

### ISSUE THREAD

**Issue by taratatach** [paulmillr/chokidar#887]
**Describe the bug**
When watching recursively a folder containing a lot of folders, we'll reach the system's limits and start getting `EMFILE` errors on some paths.
This seems to be happening only with a large number of folders, not files.
Also, I don't see the issue with Chokidar v2.1.8.

I've tried increasing the `ulimit` value of my computer from 256 to 10480 without improvements.

FYI:
```bash
$ ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
file size               (blocks, -f) unlimited
max locked memory       (kbytes, -l) unlimited
max memory size         (kbytes, -m) unlimited
open files                      (-n) 10480
pipe size            (512 bytes, -p) 1
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 1418
virtual memory          (kbytes, -v) unlimited
```

**Versions (please complete the following information):**
 - Chokidar version 3.1.0
 - Node version 8.12.0
 - OS version: macOS 10.14.6

**To Reproduce**
I've found that in my case, the smallest number of directories required to see the errors pop out is 4096.

```bash
$ mkdir dirs
$ for i in `seq 1 4096`; do mkdir "dirs/dir-$i"; done
```

```javascript
const chokidar = require('chokidar')

const watcher = chokidar.watch('./dirs', {
  cwd: '.',
  followSymlinks: false,
  alwaysStat: true,
  usePolling: false,
  useFsEvents: true,
  atomic: true,
  awaitWriteFinish: {
    pollInterval: 200,
    stabilityThreshold: 1000
  },
  interval: 1000,
  binaryInterval: 2000
})

watcher
  .on('all', console.log)
  .on('error', console.error)
```

**Expected behavior**
We should see every event and path printed out without any errors.

**Additional context**
We're using Chokidar as watcher in https://github.com/cozy-labs/cozy-desktop for macOS. We don't have any way to control the `ulimit` value on our users' computers and don't want to add arbitrary folders limits.

**Comment by paulmillr** [comment]
Node 8.12 is not supported by fsevents. Only 8.16 and higher.

**Comment by taratatach** [comment]
I tried to reproduce on Node 12.4.0 and I couldn't see the error. Thank you for the pointer and sorry for the noise.

I don't see any mention of this limitation in chokidar's repo nor in fsevents' repo. Did I miss some wiki page?

**Comment by paulmillr** [comment]
Added it to changelog in README, and added it to fsevents - should be easier.
