### ISSUE TITLE
chokidar 3.x (3.0.0 .. 3.1.1) hang/lockup on close/shutdown

### ISSUE THREAD

**Issue by GerHobbelt** [paulmillr/chokidar#890]
When invoking the `close` API as part of application shutdown, chokidar locks up instead of correctly terminating.

> Probably related to #855 and #859, but that's my uneducated guess.

Attempted various code changes, nothing works. 

Same application code base does terminate as expected when rolling back to chokidar 2.1.6 or other chokidar 2.x versions.

**Versions (please complete the following information):**

 - Chokidar version 3.0.0 - 3.1.1 -- all have been tested including 3.1.1, all FAIL
 - Node version 8.11.1
 - OS version: Windows 10/64

## To Reproduce

- git clone the project https://github.com/GerHobbelt/live-server
- (also see the revision tree or visually: https://github.com/GerHobbelt/live-server/network)

### FAIL:

- check out the commit https://github.com/GerHobbelt/live-server/commit/1fb1dfe73f61c298b8dbb26f4c81b174171d3fec
   + `npm i`
   + ` ./live-server.js --no-browser --test --port=16124` will hang; you'll have to kill the Node executable using task manager 👎 💣 
   + *or* run `npm test` to see the CLI unit tests after `--quiet` all fail 👎 💣 

(the next newer commit in there shows the same problem still persisting with latest 3.1.1 chokidar: https://github.com/GerHobbelt/live-server/commit/1c50d37babe1e051ab6ec656552b1cd70ad57e3b)

### PASS:

- check out the next newer commit https://github.com/GerHobbelt/live-server/commit/708cdd8e473ec1b37be6c26f5e4458beac3b7ef8 which rolls chokidar back to 2.1.6
   + `rm -rf node_modules`
   + `rm package-lock.json`
   + `npm i`
   + ` ./live-server.js --no-browser --test --port=16124` will terminate AS EXPECTED 👍 
   + *or* run `npm test` to see the CLI unit tests after `--quiet` all PASS 👍  

**Expected behavior**

chokidar 3.x should terminate like 2.1.6 and older versions or the error in my ways should be exhibited otherwise.

Thank you! 👍

**Comment by paulmillr** [comment]
Node 8.11 is unsupported. Try 8.16 and higher.
