### ISSUE TITLE
Error: UNKNOWN: unknown error, lstat '\\nasserver\BİRİM\ExampleFile.docx

### ISSUE THREAD

**Issue by hakirac** [paulmillr/chokidar#891]
[30/09/2019 15:59:18.345] [ERROR]  Error: UNKNOWN: unknown error, lstat '\\nasserver\xxx\BİRİM\ExampleFile.docx'

    at FSWatcher.watcher1.on.on.on.on.error (C:\node\projeler\devs\Library\gozcu\chokidar.js:407:39)
    at FSWatcher.emit (events.js:198:13)
    at FSWatcher._handleError (C:\node\projeler\devs\node_modules\chokidar\index.js:589:10)
    at ReaddirpStream.NodeFsHandler._boundHandleError (C:\node\projeler\devs\node_modules\chokidar\lib\nodefs-handler.js:251:43)
    at ReaddirpStream.emit (events.js:198:13)
    at ReaddirpStream._handleFatalError (C:\node\projeler\devs\node_modules\readdirp\index.js:274:10)
    at ReaddirpStream._formatEntry (C:\node\projeler\devs\node_modules\readdirp\index.js:196:16)

**It gives this error when I delete a file. However, it does not follow up when the file is added or changed. Reason Capital letter " İ ". " BİRİM ". Because of Turkish İ. I dont know, what can i do but i think that it is a bug for chokidar.**

Versions 
 - Chokidar version 3.1.1
 - Node version 10.16.3
 - OS version: Windows 10

**Comment by paulmillr** [comment]
I need your chokidar config

**Comment by hakirac** [comment]
`
```javascript
  const watcher1 = chokidar.watch(ayarlar.projelerKlasoru(),
      {
        ignoreInitial: true, 
        disableGlobbing: false, 
        followSymlinks: false, 
        usePolling: false,
        ignored: /(^|[\/\\])\..|.DS_Store$|~\$|kopya.docx$|kopya.jpeg$|kopya.jpg$|.tmp$|thumbs.db$/i,
        persistent: true,
        alwaysStat: false,
        interval:10000,
        binaryInterval: 10000
      })
````

Thanks for answer. 
I tried everything but it goes not. :(

**Comment by paulmillr** [comment]
why don't you handle this with `.on('error', (error)`?

**Comment by hakirac** [comment]
![image](https://user-images.githubusercontent.com/24277966/65945493-bb1e3300-e43c-11e9-9255-f3a2e1a3b5ac.png)

watcher structer is above. execuse me but i can't understand what you mean with .on('error', (error).

**Comment by paulmillr** [comment]
Merging to #895

**Comment by hakirac** [comment]
Problem resolved. IT is UTF-8 problem.

Append to file for "https://github.com/paulmillr/chokidar/blob/master/index.js" folgende code.

```
 String.prototype.toLowerCase = function () {
  var string = this;
  var letters = { "İ": "i", "I": "ı", "Ş": "ş", "Ğ": "ğ", "Ü": "ü", "Ö": "ö", "Ç": "ç" };
  string = string.replace(/(([İIŞĞÜÇÖ]))/g, function (letter) { return letters[letter]; })
  return string;
}

String.prototype.toUpperCase = function () {
  var string = this;
  var letters = { "i": "İ", "ş": "Ş", "ğ": "Ğ", "ü": "Ü", "ö": "Ö", "ç": "Ç", "ı": "I" };
  string = string.replace(/(([iışğüçö]))/g, function (letter) { return letters[letter]; })
  return string;
}
```
