### ISSUE TITLE
Engine update

### ISSUE THREAD

**Issue by kvandenhaute** [paulmillr/chokidar#892]
Going from 3.1.1 to 3.2.0 also included an engine update from minimal 8 to minimal 8.16. This broke installs for serverless, tap, .. in our AWS lambda project which are fixed on 8.10. Such a change cannot be done in a minor version bump because a lot of modules allow minor version bumps. This is a breaking change.

**Comment by paulmillr** [comment]
Yeah, 8.16 was actually the minimal required version all the time. I can release 3.2.1 which rolls this back for now, but the shit will be buggy.

**Comment by kvandenhaute** [comment]
It's just that it's breaking things now for a lot of people using serverless in combination with node 8.10 (one of two supported nodejs runtimes on AWS). We where already on a track to upgrade to nodejs 10, so we will have this issue no longer later today. But I guess there will be projects which are not that easily upgradable to a new nodejs version

**Comment by paulmillr** [comment]
I will release an update in a few hours

**Comment by bhsdodo** [comment]
```
error chokidar@3.2.0: The engine "node" is incompatible with this module. Expected version ">= 8.16".
error Found incompatible module
```

Facing same issue. We use `gulp-watch` package which requires `chokidar`. Now all our projects started to pipeline fail when installing dependencies. Please release an update.

**Comment by paulmillr** [comment]
3.2.1 is live. Nodes other than 8.16 || 10 || 12 aren't supported so don't expect too much stability though.
