### ISSUE TITLE
FATAL ERROR: Ineffective mark-comapcts near heap limit Allocation failed - JavaScript out of memory

### ISSUE THREAD

**Issue by kerafyrm007** [paulmillr/chokidar#914]
The exact error:
![image](https://user-images.githubusercontent.com/56697810/67039771-e2c8f880-f0d6-11e9-838e-5e3facb02b78.png)

What I did to produce this error:
![image](https://user-images.githubusercontent.com/56697810/67039825-08560200-f0d7-11e9-8516-00615a1583ae.png)

![image](https://user-images.githubusercontent.com/56697810/67039847-186de180-f0d7-11e9-8751-33179d07a93e.png)

**Comment by kerafyrm007** [comment]
It begins by displaying about 20 rows, then pauses, then gets to 200,. then crashes.

All I'm doing is creating 6000 files.

**Comment by paulmillr** [comment]
Node ver, os ver, chokidar ver?

**Comment by kerafyrm007** [comment]
node v10.16.3
centos 7
chokidar version 6.12.0

**Comment by kerafyrm007** [comment]
Correction on chokidar version.. it's 3.2.2

**Comment by paulmillr** [comment]
Try 3.2.3
