### ISSUE TITLE
Sometimes relative paths, sometimes absolute paths

### ISSUE THREAD

**Issue by rottmann** [paulmillr/chokidar#918]
**Versions (please complete the following information):**
 - Chokidar version 3.2.2
 - Node version 10.16.3
 - OS version: Linux Mint 19.2

```
addDir test/Unbenannter Ordner
unlinkDir test/Unbenannter Ordner
addDir test/1
add test/1/Unbenanntes Dokument
add test/1/2
unlink test/1/Unbenanntes Dokument
unlinkDir /home/rottmann/myproject/test/1
unlink test/1/2
```
1 is a dir
2 ist a file

But it only happens randomly that `unlinkDir /home/rottmann/myproject/test/1` returns the full path.

You can create a dir test/1 with file test/1/2 and start chokadir, then remove the 1 dir, sometimes it gives me the full path, but only on unlinkDir.

**Comment by almeidaalajoel** [comment]
im having the same issue - unlinkDir randomly will return an absolute path instead of relative

**Comment by Daniel-Knights** [comment]
Explicitly defining `cwd: process.cwd()` _seems_ to fix this for me
