### ISSUE TITLE
Separate GitHub Action for ESLint

### ISSUE THREAD

**Issue by paulmillr** [paulmillr/chokidar#920]
No need to run it with each `npm test`. I think we should have a separate action for that, running on Ubuntu or so.

cc @XhmikosR

**Comment by XhmikosR** [comment]
We can split it, sure but the slowdown doesn't come from this.

**Comment by XhmikosR** [comment]
BTW with caching enabled this will be faster. And if we were using `npm ci` it would be even faster. Just FYI.

That being said, tests aren't really that slow. The mocha tests are the slowest (1m+), so not running ESLint wouldn't save us enough to justify the change IMO.

**Comment by paulmillr** [comment]
It's not just slowness, I like the fact that every PR or so would describe where the fail is: be it eslint, or a particular OS.

**Comment by XhmikosR** [comment]
I will make a PR later and run ESLint only only on Node.js 12
