### ISSUE TITLE
High CPU and out of memory

### ISSUE THREAD

**Issue by bpasero** [paulmillr/chokidar#922]
**Describe the bug**

The following sample case will produce high CPU spikes and out of memory when run with master on Linux. Versions `2.x` do not show this behaviour. Originally reported as https://github.com/microsoft/vscode/issues/82427

**Versions (please complete the following information):**
 - Chokidar version: `master`, `3.2.2`
 - Node version `10.16.0`
 - OS version: Ubuntu 18

**To Reproduce:**

* `sudo apt install cargo`
* `git clone https://github.com/MusiKid/ripgrep-all.git`
* `git checkout debug`
* start the watcher with the code below
* `cargo build`

```js
function chokidar() {
    const chokidar = require("./chokidar-3"); // this can be chokidar just checked out of master
    const options = {
        ignoreInitial: true,
        followSymlinks: true
    }

    const watcher = chokidar.watch('<path to ripgrep-all>', options);

    const now = Date.now();
    watcher.on("ready", () => {
        console.log(Date.now() - now);
        console.log("ready");
    });
}

chokidar();
```

HTOP shows memory reaching 3 GB for Chokidar 3:

![image](https://user-images.githubusercontent.com/900690/67180793-ec09dc00-f3da-11e9-9f1a-34f1f15f2765.png)

And eventually produces: `FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory`

When run against master, the process crawls up to 3 GB and eventually signals an out of memory crash. Works fine with Chokidar 2 as seen from HTOP below:

![image](https://user-images.githubusercontent.com/900690/67180495-1c9d4600-f3da-11e9-8905-3b2bb91d3d1c.png)

**Comment by bpasero** [comment]
![image](https://user-images.githubusercontent.com/900690/67181074-d0530580-f3db-11e9-80ff-a67c9c34803e.png)

[Heap-20191021T082145.zip](https://github.com/paulmillr/chokidar/files/3749269/Heap-20191021T082145.zip)

**Comment by paulmillr** [comment]
That seems to fix it but we need to test all other behaviors.

**Comment by paulmillr** [comment]
coming ASAP

**Comment by paulmillr** [comment]
@bpasero 3.2.3 is up

**Comment by bpasero** [comment]
VSCode will take it, thanks.
