### ISSUE TITLE
Renaming directory is reported only as addition (no unlink events with the old name)

### ISSUE THREAD

**Issue by tgrajewski** [paulmillr/chokidar#927]
**Describe the bug**

Renaming intermediate folder in a watched directory structure is reported by Chokidar as addition (`add` event) and there is no other events, like `unlink`, `unlinkDir`, `rename`, etc. for the old name of the directory.

**Versions:**
 - Chokidar v3.2.2
 - Node v10.16.3
 - Windows 10

**To Reproduce:**

Run this script in CLI. It creates some test files, then after 3 seconds renames one of the directories created. Exit with Ctrl+C.

```javascript
'use strict';


const fs = require('fs');
const chokidar = require('chokidar');


// Create some files to demonstrate the issue
fs.mkdirSync('bug/default/', {'recursive': true});
fs.writeFileSync('bug/default/test.txt', 'żółw');


function onAll(event, filename, stats) {
    console.log(event, filename);
}

var watcher = chokidar.watch('bug/**/*.txt', {'ignoreInitial': true});

watcher.on('all', onAll);


// Rename directory, which results in only addition of the new file being
// triggered and not deletion of the old file (or unlinkDir, or anything).
setTimeout(function() {
    fs.renameSync('bug/default/', 'bug/renamed/');
}, 3000);


// Exit gracefully on Ctrl+C and clean-up
function removeFile(filename) {
    try {
        fs.unlinkSync(filename);
    } catch (e) {
        if (e.code !== 'ENOENT')
            throw e;
    }
}

function removeDirectory(filename) {
    try {
        fs.rmdirSync(filename);
    } catch (e) {
        if (e.code !== 'ENOENT')
            throw e;
    }
}

function exit() {
    if (watcher)
        watcher.close();

    // Clean-up created files
    removeFile('bug/default/test.txt');
    removeFile('bug/renamed/test.txt');
    removeDirectory('bug/default/');
    removeDirectory('bug/renamed/');
    removeDirectory('bug/');

    console.log('Exiting, bye!');
}

process.on('SIGINT', exit);
```

**Expected behavior**

The above script renames directory `bug/default/` to `bug/renamed/`. Chokidar doesn't report `unlink` nor `unlinkDir` events for the now non-existing `bug/default/` directory or the file inside it.

Alternatively, a `rename` event could be triggered with the old and new names passed in to the event callback.

**Comment by Angor-de-Redjak** [comment]
I have the same problem. When I rename a file, the "add" event is triggerred.
But more problematic, if I rename a directory with files within, the "add" event is triggerred for ALL THE FILES contained in it.
That's quite troublesome....

A "rename event" as suggested above would be interresting.

**Comment by ahmadnassri** [comment]
confirmed behaviour when moving / renaming directories

**Comment by aleclarson** [comment]
This works as expected in [filespy](https://github.com/alloc/filespy), an alternative to chokidar.
