### ISSUE TITLE
Directory monitoring is not functioning.

### ISSUE THREAD

**Issue by kintony** [paulmillr/chokidar#932]
**Describe the bug**
Directory monitoring is not functioning.

**Versions (please complete the following information):**
 - Chokidar version [e.g. 3.2.1]
 - Node version [e.g. 12.11.0]
 - OS version: [e.g. Windows 10]

**To Reproduce:**

`
var watcher = chokidar.watch((dirPath), {
  cwd: rootPath,
  ignored: /[\/\\]\./,
  ignoreInitial: true,
  usePolling: true,
  interval: 5000,
  awaitWriteFinish: {
        stabilityThreshold: 2000, 
        pollInterval: 200
    }, 
});
`

**Comment by paulmillr** [comment]
works for me. you'll need to be more specific.
