### ISSUE TITLE
Backport GH Actions + lint for 2.x?

### ISSUE THREAD

**Issue by XhmikosR** [paulmillr/chokidar#938]
@paulmillr is the 2.x branch supported? If so, I think it would make sense to backport at least the CI change, and perhaps some of the other patches.

Only thing I don't know is if you still have Coveralls added to the repo; the 2.x branch seems to still have it.

I could take a stab at it in the next days.

**Comment by XhmikosR** [comment]
Only thing I don't know is if you still have Coveralls added to the repo; the 2.x branch seems to still have it.

**Comment by paulmillr** [comment]
As we’re getting close to dropping 8.x, I’d say it’s basically unsupported. We need to direct everyone to 3.x, to have huge perf gains.
