### ISSUE TITLE
Use fs.watch recursive: true for effective work on win32 

### ISSUE THREAD

**Issue by paulmillr** [paulmillr/chokidar#939]
This should speed up things by a huge amount. `recursive: true` option has been around since 2015, or so. It uses effective low-level inferface, although shitty — otherwise there'd be no chokidar.

We will need a new watcher class for that, something like `class RecursiveWatchHandler`.

cc @XhmikosR

**Comment by XhmikosR** [comment]
Sounds good. But before making any more functional changes, we really need to figure out why tests fail.

**Comment by paulmillr** [comment]
We should use `node >= 10.16` as a requirement for Chokidar 4 and readdirp 4; because aws λ runs 10.16.3.

Ideally >= 10.17, because .17 removes experimental status from `asyncIterator`.

**Comment by XhmikosR** [comment]
Isn't it a little soon to do this? I mean, we'll have to maintain 2 branches for a long time this way.

But it's your call. As long as we have a stable CI, we can experiment with new things for sure :)

**Comment by paulmillr** [comment]
> we'll have to maintain 2 branches for a long time this way

Not really — node.js ends support of 8.x on 31 Dec, in just two months. So if chokidar 4 would be released in early 2020, chokidar 3 @ node8 would already be unsupported.

**Comment by XhmikosR** [comment]
True, but don't expect people to update so easy :)

**Comment by Wonder233** [comment]
hello, this feature is much needed~
I encountered the problem that the first-level directory cannot be deleted/renamed without using usePolling. But usePolling caused high CPU consumption.
