### ISSUE TITLE
Do I need to worry about disposing chokidar watchers?

### ISSUE THREAD

**Issue by blake-mealey** [paulmillr/chokidar#945]
This isn't a bug report, so I'm not sure if this is the correct place to put this. Please redirect me if necessary.

I'm working on adding file-watching support to a Rollup plugin (rollup-plugin-copy) using Chokidar (see this discussion for why we want to use Chokidar: https://github.com/vladshcherbin/rollup-plugin-copy/pull/27#issuecomment-546778539), and I'm wondering if I need to make sure I call `FSWatcher.close()` before the process exits. If so, I'm not sure what the recommended way to do so is, because using `process.on('exit', ...)` requires the callback to be synchronous (see https://nodejs.org/api/process.html#process_event_exit), but `FSWatcher.close()` is async.

Since I'm here, I'm also curious regarding the best practices for creating more than one `FSWatcher` instance VS creating a single master `FSWatcher` with all of the paths you care about. Is there a significant performance cost for creating multiple watchers?

**Comment by paulmillr** [comment]
You don’t need to call close() before process exit.

Creating more than one instance is possible, but may create some bugs, since we don’t test this case.

**Comment by blake-mealey** [comment]
Great, thanks for the help!
