### ISSUE TITLE
Watching directory on network share ending in $ returns no files

### ISSUE THREAD

**Issue by timfish** [paulmillr/chokidar#948]
When watching a directory on network share ending with `$`, no files are found. Shares ending in `$` are commonly used to hide shares from being listed when browsing on Windows but they work normally otherwise. 

**Versions:**
 - Chokidar version `3.3.0`
 - Node version `electron@4.2.12` ie. `node@10.11.0`
 - OS version: Windows 10

**To Reproduce:**

```
const networkDirectory = '//SOME-PLACE/share-name$/more/path';

chokidar
      .watch(networkDirectory, {
        usePolling: true,
        interval: 1000,
        awaitWriteFinish: { stabilityThreshold: 1000, pollInterval: 1000 },
        disableGlobbing: true
      })

```
Works fine in `chokidar@2.1.8`

**Comment by paulmillr** [comment]
The backlog is going to start from zero as a preparation for v4 release. v4 would bring massive rewrite to the table and drop most dependencies. All issues are being closed as preparation for v4 release.

In the future, only issues with enough community support would be considered.

See issue 1195 for more info. Thank you.
