### ISSUE TITLE
Don't trigger on 'ready' on run with electron

### ISSUE THREAD

**Issue by CCourbet** [paulmillr/chokidar#949]
**Describe the bug**

When I first run my app with electron, chokidar.watch is not working, my watcher is initialize but empty and it never get to triggered on 'ready'.
If i reload thought (I'm using electron-reload) it works perfectly...
I'm using the framework angular.

**Versions:**
 - Chokidar version 3.3.0
 - Node version 12.6.8
 - Electron version 6.0.2
 - Electron-reload 1.5.0
 - OS version: Windows 10

**To Reproduce:**

With npm run, my console.log('ready') is never displayed.
If I reload the app, it's working fine :

```
import { Injectable } from '@angular/core';
import * as chokidar from 'chokidar';

@Injectable({
  providedIn: 'root'
})
export class WatchFilesService {

  private watcher;

  constructor() {
  }

  public addWatcher(path) {

    this.watcher = chokidar.watch(path, {
      ignored: /(^|[\/\\])\../,
      persistent: true
    });
   
    this.watcher.on('ready', () => {
      console.log('ready');
    });
  }
}
```

It's seems to be working after building the app.

**Comment by paulmillr** [comment]
1. This seems to be wrong: `/(^|[\/\\])\../`
2. Search for an issue in your app initialization flow, we have a bunch of electron users and they all seem to be fine.
