### ISSUE TITLE
Watch a folder recursively for a specific file extension

### ISSUE THREAD

**Issue by juberjj** [paulmillr/chokidar#951]
Maybe more as a question than a bug.

Trying to watch a specific folder and its subfolders for a change on a specific file extension. I'm able to what for a change but I'm afraid I can't filter it by a file extension. Any help / suggestion is very much appreciated.

**Versions (please complete the following information):**
 - Chokidar version - 3.3.0
 - Node version 10.15.1 also tested on v12 
 - OS version: Fedora 31

const watcher = chokidar.watch(basePath, {
  ignored: /node_modules|\/vendor|\/storage|\.git/,
  persistent: true,
})

**To Reproduce:**

Steps to reproduce the behavior. Include filename and chokidar config.

Ideally prove a problem by isolating and making it reproducible with a very short sample program, which you could paste here:

```
const chokidar = require('chokidar');
const fs = require('fs');
// One-liner for files and directories starting with 'test'
chokidar.watch('test*', {}).on('all', (event, path) => {
  console.log(event, path);
});
fs.writeFileSync('test.txt', 'testing 1');
// In a comment describe expected output versus observed problem
```

Most valuable could be one or more test cases for [test.js](https://github.com/paulmillr/chokidar/blob/master/test.js) to demonstrate the problem.

**Expected behavior**
A clear and concise description of what you expect to happen.

**Additional context**
Optionally nice to know what project you are working on.

**Comment by paulmillr** [comment]
Use `ignored` option, like ignored: (path) => extname(path) !== '.txt'
