### ISSUE TITLE
filename in hebrew return "????" instead

### ISSUE THREAD

**Issue by jjachniuk** [paulmillr/chokidar#952]
**Describe the bug**

**Versions (please complete the following information):**
 - Chokidar version 3.3
 - OS version:  Windows 10]

**To Reproduce:**

have a filename in hebrew , when the event occur , the path is ????? instead of the name

const watcher = chokidar.watch(directoryToWatch, {
		ignored: /(^|[\/\\])\../, // ignore dotfiles
		persistent: true,
		ignoreInitial : true,
		awaitWriteFinish: true,
		usePolling: true
	});
	watcher.on('add', (path) => console.log(path))

the problem we are missing the enconding option that fs.watch has.

**Comment by paulmillr** [comment]
The default encoding is utf-8. Do you have non-unicode encoding in your file system names?
