### ISSUE TITLE
function to silently add file(s)

### ISSUE THREAD

**Issue by jasonkuhrt** [paulmillr/chokidar#953]
We have a use-case where files are added to the watcher programmatically but we do not want the add event triggered. We've wrapped chokidar in our project to have a simple `addSilently` peer function to `add`. This issue is about bringing the idea into chokidar core.

To further motivate, our use-case is that our watcher program traverses the module require graph. We want to watch this graph for changes but the initial add should not trigger an event that we react to.

**Comment by paulmillr** [comment]
Listen to `ready` event, that should do the trick.

**Comment by jasonkuhrt** [comment]
@paulmillr not sure what that solution looks like. Can you share a snippet?

Goal is that we can add files to watcher without triggering the original long-lived watch-for-all-events callback.

**Comment by paulmillr** [comment]
```
let ready = false;
watcher.add(files).on('ready', () => {
  ready = true
}).on('add', (path) => {
  if (!ready) // ignore
})
```

**Comment by jasonkuhrt** [comment]
That does not meet the needs of our use-case. We have no guarantee when the programmatic adds are going to take place.

**Comment by paulmillr** [comment]
Not much we can do here, it's deep inside chokidar logic. You're free to change it on your own though.

**Comment by jasonkuhrt** [comment]
Our current logic includes the following. 

Our implementation is not complete since it doesn't account for how remove events should possibly reset entries in the programmatically-added-files state.

So far working, though wouldn't be surprised if there is a design flaw in our approach.

```ts
const SILENT_EVENTS = ['add', 'addDir']

export function watch(
  paths: string | ReadonlyArray<string>,
  options?: FileWatcherOptions
): FileWatcher {
  log('starting', { paths, ...options })
  const watcher = chokidar.watch(paths, options) as FileWatcher
  const programmaticallyWatchedFiles: string[] = []

  watcher.addSilently = path => {
    programmaticallyWatchedFiles.push(path)
    watcher.add(path)
  }

  if (options && options.onAll) {
    watcher.on('all', (event, file, stats) => {
      if (
        programmaticallyWatchedFiles.includes(file) &&
        SILENT_EVENTS.includes(event)
      ) {
        log('ignoring file addition because was added silently %s', file)
        return
      } else {
        log('file watcher event "%s" originating from file/dir %s', event, file)
      }

      options.onAll!(event, file, stats)
    })
  }

  return watcher
}
```

**Comment by paulmillr** [comment]
Thanks for the snippet. Going to be useful! We don’t want to add the functionality to the core meanwhile.
