### ISSUE TITLE
awaitWriteFinish does not work on Windows

### ISSUE THREAD

**Issue by HeyJ0e** [paulmillr/chokidar#954]
Option `awaitWriteFinish` does not work on Windows, using NTFS file system. When I start the copy, an `add` event is fired, and when it's finished there's one `change` event.
On alpine linux it waits until the copy is finished and fires one `add` event. I guess this is the expected behaviour.
I tried with the latest Node (v12.13.1) and Chokidar (v3.3.0).

**Comment by kxzhe** [comment]
yes, i met the same situation on windows10 64 bit, ver 1909!
ntfs file system, too.

**Comment by badalyan** [comment]
Hi @paulmillr any updates or recommendations on this issue?

**Comment by badalyan** [comment]
I think I got it working. 

Originally, I used custom `awaitWriteFinish` settings, but after switching back to the default `pollInterval` value, it began working as expected.

**Comment by soubhikchatterjee** [comment]
@badalyan Can you please show us your config values for chowdikaar?

**Comment by leopucci** [comment]
Happening to me. Windows 10 version 20H2
Tried using 
`	awaitWriteFinish: {
    stabilityThreshold: 5000,
    pollInterval: 100
  },`

or also 

`awaitWriteFinish: true`

Both options does not work, big files get two events, one add event, then a change event.

Anybody succeeded?

**Comment by paulmillr** [comment]
The backlog is going to start from zero as a preparation for v4 release. v4 would bring massive rewrite to the table and drop most dependencies. All issues are being closed as preparation for v4 release.

In the future, only issues with enough community support would be considered.

See issue 1195 for more info. Thank you.
