### ISSUE TITLE
How to use micromatch in chokidar v3

### ISSUE THREAD

**Issue by vladshcherbin** [paulmillr/chokidar#956]
Hey 👋 

Chokidar v2 used `micromatch` inside, but switched to `picomatch` in v3. I've got a PR to use [chokidar as a watcher](https://github.com/vladshcherbin/rollup-plugin-copy/pull/30), but I use `globby` package inside which uses `micromatch`. So some of glob features will be missing in this case.

Is it somehow possible to use `micromatch` in chokidar v3?

**Comment by paulmillr** [comment]
So which features exactly are missing from micromatch? Micromatch uses picomatch inside.

**Comment by vladshcherbin** [comment]
@paulirish I wish I knew man, trying to figure out differences from pico/micro/mini/any/etc match.

I saw `micromatch` uses `picomatch` inside and from [comparison table](https://github.com/micromatch/picomatch#library-comparisons) seems like only _Brace expansion_ is missing from `picomatch`.

**Comment by paulmillr** [comment]
We are using braces.

**Comment by vladshcherbin** [comment]
@paulmillr that's great, thank you
