### ISSUE TITLE
troubleshooting steps in readme direct users to install Python 2.7

### ISSUE THREAD

**Issue by johng42** [paulmillr/chokidar#958]
**Describe the bug**

The readme has this:
* `ERR! stack Error: Python executable "python" is v3.4.1, which is not supported by gyp.`
  * You should be able to resolve this by installing python 2.7 and running:
    `npm config set python python2.7`

Python 2.7 gets deprecated in a couple of weeks (Jan 1 2020) and users should not be directed to install it any longer

**Versions (please complete the following information):**
 - any version of chokidar - 

**To Reproduce:**

I have no context on what error would result in this troubleshooting step.  

**Expected behavior**
No mention of installing python 2.x

**Additional context**
The simple fix would be to remove this text from the readme, but I do not know what to suggest to users who hit this error state.

**Comment by paulmillr** [comment]
Update to chokidar 3.

**Comment by johng42** [comment]
Got it - thanks.
