### ISSUE TITLE
Events not emitted under paths containing certain characters on older Mac.

### ISSUE THREAD

**Issue by Wolfnugget** [paulmillr/chokidar#960]
**Describe the bug**

Events not triggered in paths containing for example ä with Mac OS Extended(HFS+).

**Versions:**
 - Chokidar version 3.3.1
 - Node version 12.13.1
 - OS version: OS X 10.10.5

**To Reproduce:**

const chokidar = require('chokidar');
const fs = require('fs');
const path = require('path');

const testDir = 'täst';

fs.rmdirSync(testDir, {recursive: true});
fs.mkdirSync(testDir);

chokidar.watch(testDir)
.on('all', (e, p, s) => console.log(p)) // Should output 'täst' and 'täst/t'
.on('ready', () => {
 fs.mkdirSync(path.join(testDir, 't'));
});

**Expected behavior**
Expected it to detect the creation of the directory t.

**Comment by paulmillr** [comment]
macos 10.10.5 is not supported by nodejs. see https://github.com/nodejs/node/blob/master/BUILDING.md
