### ISSUE TITLE
rsync -a & usePolling=true: add event is not triggered for last big copied file

### ISSUE THREAD

**Issue by ezze** [paulmillr/chokidar#961]
**Describe the bug**

When using option `usePolling=true` and copying big files to watched directory with `rsync -a` an `add` event is not triggered for last file in a list.

**Versions (please complete the following information):**
 - Chokidar version 3.3.1
 - Node version 10.17.0
 - OS version: Kubuntu 18.04 & CentOS 7.6

**To Reproduce:**

[Here](https://github.com/ezze/chokidar-issue-961) is a repo to reproduce.

**Expected behavior**

Trigger `add` event for last file copied by rsync.

**Comment by paulmillr** [comment]
The backlog is going to start from zero as a preparation for v4 release. v4 would bring massive rewrite to the table and drop most dependencies. All issues are being closed as preparation for v4 release.

In the future, only issues with enough community support would be considered.

See issue 1195 for more info. Thank you.
