### ISSUE TITLE
Symlinks are always watched ignoring matching pattern and `followSymlinks` option

### ISSUE THREAD

**Issue by ClassicOldSong** [paulmillr/chokidar#967]
**Describe the bug**

Symlinks are always watched ignoring matching pattern and `followSymlinks` option.

**Versions (please complete the following information):**
 - Chokidar version 3.3.1
 - Node version v12.12.0
 - OS version: MacOS 10.15

**To Reproduce:**

Create a file named `test.aaa`
Create a file named `test.bbb`
Create a symlink to `test.bbb` named `test.ccc`

```javascript
const chokidar = require('chokidar')

const watcher = chokidar.watch('**/*.aaa')

const log = console.log.bind(console)

watcher
  .on('add', path => log(`File ${path} has been added`))
  .on('change', path => log(`File ${path} has been changed`))
  .on('unlink', path => log(`File ${path} has been removed`))
```

**Expected behavior**
Only `test.aaa` should be watched, but `test.ccc` is watched as well.

**Additional context**
Project: https://github.com/TheNeuronProject/ef.qt
Related code: https://github.com/TheNeuronProject/ef.qt/blob/master/watcher.js#L113
When project includes symlinks, they are no matter how watched and caused issue on code compiling .

**Comment by paulmillr** [comment]
The backlog is going to start from zero as a preparation for v4 release. v4 would bring massive rewrite to the table and drop most dependencies. All issues are being closed as preparation for v4 release.

In the future, only issues with enough community support would be considered.

See issue 1195 for more info. Thank you.
