### ISSUE TITLE
chokidar is very slow when monitoring large network drives

### ISSUE THREAD

**Issue by michaelmorton-vh** [paulmillr/chokidar#970]
**Describe the bug**

When monitoring a folder locally with `chokidar`, even with 15,000 files (each are about 2MB), the `add` event gets fired off within 1-2 seconds when a new file is added which is great. However, if this folder is instead a network drive, it takes as much as 20-30 minutes to detect the file change.

**Versions (please complete the following information):**
 - Chokidar version `3.3.1`
 - Node version `v10.16.0`
 - OS versions: each Windows 7 and macOS Catalina; the network drive is also running on a Windows 7 machine.

**To Reproduce:**

The following includes the minimal blocks of code pertaining to the watcher config and the event watched (only `add`):

```
  const watcher = chokidar.watch(path, {
      usePolling: true, // I have tried both with and without this property, in both cases it takes >20 minutes

      // wait for the file to be 100% written before sending an event
      awaitWriteFinish: {
        stabilityThreshold: 2000,
        pollInterval: 500
      },
      ignored: /(^|[\/\\])\../, // taken from the docs
      ignoreInitial: true,
      interval: 500,
      persistent: true,
  });

  const handlers = {
    add: (path) => mainWindow.webContents.send(FILE_ADDED, path),
  }
```

**Expected behavior**
For newly-added files to the network drive to be detected within 10 seconds of the file being added. 

Sometimes it appears that the `add` event never gets fired off (after leaving the app open for 30 mins to 1 hour).

**Additional context**
It makes sense that monitoring a massive network drive is slower - I am wondering if there are ways to mitigate this or otherwise improve the performance. 

The files are usually added in folders, such that there is a nested folder structure - each folder often containing between 4-10 files. I am wondering also if there is some way to have watchers on only the files from the past 24 hours or some other way to improve the performance this way. None of the existing 15,000 files will change - I just want to detect new ones.

Thanks for any insight!

**Comment by paulmillr** [comment]
#665
