### ISSUE TITLE
Chokidar to watch files from certain date and time 

### ISSUE THREAD

**Issue by mohendren** [paulmillr/chokidar#974]
Is there any option to watch files from  certain date and time . I couldn't find anything in docs. 
if it is not present is it possible to achieve. 

**ex**: chokidar to watch files created on or after - _30/01/2020 11:00 AM_

**Comment by paulmillr** [comment]
No — feel free to implement it by yourself. There is no benefit in doing this in Chokidar, since there's no low-level FS call on most platforms; except on fsevents — and even there it's not implemented yet.
