### ISSUE TITLE
Deal with 80k files in one folder

### ISSUE THREAD

**Issue by andrelec1** [paulmillr/chokidar#975]
I have a project based on data analyse produce by a lots of automates...
But one day i have a worker that stop working long time ago for some raison (not monitored :/)
And now i have a folder with more than 80000 csv files in it and i have to import ... 

So, when i relunch the app, chokida emit 80000 `add` event... and everythings start going to die ...

How can i deal with a issue like this ?

**Comment by paulmillr** [comment]
Not really — this is a limitation of the file system calls. 

node.js recently implemented `fs.opendir` to handle cases like huge amounts of files in one folder, we need to add its support once it's at least as fast as the current method. You can track the progress here at https://github.com/paulmillr/readdirp/issues/105
