### ISSUE TITLE
Memory is so large for watching a project

### ISSUE THREAD

**Issue by Lennon925** [paulmillr/chokidar#982]
Version: 3.3.1

I am watching Linux source code and the memory is 4G. Any suggestion for me?

**Comment by paulmillr** [comment]
Amount of files?
List of chokidar options?
Node version?

**Comment by Lennon925** [comment]
> Amount of files?
> List of chokidar options?
> Node version?

Amount of files: about 50000+
Node Version：12.16.0
Options：
       persistent: true,
       ignoreInitial: true,
I also want to use "ignored" option to filter some files but it doesn't work.
       ignored: ((path: string) => extname(path) !== '.c')

**Comment by paulmillr** [comment]
yeah, that doesn't happen with 50,000 files. maybe with 500k. we've did some good optimizations recently. something happens on your system that makes chokidar consume 4g. need to understand the underlying issue.

Which Linux? Distro? Kernel version?

**Comment by nainardev** [comment]
Windows 10 Distro

**Comment by paulmillr** [comment]
So @Lennon925 are you on windows?

**Comment by Lennon925** [comment]
> So @Lennon925 are you on windows?

yes, on window 10

**Comment by paulmillr** [comment]
See if there is any difference between usePolling: true and false

**Comment by Lennon925** [comment]
> See if there is any difference between usePolling: true and false
I set usePolling to true and the memory is 300M. I think it's acceptable but cpu is always 45%.
![image](https://user-images.githubusercontent.com/39362073/76293016-4274aa00-62eb-11ea-9559-7fb14be217bd.png)

Set usePolling to false. Memory is 4G and cpu is low.
![image](https://user-images.githubusercontent.com/39362073/76293651-68e71500-62ec-11ea-8e3c-7b6ba1466355.png)

**Comment by paulmillr** [comment]
So, use polling for now.

**Comment by Lennon925** [comment]
> So, use polling for now.

It's impossible for me because cpu is 45%……If I start 2 server, cpu will be very high.

**Comment by paulmillr** [comment]
Nothing we can do for now. Windows implementation needs some refinement. Specifically, support for fswatch recursive: true.

**Comment by Lennon925** [comment]
> Nothing we can do for now. Windows implementation needs some refinement. Specifically, support for fswatch recursive: true.

OK, expect for your next version for this.

**Comment by paulmillr** [comment]
Merging to #939
