### ISSUE TITLE
Ignored doesn't work

### ISSUE THREAD

**Issue by Lennon925** [paulmillr/chokidar#983]
Version 3.3.1.

//D:\Projects\linux\alpha
watcher = chokidar.watch(folderPaths, 
				{       persistent: true,
					ignoreInitial: true,
					ignored: ((path: string) => extname(path) === '.c')
				});

it doesn't work. when you delete or add a file which ends with .c, event still be triggered.

**Comment by paulmillr** [comment]
make a log inside `ignored` function and see what happens there
