### ISSUE TITLE
Paths with parentheses () are not watched - globbing issue

### ISSUE THREAD

**Issue by szalap** [paulmillr/chokidar#984]
**Describe the bug**

When I try to add a path with parentheses (f.e. "C:/Demo Projects/Test (1)" ) to be watched by Chokidar it returns with "filepath is not defined" error on **add** event. Escaping special characters does not help.

**Versions (please complete the following information):**
 - Chokidar version: 3.3.1
 - OS version: Windows 10

**To Reproduce:**
```
const chokidar = require('chokidar');
const fs = require('fs'); 

chokidar.watch("C:/Demo Projects/Test \\(1\\)", {}).on("add", filepath => handleNewAdded(config, filepath));
```

**Observed behavior**
Chokidar returns with "filepath is not defined" error on **add** event.

**Expected behavior**
A folder path with parentheses (1) is being successfully watched.

**Comment by paulmillr** [comment]
that path seems like invalid glob to me

**Comment by szalap** [comment]
How so? It's a common scenario where duplicate folders f.e. from unzipping would get (x) suffix to its name.
How else can this path be escaped to pass glob test?

**Comment by paulmillr** [comment]
Windows doesn't use `/` in paths, it uses `\`.

**Comment by paulmillr** [comment]
> How else can this path be escaped to pass glob test?

not sure

**Comment by proimage** [comment]
Have you tried this variation?

```
chokidar.watch("C:/Demo Projects/Test \(1\)", {}).on("add", filepath => handleNewAdded(config, filepath));
```

AFAIK, the backslash escapes the character that follows it, so I believe the double backslashes you had earlier were getting translated into this path: `C:\Demo Projects\Test \(1\)`, or to make it clearer:

```
C:\
    Demo Projects\
        Test \
            (1\
                )\
```

**Comment by Virgil993** [comment]
Has this issue been resolved? Is there a fix? I'm still having trouble trying to watch a path which contains the left parentheses "(".
