### ISSUE TITLE
Chokidar for Deno?

### ISSUE THREAD

**Issue by ghost** [paulmillr/chokidar#988]
Is there any plan?

**Comment by paulmillr** [comment]
Sure, contributions welcome

**Comment by franck34** [comment]
btw deno got his own watch implementation

https://deno.land/typedoc/index.html#watchfs

**Comment by paulmillr** [comment]
Node had native watch for a long time - doesn’t mean it’s not shitty.

**Comment by nainardev** [comment]
Closed by mistake! 

chokidar is powerful than node's watch, thought what about deno

thanks

**Comment by cvkline** [comment]
I've made a fork and am working on getting chokidar working on deno. What's up on deno.land/x right now does NOT work, but it should not be too difficult to fix up the imports.  (Hopefully not famous last words!)

**Comment by cvkline** [comment]
Okay, following up to myself, this is mostly a pretty straightforward job and I've got good progress thanks to esm.sh, BUT...

Deno doesn't support native-code imports, so I'm pretty much dead in the water pulling in the fsevents package which contains C code. I think the way to address this is to write a Deno plugin and then use that somehow, but that would involve either rewriting that program in Rust, or rewriting the C to use Rust bindings, neither of which I'm up for.

Do people think it's worth me finishing this without MacOS fsevents? Chokidar would have to fall back to polling mode on that platform, which would kinda suck.

Alternatively, Deno now has its own Deno.watchFs which I could try to leverage instead, but it doesn't provide all the same functionality so things like awaitWriteFinish might be a little problematic, and other fields would be missing in the event object.

**Comment by paulmillr** [comment]
see if deno.watchFs is good enough. if it's shitty like its node.js counterpart, any kind of port would be welcome.
