### ISSUE TITLE
async hook stack has become corrupted

### ISSUE THREAD

**Issue by JoeEarly** [paulmillr/chokidar#990]
Now first off am not 100% sure this is chokidars fault as I was using **fs** beforehand with the same issue, but since this is wrapper on fs I thought I would ask here. 

It's pretty much all here: https://stackoverflow.com/questions/60642082/async-hook-stack-has-become-corrupted to save me typing it all out again. 

Pretty much I watch a folder of 39ish files, all updated every hour by FTP drop. Hoping someone may have seen this before or at least point me in the right direction 

The crashing is pretty random as well, sometimes you'll get 10hr of uptime, maybe only a few minutes

**Comment by paulmillr** [comment]
Hi,

I'm not really sure if that's related to fs.watch or chokidar themselves. Perhaps it's because of some other package from your code? Seeing this error for the first time.

Also, seems like some node.js issue. See https://github.com/microsoft/vscode/issues/85601 etc.
