### ISSUE TITLE
Watch start will add whole directory

### ISSUE THREAD

**Issue by ognif** [paulmillr/chokidar#994]
I use chider on macOS. When I start watching the directory, chokidar will add all 4000 files inside the directory. Means the event is 4000 times fired before the code will run further. This is an amazing memory overhead. 
How I can avoid that chokidar will fire this 4000 events. I just need the info for 1 file.

**Comment by paulmillr** [comment]
Use ignoreInitial: true. Also the overhead is tiny, since we can reuse one fsevents instance for 300,000 files etc
