### ISSUE TITLE
Change Event Is Not Emitted When Constantly Piping Data on macOS. 

### ISSUE THREAD

**Issue by johnshamoon** [paulmillr/chokidar#999]
**Describe the bug**
When steadily piping text into a file that is being watched,  the file watcher emits one change event at the beginning (first thing that was piped) and another after terminating the program piping data into the file (^C), but not all the other times that the file is changing (once per second).

Here's a video of the bug (zipped .mov because GitHub won't let me attach a video): [chokidar-test.zip](https://github.com/paulmillr/chokidar/files/4422393/chokidar-test.zip)

**Versions**
 - Chokidar version: 3.3.1
 - Node version: 6.13.4
 - OS version: macOS Catalina 10.15.4

**To Reproduce:**
Run `node index.js` in one terminal and `sh print_test.sh | tee test.txt` in another.

```javascript
// index.js
const chokidar = require("chokidar");

const watcher = chokidar.watch(__dirname, {
    ignoreInitial: true,
    useFsEvents: true
});

watcher.on('all', (type, path) => {
    console.log(type, path);
});
```

```bash
# print_test.sh
#!/bin/bash
while true; do
  echo "test"
  sleep 1
done
```

**Expected behavior**
I expect the file watcher to emit a change event every second (or as often as the file is written to).

**Additional context**
I came across this while piping logs from a device into a file opened in VSCode. I filed a bug on VSCode before we concluded that the issue came from the file watcher instead. Here's the link to the previous bug: https://github.com/microsoft/vscode/issues/93277

**Comment by albedoa** [comment]
Hi @johnshamoon, I recently filed [this issue](https://github.com/dlmanning/gulp-sass/issues/762) at the gulp-sass repo. Would you know if it's related to yours? My package lock reports the same version of chokidar, and I am on Catalina if that matters.

**Comment by veeramarni** [comment]
I have same issue, is there any workaround for this issue?

**Comment by bersbersbers** [comment]
I see similar issues on Windows, see https://github.com/paulmillr/chokidar/issues/1297 if interested
